package com.swbr.orespawn.gametest;

import com.swbr.orespawn.OreSpawn;
import com.swbr.orespawn.block.entity.TileEntityCrystalFurnace;
import com.swbr.orespawn.block.workshop.CrystalFurnace;
import com.swbr.orespawn.combat.LegacyArmorFormula;
import com.swbr.orespawn.config.OreSpawnConfig;
import com.swbr.orespawn.item.armor.ItemOreSpawnArmor;
import com.swbr.orespawn.registry.ModBlocks;
import com.swbr.orespawn.registry.ModItems;
import java.util.List;
import java.util.Map;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.core.Holder;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.registries.Registries;
import net.minecraft.gametest.framework.GameTest;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.resources.ResourceKey;
import net.minecraft.tags.DamageTypeTags;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.damagesource.DamageSource;
import net.minecraft.world.InteractionResult;
import net.minecraft.world.entity.EquipmentSlot;
import net.minecraft.world.entity.ExperienceOrb;
import net.minecraft.world.entity.ai.attributes.AttributeModifier;
import net.minecraft.world.entity.ai.attributes.Attributes;
import net.minecraft.world.entity.item.ItemEntity;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.ArmorItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.UseAnim;
import net.minecraft.world.item.context.UseOnContext;
import net.minecraft.world.item.enchantment.Enchantment;
import net.minecraft.world.item.enchantment.EnchantmentHelper;
import net.minecraft.world.item.enchantment.Enchantments;
import net.minecraft.world.level.GameType;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.ChestBlock;
import net.minecraft.world.level.block.FurnaceBlock;
import net.minecraft.world.level.block.LiquidBlock;
import net.minecraft.world.level.block.entity.ChestBlockEntity;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.phys.AABB;
import net.minecraft.world.phys.BlockHitResult;
import net.minecraft.world.phys.Vec3;
import net.neoforged.neoforge.gametest.GameTestHolder;
import net.neoforged.neoforge.gametest.PrefixGameTestTemplate;
import net.neoforged.neoforge.registries.DeferredItem;

/**
 * Wave 3: durability and attack per tool material and per armor set against the manifest, the
 * pre-enchantment sets (R7), the Queen set's legacy armor value (R5), the Crystal Furnace's
 * 150-tick smelt and fuel table, and the four builders (catalogue README 4.4, R17).
 *
 * <p>The builders that outgrow the 13x11x13 arena (garden 15x18x10, tunnel 11x5x64) run in
 * {@code arena_large} (48x12x72, generated by the same recipe as {@code arena}: one stone layer at
 * template y = 0). In helper coordinates that floor is relative y = 1 - the template loads one block
 * above the structure block (W02.md) - so every test here stands its player at y = 2.
 */
@GameTestHolder(OreSpawn.MOD_ID)
@PrefixGameTestTemplate(false)
public class W03GameTests {

    private static final String ARENA = "arena";
    private static final String ARENA_LARGE = "arena_large";
    private static final double EPS = 1.0e-6;

    // ------------------------------------------------------------------ w03-tools

    /** One tool or weapon: max damage (setMaxDamage or the tier's maxUses) and the 1.21.1 attack total (R6). */
    private record ToolPin(DeferredItem<? extends Item> holder, int maxDamage, int attack) {}

    /**
     * Every W03 tool and weapon carries its original durability - the class's {@code setMaxDamage}
     * where the original called it, else the material's {@code maxUses} - and the R6 attack total
     * {@code 1 + modifier + tier bonus}: swords {@code 4 + damage} of 1.7.10, pickaxes {@code 2 +},
     * shovels {@code 1 +}, axes {@code 3 +}, hoes the bare 1. Manifest {@code tool_materials}.
     */
    @GameTest(template = ARENA)
    public static void everyToolAndWeaponCarriesTheOriginalDurabilityAndAttack(GameTestHelper helper) {
        List<ToolPin> pins = List.of(
                new ToolPin(ModItems.POISON_SWORD, 1300, 10),
                new ToolPin(ModItems.AMETHYST_SWORD, 2000, 15),
                new ToolPin(ModItems.AMETHYST_PICKAXE, 2000, 14),
                new ToolPin(ModItems.AMETHYST_SHOVEL, 2000, 13),
                new ToolPin(ModItems.AMETHYST_HOE, 2000, 1),
                new ToolPin(ModItems.AMETHYST_AXE, 2000, 15),
                new ToolPin(ModItems.RUBY_SWORD, 1500, 20),
                new ToolPin(ModItems.RUBY_PICKAXE, 1500, 19),
                new ToolPin(ModItems.RUBY_SHOVEL, 1500, 18),
                new ToolPin(ModItems.RUBY_HOE, 1500, 1),
                new ToolPin(ModItems.RUBY_AXE, 1500, 20),
                new ToolPin(ModItems.EMERALD_SWORD, 1300, 10),
                new ToolPin(ModItems.EMERALD_PICKAXE, 1300, 9),
                new ToolPin(ModItems.EMERALD_SHOVEL, 1300, 8),
                new ToolPin(ModItems.EMERALD_HOE, 1300, 1),
                new ToolPin(ModItems.EMERALD_AXE, 1300, 10),
                new ToolPin(ModItems.EXPERIENCE_SWORD, 1400, 10),
                new ToolPin(ModItems.ULTIMATE_SWORD, 3000, 40),
                new ToolPin(ModItems.ULTIMATE_PICKAXE, 3000, 39),
                new ToolPin(ModItems.ULTIMATE_SHOVEL, 3000, 38),
                new ToolPin(ModItems.ULTIMATE_HOE, 3000, 1),
                new ToolPin(ModItems.ULTIMATE_AXE, 3000, 40),
                new ToolPin(ModItems.MANTIS_CLAW, 1000, 10),
                new ToolPin(ModItems.BIG_HAMMER, 9000, 15),
                new ToolPin(ModItems.NIGHTMARE_SWORD, 1200, 30),
                new ToolPin(ModItems.CRYSTALWOOD_SWORD, 300, 6),
                new ToolPin(ModItems.CRYSTALWOOD_PICKAXE, 300, 5),
                new ToolPin(ModItems.CRYSTALWOOD_SHOVEL, 300, 4),
                new ToolPin(ModItems.CRYSTALWOOD_HOE, 300, 1),
                new ToolPin(ModItems.CRYSTALWOOD_AXE, 300, 6),
                new ToolPin(ModItems.CRYSTALPINK_SWORD, 1100, 11),
                new ToolPin(ModItems.CRYSTALPINK_PICKAXE, 1100, 10),
                new ToolPin(ModItems.CRYSTALPINK_SHOVEL, 1100, 9),
                new ToolPin(ModItems.CRYSTALPINK_HOE, 1100, 1),
                new ToolPin(ModItems.CRYSTALPINK_AXE, 1100, 11),
                new ToolPin(ModItems.CRYSTALSTONE_SWORD, 800, 9),
                new ToolPin(ModItems.CRYSTALSTONE_PICKAXE, 800, 8),
                new ToolPin(ModItems.CRYSTALSTONE_SHOVEL, 800, 7),
                new ToolPin(ModItems.CRYSTALSTONE_HOE, 800, 1),
                new ToolPin(ModItems.CRYSTALSTONE_AXE, 800, 9),
                new ToolPin(ModItems.TIGERSEYE_SWORD, 1600, 12),
                new ToolPin(ModItems.TIGERSEYE_PICKAXE, 1600, 11),
                new ToolPin(ModItems.TIGERSEYE_SHOVEL, 1600, 10),
                new ToolPin(ModItems.TIGERSEYE_HOE, 1600, 1),
                new ToolPin(ModItems.TIGERSEYE_AXE, 1600, 12),
                new ToolPin(ModItems.BATTLE_AXE, 3000, 50),
                new ToolPin(ModItems.CHAINSAW, 3000, 60),
                new ToolPin(ModItems.QUEEN_BATTLE_AXE, 3000, 666),
                new ToolPin(ModItems.ROSE_SWORD, 1300, 10));
        if (pins.size() != 49) {
            helper.fail("expected 49 W03 tool and weapon holders, found " + pins.size());
        }
        for (ToolPin pin : pins) {
            ItemStack stack = new ItemStack(pin.holder().get());
            if (stack.getMaxStackSize() != 1) {
                helper.fail(pin.holder().getId() + " stacks to " + stack.getMaxStackSize() + ", expected 1");
            }
            if (stack.getMaxDamage() != pin.maxDamage()) {
                helper.fail(pin.holder().getId() + " has max damage " + stack.getMaxDamage() + ", expected " + pin.maxDamage());
            }
            double attack = attackDamage(stack);
            if (Math.abs(attack - pin.attack()) > EPS) {
                helper.fail(pin.holder().getId() + " attacks for " + attack + ", expected " + pin.attack());
            }
        }
        helper.succeed();
    }

    /** The player's base 1 plus every ADD_VALUE attack modifier the stack grants in the main hand. */
    private static double attackDamage(ItemStack stack) {
        double[] sum = {1.0};
        stack.forEachModifier(EquipmentSlot.MAINHAND, (attribute, modifier) -> {
            if (attribute.value() == Attributes.ATTACK_DAMAGE.value()
                    && modifier.operation() == AttributeModifier.Operation.ADD_VALUE) {
                sum[0] += modifier.amount();
            }
        });
        return sum[0];
    }

    /**
     * R7 on the tools: NightmareSword.onCreated gives Sharpness I, Knockback III, Fire Aspect I and a
     * bare stack gets the same set on its first tick; EmeraldPickaxe has no onCreated and gets Silk
     * Touch I only through the tick; UltimatePickaxe Efficiency V and Fortune V; UltimateSword with
     * the default magic 5: Sharpness/Smite/Bane 5, Knockback/Looting/Unbreaking 3, Fire Aspect 2;
     * the Battle Axe only Looting 3 and Unbreaking 3; the Chainsaw nothing, crafted or ticked.
     */
    @GameTest(template = ARENA)
    public static void toolsCarryTheirPreEnchantmentsOnCraftAndOnFirstTick(GameTestHelper helper) {
        Player player = helper.makeMockPlayer(GameType.SURVIVAL);

        ItemStack crafted = new ItemStack(ModItems.NIGHTMARE_SWORD.get());
        crafted.getItem().onCraftedBy(crafted, helper.getLevel(), player);
        expectEnchantments(helper, crafted, Map.of(Enchantments.SHARPNESS, 1, Enchantments.KNOCKBACK, 3, Enchantments.FIRE_ASPECT, 1));

        ItemStack ticked = new ItemStack(ModItems.NIGHTMARE_SWORD.get());
        ticked.getItem().inventoryTick(ticked, helper.getLevel(), player, 0, false);
        expectEnchantments(helper, ticked, Map.of(Enchantments.SHARPNESS, 1, Enchantments.KNOCKBACK, 3, Enchantments.FIRE_ASPECT, 1));
        // A second tick with the sentinel present adds nothing (the original checked getEnchantmentLevel first).
        ticked.getItem().inventoryTick(ticked, helper.getLevel(), player, 0, false);
        expectEnchantments(helper, ticked, Map.of(Enchantments.SHARPNESS, 1, Enchantments.KNOCKBACK, 3, Enchantments.FIRE_ASPECT, 1));

        ItemStack emerald = new ItemStack(ModItems.EMERALD_PICKAXE.get());
        emerald.getItem().onCraftedBy(emerald, helper.getLevel(), player);
        expectEnchantments(helper, emerald, Map.of());
        emerald.getItem().inventoryTick(emerald, helper.getLevel(), player, 0, false);
        expectEnchantments(helper, emerald, Map.of(Enchantments.SILK_TOUCH, 1));

        ItemStack ultimatePickaxe = new ItemStack(ModItems.ULTIMATE_PICKAXE.get());
        ultimatePickaxe.getItem().onCraftedBy(ultimatePickaxe, helper.getLevel(), player);
        expectEnchantments(helper, ultimatePickaxe, Map.of(Enchantments.EFFICIENCY, 5, Enchantments.FORTUNE, 5));

        ItemStack ultimateSword = new ItemStack(ModItems.ULTIMATE_SWORD.get());
        ultimateSword.getItem().onCraftedBy(ultimateSword, helper.getLevel(), player);
        expectEnchantments(helper, ultimateSword, Map.of(
                Enchantments.SHARPNESS, 5, Enchantments.SMITE, 5, Enchantments.BANE_OF_ARTHROPODS, 5,
                Enchantments.KNOCKBACK, 3, Enchantments.LOOTING, 3, Enchantments.UNBREAKING, 3, Enchantments.FIRE_ASPECT, 2));

        ItemStack battleAxe = new ItemStack(ModItems.BATTLE_AXE.get());
        battleAxe.getItem().inventoryTick(battleAxe, helper.getLevel(), player, 0, false);
        expectEnchantments(helper, battleAxe, Map.of(Enchantments.LOOTING, 3, Enchantments.UNBREAKING, 3));

        ItemStack chainsaw = new ItemStack(ModItems.CHAINSAW.get());
        chainsaw.getItem().onCraftedBy(chainsaw, helper.getLevel(), player);
        chainsaw.getItem().inventoryTick(chainsaw, helper.getLevel(), player, 0, false);
        expectEnchantments(helper, chainsaw, Map.of());
        helper.succeed();
    }

    // ------------------------------------------------------------------ w03-armor

    /** One armor set: prefix, EnumHelper.addArmorMaterial durability, {head, chest, legs, boots}, enchantability. */
    private record ArmorPin(String prefix, int durability, int[] defense, int enchantability) {}

    private static final List<ArmorPin> ARMOR_PINS = List.of(
            new ArmorPin("ultimate", 200, new int[] {6, 12, 10, 6}, 100),
            new ArmorPin("mobzilla", 1000, new int[] {7, 13, 11, 7}, 150),
            new ArmorPin("lavaeel", 40, new int[] {2, 7, 5, 2}, 35),
            new ArmorPin("mothscale", 50, new int[] {2, 7, 5, 2}, 50),
            new ArmorPin("emerald", 60, new int[] {3, 8, 6, 3}, 40),
            new ArmorPin("experience", 70, new int[] {5, 9, 7, 4}, 50),
            new ArmorPin("ruby", 90, new int[] {4, 9, 8, 4}, 40),
            new ArmorPin("amethyst", 100, new int[] {4, 8, 7, 3}, 40),
            new ArmorPin("pink", 50, new int[] {3, 7, 5, 2}, 40),
            new ArmorPin("tigerseye", 80, new int[] {4, 8, 7, 4}, 55),
            new ArmorPin("peacock", 40, new int[] {2, 5, 4, 2}, 30),
            new ArmorPin("royal", 2000, new int[] {8, 14, 12, 8}, 200),
            new ArmorPin("lapis", 60, new int[] {2, 7, 5, 2}, 60),
            new ArmorPin("queen", 1500, new int[] {9, 16, 14, 9}, 150));

    private static final ArmorItem.Type[] PIECES = {
            ArmorItem.Type.HELMET, ArmorItem.Type.CHESTPLATE, ArmorItem.Type.LEGGINGS, ArmorItem.Type.BOOTS};
    private static final String[] PIECE_SUFFIX = {"_helmet", "_chest", "_leggings", "_boots"};

    private static Item item(String id) {
        return BuiltInRegistries.ITEM.get(net.minecraft.resources.ResourceLocation.fromNamespaceAndPath(OreSpawn.MOD_ID, id));
    }

    /**
     * The 1.7.10 sword block of the classes that overrode {@code getMaxItemUseDuration}
     * (UltimateSword.java:148-150 = 9000 for all four variants, NightmareSword.java:49-51 = 5000,
     * ExperienceSword.java:140-142, PoisonSword.java:56-58 and MantisClaw.java:37-39 = 3000):
     * right-click starts the block with that duration, and {@code EntityPlayer.damageEntity} then
     * took {@code (1 + damage) * 0.5} of every blockable hit <em>before</em> armor - 10 cactus
     * points become 5.5; over a single emerald_chest (8 points, R5) {@code 5.5 * 17 / 25 = 3.74};
     * an unblockable source ({@code #minecraft:bypasses_armor}) passes in full, as does a hit on
     * a player who is not blocking.
     */
    @GameTest(template = ARENA)
    public static void blockingSwordsHalveBlockableDamageBeforeArmor(GameTestHelper helper) {
        DamageSource cactus = helper.getLevel().damageSources().cactus();
        DamageSource generic = helper.getLevel().damageSources().generic();
        if (cactus.is(DamageTypeTags.BYPASSES_ARMOR) || !generic.is(DamageTypeTags.BYPASSES_ARMOR)) {
            helper.fail("precondition: minecraft:cactus must be blockable and minecraft:generic unblockable");
        }
        // Every value is the class's own func_77626_a in the 20.3 jar (DECISIONS R19).
        Map<String, Integer> durations = Map.ofEntries(
                Map.entry("ultimatesword", 9000), Map.entry("battleaxesmall", 9000), Map.entry("chainsawsmall", 9000),
                Map.entry("queenbattleaxesmall", 9000), Map.entry("nightmaresword", 5000), Map.entry("experiencesword", 3000),
                Map.entry("poisonsword", 3000), Map.entry("mantisclaw", 3000), Map.entry("amethystsword", 3500),
                Map.entry("crystalwoodsword", 300), Map.entry("crystalpinksword", 300), Map.entry("crystalstonesword", 300),
                Map.entry("tigerseye_sword", 300), Map.entry("rubysword", 4000), Map.entry("emeraldsword", 3000),
                Map.entry("rosesword", 3000), Map.entry("bighammer", 3000));
        for (Map.Entry<String, Integer> entry : durations.entrySet()) {
            Player player = helper.makeMockPlayer(GameType.SURVIVAL);
            ItemStack sword = new ItemStack(item(entry.getKey()));
            player.setItemInHand(InteractionHand.MAIN_HAND, sword);
            if (sword.getUseAnimation() != UseAnim.BLOCK || sword.getUseDuration(player) != entry.getValue()) {
                helper.fail(entry.getKey() + " has use animation " + sword.getUseAnimation() + " for "
                        + sword.getUseDuration(player) + " ticks, expected BLOCK for " + entry.getValue());
            }
            if (sword.use(helper.getLevel(), player, InteractionHand.MAIN_HAND).getResult() != InteractionResult.CONSUME
                    || !player.isUsingItem() || player.getUseItem() != sword) {
                helper.fail(entry.getKey() + ": right-click did not start the block");
            }
            expectHealthAfterHit(helper, player, cactus, 10.0F, 20.0F - (1.0F + 10.0F) * 0.5F,
                    entry.getKey() + " blocking a blockable hit");
        }

        Player idle = helper.makeMockPlayer(GameType.SURVIVAL);
        idle.setItemInHand(InteractionHand.MAIN_HAND, new ItemStack(item("ultimatesword")));
        expectHealthAfterHit(helper, idle, cactus, 10.0F, 10.0F, "ultimatesword held but not blocking");

        Player unblockable = helper.makeMockPlayer(GameType.SURVIVAL);
        unblockable.setItemInHand(InteractionHand.MAIN_HAND, new ItemStack(item("ultimatesword")));
        unblockable.startUsingItem(InteractionHand.MAIN_HAND);
        expectHealthAfterHit(helper, unblockable, generic, 10.0F, 10.0F, "ultimatesword blocking an unblockable hit");

        Player armored = helper.makeMockPlayer(GameType.SURVIVAL);
        armored.setItemSlot(EquipmentSlot.CHEST, new ItemStack(item("emerald_chest")));
        applyEquipmentAttributes(armored);
        armored.setItemInHand(InteractionHand.MAIN_HAND, new ItemStack(item("ultimatesword")));
        armored.startUsingItem(InteractionHand.MAIN_HAND);
        expectHealthAfterHit(helper, armored, cactus, 10.0F, 20.0F - (1.0F + 10.0F) * 0.5F * (25.0F - 8.0F) / 25.0F,
                "ultimatesword blocking over a single emerald_chest: halved first, then the R5 armor formula");
        helper.succeed();
    }

    /**
     * All 56 pieces: the registered {@code ArmorMaterial} carries the manifest reductions and
     * enchantability, and each piece's max damage is {@code type.getDurability(durability)} - the
     * 11/16/15/13 factors of 1.7.10's {@code ItemArmor.maxDamageArray} (Royal chest 32000, Queen
     * chest 24000, Lava Eel chest 640). Stack size 1, tag {@code orespawn:legacy_armor}.
     */
    @GameTest(template = ARENA)
    public static void everyArmorPieceCarriesTheOriginalDefenseAndDurability(GameTestHelper helper) {
        int pieces = 0;
        for (ArmorPin pin : ARMOR_PINS) {
            for (int i = 0; i < 4; i++) {
                String id = pin.prefix() + PIECE_SUFFIX[i];
                Item item = item(id);
                if (!(item instanceof ItemOreSpawnArmor armor)) {
                    helper.fail(id + " is not an ItemOreSpawnArmor: " + item);
                    return;
                }
                pieces++;
                ItemStack stack = new ItemStack(armor);
                int defense = armor.getMaterial().value().getDefense(PIECES[i]);
                if (defense != pin.defense()[i]) {
                    helper.fail(id + " defends " + defense + ", expected " + pin.defense()[i]);
                }
                if (armor.getMaterial().value().enchantmentValue() != pin.enchantability()) {
                    helper.fail(id + " enchantability " + armor.getMaterial().value().enchantmentValue() + ", expected " + pin.enchantability());
                }
                int expectedDurability = PIECES[i].getDurability(pin.durability());
                if (stack.getMaxDamage() != expectedDurability) {
                    helper.fail(id + " max damage " + stack.getMaxDamage() + ", expected " + expectedDurability);
                }
                if (stack.getMaxStackSize() != 1) {
                    helper.fail(id + " stacks to " + stack.getMaxStackSize());
                }
                if (armor.get_armor_type() != i) {
                    helper.fail(id + " armor_type " + armor.get_armor_type() + ", expected " + i);
                }
                if (!LegacyArmorFormula.isLegacyArmor(stack) || !stack.is(LegacyArmorFormula.LEGACY_ARMOR)) {
                    helper.fail(id + " is not legacy armor by interface and tag");
                }
            }
        }
        if (pieces != 56) {
            helper.fail("expected 56 armor pieces, found " + pieces);
        }
        if (new ItemStack(item("royal_chest")).getMaxDamage() != 32000
                || new ItemStack(item("queen_chest")).getMaxDamage() != 24000
                || new ItemStack(item("lavaeel_chest")).getMaxDamage() != 640) {
            helper.fail("the three documented chest durabilities do not match (32000 / 24000 / 640)");
        }
        helper.succeed();
    }

    /**
     * R7 on the armor (ItemOreSpawnArmor.onCreated / onUpdate): a crafted ultimate_helmet carries
     * Protection 5, Fire 5, Blast 5, Projectile 5, Respiration 2, Aqua Affinity 3 and no Feather
     * Falling; ultimate_boots ticked once get the four protections and Feather Falling 3 but no
     * Respiration; mobzilla_chest Protection/Fire/Blast/Projectile 10 and Unbreaking 5; emerald and
     * queen pieces nothing, crafted or ticked.
     */
    @GameTest(template = ARENA)
    public static void armorEnchantmentSetsFollowTheOriginal(GameTestHelper helper) {
        Player player = helper.makeMockPlayer(GameType.SURVIVAL);

        ItemStack helmet = new ItemStack(item("ultimate_helmet"));
        helmet.getItem().onCraftedBy(helmet, helper.getLevel(), player);
        expectEnchantments(helper, helmet, Map.of(
                Enchantments.PROTECTION, 5, Enchantments.FIRE_PROTECTION, 5, Enchantments.BLAST_PROTECTION, 5,
                Enchantments.PROJECTILE_PROTECTION, 5, Enchantments.RESPIRATION, 2, Enchantments.AQUA_AFFINITY, 3));

        ItemStack boots = new ItemStack(item("ultimate_boots"));
        boots.getItem().inventoryTick(boots, helper.getLevel(), player, 0, false);
        expectEnchantments(helper, boots, Map.of(
                Enchantments.PROTECTION, 5, Enchantments.FIRE_PROTECTION, 5, Enchantments.BLAST_PROTECTION, 5,
                Enchantments.PROJECTILE_PROTECTION, 5, Enchantments.FEATHER_FALLING, 3));
        boots.getItem().inventoryTick(boots, helper.getLevel(), player, 0, false);
        expectEnchantments(helper, boots, Map.of(
                Enchantments.PROTECTION, 5, Enchantments.FIRE_PROTECTION, 5, Enchantments.BLAST_PROTECTION, 5,
                Enchantments.PROJECTILE_PROTECTION, 5, Enchantments.FEATHER_FALLING, 3));

        ItemStack chest = new ItemStack(item("mobzilla_chest"));
        chest.getItem().onCraftedBy(chest, helper.getLevel(), player);
        expectEnchantments(helper, chest, Map.of(
                Enchantments.PROTECTION, 10, Enchantments.FIRE_PROTECTION, 10, Enchantments.BLAST_PROTECTION, 10,
                Enchantments.PROJECTILE_PROTECTION, 10, Enchantments.UNBREAKING, 5));

        for (String id : List.of("emerald_helmet", "emerald_boots", "queen_chest", "queen_boots")) {
            ItemStack plain = new ItemStack(item(id));
            plain.getItem().onCraftedBy(plain, helper.getLevel(), player);
            plain.getItem().inventoryTick(plain, helper.getLevel(), player, 0, false);
            expectEnchantments(helper, plain, Map.of());
        }
        helper.succeed();
    }

    /**
     * ItemOreSpawnArmor.onArmorTick (:341-363): worn royal_boots clamp a fall to -0.1 and zero the
     * fall distance, peacock_boots the same, queen_boots to -0.25; with RoyalGlideEnable = 0 the
     * Royal and Queen boots do nothing, Peacock still glides.
     */
    @GameTest(template = ARENA)
    public static void royalPeacockAndQueenBootsGlide(GameTestHelper helper) {
        Player player = helper.makeMockPlayer(GameType.SURVIVAL);
        expectGlide(helper, player, "royal_boots", -0.1);
        expectGlide(helper, player, "peacock_boots", -0.1);
        expectGlide(helper, player, "queen_boots", -0.25);
        expectGlide(helper, player, "emerald_boots", -1.0);
        int saved = OreSpawnConfig.TWEAKS.RoyalGlideEnable.get();
        OreSpawnConfig.TWEAKS.RoyalGlideEnable.set(0);
        try {
            expectGlide(helper, player, "royal_boots", -1.0);
            expectGlide(helper, player, "queen_boots", -1.0);
            expectGlide(helper, player, "peacock_boots", -0.1);
        } finally {
            OreSpawnConfig.TWEAKS.RoyalGlideEnable.set(saved);
        }
        helper.succeed();
    }

    private static void expectGlide(GameTestHelper helper, Player player, String bootsId, double expectedY) {
        ItemStack boots = new ItemStack(item(bootsId));
        player.setItemSlot(EquipmentSlot.FEET, boots);
        player.setDeltaMovement(0.0, -1.0, 0.0);
        player.fallDistance = 5.0f;
        // Inventory.tick hands the armor compartment's stacks to inventoryTick; the piece recognises
        // itself as worn through player.getItemBySlot(type.getSlot()) == stack.
        boots.getItem().inventoryTick(boots, helper.getLevel(), player, 36, false);
        Vec3 motion = player.getDeltaMovement();
        if (Math.abs(motion.y - expectedY) > 1.0e-6) {
            helper.fail(bootsId + " left motion y = " + motion.y + ", expected " + expectedY);
        }
        boolean expectReset = expectedY > -1.0;
        if (expectReset && player.fallDistance != 0.0f) {
            helper.fail(bootsId + " left fallDistance " + player.fallDistance + ", expected 0");
        }
        if (!expectReset && player.fallDistance != 5.0f) {
            helper.fail(bootsId + " touched fallDistance (" + player.fallDistance + ") without gliding");
        }
        player.setItemSlot(EquipmentSlot.FEET, ItemStack.EMPTY);
    }

    /**
     * R5: a player in the full Queen Scale set has 9 + 16 + 14 + 9 = 48 armor points under the
     * legacy formula (the attribute would clamp at 30), the Royal Guardian set 42, and the formula
     * applies to a player wearing a single piece.
     */
    @GameTest(template = ARENA)
    public static void queenSetGivesFortyEightLegacyArmorPoints(GameTestHelper helper) {
        Player player = helper.makeMockPlayer(GameType.SURVIVAL);
        if (LegacyArmorFormula.applies(player)) {
            helper.fail("the legacy formula applies to a bare player");
        }
        wear(player, "queen");
        if (!LegacyArmorFormula.applies(player) || LegacyArmorFormula.armorValue(player) != 48) {
            helper.fail("full queen set: applies=" + LegacyArmorFormula.applies(player)
                    + ", armor " + LegacyArmorFormula.armorValue(player) + ", expected 48");
        }
        wear(player, "royal");
        if (LegacyArmorFormula.armorValue(player) != 42) {
            helper.fail("full royal set: armor " + LegacyArmorFormula.armorValue(player) + ", expected 42");
        }
        for (EquipmentSlot slot : EquipmentSlot.values()) {
            if (slot.isArmor()) {
                player.setItemSlot(slot, ItemStack.EMPTY);
            }
        }
        player.setItemSlot(EquipmentSlot.HEAD, new ItemStack(item("lapis_helmet")));
        if (!LegacyArmorFormula.applies(player) || LegacyArmorFormula.armorValue(player) != 2) {
            helper.fail("lapis_helmet alone: applies=" + LegacyArmorFormula.applies(player)
                    + ", armor " + LegacyArmorFormula.armorValue(player) + ", expected 2");
        }
        helper.succeed();
    }

    private static void wear(Player player, String prefix) {
        player.setItemSlot(EquipmentSlot.HEAD, new ItemStack(item(prefix + "_helmet")));
        player.setItemSlot(EquipmentSlot.CHEST, new ItemStack(item(prefix + "_chest")));
        player.setItemSlot(EquipmentSlot.LEGS, new ItemStack(item(prefix + "_leggings")));
        player.setItemSlot(EquipmentSlot.FEET, new ItemStack(item(prefix + "_boots")));
    }

    /**
     * R5 through {@code LivingEntity.hurt} itself, with the real armor items: the full Queen Scale
     * set (48 points) takes nothing from a 10-point cactus hit - vanilla would clamp the attribute
     * to 30 and let 2 through - and a player in nothing but the emerald_chest (8 points) takes
     * {@code 10 * (25 - 8) / 25 = 6.8}, the 1.7.10 {@code applyArmorCalculations} number, where
     * vanilla's {@code CombatRules.getDamageAfterAbsorb} would take 8.8. An unblockable source
     * ({@code #minecraft:bypasses_armor}, 1.7.10's {@code isUnblockable()}) passes the Queen set
     * untouched.
     *
     * <p>The worn items' attribute modifiers are applied by hand, as {@code LivingEntity.tick} would
     * for a real player: a mock player never ticks, and with the {@code ARMOR} attribute at 0 vanilla
     * would reduce nothing either, which would let the Queen case pass for the wrong reason.
     */
    @GameTest(template = ARENA)
    public static void queenSetBlocksEverythingAndOneEmeraldPieceReducesByTheOriginalFormula(GameTestHelper helper) {
        DamageSource cactus = helper.getLevel().damageSources().cactus();
        if (cactus.is(DamageTypeTags.BYPASSES_ARMOR)) {
            helper.fail("precondition: minecraft:cactus must be blockable");
        }

        Player queen = helper.makeMockPlayer(GameType.SURVIVAL);
        wear(queen, "queen");
        applyEquipmentAttributes(queen);
        if (queen.getAttributeValue(Attributes.ARMOR) > 30.0 + EPS) {
            helper.fail("precondition: the ARMOR attribute is expected to clamp at 30, read " + queen.getAttributeValue(Attributes.ARMOR));
        }
        expectHealthAfterHit(helper, queen, cactus, 10.0F, 20.0F, "full Queen Scale set (48 points) against a blockable hit");

        Player emerald = helper.makeMockPlayer(GameType.SURVIVAL);
        emerald.setItemSlot(EquipmentSlot.CHEST, new ItemStack(item("emerald_chest")));
        applyEquipmentAttributes(emerald);
        if (LegacyArmorFormula.armorValue(emerald) != 8) {
            helper.fail("emerald_chest alone sums to " + LegacyArmorFormula.armorValue(emerald) + " armor points, expected 8");
        }
        expectHealthAfterHit(helper, emerald, cactus, 10.0F, 20.0F - 10.0F * (25.0F - 8.0F) / 25.0F,
                "a single emerald_chest (8 points) against a blockable hit");

        Player unblockable = helper.makeMockPlayer(GameType.SURVIVAL);
        wear(unblockable, "queen");
        applyEquipmentAttributes(unblockable);
        DamageSource generic = helper.getLevel().damageSources().generic();
        if (!generic.is(DamageTypeTags.BYPASSES_ARMOR)) {
            helper.fail("precondition: minecraft:generic must bypass armor");
        }
        expectHealthAfterHit(helper, unblockable, generic, 10.0F, 10.0F, "full Queen Scale set against unblockable damage");
        helper.succeed();
    }

    /**
     * What {@code LivingEntity.tick} -> {@code collectEquipmentChanges} -> {@code handleEquipmentChanges}
     * does for a real player: puts the worn items' modifiers on the attributes (same helper as W01).
     */
    private static void applyEquipmentAttributes(Player player) {
        for (EquipmentSlot slot : EquipmentSlot.values()) {
            if (!slot.isArmor()) {
                continue;
            }
            player.getItemBySlot(slot).forEachModifier(slot, (attribute, modifier) -> {
                var instance = player.getAttribute(attribute);
                if (instance != null) {
                    instance.removeModifier(modifier.id());
                    instance.addTransientModifier(modifier);
                }
            });
        }
    }

    private static void expectHealthAfterHit(GameTestHelper helper, Player player, DamageSource source,
            float damage, float expectedRemaining, String what) {
        float before = player.getHealth();
        if (!player.hurt(source, damage)) {
            helper.fail(what + ": hurt() was refused");
        }
        float remaining = player.getHealth();
        if (Math.abs(remaining - expectedRemaining) > 0.05F) {
            helper.fail(what + ": health went from " + before + " to " + remaining
                    + " on " + damage + " damage, expected " + expectedRemaining);
        }
    }

    // ------------------------------------------------------------------ w03-workshop

    /**
     * TileEntityCrystalFurnace.updateEntity (:141-183): iron ore over one coal is an iron ingot after
     * exactly 150 ticks (checked at 140: still cooking; at 160: done, cook time back at 0, the block
     * LIT, the burn time counting down from the coal's 1600); breaking the block throws the slots out
     * as item entities and pays no experience.
     */
    @GameTest(template = ARENA, timeoutTicks = 300)
    public static void crystalFurnaceSmeltsInOneHundredFiftyTicks(GameTestHelper helper) {
        BlockPos rel = new BlockPos(3, 1, 3);
        helper.setBlock(rel, ModBlocks.CRYSTALFURNACE.get());
        BlockPos abs = helper.absolutePos(rel);
        TileEntityCrystalFurnace furnace = helper.getBlockEntity(rel);
        furnace.setItem(TileEntityCrystalFurnace.SLOT_INPUT, new ItemStack(Items.IRON_ORE));
        furnace.setItem(TileEntityCrystalFurnace.SLOT_FUEL, new ItemStack(Items.COAL));
        helper.runAfterDelay(140, () -> {
            if (!furnace.getItem(TileEntityCrystalFurnace.SLOT_OUTPUT).isEmpty()) {
                helper.fail("output appeared before tick 150: " + furnace.getItem(TileEntityCrystalFurnace.SLOT_OUTPUT));
            }
            if (furnace.furnaceCookTime < 130 || furnace.furnaceCookTime > 145) {
                helper.fail("cook time at tick 140 is " + furnace.furnaceCookTime);
            }
            if (!helper.getBlockState(rel).getValue(CrystalFurnace.LIT)) {
                helper.fail("furnace is not LIT while burning");
            }
            if (!furnace.getItem(TileEntityCrystalFurnace.SLOT_FUEL).isEmpty()) {
                helper.fail("the single coal was not consumed when burning started");
            }
        });
        helper.runAfterDelay(160, () -> {
            ItemStack out = furnace.getItem(TileEntityCrystalFurnace.SLOT_OUTPUT);
            if (!out.is(Items.IRON_INGOT) || out.getCount() != 1) {
                helper.fail("output at tick 160 is " + out + ", expected 1 iron ingot");
            }
            if (!furnace.getItem(TileEntityCrystalFurnace.SLOT_INPUT).isEmpty()) {
                helper.fail("input was not consumed");
            }
            if (furnace.furnaceCookTime != 0) {
                helper.fail("cook time after the smelt is " + furnace.furnaceCookTime + ", expected 0");
            }
            if (furnace.furnaceBurnTime < 1600 - 165 || furnace.furnaceBurnTime > 1600 - 155) {
                helper.fail("burn time at tick 160 is " + furnace.furnaceBurnTime + ", expected about 1440");
            }
            if (furnace.currentItemBurnTime != 1600) {
                helper.fail("current item burn time is " + furnace.currentItemBurnTime + ", expected 1600 (coal)");
            }
            if (!helper.getBlockState(rel).getValue(CrystalFurnace.LIT)) {
                helper.fail("furnace is not LIT after the smelt");
            }
            helper.getLevel().destroyBlock(abs, true);
            AABB box = new AABB(abs).inflate(2.0);
            List<ItemEntity> items = helper.getLevel().getEntitiesOfClass(ItemEntity.class, box);
            int ingots = items.stream().filter(e -> e.getItem().is(Items.IRON_INGOT)).mapToInt(e -> e.getItem().getCount()).sum();
            int furnaces = items.stream().filter(e -> e.getItem().is(ModItems.CRYSTALFURNACE.get())).mapToInt(e -> e.getItem().getCount()).sum();
            if (ingots != 1 || furnaces != 1 || items.size() != 2) {
                helper.fail("breaking dropped " + items.stream().map(ItemEntity::getItem).toList() + ", expected the ingot and the furnace");
            }
            if (!helper.getLevel().getEntitiesOfClass(ExperienceOrb.class, box).isEmpty()) {
                helper.fail("breaking the furnace paid experience; the original tracked none");
            }
            helper.succeed();
        });
    }

    /** TileEntityCrystalFurnace.getItemBurnTime (:221-272), the original list and nothing else (R18). */
    @GameTest(template = ARENA)
    public static void crystalFurnaceFuelTableIsTheOriginalList(GameTestHelper helper) {
        Map<ItemStack, Integer> table = Map.ofEntries(
                Map.entry(new ItemStack(ModBlocks.CRYSTALCOAL.get()), 20000),
                Map.entry(new ItemStack(ModBlocks.CRYSTAL_PLANKS.get()), 300),
                Map.entry(new ItemStack(ModBlocks.CRYSTAL_TREE_LOG.get()), 300),
                Map.entry(new ItemStack(ModBlocks.CRYSTALWORKBENCH.get()), 300),
                Map.entry(new ItemStack(Items.OAK_PLANKS), 300),
                Map.entry(new ItemStack(Items.OAK_SLAB), 150),
                Map.entry(new ItemStack(Items.WOODEN_PICKAXE), 200),
                Map.entry(new ItemStack(Items.STICK), 100),
                Map.entry(new ItemStack(Items.COAL), 1600),
                Map.entry(new ItemStack(Items.CHARCOAL), 1600),
                Map.entry(new ItemStack(Items.LAVA_BUCKET), 20000),
                Map.entry(new ItemStack(Items.OAK_SAPLING), 100),
                Map.entry(new ItemStack(Items.BLAZE_ROD), 2400),
                Map.entry(new ItemStack(Items.COAL_BLOCK), 16000),
                Map.entry(new ItemStack(Items.OAK_BUTTON), 0),
                Map.entry(new ItemStack(Items.CRIMSON_PLANKS), 0),
                Map.entry(new ItemStack(Items.DRIED_KELP_BLOCK), 0),
                Map.entry(new ItemStack(Items.BAMBOO), 0),
                Map.entry(ItemStack.EMPTY, 0));
        for (Map.Entry<ItemStack, Integer> entry : table.entrySet()) {
            int burn = TileEntityCrystalFurnace.getItemBurnTime(entry.getKey());
            if (burn != entry.getValue()) {
                helper.fail(entry.getKey() + " burns " + burn + ", expected " + entry.getValue());
            }
        }
        helper.succeed();
    }

    // ------------------------------------------------------------------ w03-utility

    /**
     * InstantShelter.onItemUse (:21-131): clicking the floor east of the player builds the 7x7 hut
     * around him - cobblestone floor one below his feet, plank walls, a glass row at k = 3, a plank
     * roof at k = 4, a two-high door hole in the east wall, and furnace / crafting table / chest (14
     * stacks, slot 12 = 4 Salt Ore) against the south wall facing north. One item is consumed.
     */
    @GameTest(template = ARENA)
    public static void instantShelterBuildsTheHutAroundThePlayer(GameTestHelper helper) {
        // The arena's stone floor is relative y = 1 (the template loads one block above the structure
        // block, see W02.md); the player stands on it at y = 2 and clicks the floor block east of him.
        Player player = helper.makeMockPlayer(GameType.SURVIVAL);
        BlockPos centre = helper.absolutePos(new BlockPos(6, 2, 6));
        player.setPos(centre.getX() + 0.5, centre.getY(), centre.getZ() + 0.5);
        ItemStack stack = new ItemStack(ModItems.INSTANT_SHELTER.get(), 16);
        InteractionResult result = useOn(helper, player, stack, hitTop(helper.absolutePos(new BlockPos(7, 1, 6))));
        if (result != InteractionResult.CONSUME) {
            helper.fail("useOn returned " + result);
        }
        if (stack.getCount() != 15) {
            helper.fail("shelter left " + stack.getCount() + " items, expected 15");
        }
        for (int i = -3; i <= 3; i++) {
            for (int j = -3; j <= 3; j++) {
                for (int k = 0; k <= 4; k++) {
                    BlockPos rel = new BlockPos(6 + i, 1 + k, 6 + j);
                    Block expected;
                    if (k == 4) {
                        expected = Blocks.OAK_PLANKS;
                    } else if (k == 0) {
                        expected = Blocks.COBBLESTONE;
                    } else if (Math.abs(i) == 3 || Math.abs(j) == 3) {
                        if (k == 3) {
                            expected = Blocks.GLASS;
                        } else if (i == 3 && j == 0) {
                            expected = Blocks.AIR; // the door hole, k = 1 and 2
                        } else {
                            expected = Blocks.OAK_PLANKS;
                        }
                    } else if (k == 1 && j == 2 && i == 2) {
                        expected = Blocks.FURNACE;
                    } else if (k == 1 && j == 2 && i == 1) {
                        expected = Blocks.CRAFTING_TABLE;
                    } else if (k == 1 && j == 2 && i == 0) {
                        expected = Blocks.CHEST;
                    } else {
                        expected = Blocks.AIR;
                    }
                    BlockState state = helper.getBlockState(rel);
                    if (!state.is(expected)) {
                        helper.fail("shelter block at " + rel + " is " + state + ", expected " + expected);
                        return;
                    }
                }
            }
        }
        if (helper.getBlockState(new BlockPos(8, 2, 8)).getValue(FurnaceBlock.FACING) != Direction.NORTH
                || helper.getBlockState(new BlockPos(6, 2, 8)).getValue(ChestBlock.FACING) != Direction.NORTH) {
            helper.fail("furnace and chest must face north (stuffdir 2) when the door is east");
        }
        if (!(helper.getBlockEntity(new BlockPos(6, 2, 8)) instanceof ChestBlockEntity chest)) {
            helper.fail("no chest block entity");
            return;
        }
        int filled = 0;
        for (int slot = 0; slot < chest.getContainerSize(); slot++) {
            if (!chest.getItem(slot).isEmpty()) {
                filled++;
            }
        }
        ItemStack salt = chest.getItem(12);
        if (filled != 14 || !salt.is(ModItems.ORESALT.get()) || salt.getCount() != 4
                || !chest.getItem(0).is(Items.COMPASS) || !chest.getItem(13).is(Items.CHEST)) {
            helper.fail("chest holds " + filled + " stacks, slot 12 = " + salt + "; expected 14 stacks with 4 Salt Ore");
        }
        helper.succeed();
    }

    /**
     * ZooCage.onItemUse (:23-65) for zoo2 (cage_size 3, half width 2): a 5x5 quartz floor one below
     * the player's feet, glass walls two high, a quartz ceiling, air inside. One item consumed.
     */
    @GameTest(template = ARENA)
    public static void zooCageBuildsAGlassBoxAroundThePlayer(GameTestHelper helper) {
        Player player = helper.makeMockPlayer(GameType.SURVIVAL);
        BlockPos centre = helper.absolutePos(new BlockPos(6, 2, 6));
        player.setPos(centre.getX() + 0.5, centre.getY(), centre.getZ() + 0.5);
        ItemStack stack = new ItemStack(ModItems.ZOO_CAGE2.get(), 16);
        InteractionResult result = useOn(helper, player, stack, hitTop(helper.absolutePos(new BlockPos(6, 0, 6))));
        if (result != InteractionResult.CONSUME || stack.getCount() != 15) {
            helper.fail("zoo2 returned " + result + " and left " + stack.getCount() + " items");
        }
        for (int i = -2; i <= 2; i++) {
            for (int j = -2; j <= 2; j++) {
                for (int k = 0; k <= 3; k++) {
                    BlockPos rel = new BlockPos(6 + i, 1 + k, 6 + j);
                    Block expected;
                    if (k == 0 || k == 3) {
                        expected = Blocks.QUARTZ_BLOCK;
                    } else if (Math.abs(i) == 2 || Math.abs(j) == 2) {
                        expected = Blocks.GLASS;
                    } else {
                        expected = Blocks.AIR;
                    }
                    if (!helper.getBlockState(rel).is(expected)) {
                        helper.fail("cage block at " + rel + " is " + helper.getBlockState(rel) + ", expected " + expected);
                        return;
                    }
                }
            }
        }
        // The arena floor (relative y = 1) outside the cage is untouched, and nothing sits above the ceiling.
        if (!helper.getBlockState(new BlockPos(3, 1, 6)).is(Blocks.STONE) || !helper.getBlockState(new BlockPos(6, 5, 6)).isAir()) {
            helper.fail("zoo2 wrote outside its 5x5x4 box");
        }
        helper.succeed();
    }

    /**
     * InstantGarden.onItemUse (:20-139) with the player south of the garden: rows i = 1..13 as the
     * class's table (farmland + radish, lettuce, carrots, water on cobblestone, potatoes, wheat,
     * tomato, water, corn, strawberry, sand + sugar cane, water, melon stem), the edge rows 0 and 14
     * bare grass, and the water stays a source (no neighbour updates). One item consumed.
     */
    @GameTest(template = ARENA_LARGE)
    public static void instantGardenPlantsTheFifteenRows(GameTestHelper helper) {
        Player player = helper.makeMockPlayer(GameType.SURVIVAL);
        BlockPos feet = helper.absolutePos(new BlockPos(24, 2, 3));
        player.setPos(feet.getX() + 0.5, feet.getY(), feet.getZ() + 0.5);
        ItemStack stack = new ItemStack(ModItems.INSTANT_GARDEN.get(), 16);
        InteractionResult result = useOn(helper, player, stack, hitTop(helper.absolutePos(new BlockPos(24, 1, 4))));
        if (result != InteractionResult.CONSUME || stack.getCount() != 15) {
            helper.fail("garden returned " + result + " and left " + stack.getCount() + " items");
        }
        // Cleared volume: x 17..31, y 2..11, z 4..21; grass at y = 1 under all of it.
        for (int k = 0; k < 18; k++) {
            for (int j = -7; j <= 7; j++) {
                int x = 24 + j;
                int z = 4 + k;
                for (int i = 2; i <= 11; i++) {
                    BlockState s = helper.getBlockState(new BlockPos(x, i, z));
                    boolean cropRow = k >= 1 && k <= 16 && i == 2;
                    if (!cropRow && !s.isAir()) {
                        helper.fail("garden volume at " + new BlockPos(x, i, z) + " is " + s + ", expected air");
                        return;
                    }
                }
                if (k == 0 || k == 17) {
                    if (!helper.getBlockState(new BlockPos(x, 1, z)).is(Blocks.GRASS_BLOCK)) {
                        helper.fail("garden end row at " + new BlockPos(x, 1, z) + " is not grass");
                        return;
                    }
                    continue;
                }
                int row = j + 7;
                BlockState below = helper.getBlockState(new BlockPos(x, 1, z));
                BlockState plant = helper.getBlockState(new BlockPos(x, 2, z));
                BlockState under = helper.getBlockState(new BlockPos(x, 0, z));
                Block expectedBelow;
                Block expectedPlant;
                // y = 0 lies below the template floor (which is y = 1): only the water and sugar-cane
                // rows write there (cobblestone), everything else leaves it as the world had it.
                Block expectedUnder = null;
                switch (row) {
                    case 1 -> { expectedBelow = Blocks.FARMLAND; expectedPlant = ModBlocks.RADISH_PLANT.get(); }
                    case 2 -> { expectedBelow = Blocks.FARMLAND; expectedPlant = ModBlocks.LETTUCE_0.get(); }
                    case 3 -> { expectedBelow = Blocks.FARMLAND; expectedPlant = Blocks.CARROTS; }
                    case 4, 8, 12 -> { expectedBelow = Blocks.WATER; expectedPlant = Blocks.AIR; expectedUnder = Blocks.COBBLESTONE; }
                    case 5 -> { expectedBelow = Blocks.FARMLAND; expectedPlant = Blocks.POTATOES; }
                    case 6 -> { expectedBelow = Blocks.FARMLAND; expectedPlant = Blocks.WHEAT; }
                    case 7 -> { expectedBelow = Blocks.FARMLAND; expectedPlant = ModBlocks.TOMATO_0.get(); }
                    case 9 -> { expectedBelow = Blocks.FARMLAND; expectedPlant = ModBlocks.CORN_0.get(); }
                    case 10 -> { expectedBelow = Blocks.FARMLAND; expectedPlant = ModBlocks.STRAWBERRY_PLANT.get(); }
                    case 11 -> { expectedBelow = Blocks.SAND; expectedPlant = Blocks.SUGAR_CANE; expectedUnder = Blocks.COBBLESTONE; }
                    case 13 -> { expectedBelow = Blocks.FARMLAND; expectedPlant = Blocks.MELON_STEM; }
                    default -> { expectedBelow = Blocks.GRASS_BLOCK; expectedPlant = Blocks.AIR; }
                }
                if (!below.is(expectedBelow) || !plant.is(expectedPlant) || (expectedUnder != null && !under.is(expectedUnder))) {
                    helper.fail("garden row " + row + " at z=" + z + ": under " + under + ", below " + below + ", plant " + plant
                            + "; expected " + expectedUnder + " / " + expectedBelow + " / " + expectedPlant);
                    return;
                }
                if (below.is(Blocks.WATER) && below.getValue(LiquidBlock.LEVEL) != 0) {
                    helper.fail("garden water at " + new BlockPos(x, 1, z) + " is not a source: " + below);
                    return;
                }
            }
        }
        helper.succeed();
    }

    /**
     * ItemMinersDream.onItemUse (:20-110): through solid stone the tunnel is 11 wide, 5 high and 64
     * long from the clicked block, an ore inside it stays, the stone roof stays (no cobblestone
     * where the ceiling was solid), the walls beyond j = +-5 stay, and an Extreme Torch stands on
     * the centre line every five blocks. One item consumed.
     */
    @GameTest(template = ARENA_LARGE, timeoutTicks = 200)
    public static void minersDreamDigsATunnelThroughStoneOnly(GameTestHelper helper) {
        for (int x = 18; x <= 30; x++) {
            for (int z = 3; z <= 70; z++) {
                for (int y = 1; y <= 7; y++) {
                    helper.setBlock(new BlockPos(x, y, z), Blocks.STONE);
                }
            }
        }
        helper.setBlock(new BlockPos(24, 3, 20), Blocks.IRON_ORE);
        helper.setBlock(new BlockPos(22, 4, 40), Blocks.DIAMOND_ORE);
        Player player = helper.makeMockPlayer(GameType.SURVIVAL);
        BlockPos feet = helper.absolutePos(new BlockPos(24, 2, 2));
        player.setPos(feet.getX() + 0.5, feet.getY(), feet.getZ() + 0.5);
        ItemStack stack = new ItemStack(ModItems.MINERS_DREAM.get(), 16);
        InteractionResult result = useOn(helper, player, stack, hitTop(helper.absolutePos(new BlockPos(24, 1, 3))));
        if (result != InteractionResult.CONSUME || stack.getCount() != 15) {
            helper.fail("minersdream returned " + result + " and left " + stack.getCount() + " items");
        }
        int torches = 0;
        for (int k = 0; k < 64; k++) {
            int z = 3 + k;
            for (int j = -5; j <= 5; j++) {
                int x = 24 + j;
                for (int i = 0; i < 5; i++) {
                    BlockPos rel = new BlockPos(x, 2 + i, z);
                    BlockState s = helper.getBlockState(rel);
                    if (rel.equals(new BlockPos(24, 3, 20))) {
                        if (!s.is(Blocks.IRON_ORE)) {
                            helper.fail("the iron ore inside the tunnel was removed: " + s);
                            return;
                        }
                        continue;
                    }
                    if (rel.equals(new BlockPos(22, 4, 40))) {
                        if (!s.is(Blocks.DIAMOND_ORE)) {
                            helper.fail("the diamond ore inside the tunnel was removed: " + s);
                            return;
                        }
                        continue;
                    }
                    if (j == 0 && i == 0 && k % 5 == 0) {
                        if (!s.is(ModBlocks.EXTREME_TORCH.get())) {
                            helper.fail("no Extreme Torch at " + rel + ": " + s);
                            return;
                        }
                        torches++;
                        continue;
                    }
                    if (!s.isAir()) {
                        helper.fail("tunnel block at " + rel + " is " + s + ", expected air");
                        return;
                    }
                }
                if (!helper.getBlockState(new BlockPos(x, 7, z)).is(Blocks.STONE)
                        || !helper.getBlockState(new BlockPos(x, 1, z)).is(Blocks.STONE)) {
                    helper.fail("tunnel roof or floor at x=" + x + " z=" + z + " was replaced");
                    return;
                }
            }
            if (!helper.getBlockState(new BlockPos(18, 3, z)).is(Blocks.STONE)
                    || !helper.getBlockState(new BlockPos(30, 3, z)).is(Blocks.STONE)) {
                helper.fail("tunnel wall beyond j = +-5 at z=" + z + " was dug");
                return;
            }
        }
        if (torches != 13) {
            helper.fail("found " + torches + " Extreme Torches, expected 13 (k = 0, 5, ..., 60)");
        }
        if (!helper.getBlockState(new BlockPos(24, 3, 67)).is(Blocks.STONE)) {
            helper.fail("the tunnel ran past 64 blocks");
        }
        helper.succeed();
    }

    /**
     * ItemMinersDream writes with {@code world.setBlock(..., 0, 2)} (:73, :82, :85, :92, :100,
     * :103): no neighbour notification of any kind. A water source in the tunnel wall (j = +6) and
     * one at the tunnel's end therefore stayed still, a torch and a sand block whose supporting
     * stone was dug out kept floating. In 1.21.1 that needs {@code UPDATE_KNOWN_SHAPE} on top of
     * {@code UPDATE_CLIENTS}; with flag 2 alone the shape updates schedule the water's flow tick,
     * drop the sand and pop the torch.
     *
     * <p>Since DECISIONS R22 the tunnel digs every non-ore block, so a probe inside the tunnel volume
     * (y 2..6) would be dug itself. The torch and the falling block therefore sit on the roof row
     * (y = 7) and stand on stone at y = 6, which is dug. The falling block is white concrete powder,
     * not sand: sand on the roof row would be replaced by cobblestone ({@code needsRoof}, :80).
     *
     * <p>The probes are placed ten ticks before the dig: {@code LiquidBlock.onPlace} and
     * {@code FallingBlock.onPlace} schedule a tick of their own, which must have run - and found
     * the probe enclosed - before the tunnel opens the side.
     */
    @GameTest(template = ARENA_LARGE, timeoutTicks = 200)
    public static void minersDreamLeavesCutLiquidsAndUnsupportedBlocksStill(GameTestHelper helper) {
        for (int x = 18; x <= 30; x++) {
            for (int z = 3; z <= 70; z++) {
                for (int y = 1; y <= 7; y++) {
                    helper.setBlock(new BlockPos(x, y, z), Blocks.STONE);
                }
            }
        }
        BlockPos wallWater = new BlockPos(30, 3, 20);   // j = +6, one block outside the tunnel
        BlockPos endWater = new BlockPos(24, 3, 67);    // k = 64, the block the tunnel stops at
        BlockPos torch = new BlockPos(24, 7, 30);       // roof row, stands on stone at y = 6, which is dug
        BlockPos sand = new BlockPos(24, 7, 40);        // roof row, rests on stone at y = 6, which is dug
        helper.setBlock(wallWater, Blocks.WATER);
        helper.setBlock(endWater, Blocks.WATER);
        helper.setBlock(torch, Blocks.TORCH);
        helper.setBlock(sand, Blocks.WHITE_CONCRETE_POWDER);
        helper.runAfterDelay(10, () -> {
            Player player = helper.makeMockPlayer(GameType.SURVIVAL);
            BlockPos feet = helper.absolutePos(new BlockPos(24, 2, 2));
            player.setPos(feet.getX() + 0.5, feet.getY(), feet.getZ() + 0.5);
            ItemStack stack = new ItemStack(ModItems.MINERS_DREAM.get(), 16);
            InteractionResult result = useOn(helper, player, stack, hitTop(helper.absolutePos(new BlockPos(24, 1, 3))));
            if (result != InteractionResult.CONSUME) {
                helper.fail("minersdream returned " + result);
            }
            helper.runAfterDelay(40, () -> {
                for (BlockPos source : List.of(wallWater, endWater)) {
                    if (!helper.getBlockState(source).is(Blocks.WATER) || helper.getBlockState(source).getFluidState().getAmount() != 8) {
                        helper.fail("water source at " + source + " changed: " + helper.getBlockState(source));
                    }
                }
                // The tunnel runs toward +z: the wall source's open side is x - 1, the end source's is z - 1.
                for (BlockPos opened : List.of(wallWater.west(), endWater.north())) {
                    if (!helper.getBlockState(opened).isAir()) {
                        helper.fail("the cut liquid flowed into the tunnel at " + opened + ": " + helper.getBlockState(opened));
                    }
                }
                if (!helper.getBlockState(torch).is(Blocks.TORCH) || !helper.getBlockState(torch.below()).isAir()) {
                    helper.fail("the torch over dug stone did not stay floating: " + helper.getBlockState(torch)
                            + " over " + helper.getBlockState(torch.below()));
                }
                if (!helper.getBlockState(sand).is(Blocks.WHITE_CONCRETE_POWDER) || !helper.getBlockState(sand.below()).isAir()) {
                    helper.fail("the concrete powder over dug stone did not stay floating: " + helper.getBlockState(sand)
                            + " over " + helper.getBlockState(sand.below()));
                }
                helper.succeed();
            });
        });
    }

    /**
     * StepUp.onItemUse (:20-102): head yaw 0 (sector 0, +z) lays a cobblestone stair from the
     * clicked block with an Extreme Torch on the first step and stops at the first non-air block;
     * a head yaw of -90 falls into no sector - the original's negative-yaw hole (R18) - builds
     * nothing, and returns <em>before</em> the item is consumed (:73-75 precede :98-100).
     */
    @GameTest(template = ARENA)
    public static void stepUpFollowsTheHeadYawAndHasTheNegativeYawHole(GameTestHelper helper) {
        // Floor stone at relative y = 1; the player stands on it and clicks the floor block under his feet.
        Player player = helper.makeMockPlayer(GameType.SURVIVAL);
        BlockPos feet = helper.absolutePos(new BlockPos(3, 2, 3));
        player.setPos(feet.getX() + 0.5, feet.getY(), feet.getZ() + 0.5);
        BlockHitResult floor = hitTop(helper.absolutePos(new BlockPos(3, 1, 3)));
        helper.setBlock(new BlockPos(3, 4, 6), Blocks.STONE); // stops the stair at k = 3

        player.setYHeadRot(-90.0f);
        ItemStack stack = new ItemStack(ModItems.STEP_UP.get(), 16);
        InteractionResult result = useOn(helper, player, stack, floor);
        if (result != InteractionResult.PASS || stack.getCount() != 16) {
            helper.fail("yaw -90 returned " + result + " and left " + stack.getCount() + " items; expected PASS and 16");
        }
        for (BlockPos rel : List.of(new BlockPos(3, 2, 4), new BlockPos(3, 2, 2), new BlockPos(4, 2, 3), new BlockPos(2, 2, 3))) {
            if (!helper.getBlockState(rel).isAir()) {
                helper.fail("yaw -90 built " + helper.getBlockState(rel) + " at " + rel);
            }
        }

        player.setYHeadRot(0.0f);
        result = useOn(helper, player, stack, floor);
        if (result != InteractionResult.CONSUME || stack.getCount() != 15) {
            helper.fail("yaw 0 returned " + result + " and left " + stack.getCount() + " items; expected CONSUME and 15");
        }
        if (!helper.getBlockState(new BlockPos(3, 2, 4)).is(Blocks.COBBLESTONE)
                || !helper.getBlockState(new BlockPos(3, 3, 4)).is(ModBlocks.EXTREME_TORCH.get())
                || !helper.getBlockState(new BlockPos(3, 3, 5)).is(Blocks.COBBLESTONE)
                || !helper.getBlockState(new BlockPos(3, 4, 6)).is(Blocks.STONE)
                || !helper.getBlockState(new BlockPos(3, 5, 7)).isAir()) {
            helper.fail("yaw 0 stair is wrong: " + helper.getBlockState(new BlockPos(3, 2, 4)) + ", "
                    + helper.getBlockState(new BlockPos(3, 3, 4)) + ", " + helper.getBlockState(new BlockPos(3, 3, 5))
                    + ", " + helper.getBlockState(new BlockPos(3, 4, 6)) + ", " + helper.getBlockState(new BlockPos(3, 5, 7)));
        }
        helper.succeed();
    }

    // ------------------------------------------------------------------ shared helpers

    private static BlockHitResult hitTop(BlockPos abs) {
        return new BlockHitResult(Vec3.atCenterOf(abs).add(0, 0.5, 0), Direction.UP, abs, false);
    }

    private static InteractionResult useOn(GameTestHelper helper, Player player, ItemStack stack, BlockHitResult hit) {
        player.setItemInHand(InteractionHand.MAIN_HAND, stack);
        return stack.useOn(new UseOnContext(helper.getLevel(), player, InteractionHand.MAIN_HAND, stack, hit));
    }

    private static Holder<Enchantment> enchantment(GameTestHelper helper, ResourceKey<Enchantment> key) {
        return helper.getLevel().registryAccess().lookupOrThrow(Registries.ENCHANTMENT).getOrThrow(key);
    }

    /** The stack carries exactly {@code expected} (key to level) and no other enchantment. */
    private static void expectEnchantments(GameTestHelper helper, ItemStack stack, Map<ResourceKey<Enchantment>, Integer> expected) {
        int total = 0;
        for (Map.Entry<ResourceKey<Enchantment>, Integer> entry : expected.entrySet()) {
            int level = EnchantmentHelper.getTagEnchantmentLevel(enchantment(helper, entry.getKey()), stack);
            if (level != entry.getValue()) {
                helper.fail(stack + " has " + entry.getKey().location() + " " + level + ", expected " + entry.getValue());
            }
            total += entry.getValue();
        }
        int actual = 0;
        for (var e : EnchantmentHelper.getEnchantmentsForCrafting(stack).entrySet()) {
            actual += e.getIntValue();
        }
        if (actual != total) {
            helper.fail(stack + " carries enchantment levels summing to " + actual + ", expected " + total + ": "
                    + EnchantmentHelper.getEnchantmentsForCrafting(stack));
        }
    }
}
