// GENERATED by tools/gen_models.py from reference/jar/models/ModelAlien.json - do not edit.
package com.swbr.orespawn.client.model.geom;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Geometry of OreSpawn's ModelAlien (55 parts), copied unchanged from the 1.7.10 jar.
 * Part order is the order the original constructor created them.
 */
public final class AlienGeometry {

    public static final int TEXTURE_WIDTH = 256;
    public static final int TEXTURE_HEIGHT = 128;

    public static final String TORSO = "torso";
    public static final String STOMACH = "stomach";
    public static final String R_THIGH = "rThigh";
    public static final String L_THIGH = "lThigh";
    public static final String L_SHIN = "lShin";
    public static final String R_SHIN = "rShin";
    public static final String L_SHIN1 = "lShin1";
    public static final String R_SHIN1 = "rShin1";
    public static final String L_FOOT = "lFoot";
    public static final String R_FOOT = "rFoot";
    public static final String NECK = "neck";
    public static final String FAN = "fan";
    public static final String TAIL2 = "tail2";
    public static final String TAIL3 = "tail3";
    public static final String TAIL4 = "tail4";
    public static final String TAIL5 = "tail5";
    public static final String TAIL1 = "tail1";
    public static final String FANL1 = "fanl1";
    public static final String FANR1 = "fanr1";
    public static final String FANL2 = "fanl2";
    public static final String FANR2 = "fanr2";
    public static final String FANL3 = "fanl3";
    public static final String FANR3 = "fanr3";
    public static final String FANL4 = "fanl4";
    public static final String FANR4 = "fanr4";
    public static final String FANL5 = "fanl5";
    public static final String FANR5 = "fanr5";
    public static final String FANL6 = "fanl6";
    public static final String FANR6 = "fanr6";
    public static final String SPIKE4 = "spike4";
    public static final String SPIKE5 = "spike5";
    public static final String SPIKE3 = "spike3";
    public static final String FANL7 = "fanl7";
    public static final String FANR7 = "fanr7";
    public static final String HEAD = "head";
    public static final String HEAD1 = "head1";
    public static final String JAW1 = "jaw1";
    public static final String HEAD2 = "head2";
    public static final String JAW2 = "jaw2";
    public static final String FANG1 = "fang1";
    public static final String FANG2 = "fang2";
    public static final String FANG3 = "fang3";
    public static final String FANG4 = "fang4";
    public static final String SPIKE2 = "spike2";
    public static final String SPIKE1 = "spike1";
    public static final String ARML1 = "arml1";
    public static final String ARMR1 = "armr1";
    public static final String ARML2 = "arml2";
    public static final String ARMR2 = "armr2";
    public static final String CLAWR1 = "clawr1";
    public static final String CLAWR2 = "clawr2";
    public static final String CLAWR3 = "clawr3";
    public static final String CLAWL2 = "clawl2";
    public static final String CLAWL3 = "clawl3";
    public static final String CLAWL1 = "clawl1";

    /** Every part in creation order. */
    public static final String[] PARTS = {
            TORSO,
            STOMACH,
            R_THIGH,
            L_THIGH,
            L_SHIN,
            R_SHIN,
            L_SHIN1,
            R_SHIN1,
            L_FOOT,
            R_FOOT,
            NECK,
            FAN,
            TAIL2,
            TAIL3,
            TAIL4,
            TAIL5,
            TAIL1,
            FANL1,
            FANR1,
            FANL2,
            FANR2,
            FANL3,
            FANR3,
            FANL4,
            FANR4,
            FANL5,
            FANR5,
            FANL6,
            FANR6,
            SPIKE4,
            SPIKE5,
            SPIKE3,
            FANL7,
            FANR7,
            HEAD,
            HEAD1,
            JAW1,
            HEAD2,
            JAW2,
            FANG1,
            FANG2,
            FANG3,
            FANG4,
            SPIKE2,
            SPIKE1,
            ARML1,
            ARMR1,
            ARML2,
            ARMR2,
            CLAWR1,
            CLAWR2,
            CLAWR3,
            CLAWL2,
            CLAWL3,
            CLAWL1
    };

    /** Parts the original hid at construction time (showModel = false or isHidden = true). */
    public static final String[] HIDDEN = {};

    private AlienGeometry() {}

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild(TORSO, CubeListBuilder.create().texOffs(0, 46).addBox(-4.5F, -2F, 0F, 9F, 8F, 10F),
                PartPose.offsetAndRotation(0F, -2.5F, -8F, -0.1919862F, 0F, 0F));
        root.addOrReplaceChild(STOMACH, CubeListBuilder.create().texOffs(0, 27).addBox(-3.5F, -5F, 8F, 7F, 6F, 12F),
                PartPose.offsetAndRotation(0F, -2.5F, -8F, -0.5585054F, 0F, 0F));
        root.addOrReplaceChild(R_THIGH, CubeListBuilder.create().texOffs(59, 45).addBox(-1.5F, -4F, -2.5F, 4F, 14F, 5F),
                PartPose.offsetAndRotation(-4.5F, 7F, 8F, -0.8028515F, 0.2443461F, 0.418879F));
        root.addOrReplaceChild(L_THIGH, CubeListBuilder.create().texOffs(40, 45).addBox(-2.5F, -4F, -2.5F, 4F, 14F, 5F),
                PartPose.offsetAndRotation(4.5F, 7F, 8F, -0.8028515F, -0.2443461F, -0.418879F));
        root.addOrReplaceChild(L_SHIN, CubeListBuilder.create().texOffs(79, 49).addBox(-2F, 8F, -5.5F, 3F, 3F, 12F),
                PartPose.offsetAndRotation(4.5F, 7F, 8F, -0.4014257F, -0.2443461F, -0.418879F));
        root.addOrReplaceChild(R_SHIN, CubeListBuilder.create().texOffs(79, 33).addBox(-1F, 8F, -5.5F, 3F, 3F, 12F),
                PartPose.offsetAndRotation(-4.5F, 7F, 8F, -0.4014257F, 0.2443461F, 0.418879F));
        root.addOrReplaceChild(L_SHIN1, CubeListBuilder.create().texOffs(113, 40).addBox(-1.5F, 5.5F, 9F, 2F, 9F, 2F),
                PartPose.offsetAndRotation(4.5F, 7F, 8F, -0.8028515F, -0.2443461F, -0.418879F));
        root.addOrReplaceChild(R_SHIN1, CubeListBuilder.create().texOffs(113, 53).addBox(-0.5F, 5.5F, 9F, 2F, 9F, 2F),
                PartPose.offsetAndRotation(-4.5F, 7F, 8F, -0.8028515F, 0.2443461F, 0.418879F));
        root.addOrReplaceChild(L_FOOT, CubeListBuilder.create().texOffs(110, 24).addBox(5F, 15F, -8F, 2F, 2F, 6F),
                PartPose.offsetAndRotation(4.5F, 7F, 8F, 0F, -0.2443461F, 0F));
        root.addOrReplaceChild(R_FOOT, CubeListBuilder.create().texOffs(95, 24).addBox(-7F, 15F, -8F, 2F, 2F, 6F),
                PartPose.offsetAndRotation(-4.5F, 7F, 8F, 0F, 0.2443461F, 0F));
        root.addOrReplaceChild(NECK, CubeListBuilder.create().texOffs(23, 86).addBox(-2F, -2F, -4F, 4F, 6F, 5F),
                PartPose.offsetAndRotation(0F, -2.5F, -8F, -0.1919862F, 0F, 0F));
        root.addOrReplaceChild(FAN, CubeListBuilder.create().texOffs(149, 10).addBox(-3F, -24F, 0F, 6F, 24F, 1F),
                PartPose.offsetAndRotation(0F, -7F, -10F, 0F, 0F, 0F));
        root.addOrReplaceChild(TAIL2, CubeListBuilder.create().texOffs(85, 66).addBox(-2F, -1.5F, 0F, 4F, 4F, 11F),
                PartPose.offsetAndRotation(0F, 9.5F, 20.5F, -0.3141593F, 0F, 0F));
        root.addOrReplaceChild(TAIL3, CubeListBuilder.create().texOffs(118, 66).addBox(-1.5F, -1.5F, 0F, 3F, 3F, 11F),
                PartPose.offsetAndRotation(0F, 13.5F, 30.5F, -0.2094395F, 0F, 0F));
        root.addOrReplaceChild(TAIL4, CubeListBuilder.create().texOffs(149, 66).addBox(-1F, -1F, 0F, 2F, 2F, 11F),
                PartPose.offsetAndRotation(0F, 15.5F, 40.5F, -0.1396263F, 0F, 0F));
        root.addOrReplaceChild(TAIL5, CubeListBuilder.create().texOffs(178, 66).addBox(-0.5F, -0.5F, 0F, 1F, 1F, 11F),
                PartPose.offsetAndRotation(0F, 17.5F, 50.5F, -0.0523599F, 0F, 0F));
        root.addOrReplaceChild(TAIL1, CubeListBuilder.create().texOffs(50, 66).addBox(-2F, -2.5F, 0F, 4F, 4F, 11F),
                PartPose.offsetAndRotation(0F, 6.5F, 10.5F, -0.4014257F, 0F, 0F));
        root.addOrReplaceChild(FANL1, CubeListBuilder.create().texOffs(130, 10).addBox(-3F, -24F, 0F, 6F, 24F, 1F),
                PartPose.offsetAndRotation(0F, -7F, -10F, 0F, 0F, 0.2617994F));
        root.addOrReplaceChild(FANR1, CubeListBuilder.create().texOffs(130, 10).addBox(-3F, -24F, 0F, 6F, 24F, 1F),
                PartPose.offsetAndRotation(0F, -7F, -10F, 0F, 0F, -0.2617994F));
        root.addOrReplaceChild(FANL2, CubeListBuilder.create().texOffs(130, 10).addBox(-3F, -24F, 0F, 6F, 24F, 1F),
                PartPose.offsetAndRotation(0F, -7F, -10F, 0F, 0F, 0.5235988F));
        root.addOrReplaceChild(FANR2, CubeListBuilder.create().texOffs(130, 10).addBox(-3F, -24F, 0F, 6F, 24F, 1F),
                PartPose.offsetAndRotation(0F, -7F, -10F, 0F, 0F, -0.5235988F));
        root.addOrReplaceChild(FANL3, CubeListBuilder.create().texOffs(130, 10).addBox(-3F, -24F, 0F, 6F, 24F, 1F),
                PartPose.offsetAndRotation(0F, -7F, -10F, 0F, 0F, 0.7853982F));
        root.addOrReplaceChild(FANR3, CubeListBuilder.create().texOffs(130, 10).addBox(-3F, -24F, 0F, 6F, 24F, 1F),
                PartPose.offsetAndRotation(0F, -7F, -10F, 0F, 0F, -0.7853982F));
        root.addOrReplaceChild(FANL4, CubeListBuilder.create().texOffs(130, 10).addBox(-3F, -24F, 0F, 6F, 24F, 1F),
                PartPose.offsetAndRotation(0F, -7F, -10F, 0F, 0F, 1.047198F));
        root.addOrReplaceChild(FANR4, CubeListBuilder.create().texOffs(130, 10).addBox(-3F, -24F, 0F, 6F, 24F, 1F),
                PartPose.offsetAndRotation(0F, -7F, -10F, 0F, 0F, -1.047198F));
        root.addOrReplaceChild(FANL5, CubeListBuilder.create().texOffs(130, 10).addBox(-3F, -24F, 0F, 6F, 24F, 1F),
                PartPose.offsetAndRotation(0F, -7F, -10F, 0F, 0F, 1.308997F));
        root.addOrReplaceChild(FANR5, CubeListBuilder.create().texOffs(130, 10).addBox(-3F, -24F, 0F, 6F, 24F, 1F),
                PartPose.offsetAndRotation(0F, -7F, -10F, 0F, 0F, -1.308997F));
        root.addOrReplaceChild(FANL6, CubeListBuilder.create().texOffs(130, 10).addBox(-3F, -24F, 0F, 6F, 24F, 1F),
                PartPose.offsetAndRotation(0F, -7F, -10F, 0F, 0F, 1.570796F));
        root.addOrReplaceChild(FANR6, CubeListBuilder.create().texOffs(130, 10).addBox(-3F, -24F, 0F, 6F, 24F, 1F),
                PartPose.offsetAndRotation(0F, -7F, -10F, 0F, 0F, -1.570796F));
        root.addOrReplaceChild(SPIKE4, CubeListBuilder.create().texOffs(178, 66).addBox(-0.5F, -0.5F, 0F, 1F, 1F, 11F),
                PartPose.offsetAndRotation(0F, 16F, 41F, -0.0523599F, 0.5235988F, 0F));
        root.addOrReplaceChild(SPIKE5, CubeListBuilder.create().texOffs(178, 66).addBox(-0.5F, -0.5F, 0F, 1F, 1F, 11F),
                PartPose.offsetAndRotation(0F, 16F, 41F, -0.0523599F, -0.5759587F, 0F));
        root.addOrReplaceChild(SPIKE3, CubeListBuilder.create().texOffs(178, 66).addBox(-0.5F, -0.5F, 0F, 1F, 1F, 11F),
                PartPose.offsetAndRotation(0F, 13.5F, 30.5F, 0.3141593F, 0F, 0F));
        root.addOrReplaceChild(FANL7, CubeListBuilder.create().texOffs(130, 10).addBox(-3F, -24F, 0F, 6F, 24F, 1F),
                PartPose.offsetAndRotation(0F, -7F, -10F, 0F, 0F, 1.832596F));
        root.addOrReplaceChild(FANR7, CubeListBuilder.create().texOffs(130, 10).addBox(-3F, -24F, 0F, 6F, 24F, 1F),
                PartPose.offsetAndRotation(0F, -7F, -10F, 0F, 0F, -1.832596F));
        root.addOrReplaceChild(HEAD, CubeListBuilder.create().texOffs(200, 0).addBox(-3F, -4F, -7F, 6F, 7F, 8F),
                PartPose.offsetAndRotation(0F, -3F, -11F, 0F, 0F, 0F));
        root.addOrReplaceChild(HEAD1, CubeListBuilder.create().texOffs(200, 18).addBox(-2.5F, -2F, -15F, 5F, 2F, 8F),
                PartPose.offsetAndRotation(0F, -3F, -11F, 0F, 0F, 0F));
        root.addOrReplaceChild(JAW1, CubeListBuilder.create().texOffs(200, 43).addBox(-2F, -1F, -7F, 4F, 2F, 8F),
                PartPose.offsetAndRotation(0F, -2F, -19F, 0F, 0F, 0F));
        root.addOrReplaceChild(HEAD2, CubeListBuilder.create().texOffs(200, 31).addBox(-2F, -2F, -22F, 4F, 2F, 7F),
                PartPose.offsetAndRotation(0F, -3F, -11F, 0F, 0F, 0F));
        root.addOrReplaceChild(JAW2, CubeListBuilder.create().texOffs(200, 56).addBox(-1.5F, -1F, -13F, 3F, 2F, 6F),
                PartPose.offsetAndRotation(0F, -2F, -19F, 0F, 0F, 0F));
        root.addOrReplaceChild(FANG1, CubeListBuilder.create().texOffs(42, 0).addBox(1F, 0F, -20F, 1F, 5F, 1F),
                PartPose.offsetAndRotation(0F, -3F, -11F, 0F, 0F, 0F));
        root.addOrReplaceChild(FANG2, CubeListBuilder.create().texOffs(50, 0).addBox(-2F, 0F, -20F, 1F, 5F, 1F),
                PartPose.offsetAndRotation(0F, -3F, -11F, 0F, 0F, 0F));
        root.addOrReplaceChild(FANG3, CubeListBuilder.create().texOffs(60, 0).addBox(1F, 0F, -14F, 1F, 3F, 1F),
                PartPose.offsetAndRotation(0F, -3F, -11F, 0F, 0F, 0F));
        root.addOrReplaceChild(FANG4, CubeListBuilder.create().texOffs(69, 0).addBox(-2F, 0F, -14F, 1F, 3F, 1F),
                PartPose.offsetAndRotation(0F, -3F, -11F, 0F, 0F, 0F));
        root.addOrReplaceChild(SPIKE2, CubeListBuilder.create().texOffs(178, 66).addBox(-0.5F, -0.5F, 0F, 1F, 1F, 11F),
                PartPose.offsetAndRotation(0F, 9.5F, 20.5F, 0.3141593F, 0F, 0F));
        root.addOrReplaceChild(SPIKE1, CubeListBuilder.create().texOffs(178, 66).addBox(-0.5F, -1.5F, 0F, 1F, 1F, 11F),
                PartPose.offsetAndRotation(0F, 6.5F, 10.5F, 0.3141593F, 0F, 0F));
        root.addOrReplaceChild(ARML1, CubeListBuilder.create().texOffs(50, 98).addBox(0F, 0F, -2F, 11F, 3F, 4F),
                PartPose.offsetAndRotation(2F, -1F, -6F, 0F, -0.5235988F, 0.1745329F));
        root.addOrReplaceChild(ARMR1, CubeListBuilder.create().texOffs(49, 88).addBox(0F, 0F, -2F, 11F, 3F, 4F),
                PartPose.offsetAndRotation(-3F, -1F, -6F, 0F, -2.617994F, -0.1745329F));
        root.addOrReplaceChild(ARML2, CubeListBuilder.create().texOffs(41, 107).addBox(0F, -1F, -1F, 15F, 3F, 3F),
                PartPose.offsetAndRotation(11F, 2F, -1F, 0F, 0.8552113F, 0F));
        root.addOrReplaceChild(ARMR2, CubeListBuilder.create().texOffs(42, 115).addBox(0F, -1F, -2F, 15F, 3F, 3F),
                PartPose.offsetAndRotation(-11F, 2F, -1F, 0F, 2.268928F, 0F));
        root.addOrReplaceChild(CLAWR1, CubeListBuilder.create().texOffs(100, 85).addBox(-0.5F, -1F, -6F, 1F, 1F, 6F),
                PartPose.offsetAndRotation(-21F, 2F, -12F, -0.1745329F, 0.4363323F, 0F));
        root.addOrReplaceChild(CLAWR2, CubeListBuilder.create().texOffs(100, 94).addBox(0F, 0F, -10F, 1F, 1F, 10F),
                PartPose.offsetAndRotation(-21F, 2F, -12F, 0F, 0.8726646F, 0F));
        root.addOrReplaceChild(CLAWR3, CubeListBuilder.create().texOffs(100, 107).addBox(0F, 1F, -6F, 1F, 1F, 6F),
                PartPose.offsetAndRotation(-21F, 2F, -12F, 0.1745329F, 0.4363323F, 0F));
        root.addOrReplaceChild(CLAWL2, CubeListBuilder.create().texOffs(130, 94).addBox(0F, 0F, 0F, 1F, 1F, 10F),
                PartPose.offsetAndRotation(21F, 2F, -12F, 0F, 2.268928F, 0F));
        root.addOrReplaceChild(CLAWL3, CubeListBuilder.create().texOffs(130, 109).addBox(0F, 1F, 0F, 1F, 1F, 6F),
                PartPose.offsetAndRotation(21F, 2F, -12F, -0.1745329F, 2.70526F, 0F));
        root.addOrReplaceChild(CLAWL1, CubeListBuilder.create().texOffs(130, 83).addBox(0F, -1F, 0F, 1F, 1F, 6F),
                PartPose.offsetAndRotation(21F, 2F, -12F, 0.1745329F, 2.70526F, 0F));
        return LayerDefinition.create(mesh, TEXTURE_WIDTH, TEXTURE_HEIGHT);
    }
}
