// GENERATED by tools/gen_models.py from reference/jar/models/ModelAttackSquid.json - do not edit.
package com.swbr.orespawn.client.model.geom;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Geometry of OreSpawn's ModelAttackSquid (9 parts), copied unchanged from the 1.7.10 jar.
 * Part order is the order the original constructor created them.
 */
public final class AttackSquidGeometry {

    public static final int TEXTURE_WIDTH = 64;
    public static final int TEXTURE_HEIGHT = 32;

    public static final String TENT1 = "tent1";
    public static final String TENT2 = "tent2";
    public static final String TENT3 = "tent3";
    public static final String TENT4 = "tent4";
    public static final String TENT5 = "tent5";
    public static final String TENT6 = "tent6";
    public static final String TENT7 = "tent7";
    public static final String BODY = "body";
    public static final String TENT8 = "tent8";

    /** Every part in creation order. */
    public static final String[] PARTS = {
            TENT1,
            TENT2,
            TENT3,
            TENT4,
            TENT5,
            TENT6,
            TENT7,
            BODY,
            TENT8
    };

    /** Parts the original hid at construction time (showModel = false or isHidden = true). */
    public static final String[] HIDDEN = {};

    private AttackSquidGeometry() {}

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild(TENT1, CubeListBuilder.create().texOffs(0, 18).addBox(-1F, 0F, -1F, 2F, 9F, 2F),
                PartPose.offsetAndRotation(5F, 15F, -1F, -0.9250245F, -1.745329F, 0F));
        root.addOrReplaceChild(TENT2, CubeListBuilder.create().texOffs(0, 18).addBox(-8F, -1F, -1F, 8F, 2F, 2F),
                PartPose.offsetAndRotation(-2F, 15F, -3F, -0.1745329F, -0.6632251F, -0.2443461F));
        root.addOrReplaceChild(TENT3, CubeListBuilder.create().texOffs(0, 18).addBox(-1F, 0F, -1F, 2F, 10F, 2F),
                PartPose.offsetAndRotation(1F, 15F, -4F, -1.134464F, 0.3316126F, 0F));
        root.addOrReplaceChild(TENT4, CubeListBuilder.create().texOffs(0, 18).addBox(-1F, 0F, -1F, 2F, 10F, 2F),
                PartPose.offsetAndRotation(-3F, 15F, -1F, 0.5585054F, -1.692969F, 0F));
        root.addOrReplaceChild(TENT5, CubeListBuilder.create().texOffs(0, 18).addBox(-1F, 0F, -1F, 2F, 10F, 2F),
                PartPose.offsetAndRotation(1F, 15F, 3F, 0.5410521F, 0.2268928F, 0F));
        root.addOrReplaceChild(TENT6, CubeListBuilder.create().texOffs(0, 18).addBox(-1F, -1F, 0F, 2F, 2F, 8F),
                PartPose.offsetAndRotation(-2F, 15F, 2F, -0.418879F, -0.6806784F, 0F));
        root.addOrReplaceChild(TENT7, CubeListBuilder.create().texOffs(0, 18).addBox(0F, -1F, -1F, 8F, 2F, 2F),
                PartPose.offsetAndRotation(3F, 15F, 1F, -0.1919862F, -0.6632251F, 0.418879F));
        root.addOrReplaceChild(BODY, CubeListBuilder.create().texOffs(0, 0).addBox(-4F, -10F, -4F, 8F, 10F, 8F),
                PartPose.offsetAndRotation(1F, 16F, -1F, -0.1919862F, -0.6806784F, 0F));
        root.addOrReplaceChild(TENT8, CubeListBuilder.create().texOffs(0, 18).addBox(-1F, -1F, -8F, 2F, 2F, 8F),
                PartPose.offsetAndRotation(3F, 15F, -4F, 0.1919862F, -0.6806784F, 0F));
        return LayerDefinition.create(mesh, TEXTURE_WIDTH, TEXTURE_HEIGHT);
    }
}
