// GENERATED by tools/gen_models.py from reference/jar/models/ModelBaryonyx.json - do not edit.
package com.swbr.orespawn.client.model.geom;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Geometry of OreSpawn's ModelBaryonyx (52 parts), copied unchanged from the 1.7.10 jar.
 * Part order is the order the original constructor created them.
 */
public final class BaryonyxGeometry {

    public static final int TEXTURE_WIDTH = 128;
    public static final int TEXTURE_HEIGHT = 128;

    public static final String SHAPE27 = "Shape27";
    public static final String SHAPE28 = "Shape28";
    public static final String SHAPE29 = "Shape29";
    public static final String SHAPE30 = "Shape30";
    public static final String SHAPE31 = "Shape31";
    public static final String SHAPE32 = "Shape32";
    public static final String SHAPE33 = "Shape33";
    public static final String SHAPE34 = "Shape34";
    public static final String SHAPE35 = "Shape35";
    public static final String SHAPE36 = "Shape36";
    public static final String SHAPE37 = "Shape37";
    public static final String SHAPE38 = "Shape38";
    public static final String SHAPE39 = "Shape39";
    public static final String SHAPE40 = "Shape40";
    public static final String SHAPE41 = "Shape41";
    public static final String SHAPE42 = "Shape42";
    public static final String SHAPE43 = "Shape43";
    public static final String SHAPE44 = "Shape44";
    public static final String SHAPE45 = "Shape45";
    public static final String SHAPE46 = "Shape46";
    public static final String SHAPE47 = "Shape47";
    public static final String SHAPE48 = "Shape48";
    public static final String SHAPE49 = "Shape49";
    public static final String SHAPE50 = "Shape50";
    public static final String SHAPE51 = "Shape51";
    public static final String SHAPE1 = "Shape1";
    public static final String SHAPE2 = "Shape2";
    public static final String SHAPE3 = "Shape3";
    public static final String SHAPE4 = "Shape4";
    public static final String SHAPE5 = "Shape5";
    public static final String SHAPE6 = "Shape6";
    public static final String SHAPE7 = "Shape7";
    public static final String SHAPE8 = "Shape8";
    public static final String SHAPE9 = "Shape9";
    public static final String SHAPE10 = "Shape10";
    public static final String SHAPE11 = "Shape11";
    public static final String SHAPE12 = "Shape12";
    public static final String SHAPE13 = "Shape13";
    public static final String SHAPE14 = "Shape14";
    public static final String SHAPE15 = "Shape15";
    public static final String SHAPE16 = "Shape16";
    public static final String SHAPE17 = "Shape17";
    public static final String SHAPE18 = "Shape18";
    public static final String SHAPE19 = "Shape19";
    public static final String SHAPE20 = "Shape20";
    public static final String SHAPE21 = "Shape21";
    public static final String SHAPE22 = "Shape22";
    public static final String SHAPE23 = "Shape23";
    public static final String SHAPE24 = "Shape24";
    public static final String SHAPE25 = "Shape25";
    public static final String SHAPE26 = "Shape26";
    public static final String SHAPE52 = "Shape52";

    /** Every part in creation order. */
    public static final String[] PARTS = {
            SHAPE27,
            SHAPE28,
            SHAPE29,
            SHAPE30,
            SHAPE31,
            SHAPE32,
            SHAPE33,
            SHAPE34,
            SHAPE35,
            SHAPE36,
            SHAPE37,
            SHAPE38,
            SHAPE39,
            SHAPE40,
            SHAPE41,
            SHAPE42,
            SHAPE43,
            SHAPE44,
            SHAPE45,
            SHAPE46,
            SHAPE47,
            SHAPE48,
            SHAPE49,
            SHAPE50,
            SHAPE51,
            SHAPE1,
            SHAPE2,
            SHAPE3,
            SHAPE4,
            SHAPE5,
            SHAPE6,
            SHAPE7,
            SHAPE8,
            SHAPE9,
            SHAPE10,
            SHAPE11,
            SHAPE12,
            SHAPE13,
            SHAPE14,
            SHAPE15,
            SHAPE16,
            SHAPE17,
            SHAPE18,
            SHAPE19,
            SHAPE20,
            SHAPE21,
            SHAPE22,
            SHAPE23,
            SHAPE24,
            SHAPE25,
            SHAPE26,
            SHAPE52
    };

    /** Parts the original hid at construction time (showModel = false or isHidden = true). */
    public static final String[] HIDDEN = {};

    private BaryonyxGeometry() {}

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild(SHAPE27, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 0F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -17F, -10F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE28, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 0F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -17F, -7F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE29, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 0F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -17F, -4F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE30, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 0F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -17F, -1F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE31, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 0F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -17F, 2F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE32, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 0F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -17F, 5F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE33, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 0F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -17F, 8F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE34, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 0F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -17F, 11F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE35, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 0F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -17F, 14F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE36, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 0F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -17F, 17F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE37, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 0F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -17F, 20F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE38, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 0F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -17F, 23F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE39, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 0F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -17F, 26F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE40, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 0F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -17F, 29F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE41, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 0F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -17F, 32F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE42, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 0F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -17F, 35F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE43, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 0F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -17F, 38F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE44, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 0F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -17F, 41F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE45, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 0F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -17F, 44F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE46, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 0F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -12F, -11F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE47, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 0F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -13F, -13F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE48, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 0F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -15F, -15F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE49, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 0F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -16F, -16F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE50, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 0F, 1F, 1F),
                PartPose.offsetAndRotation(0F, -19F, -17F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE51, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 0F, 1F, 1F),
                PartPose.offsetAndRotation(0F, -19F, -19F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE1, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 10F, 17F, 25F),
                PartPose.offsetAndRotation(-5F, -15F, -10F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE2, CubeListBuilder.create().texOffs(0, 93).addBox(-3F, 0F, -11F, 6F, 10F, 11F),
                PartPose.offsetAndRotation(0F, -10F, -6F, -0.1919862F, 0F, 0F));
        root.addOrReplaceChild(SHAPE3, CubeListBuilder.create().texOffs(29, 110).addBox(-2F, -9F, -8F, 4F, 9F, 8F),
                PartPose.offsetAndRotation(0F, -10F, -11F, 0.7504916F, 0F, 0F));
        root.addOrReplaceChild(SHAPE4, CubeListBuilder.create().texOffs(54, 108).addBox(0F, 0F, 0F, 6F, 7F, 12F),
                PartPose.offsetAndRotation(-3F, -18F, -28F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE5, CubeListBuilder.create().texOffs(54, 86).addBox(0F, 0F, 0F, 3F, 6F, 15F),
                PartPose.offsetAndRotation(-1.5F, -17.5F, -43F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE6, CubeListBuilder.create().texOffs(0, 43).addBox(0F, 0F, 0F, 8F, 11F, 8F),
                PartPose.offsetAndRotation(-4F, -15F, 15F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE7, CubeListBuilder.create().texOffs(0, 63).addBox(0F, 0F, 0F, 6F, 6F, 23F),
                PartPose.offsetAndRotation(-3F, -15F, 23F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE8, CubeListBuilder.create().texOffs(47, 0).addBox(0F, 0F, 0F, 2F, 5F, 3F),
                PartPose.offsetAndRotation(5F, 0F, -7F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE9, CubeListBuilder.create().texOffs(49, 10).addBox(0F, 0F, 0F, 2F, 6F, 2F),
                PartPose.offsetAndRotation(5.1F, 3F, -6F, -0.3839724F, 0F, 0F));
        root.addOrReplaceChild(SHAPE10, CubeListBuilder.create().texOffs(13, 17).addBox(0F, 0F, 0F, 2F, 4F, 3F),
                PartPose.offsetAndRotation(5F, 7F, -8F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE11, CubeListBuilder.create().texOffs(0, 17).addBox(0F, 0F, -2F, 1F, 1F, 2F),
                PartPose.offsetAndRotation(5F, 8F, -8F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE12, CubeListBuilder.create().texOffs(0, 21).addBox(0F, 0F, 0F, 1F, 1F, 1F),
                PartPose.offsetAndRotation(5F, 9F, -11F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE13, CubeListBuilder.create().texOffs(95, 36).addBox(0F, 0F, 0F, 3F, 21F, 13F),
                PartPose.offsetAndRotation(5F, -15F, 2F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE14, CubeListBuilder.create().texOffs(36, 94).addBox(0F, 0F, -3F, 3F, 5F, 3F),
                PartPose.offsetAndRotation(-1.5F, -17F, -43F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE15, CubeListBuilder.create().texOffs(113, 71).addBox(0F, 18F, 8F, 3F, 18F, 4F),
                PartPose.offsetAndRotation(5F, -15F, 2F, -0.1745329F, 0F, 0F));
        root.addOrReplaceChild(SHAPE16, CubeListBuilder.create().texOffs(13, 11).addBox(-2F, 0F, 0F, 2F, 1F, 3F),
                PartPose.offsetAndRotation(5F, 10F, -8F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE17, CubeListBuilder.create().texOffs(0, 74).addBox(0F, 35F, -1F, 3F, 3F, 6F),
                PartPose.offsetAndRotation(5F, -15F, 2F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE18, CubeListBuilder.create().texOffs(58, 0).addBox(-2F, 0F, 0F, 2F, 5F, 3F),
                PartPose.offsetAndRotation(-5F, 0F, -7F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE19, CubeListBuilder.create().texOffs(59, 10).addBox(-2F, 0F, 0F, 2F, 6F, 2F),
                PartPose.offsetAndRotation(-5.1F, 3F, -6F, -0.3839724F, 0F, 0F));
        root.addOrReplaceChild(SHAPE20, CubeListBuilder.create().texOffs(71, 5).addBox(-2F, 0F, 0F, 2F, 4F, 3F),
                PartPose.offsetAndRotation(-5F, 7F, -8F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE21, CubeListBuilder.create().texOffs(71, 0).addBox(0F, 0F, 0F, 2F, 1F, 3F),
                PartPose.offsetAndRotation(-5F, 10F, -8F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE22, CubeListBuilder.create().texOffs(0, 10).addBox(-1F, 0F, -2F, 1F, 1F, 2F),
                PartPose.offsetAndRotation(-5F, 8F, -8F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE23, CubeListBuilder.create().texOffs(0, 14).addBox(-1F, 0F, 0F, 1F, 1F, 1F),
                PartPose.offsetAndRotation(-5F, 9F, -11F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE24, CubeListBuilder.create().texOffs(95, 0).addBox(-3F, 0F, 0F, 3F, 22F, 13F),
                PartPose.offsetAndRotation(-5F, -15F, 2F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE25, CubeListBuilder.create().texOffs(96, 71).addBox(-3F, 18F, 8F, 3F, 18F, 4F),
                PartPose.offsetAndRotation(-5F, -15F, 2F, -0.1745329F, 0F, 0F));
        root.addOrReplaceChild(SHAPE26, CubeListBuilder.create().texOffs(0, 64).addBox(-3F, 35F, -1F, 3F, 3F, 6F),
                PartPose.offsetAndRotation(-5F, -15F, 2F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE52, CubeListBuilder.create().texOffs(9, 0).addBox(0F, 0F, 0F, 0F, 2F, 2F),
                PartPose.offsetAndRotation(0F, -19F, -30F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, TEXTURE_WIDTH, TEXTURE_HEIGHT);
    }
}
