// GENERATED by tools/gen_models.py from reference/jar/models/ModelBasilisk.json - do not edit.
package com.swbr.orespawn.client.model.geom;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Geometry of OreSpawn's ModelBasilisk (21 parts), copied unchanged from the 1.7.10 jar.
 * Part order is the order the original constructor created them.
 */
public final class BasiliskGeometry {

    public static final int TEXTURE_WIDTH = 256;
    public static final int TEXTURE_HEIGHT = 64;

    public static final String BODY3 = "body3";
    public static final String BODY2 = "body2";
    public static final String BODY1 = "body1";
    public static final String BODY4 = "body4";
    public static final String BODY5 = "body5";
    public static final String BODY6 = "body6";
    public static final String TAIL1 = "tail1";
    public static final String TAIL2 = "tail2";
    public static final String TAIL3 = "tail3";
    public static final String TAIL4 = "tail4";
    public static final String NECK2 = "neck2";
    public static final String NECK1 = "neck1";
    public static final String HEAD = "head";
    public static final String ROG_1 = "rog_1";
    public static final String ROG_2 = "rog_2";
    public static final String ROG_3 = "rog_3";
    public static final String ROG_4 = "rog_4";
    public static final String ROG_5 = "rog_5";
    public static final String ROG_6 = "rog_6";
    public static final String SNOUT = "snout";
    public static final String JAW = "jaw";

    /** Every part in creation order. */
    public static final String[] PARTS = {
            BODY3,
            BODY2,
            BODY1,
            BODY4,
            BODY5,
            BODY6,
            TAIL1,
            TAIL2,
            TAIL3,
            TAIL4,
            NECK2,
            NECK1,
            HEAD,
            ROG_1,
            ROG_2,
            ROG_3,
            ROG_4,
            ROG_5,
            ROG_6,
            SNOUT,
            JAW
    };

    /** Parts the original hid at construction time (showModel = false or isHidden = true). */
    public static final String[] HIDDEN = {};

    private BasiliskGeometry() {}

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild(BODY3, CubeListBuilder.create().texOffs(0, 32).addBox(0F, 0F, 0F, 16F, 16F, 16F),
                PartPose.offsetAndRotation(-8F, 8F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(BODY2, CubeListBuilder.create().texOffs(0, 32).addBox(0F, 0F, 0F, 16F, 16F, 16F),
                PartPose.offsetAndRotation(-8F, 4F, -10F, -0.2974289F, 0F, 0F));
        root.addOrReplaceChild(BODY1, CubeListBuilder.create().texOffs(0, 32).addBox(0F, 0F, 0F, 16F, 16F, 16F),
                PartPose.offsetAndRotation(-8F, 2F, -25F, -0.1487144F, 0F, 0F));
        root.addOrReplaceChild(BODY4, CubeListBuilder.create().texOffs(0, 32).addBox(0F, 0F, 0F, 16F, 16F, 16F),
                PartPose.offsetAndRotation(-8F, 8F, 13F, 0.1487144F, 0F, 0F));
        root.addOrReplaceChild(BODY5, CubeListBuilder.create().texOffs(0, 32).addBox(0F, 0F, 0F, 16F, 16F, 16F),
                PartPose.offsetAndRotation(-8F, 5.8F, 28.8F, 0F, 0F, 0F));
        root.addOrReplaceChild(BODY6, CubeListBuilder.create().texOffs(148, 4).addBox(0F, 0F, 0F, 15F, 15F, 17F),
                PartPose.offsetAndRotation(-7.5F, 6.166667F, 44F, -0.1115358F, 0F, 0F));
        root.addOrReplaceChild(TAIL1, CubeListBuilder.create().texOffs(140, 36).addBox(0F, 0F, 0F, 13F, 13F, 15F),
                PartPose.offsetAndRotation(-6.5F, 9F, 58F, 0.1115358F, 0F, 0F));
        root.addOrReplaceChild(TAIL2, CubeListBuilder.create().texOffs(64, 41).addBox(0F, 0F, 0F, 10F, 10F, 13F),
                PartPose.offsetAndRotation(-5F, 10F, 70F, 0.4089647F, 0F, 0F));
        root.addOrReplaceChild(TAIL3, CubeListBuilder.create().texOffs(64, 20).addBox(0F, 0F, 0F, 8F, 8F, 13F),
                PartPose.offsetAndRotation(-4F, 6F, 82F, 0.2230717F, 0F, 0F));
        root.addOrReplaceChild(TAIL4, CubeListBuilder.create().texOffs(64, 1).addBox(0F, 0F, 0F, 6F, 6F, 13F),
                PartPose.offsetAndRotation(-3F, 4F, 95F, -0.0743572F, 0F, 0F));
        root.addOrReplaceChild(NECK2, CubeListBuilder.create().texOffs(0, 32).addBox(0F, 0F, 0F, 16F, 16F, 16F),
                PartPose.offsetAndRotation(-8F, -4.9F, -26F, -0.8464847F, 0F, 0F));
        root.addOrReplaceChild(NECK1, CubeListBuilder.create().texOffs(0, 32).addBox(0F, 0F, 0F, 16F, 16F, 16F),
                PartPose.offsetAndRotation(-8F, -15F, -29F, -1.181092F, 0F, 0F));
        root.addOrReplaceChild(HEAD, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 16F, 18F, 10F),
                PartPose.offsetAndRotation(-8F, -21F, -30F, -1.404164F, 0F, 0F));
        root.addOrReplaceChild(ROG_1, CubeListBuilder.create().texOffs(110, 45).addBox(0F, 0F, 0F, 3F, 3F, 5F),
                PartPose.offsetAndRotation(3F, -21F, -32F, 0.6320364F, 0.2230717F, 0F));
        root.addOrReplaceChild(ROG_2, CubeListBuilder.create().texOffs(110, 45).addBox(0F, 0F, 0F, 3F, 3F, 5F),
                PartPose.offsetAndRotation(-6F, -21F, -32.8F, 0.6320364F, -0.2230705F, 0F));
        root.addOrReplaceChild(ROG_3, CubeListBuilder.create().texOffs(52, 0).addBox(0F, 0F, 0F, 2F, 2F, 4F),
                PartPose.offsetAndRotation(0.4666667F, -21F, -31F, 0.6320364F, 0.2230717F, 0F));
        root.addOrReplaceChild(ROG_4, CubeListBuilder.create().texOffs(52, 0).addBox(0F, 0F, 0F, 2F, 2F, 4F),
                PartPose.offsetAndRotation(-2.466667F, -21F, -31.46667F, 0.6320364F, -0.2230705F, 0F));
        root.addOrReplaceChild(ROG_5, CubeListBuilder.create().texOffs(52, 0).addBox(0F, 0F, 0F, 2F, 2F, 4F),
                PartPose.offsetAndRotation(-8F, -17F, -32F, 0.6320364F, -0.6692139F, 0F));
        root.addOrReplaceChild(ROG_6, CubeListBuilder.create().texOffs(52, 0).addBox(0F, 0F, 0F, 2F, 2F, 4F),
                PartPose.offsetAndRotation(6.4F, -17F, -32F, 0.6320364F, 0.6692116F, 0F));
        root.addOrReplaceChild(SNOUT, CubeListBuilder.create().texOffs(102, 1).addBox(0F, 0F, 0F, 14F, 16F, 9F),
                PartPose.offsetAndRotation(-7F, -17F, -43F, -1.404164F, 0F, 0F));
        root.addOrReplaceChild(JAW, CubeListBuilder.create().texOffs(106, 26).addBox(0F, 0F, 0F, 14F, 16F, 3F),
                PartPose.offsetAndRotation(-7F, -11F, -39F, -0.8836633F, 0F, 0F));
        return LayerDefinition.create(mesh, TEXTURE_WIDTH, TEXTURE_HEIGHT);
    }
}
