// GENERATED by tools/gen_models.py from reference/jar/models/ModelBattleAxe.json - do not edit.
package com.swbr.orespawn.client.model.geom;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Geometry of OreSpawn's ModelBattleAxe (15 parts), copied unchanged from the 1.7.10 jar.
 * Part order is the order the original constructor created them.
 */
public final class BattleAxeGeometry {

    public static final int TEXTURE_WIDTH = 128;
    public static final int TEXTURE_HEIGHT = 64;

    public static final String HANDLE1 = "Handle1";
    public static final String HEAD1 = "Head1";
    public static final String GRIP = "Grip";
    public static final String PIN = "Pin";
    public static final String TOP = "Top";
    public static final String BLADE1 = "Blade1";
    public static final String BLADE2 = "Blade2";
    public static final String BLADE3 = "Blade3";
    public static final String BLADE4 = "Blade4";
    public static final String BLADE5 = "Blade5";
    public static final String BLADE6 = "Blade6";
    public static final String BLADE7 = "Blade7";
    public static final String BLADE8 = "Blade8";
    public static final String BLADE9 = "Blade9";
    public static final String BLADE10 = "Blade10";

    /** Every part in creation order. */
    public static final String[] PARTS = {
            HANDLE1,
            HEAD1,
            GRIP,
            PIN,
            TOP,
            BLADE1,
            BLADE2,
            BLADE3,
            BLADE4,
            BLADE5,
            BLADE6,
            BLADE7,
            BLADE8,
            BLADE9,
            BLADE10
    };

    /** Parts the original hid at construction time (showModel = false or isHidden = true). */
    public static final String[] HIDDEN = {};

    private BattleAxeGeometry() {}

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild(HANDLE1, CubeListBuilder.create().texOffs(0, 0).addBox(-7F, -0.5F, 0F, 31F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -12F, 0F, 0F, 0F, 1.570796F));
        root.addOrReplaceChild(HEAD1, CubeListBuilder.create().texOffs(29, 18).addBox(-2F, -4.5F, -0.5F, 3F, 4F, 2F),
                PartPose.offsetAndRotation(0F, -12F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(GRIP, CubeListBuilder.create().texOffs(0, 7).addBox(-1.92F, 13F, -0.5F, 3F, 11F, 2F),
                PartPose.offsetAndRotation(0F, -12F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(PIN, CubeListBuilder.create().texOffs(38, 11).addBox(-1F, -3F, -1F, 1F, 1F, 3F),
                PartPose.offsetAndRotation(0F, -12F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(TOP, CubeListBuilder.create().texOffs(24, 11).addBox(-2F, -8F, -0.5F, 3F, 2F, 2F),
                PartPose.offsetAndRotation(0F, -12F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(BLADE1, CubeListBuilder.create().texOffs(70, 0).addBox(6F, -8F, 0F, 3F, 10F, 1F),
                PartPose.offsetAndRotation(0F, -12F, 0F, 0F, 0F, 0.5061455F));
        root.addOrReplaceChild(BLADE2, CubeListBuilder.create().texOffs(70, 0).addBox(8.5F, -6.9F, 0F, 3F, 10F, 1F),
                PartPose.offsetAndRotation(0F, -12F, 0F, 0F, 0F, -0.5061455F));
        root.addOrReplaceChild(BLADE3, CubeListBuilder.create().texOffs(0, 0).addBox(-1.5F, -3F, 0F, 10F, 1F, 1F),
                PartPose.offsetAndRotation(0F, -12F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(BLADE4, CubeListBuilder.create().texOffs(0, 0).addBox(-1F, -2F, 0F, 7F, 1F, 1F),
                PartPose.offsetAndRotation(0F, -12F, 0F, 0F, 0F, 0.5061455F));
        root.addOrReplaceChild(BLADE5, CubeListBuilder.create().texOffs(0, 0).addBox(0.5F, -3.5F, 0F, 8F, 1F, 1F),
                PartPose.offsetAndRotation(0F, -12F, 0F, 0F, 0F, -0.5061455F));
        root.addOrReplaceChild(BLADE6, CubeListBuilder.create().texOffs(70, 0).addBox(-12.2F, -5.2F, 0F, 3F, 10F, 1F),
                PartPose.offsetAndRotation(0F, -13F, 0F, 0F, 0F, 0.5061455F));
        root.addOrReplaceChild(BLADE7, CubeListBuilder.create().texOffs(0, 0).addBox(-9.9F, -3F, 0F, 8F, 1F, 1F),
                PartPose.offsetAndRotation(0F, -12F, 0F, 0F, 0F, 0.5061455F));
        root.addOrReplaceChild(BLADE8, CubeListBuilder.create().texOffs(0, 0).addBox(-10F, -3F, 0F, 10F, 1F, 1F),
                PartPose.offsetAndRotation(0F, -12F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(BLADE9, CubeListBuilder.create().texOffs(70, 0).addBox(-10F, -8.5F, 0F, 3F, 10F, 1F),
                PartPose.offsetAndRotation(0F, -12F, 0F, 0F, 0F, -0.5061455F));
        root.addOrReplaceChild(BLADE10, CubeListBuilder.create().texOffs(0, 0).addBox(-7F, -2.5F, 0F, 7F, 1F, 1F),
                PartPose.offsetAndRotation(0F, -12F, 0F, 0F, 0F, -0.5061455F));
        return LayerDefinition.create(mesh, TEXTURE_WIDTH, TEXTURE_HEIGHT);
    }
}
