// GENERATED by tools/gen_models.py from reference/jar/models/ModelBee.json - do not edit.
package com.swbr.orespawn.client.model.geom;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Geometry of OreSpawn's ModelBee (23 parts), copied unchanged from the 1.7.10 jar.
 * Part order is the order the original constructor created them.
 */
public final class BeeGeometry {

    public static final int TEXTURE_WIDTH = 256;
    public static final int TEXTURE_HEIGHT = 256;

    public static final String STING = "Sting";
    public static final String ABDOMNEM1 = "Abdomnem1";
    public static final String ABDOMNEM2 = "Abdomnem2";
    public static final String ABDOMNEM3 = "Abdomnem3";
    public static final String ABDOMNEM4 = "Abdomnem4";
    public static final String ABDOMNEM5 = "Abdomnem5";
    public static final String MAIN_BODY = "MainBody";
    public static final String NECK = "Neck";
    public static final String HEAD = "Head";
    public static final String WING_RIGHT = "WingRight";
    public static final String WING_LEFT = "WingLeft";
    public static final String RA1 = "RA1";
    public static final String LA1 = "LA1";
    public static final String LA2 = "LA2";
    public static final String RA2 = "RA2";
    public static final String RA3 = "RA3";
    public static final String LA3 = "LA3";
    public static final String LEFT_POM = "LeftPom";
    public static final String RIGHT_POM = "RightPom";
    public static final String LEFT_PINCER_EXTRA = "LeftPincerExtra";
    public static final String LEFT_PINCER_MAIN = "LeftPincerMain";
    public static final String RIGHT_PINCER_MAIN = "RightPincerMain";
    public static final String RIGHT_PINCER_EXTRA = "RightPincerExtra";

    /** Every part in creation order. */
    public static final String[] PARTS = {
            STING,
            ABDOMNEM1,
            ABDOMNEM2,
            ABDOMNEM3,
            ABDOMNEM4,
            ABDOMNEM5,
            MAIN_BODY,
            NECK,
            HEAD,
            WING_RIGHT,
            WING_LEFT,
            RA1,
            LA1,
            LA2,
            RA2,
            RA3,
            LA3,
            LEFT_POM,
            RIGHT_POM,
            LEFT_PINCER_EXTRA,
            LEFT_PINCER_MAIN,
            RIGHT_PINCER_MAIN,
            RIGHT_PINCER_EXTRA
    };

    /** Parts the original hid at construction time (showModel = false or isHidden = true). */
    public static final String[] HIDDEN = {};

    private BeeGeometry() {}

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild(STING, CubeListBuilder.create().texOffs(68, 0).addBox(-1F, 0F, -1F, 2F, 10F, 2F),
                PartPose.offsetAndRotation(0F, 16F, 1F, -0.7853982F, 0F, 0F));
        root.addOrReplaceChild(ABDOMNEM1, CubeListBuilder.create().texOffs(64, 12).addBox(-2F, 0F, 0F, 4F, 8F, 4F),
                PartPose.offsetAndRotation(0F, 9F, 2F, -0.5235988F, 0F, 0F));
        root.addOrReplaceChild(ABDOMNEM2, CubeListBuilder.create().texOffs(60, 24).addBox(-3F, 0F, 0F, 6F, 6F, 6F),
                PartPose.offsetAndRotation(0F, 5F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(ABDOMNEM3, CubeListBuilder.create().texOffs(56, 36).addBox(-4F, 0F, 0F, 8F, 7F, 8F),
                PartPose.offsetAndRotation(0F, 1F, -2F, 0.2617994F, 0F, 0F));
        root.addOrReplaceChild(ABDOMNEM4, CubeListBuilder.create().texOffs(53, 51).addBox(-5F, 0F, 0F, 10F, 12F, 10F),
                PartPose.offsetAndRotation(0F, -6F, -8F, 0.5934119F, 0F, 0F));
        root.addOrReplaceChild(ABDOMNEM5, CubeListBuilder.create().texOffs(48, 73).addBox(-6F, 0F, 0F, 12F, 12F, 12F),
                PartPose.offsetAndRotation(0F, -6F, -15F, 1.099557F, 0F, 0F));
        root.addOrReplaceChild(MAIN_BODY, CubeListBuilder.create().texOffs(48, 97).addBox(-6F, 0F, -6F, 12F, 14F, 12F),
                PartPose.offsetAndRotation(0F, -12F, -24F, 1.48353F, 0F, 0F));
        root.addOrReplaceChild(NECK, CubeListBuilder.create().texOffs(55, 123).addBox(-4F, -4F, -8F, 8F, 8F, 8F),
                PartPose.offsetAndRotation(0F, -12F, -23F, 0F, 0F, 0F));
        root.addOrReplaceChild(HEAD, CubeListBuilder.create().texOffs(51, 139).addBox(-5F, -5F, -10F, 10F, 10F, 10F),
                PartPose.offsetAndRotation(0F, -13F, -28F, 0.2617994F, 0F, 0F));
        root.addOrReplaceChild(WING_RIGHT, CubeListBuilder.create().texOffs(0, 91).addBox(0F, 0F, 0F, 0F, 8F, 24F),
                PartPose.offsetAndRotation(-4F, -14F, -15F, -0.7853982F, -0.5235988F, 2.617994F));
        root.addOrReplaceChild(WING_LEFT, CubeListBuilder.create().texOffs(96, 91).addBox(0F, 0F, 0F, 0F, 8F, 24F),
                PartPose.offsetAndRotation(3F, -14F, -15F, -0.7853982F, 0.5235988F, -2.617994F));
        root.addOrReplaceChild(RA1, CubeListBuilder.create().texOffs(47, 152).addBox(0F, -6F, -1F, 1F, 6F, 1F),
                PartPose.offsetAndRotation(-3F, -17F, -31F, 0.2617994F, 0.5235988F, 0F));
        root.addOrReplaceChild(LA1, CubeListBuilder.create().texOffs(91, 152).addBox(0F, -6F, -1F, 1F, 6F, 1F),
                PartPose.offsetAndRotation(2F, -17F, -32F, 0.2617994F, -0.5235988F, 0F));
        root.addOrReplaceChild(LA2, CubeListBuilder.create().texOffs(91, 145).addBox(0F, -11F, 0F, 1F, 6F, 1F),
                PartPose.offsetAndRotation(2F, -17F, -32F, 0.4363323F, -0.6108652F, 0F));
        root.addOrReplaceChild(RA2, CubeListBuilder.create().texOffs(47, 145).addBox(0F, -11F, 0F, 1F, 6F, 1F),
                PartPose.offsetAndRotation(-3F, -17F, -31F, 0.4363323F, 0.6108652F, 0F));
        root.addOrReplaceChild(RA3, CubeListBuilder.create().texOffs(47, 138).addBox(0F, -16F, 2F, 1F, 6F, 1F),
                PartPose.offsetAndRotation(-3F, -17F, -31F, 0.6108652F, 0.6981317F, 0F));
        root.addOrReplaceChild(LA3, CubeListBuilder.create().texOffs(91, 138).addBox(0F, -16F, 2F, 1F, 6F, 1F),
                PartPose.offsetAndRotation(2F, -17F, -32F, 0.6108652F, -0.6981317F, 0F));
        root.addOrReplaceChild(LEFT_POM, CubeListBuilder.create().texOffs(89, 134).addBox(4F, -16F, -6F, 2F, 2F, 2F),
                PartPose.offsetAndRotation(2F, -17F, -32F, 0F, 0F, 0F));
        root.addOrReplaceChild(RIGHT_POM, CubeListBuilder.create().texOffs(45, 134).addBox(-5F, -16F, -7F, 2F, 2F, 2F),
                PartPose.offsetAndRotation(-3F, -17F, -31F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEFT_PINCER_EXTRA, CubeListBuilder.create().texOffs(71, 166).addBox(-2F, 0F, -6F, 2F, 1F, 2F),
                PartPose.offsetAndRotation(2F, -8F, -36F, 0.1745329F, -0.1745329F, 0F));
        root.addOrReplaceChild(LEFT_PINCER_MAIN, CubeListBuilder.create().texOffs(71, 159).addBox(0F, 0F, -6F, 2F, 1F, 6F),
                PartPose.offsetAndRotation(2F, -8F, -36F, 0.1745329F, -0.1745329F, 0F));
        root.addOrReplaceChild(RIGHT_PINCER_MAIN, CubeListBuilder.create().texOffs(55, 159).addBox(0F, 0F, -6F, 2F, 1F, 6F),
                PartPose.offsetAndRotation(-4F, -8F, -36F, 0.1745329F, 0.1745329F, 0F));
        root.addOrReplaceChild(RIGHT_PINCER_EXTRA, CubeListBuilder.create().texOffs(63, 166).addBox(2F, 0F, -6F, 2F, 1F, 2F),
                PartPose.offsetAndRotation(-4F, -8F, -36F, 0.1745329F, 0.1745329F, 0F));
        return LayerDefinition.create(mesh, TEXTURE_WIDTH, TEXTURE_HEIGHT);
    }
}
