// GENERATED by tools/gen_models.py from reference/jar/models/ModelButterfly.json - do not edit.
package com.swbr.orespawn.client.model.geom;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Geometry of OreSpawn's ModelButterfly (10 parts), copied unchanged from the 1.7.10 jar.
 * Part order is the order the original constructor created them.
 */
public final class ButterflyGeometry {

    public static final int TEXTURE_WIDTH = 64;
    public static final int TEXTURE_HEIGHT = 32;

    public static final String BODY = "body";
    public static final String LEFTWING = "leftwing";
    public static final String RIGHTWING = "rightwing";
    public static final String LEFTWING2 = "leftwing2";
    public static final String RIGHTWING2 = "rightwing2";
    public static final String LEFTWING3 = "leftwing3";
    public static final String RIGHTWING3 = "rightwing3";
    public static final String HEAD = "head";
    public static final String LEFTWING4 = "leftwing4";
    public static final String RIGHTWING4 = "rightwing4";

    /** Every part in creation order. */
    public static final String[] PARTS = {
            BODY,
            LEFTWING,
            RIGHTWING,
            LEFTWING2,
            RIGHTWING2,
            LEFTWING3,
            RIGHTWING3,
            HEAD,
            LEFTWING4,
            RIGHTWING4
    };

    /** Parts the original hid at construction time (showModel = false or isHidden = true). */
    public static final String[] HIDDEN = {};

    private ButterflyGeometry() {}

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild(BODY, CubeListBuilder.create().texOffs(21, 19).addBox(0F, 0F, -4F, 1F, 1F, 8F),
                PartPose.offsetAndRotation(0F, 17F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEFTWING, CubeListBuilder.create().texOffs(43, 24).addBox(0F, 0F, -4F, 5F, 1F, 5F),
                PartPose.offsetAndRotation(1F, 17F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(RIGHTWING, CubeListBuilder.create().texOffs(43, 17).addBox(-5F, 0F, -4F, 5F, 1F, 5F),
                PartPose.offsetAndRotation(0F, 17F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEFTWING2, CubeListBuilder.create().texOffs(0, 0).addBox(1F, 0F, -6F, 6F, 1F, 7F),
                PartPose.offsetAndRotation(1F, 17F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(RIGHTWING2, CubeListBuilder.create().texOffs(29, 0).addBox(-7F, 0F, -6F, 6F, 1F, 7F),
                PartPose.offsetAndRotation(0F, 17F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEFTWING3, CubeListBuilder.create().texOffs(0, 9).addBox(0F, 0F, 1F, 5F, 1F, 5F),
                PartPose.offsetAndRotation(1F, 17F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(RIGHTWING3, CubeListBuilder.create().texOffs(27, 9).addBox(-5F, 0F, 1F, 5F, 1F, 5F),
                PartPose.offsetAndRotation(0F, 17F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(HEAD, CubeListBuilder.create().texOffs(21, 11).addBox(0F, 0F, -6F, 1F, 1F, 1F),
                PartPose.offsetAndRotation(0F, 17F, 1F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEFTWING4, CubeListBuilder.create().texOffs(2, 24).addBox(0F, 0F, 6F, 1F, 1F, 7F),
                PartPose.offsetAndRotation(1F, 17F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(RIGHTWING4, CubeListBuilder.create().texOffs(2, 16).addBox(-1F, 0F, 6F, 1F, 1F, 7F),
                PartPose.offsetAndRotation(0F, 17F, 0F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, TEXTURE_WIDTH, TEXTURE_HEIGHT);
    }
}
