// GENERATED by tools/gen_models.py from reference/jar/models/ModelCassowary.json - do not edit.
package com.swbr.orespawn.client.model.geom;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Geometry of OreSpawn's ModelCassowary (12 parts), copied unchanged from the 1.7.10 jar.
 * Part order is the order the original constructor created them.
 */
public final class CassowaryGeometry {

    public static final int TEXTURE_WIDTH = 64;
    public static final int TEXTURE_HEIGHT = 32;

    public static final String TAIL = "tail";
    public static final String BODY = "body";
    public static final String NECK1 = "neck1";
    public static final String NECK = "neck";
    public static final String HEAD = "head";
    public static final String BEAK = "beak";
    public static final String LEG1 = "leg1";
    public static final String LEG2 = "leg2";
    public static final String CREST = "crest";
    public static final String FOOT1 = "foot1";
    public static final String FOOT2 = "foot2";
    public static final String GOBBLER = "gobbler";

    /** Every part in creation order. */
    public static final String[] PARTS = {
            TAIL,
            BODY,
            NECK1,
            NECK,
            HEAD,
            BEAK,
            LEG1,
            LEG2,
            CREST,
            FOOT1,
            FOOT2,
            GOBBLER
    };

    /** Parts the original hid at construction time (showModel = false or isHidden = true). */
    public static final String[] HIDDEN = {};

    private CassowaryGeometry() {}

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild(TAIL, CubeListBuilder.create().texOffs(38, 16).addBox(-3F, 0F, 0F, 6F, 9F, 7F),
                PartPose.offsetAndRotation(0F, 8F, 1F, 0.8922867F, 0F, 0F));
        root.addOrReplaceChild(BODY, CubeListBuilder.create().texOffs(0, 13).addBox(-4F, 0F, 0F, 8F, 10F, 9F),
                PartPose.offsetAndRotation(0F, 5F, -3F, 0.3346075F, 0F, 0F));
        root.addOrReplaceChild(NECK1, CubeListBuilder.create().texOffs(48, 0).addBox(-2F, 0F, 0F, 4F, 5F, 4F),
                PartPose.offsetAndRotation(0F, 4F, -1F, -1.189716F, 0F, 0F));
        root.addOrReplaceChild(NECK, CubeListBuilder.create().texOffs(38, 0).addBox(-1F, 0F, 0F, 2F, 7F, 2F),
                PartPose.offsetAndRotation(0F, 8F, -3F, -2.806985F, 0F, 0F));
        root.addOrReplaceChild(HEAD, CubeListBuilder.create().texOffs(24, 0).addBox(-1F, -2F, -3F, 2F, 2F, 4F),
                PartPose.offsetAndRotation(0F, 2F, -6F, 0.0371786F, 0F, 0F));
        root.addOrReplaceChild(BEAK, CubeListBuilder.create().texOffs(28, 7).addBox(-0.5F, 0F, 3F, 1F, 1F, 3F),
                PartPose.offsetAndRotation(0F, 2F, -6F, -3.104414F, 0F, 0F));
        root.addOrReplaceChild(LEG1, CubeListBuilder.create().texOffs(0, 0).addBox(-0.5F, 0F, -1F, 1F, 11F, 2F),
                PartPose.offsetAndRotation(3F, 12F, 3F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEG2, CubeListBuilder.create().texOffs(0, 0).addBox(-0.5F, 0F, -1F, 1F, 11F, 2F),
                PartPose.offsetAndRotation(-3F, 12F, 3F, 0F, 0F, 0F));
        root.addOrReplaceChild(CREST, CubeListBuilder.create().texOffs(10, 0).addBox(-0.5F, -4F, 1F, 1F, 4F, 5F),
                PartPose.offsetAndRotation(0F, 2F, -6F, 1.710216F, 0F, 0F));
        root.addOrReplaceChild(FOOT1, CubeListBuilder.create().texOffs(47, 10).addBox(-1.033333F, 11F, -2F, 2F, 1F, 3F),
                PartPose.offsetAndRotation(-3F, 12F, 3F, 0F, 0F, 0F));
        root.addOrReplaceChild(FOOT2, CubeListBuilder.create().texOffs(47, 10).addBox(-1F, 11F, -2F, 2F, 1F, 3F),
                PartPose.offsetAndRotation(3F, 12F, 3F, 0F, 0F, 0F));
        root.addOrReplaceChild(GOBBLER, CubeListBuilder.create().texOffs(38, 10).addBox(-0.5F, -1F, -2.5F, 1F, 5F, 1F),
                PartPose.offsetAndRotation(0F, 8F, -3F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, TEXTURE_WIDTH, TEXTURE_HEIGHT);
    }
}
