// GENERATED by tools/gen_models.py from reference/jar/models/ModelChipmunk.json - do not edit.
package com.swbr.orespawn.client.model.geom;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Geometry of OreSpawn's ModelChipmunk (18 parts), copied unchanged from the 1.7.10 jar.
 * Part order is the order the original constructor created them.
 */
public final class ChipmunkGeometry {

    public static final int TEXTURE_WIDTH = 64;
    public static final int TEXTURE_HEIGHT = 32;

    public static final String CHEEK2 = "Cheek2";
    public static final String LEG1 = "Leg1";
    public static final String LEG2 = "Leg2";
    public static final String LEG3 = "Leg3";
    public static final String LEG4 = "Leg4";
    public static final String TAIL2 = "Tail2";
    public static final String NECK = "Neck";
    public static final String HEAD = "Head";
    public static final String MOUTH_UNDER = "MouthUnder";
    public static final String CHEEK1 = "Cheek1";
    public static final String EAR2 = "Ear2";
    public static final String NOSE = "Nose";
    public static final String EAR1 = "Ear1";
    public static final String BODY = "Body";
    public static final String BODY_TAIL = "BodyTail";
    public static final String TAIL1 = "Tail1";
    public static final String HAT1 = "Hat1";
    public static final String HAT2 = "Hat2";

    /** Every part in creation order. */
    public static final String[] PARTS = {
            CHEEK2,
            LEG1,
            LEG2,
            LEG3,
            LEG4,
            TAIL2,
            NECK,
            HEAD,
            MOUTH_UNDER,
            CHEEK1,
            EAR2,
            NOSE,
            EAR1,
            BODY,
            BODY_TAIL,
            TAIL1,
            HAT1,
            HAT2
    };

    /** Parts the original hid at construction time (showModel = false or isHidden = true). */
    public static final String[] HIDDEN = {};

    private ChipmunkGeometry() {}

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild(CHEEK2, CubeListBuilder.create().texOffs(14, 0).addBox(0.5F, -1.5F, -3.5F, 2F, 2F, 2F),
                PartPose.offsetAndRotation(0F, 20F, -3F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEG1, CubeListBuilder.create().texOffs(22, 7).addBox(0F, 0F, 0F, 1F, 1F, 1F),
                PartPose.offsetAndRotation(-2F, 23F, -4F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEG2, CubeListBuilder.create().texOffs(22, 9).addBox(0F, 0F, 0F, 1F, 1F, 1F),
                PartPose.offsetAndRotation(1F, 23F, -4F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEG3, CubeListBuilder.create().texOffs(22, 11).addBox(0F, 0F, 0F, 1F, 1F, 1F),
                PartPose.offsetAndRotation(1F, 23F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEG4, CubeListBuilder.create().texOffs(22, 13).addBox(0F, 0F, 0F, 1F, 1F, 1F),
                PartPose.offsetAndRotation(-2F, 23F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(TAIL2, CubeListBuilder.create().texOffs(28, 15).addBox(-0.5F, 1F, 2.5F, 3F, 3F, 4F),
                PartPose.offsetAndRotation(-1F, 20F, 1F, 0.7662421F, 0F, 0F));
        root.addOrReplaceChild(NECK, CubeListBuilder.create().texOffs(26, 9).addBox(0F, 0F, 0F, 3F, 2F, 4F),
                PartPose.offsetAndRotation(-1.5F, 22F, -5F, 1.570796F, 0F, 0F));
        root.addOrReplaceChild(HEAD, CubeListBuilder.create().texOffs(0, 0).addBox(-2F, -3F, 0F, 4F, 4F, 3F),
                PartPose.offsetAndRotation(0F, 20F, -3F, 1.570796F, 0F, 0F));
        root.addOrReplaceChild(MOUTH_UNDER, CubeListBuilder.create().texOffs(20, 4).addBox(-1F, -1.9F, -3.8F, 2F, 2F, 1F),
                PartPose.offsetAndRotation(0F, 20F, -3F, 0F, 0F, 0F));
        root.addOrReplaceChild(CHEEK1, CubeListBuilder.create().texOffs(22, 0).addBox(-2.5F, -1.5F, -3.5F, 2F, 2F, 2F),
                PartPose.offsetAndRotation(0F, 20F, -3F, 0F, 0F, 0F));
        root.addOrReplaceChild(EAR2, CubeListBuilder.create().texOffs(18, 11).addBox(1F, 0F, 3F, 1F, 1F, 1F),
                PartPose.offsetAndRotation(0F, 20F, -3F, 1.570796F, 0F, 0F));
        root.addOrReplaceChild(NOSE, CubeListBuilder.create().texOffs(18, 7).addBox(-0.5F, -2F, -4.2F, 1F, 1F, 1F),
                PartPose.offsetAndRotation(0F, 20F, -3F, 0F, 0F, 0F));
        root.addOrReplaceChild(EAR1, CubeListBuilder.create().texOffs(18, 9).addBox(-2F, 0F, 3F, 1F, 1F, 1F),
                PartPose.offsetAndRotation(0F, 20F, -3F, 1.570796F, 0F, 0F));
        root.addOrReplaceChild(BODY, CubeListBuilder.create().texOffs(0, 7).addBox(0F, 0F, 0F, 4F, 3F, 5F),
                PartPose.offsetAndRotation(-2F, 20F, -4F, 0F, 0F, 0F));
        root.addOrReplaceChild(BODY_TAIL, CubeListBuilder.create().texOffs(0, 15).addBox(0F, 0F, 0F, 5F, 4F, 3F),
                PartPose.offsetAndRotation(-2.5F, 19F, -1F, 0F, 0F, 0F));
        root.addOrReplaceChild(TAIL1, CubeListBuilder.create().texOffs(16, 15).addBox(0F, 0F, 0F, 2F, 2F, 4F),
                PartPose.offsetAndRotation(-1F, 20F, 1F, 0.3064968F, 0F, 0F));
        root.addOrReplaceChild(HAT1, CubeListBuilder.create().texOffs(40, 0).addBox(-2.5F, -4F, -4F, 5F, 1F, 5F),
                PartPose.offsetAndRotation(0F, 20F, -3F, 0F, 0F, 0F));
        root.addOrReplaceChild(HAT2, CubeListBuilder.create().texOffs(40, 0).addBox(-2F, -6F, -3F, 4F, 2F, 4F),
                PartPose.offsetAndRotation(0F, 20F, -3F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, TEXTURE_WIDTH, TEXTURE_HEIGHT);
    }
}
