// GENERATED by tools/gen_models.py from reference/jar/models/ModelCloudShark.json - do not edit.
package com.swbr.orespawn.client.model.geom;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Geometry of OreSpawn's ModelCloudShark (8 parts), copied unchanged from the 1.7.10 jar.
 * Part order is the order the original constructor created them.
 */
public final class CloudSharkGeometry {

    public static final int TEXTURE_WIDTH = 64;
    public static final int TEXTURE_HEIGHT = 64;

    public static final String BODY = "body";
    public static final String HEAD = "head";
    public static final String JAW = "jaw";
    public static final String TOPFIN = "topfin";
    public static final String BBODY = "bbody";
    public static final String FINS = "fins";
    public static final String LEFTFIN = "leftfin";
    public static final String RIGHTFIN = "rightfin";

    /** Every part in creation order. */
    public static final String[] PARTS = {
            BODY,
            HEAD,
            JAW,
            TOPFIN,
            BBODY,
            FINS,
            LEFTFIN,
            RIGHTFIN
    };

    /** Parts the original hid at construction time (showModel = false or isHidden = true). */
    public static final String[] HIDDEN = {};

    private CloudSharkGeometry() {}

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild(BODY, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 6F, 8F, 15F),
                PartPose.offsetAndRotation(-4F, 11F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(HEAD, CubeListBuilder.create().texOffs(0, 51).addBox(-2.5F, 0F, -8F, 5F, 5F, 8F),
                PartPose.offsetAndRotation(-1F, 11F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(JAW, CubeListBuilder.create().texOffs(42, 0).addBox(-2.5F, 0F, -6F, 5F, 2F, 6F),
                PartPose.offsetAndRotation(-1F, 15F, 0F, 0.5056291F, 0F, 0F));
        root.addOrReplaceChild(TOPFIN, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 1F, 3F, 6F),
                PartPose.offsetAndRotation(-1.5F, 11F, 5F, 0.935765F, 0F, 0F));
        root.addOrReplaceChild(BBODY, CubeListBuilder.create().texOffs(0, 9).addBox(-2F, 0F, 0F, 4F, 8F, 6F),
                PartPose.offsetAndRotation(-1F, 11F, 15F, 0F, 0F, 0F));
        root.addOrReplaceChild(FINS, CubeListBuilder.create().texOffs(0, 24).addBox(0F, 0F, 0F, 0F, 10F, 10F),
                PartPose.offsetAndRotation(-1F, 16F, 16F, 0.9220296F, 0F, 0F));
        root.addOrReplaceChild(LEFTFIN, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 0F, 3F, 7F),
                PartPose.offsetAndRotation(2F, 16F, 6F, -0.6108652F, 1.134464F, -0.6108652F));
        root.addOrReplaceChild(RIGHTFIN, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 0F, 3F, 7F),
                PartPose.offsetAndRotation(-4F, 16F, 6F, -0.6283185F, -1.134464F, 0.6108652F));
        return LayerDefinition.create(mesh, TEXTURE_WIDTH, TEXTURE_HEIGHT);
    }
}
