// GENERATED by tools/gen_models.py from reference/jar/models/ModelCockateil.json - do not edit.
package com.swbr.orespawn.client.model.geom;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Geometry of OreSpawn's ModelCockateil (16 parts), copied unchanged from the 1.7.10 jar.
 * Part order is the order the original constructor created them.
 */
public final class CockateilGeometry {

    public static final int TEXTURE_WIDTH = 64;
    public static final int TEXTURE_HEIGHT = 32;

    public static final String BODY = "Body";
    public static final String HEAD = "Head";
    public static final String BEAK = "Beak";
    public static final String LOWER_BEAK = "LowerBeak";
    public static final String FEATHER2 = "feather2";
    public static final String FEATHER1 = "feather1";
    public static final String FEATHER3 = "feather3";
    public static final String TAILFEATHER1 = "tailfeather1";
    public static final String RWING1 = "rwing1";
    public static final String LWING1 = "lwing1";
    public static final String LEG = "leg";
    public static final String OTHERLEG = "otherleg";
    public static final String LWING2 = "lwing2";
    public static final String RWING2 = "rwing2";
    public static final String TAILFEATHER2 = "tailfeather2";
    public static final String TAILFEATHER3 = "tailfeather3";

    /** Every part in creation order. */
    public static final String[] PARTS = {
            BODY,
            HEAD,
            BEAK,
            LOWER_BEAK,
            FEATHER2,
            FEATHER1,
            FEATHER3,
            TAILFEATHER1,
            RWING1,
            LWING1,
            LEG,
            OTHERLEG,
            LWING2,
            RWING2,
            TAILFEATHER2,
            TAILFEATHER3
    };

    /** Parts the original hid at construction time (showModel = false or isHidden = true). */
    public static final String[] HIDDEN = {};

    private CockateilGeometry() {}

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild(BODY, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 5F, 3F, 6F),
                PartPose.offsetAndRotation(-1F, 18F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(HEAD, CubeListBuilder.create().texOffs(22, 0).addBox(0F, 0F, 0F, 3F, 3F, 4F),
                PartPose.offsetAndRotation(0F, 16F, -3F, 0F, 0F, 0F));
        root.addOrReplaceChild(BEAK, CubeListBuilder.create().texOffs(0, 21).addBox(0F, 0F, 0F, 1F, 1F, 3F),
                PartPose.offsetAndRotation(1F, 17F, -6F, 0F, 0F, 0F));
        root.addOrReplaceChild(LOWER_BEAK, CubeListBuilder.create().texOffs(1, 17).addBox(0F, 0F, 0F, 1F, 1F, 1F),
                PartPose.offsetAndRotation(1F, 18F, -4F, 0F, 0F, 0F));
        root.addOrReplaceChild(FEATHER2, CubeListBuilder.create().texOffs(15, 9).addBox(0F, -2.5F, -0.75F, 1F, 3F, 1F),
                PartPose.offsetAndRotation(1F, 16F, 0F, -0.6426736F, 0F, 0F));
        root.addOrReplaceChild(FEATHER1, CubeListBuilder.create().texOffs(11, 9).addBox(0F, -2.5F, -0.5F, 1F, 3F, 1F),
                PartPose.offsetAndRotation(1F, 16F, -2F, -0.2230717F, 0F, 0F));
        root.addOrReplaceChild(FEATHER3, CubeListBuilder.create().texOffs(19, 9).addBox(0F, -3F, 0.5F, 1F, 4F, 1F),
                PartPose.offsetAndRotation(1F, 16F, 1F, -1.276259F, 0F, 0F));
        root.addOrReplaceChild(TAILFEATHER1, CubeListBuilder.create().texOffs(46, 15).addBox(0F, 0F, 0F, 3F, 2F, 3F),
                PartPose.offsetAndRotation(0F, 18F, 6F, 0F, 0F, 0F));
        root.addOrReplaceChild(RWING1, CubeListBuilder.create().texOffs(23, 9).addBox(0F, 0F, 0F, 1F, 4F, 4F),
                PartPose.offsetAndRotation(-1F, 18F, 1F, 0F, 0F, 1.595066F));
        root.addOrReplaceChild(LWING1, CubeListBuilder.create().texOffs(33, 9).addBox(-1F, 0F, 0F, 1F, 4F, 4F),
                PartPose.offsetAndRotation(4F, 18F, 1F, 0F, 0F, -1.561488F));
        root.addOrReplaceChild(LEG, CubeListBuilder.create().texOffs(4, 12).addBox(0F, 0F, 0F, 1F, 3F, 1F),
                PartPose.offsetAndRotation(2F, 21F, 3F, 0.8726646F, 0F, 0F));
        root.addOrReplaceChild(OTHERLEG, CubeListBuilder.create().texOffs(0, 12).addBox(0F, 0F, 0F, 1F, 3F, 1F),
                PartPose.offsetAndRotation(0F, 21F, 3F, 0.6108652F, 0F, 0F));
        root.addOrReplaceChild(LWING2, CubeListBuilder.create().texOffs(10, 14).addBox(4F, 0F, 0F, 3F, 1F, 3F),
                PartPose.offsetAndRotation(4F, 18F, 1F, 0F, 0F, 0F));
        root.addOrReplaceChild(RWING2, CubeListBuilder.create().texOffs(10, 19).addBox(-7F, 0F, 0F, 3F, 1F, 3F),
                PartPose.offsetAndRotation(-1F, 18F, 1F, 0F, 0F, 0F));
        root.addOrReplaceChild(TAILFEATHER2, CubeListBuilder.create().texOffs(44, 20).addBox(-0.5F, 0F, 3F, 4F, 1F, 4F),
                PartPose.offsetAndRotation(0F, 18F, 6F, 0F, 0F, 0F));
        root.addOrReplaceChild(TAILFEATHER3, CubeListBuilder.create().texOffs(36, 26).addBox(-1F, 0F, 7F, 5F, 1F, 4F),
                PartPose.offsetAndRotation(0F, 18F, 6F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, TEXTURE_WIDTH, TEXTURE_HEIGHT);
    }
}
