// GENERATED by tools/gen_models.py from reference/jar/models/ModelCrab.json - do not edit.
package com.swbr.orespawn.client.model.geom;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Geometry of OreSpawn's ModelCrab (25 parts), copied unchanged from the 1.7.10 jar.
 * Part order is the order the original constructor created them.
 */
public final class CrabGeometry {

    public static final int TEXTURE_WIDTH = 256;
    public static final int TEXTURE_HEIGHT = 512;

    public static final String BODY1 = "body1";
    public static final String BODY2 = "body2";
    public static final String LEG1 = "leg1";
    public static final String BODY3 = "body3";
    public static final String BODY4 = "body4";
    public static final String LEG2 = "leg2";
    public static final String LEG3 = "leg3";
    public static final String BODY5 = "body5";
    public static final String BODY6 = "body6";
    public static final String LEYE1 = "Leye1";
    public static final String REYE1 = "Reye1";
    public static final String LEYE2 = "Leye2";
    public static final String REYE2 = "Reye2";
    public static final String LCLAW1 = "Lclaw1";
    public static final String LCLAW2 = "Lclaw2";
    public static final String LCLAW3 = "Lclaw3";
    public static final String LCLAW4 = "Lclaw4";
    public static final String LCLAW5 = "Lclaw5";
    public static final String RCLAW1 = "Rclaw1";
    public static final String RCLAW2 = "Rclaw2";
    public static final String RCLAW3 = "Rclaw3";
    public static final String RCLAW4 = "Rclaw4";
    public static final String RCLAW5 = "Rclaw5";
    public static final String RMOUTH = "Rmouth";
    public static final String LMOUTH = "Lmouth";

    /** Every part in creation order. */
    public static final String[] PARTS = {
            BODY1,
            BODY2,
            LEG1,
            BODY3,
            BODY4,
            LEG2,
            LEG3,
            BODY5,
            BODY6,
            LEYE1,
            REYE1,
            LEYE2,
            REYE2,
            LCLAW1,
            LCLAW2,
            LCLAW3,
            LCLAW4,
            LCLAW5,
            RCLAW1,
            RCLAW2,
            RCLAW3,
            RCLAW4,
            RCLAW5,
            RMOUTH,
            LMOUTH
    };

    /** Parts the original hid at construction time (showModel = false or isHidden = true). */
    public static final String[] HIDDEN = {};

    private CrabGeometry() {}

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild(BODY1, CubeListBuilder.create().texOffs(0, 450).addBox(-38F, -5F, -8F, 76F, 10F, 48F),
                PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(BODY2, CubeListBuilder.create().texOffs(0, 406).addBox(-32F, -10F, -10F, 64F, 5F, 34F),
                PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEG1, CubeListBuilder.create().texOffs(128, 0).addBox(-2F, 0F, -2F, 4F, 12F, 4F),
                PartPose.offsetAndRotation(36F, 3F, 0F, -1.343904F, -1.500983F, 0F));
        root.addOrReplaceChild(BODY3, CubeListBuilder.create().texOffs(0, 357).addBox(0F, 0F, 0F, 8F, 4F, 40F),
                PartPose.offsetAndRotation(38F, -5F, -6F, 0F, 0F, 0F));
        root.addOrReplaceChild(BODY4, CubeListBuilder.create().texOffs(100, 357).addBox(0F, 0F, 0F, 8F, 4F, 40F),
                PartPose.offsetAndRotation(-46F, -5F, -6F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEG2, CubeListBuilder.create().texOffs(128, 20).addBox(-1F, 10F, -6F, 3F, 16F, 3F),
                PartPose.offsetAndRotation(36F, 3F, 0F, -0.9599311F, -1.500983F, 0F));
        root.addOrReplaceChild(LEG3, CubeListBuilder.create().texOffs(128, 43).addBox(0F, 21F, -15F, 2F, 16F, 2F),
                PartPose.offsetAndRotation(36F, 3F, 0F, -0.5759587F, -1.500983F, 0F));
        root.addOrReplaceChild(BODY5, CubeListBuilder.create().texOffs(0, 339).addBox(-25F, 0F, 0F, 50F, 4F, 10F),
                PartPose.offsetAndRotation(0F, -4F, 40F, 0F, 0F, 0F));
        root.addOrReplaceChild(BODY6, CubeListBuilder.create().texOffs(124, 342).addBox(-14F, 0F, 0F, 28F, 3F, 4F),
                PartPose.offsetAndRotation(0F, -10F, -14F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEYE1, CubeListBuilder.create().texOffs(62, 0).addBox(-0.5F, -12F, -0.5F, 1F, 12F, 1F),
                PartPose.offsetAndRotation(9F, -9F, -11F, 0F, 0F, 0.4886922F));
        root.addOrReplaceChild(REYE1, CubeListBuilder.create().texOffs(40, 0).addBox(-0.5F, -12F, -0.5F, 1F, 12F, 1F),
                PartPose.offsetAndRotation(-9F, -9F, -11F, 0F, 0F, -0.4886922F));
        root.addOrReplaceChild(LEYE2, CubeListBuilder.create().texOffs(50, 0).addBox(-1F, -14F, -1F, 2F, 2F, 2F),
                PartPose.offsetAndRotation(9F, -9F, -11F, 0F, 0F, 0.4886922F));
        root.addOrReplaceChild(REYE2, CubeListBuilder.create().texOffs(26, 0).addBox(-1F, -14F, -1F, 2F, 2F, 2F),
                PartPose.offsetAndRotation(-9F, -9F, -11F, 0F, 0F, -0.4886922F));
        root.addOrReplaceChild(LCLAW1, CubeListBuilder.create().texOffs(0, 80).addBox(-4F, 0F, -14F, 8F, 4F, 18F),
                PartPose.offsetAndRotation(31F, -2F, -8F, 0F, -0.4886922F, 0F));
        root.addOrReplaceChild(LCLAW2, CubeListBuilder.create().texOffs(0, 105).addBox(-7F, -3F, -12F, 17F, 6F, 16F),
                PartPose.offsetAndRotation(37F, 0F, -20F, 0F, -0.1745329F, 0F));
        root.addOrReplaceChild(LCLAW3, CubeListBuilder.create().texOffs(0, 131).addBox(0F, -5F, -25F, 17F, 10F, 30F),
                PartPose.offsetAndRotation(37F, 0F, -31F, 0F, -0.4537856F, 0F));
        root.addOrReplaceChild(LCLAW4, CubeListBuilder.create().texOffs(0, 175).addBox(2F, -3F, -32F, 11F, 5F, 12F),
                PartPose.offsetAndRotation(37F, 0F, -31F, 0F, -0.3490659F, 0F));
        root.addOrReplaceChild(LCLAW5, CubeListBuilder.create().texOffs(0, 197).addBox(-4F, -3F, -27F, 7F, 5F, 32F),
                PartPose.offsetAndRotation(36F, 0F, -31F, 0F, 0.3839724F, 0F));
        root.addOrReplaceChild(RCLAW1, CubeListBuilder.create().texOffs(102, 78).addBox(-4F, 0F, -14F, 8F, 4F, 18F),
                PartPose.offsetAndRotation(-31F, -2F, -8F, 0F, 0.4886922F, 0F));
        root.addOrReplaceChild(RCLAW2, CubeListBuilder.create().texOffs(103, 106).addBox(-10F, -3F, -12F, 17F, 6F, 16F),
                PartPose.offsetAndRotation(-37F, 0F, -20F, 0F, 0.1745329F, 0F));
        root.addOrReplaceChild(RCLAW3, CubeListBuilder.create().texOffs(100, 131).addBox(-17F, -5F, -25F, 17F, 10F, 30F),
                PartPose.offsetAndRotation(-37F, 0F, -31F, 0F, 0.4537856F, 0F));
        root.addOrReplaceChild(RCLAW4, CubeListBuilder.create().texOffs(101, 175).addBox(-13F, -3F, -32F, 11F, 5F, 12F),
                PartPose.offsetAndRotation(-37F, 0F, -31F, 0F, 0.3490659F, 0F));
        root.addOrReplaceChild(RCLAW5, CubeListBuilder.create().texOffs(100, 197).addBox(-4F, -3F, -27F, 7F, 5F, 32F),
                PartPose.offsetAndRotation(-36F, 0F, -31F, 0F, -0.3839724F, 0F));
        root.addOrReplaceChild(RMOUTH, CubeListBuilder.create().texOffs(0, 28).addBox(0F, 0F, -0.5F, 6F, 3F, 1F),
                PartPose.offsetAndRotation(-7F, 0F, -7.5F, 0F, 0.3665191F, 0F));
        root.addOrReplaceChild(LMOUTH, CubeListBuilder.create().texOffs(0, 19).addBox(-6F, 0F, -0.5F, 6F, 3F, 1F),
                PartPose.offsetAndRotation(7F, 0F, -7.5F, 0F, -0.3665191F, 0F));
        return LayerDefinition.create(mesh, TEXTURE_WIDTH, TEXTURE_HEIGHT);
    }
}
