// GENERATED by tools/gen_models.py from reference/jar/models/ModelCreepingHorror.json - do not edit.
package com.swbr.orespawn.client.model.geom;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Geometry of OreSpawn's ModelCreepingHorror (26 parts), copied unchanged from the 1.7.10 jar.
 * Part order is the order the original constructor created them.
 */
public final class CreepingHorrorGeometry {

    public static final int TEXTURE_WIDTH = 128;
    public static final int TEXTURE_HEIGHT = 128;

    public static final String BODY = "body";
    public static final String LEG1 = "leg1";
    public static final String LEG1PART2 = "leg1part2";
    public static final String LEG2 = "leg2";
    public static final String LEG2PART2 = "leg2part2";
    public static final String LEG3 = "leg3";
    public static final String LEG3PART2 = "leg3part2";
    public static final String LEG4 = "leg4";
    public static final String LEG4PART2 = "leg4part2";
    public static final String TAILSEG1 = "tailseg1";
    public static final String TAILSEG2 = "tailseg2";
    public static final String TAILSEG3 = "tailseg3";
    public static final String PINCER1 = "pincer1";
    public static final String PINCER1PART2 = "pincer1part2";
    public static final String PINCER2 = "pincer2";
    public static final String PINCER2PART2 = "pincer2part2";
    public static final String SPIKE1 = "spike1";
    public static final String SPIKE2 = "spike2";
    public static final String SPIKE3 = "spike3";
    public static final String SPIKE4 = "spike4";
    public static final String SPIKE5 = "spike5";
    public static final String INSIDES1 = "insides1";
    public static final String INSIDES2 = "insides2";
    public static final String INSIDES3 = "insides3";
    public static final String INSIDES4 = "insides4";
    public static final String INSIDES5 = "insides5";

    /** Every part in creation order. */
    public static final String[] PARTS = {
            BODY,
            LEG1,
            LEG1PART2,
            LEG2,
            LEG2PART2,
            LEG3,
            LEG3PART2,
            LEG4,
            LEG4PART2,
            TAILSEG1,
            TAILSEG2,
            TAILSEG3,
            PINCER1,
            PINCER1PART2,
            PINCER2,
            PINCER2PART2,
            SPIKE1,
            SPIKE2,
            SPIKE3,
            SPIKE4,
            SPIKE5,
            INSIDES1,
            INSIDES2,
            INSIDES3,
            INSIDES4,
            INSIDES5
    };

    /** Parts the original hid at construction time (showModel = false or isHidden = true). */
    public static final String[] HIDDEN = {};

    private CreepingHorrorGeometry() {}

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild(BODY, CubeListBuilder.create().texOffs(0, 30).addBox(-4F, -5F, -4F, 8F, 8F, 8F),
                PartPose.offsetAndRotation(0F, 20F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEG1, CubeListBuilder.create().texOffs(65, 0).addBox(-1F, -1F, -1F, 16F, 2F, 2F),
                PartPose.offsetAndRotation(4F, 18F, -2F, 0F, 0.5759587F, 0.1919862F));
        root.addOrReplaceChild(LEG1PART2, CubeListBuilder.create().texOffs(37, 5).addBox(13.01F, -1.01F, -1F, 2F, 5F, 2F),
                PartPose.offsetAndRotation(4F, 18F, -2F, 0F, 0.5759587F, 0.1919862F));
        root.addOrReplaceChild(LEG2, CubeListBuilder.create().texOffs(65, 0).addBox(-1F, -1F, -1F, 16F, 2F, 2F),
                PartPose.offsetAndRotation(4F, 18F, 2F, 0F, -0.5759587F, 0.1919862F));
        root.addOrReplaceChild(LEG2PART2, CubeListBuilder.create().texOffs(37, 5).addBox(13.01F, -1.01F, -1F, 2F, 5F, 2F),
                PartPose.offsetAndRotation(4F, 18F, 2F, 0F, -0.5759587F, 0.1919862F));
        root.addOrReplaceChild(LEG3, CubeListBuilder.create().texOffs(28, 0).addBox(-15F, -1F, -1F, 16F, 2F, 2F),
                PartPose.offsetAndRotation(-4F, 18F, -2F, 0F, -0.5759587F, -0.1919862F));
        root.addOrReplaceChild(LEG3PART2, CubeListBuilder.create().texOffs(28, 5).addBox(-15.01F, -1.01F, -1F, 2F, 5F, 2F),
                PartPose.offsetAndRotation(-4F, 18F, -2F, 0F, -0.5759587F, -0.1919862F));
        root.addOrReplaceChild(LEG4, CubeListBuilder.create().texOffs(28, 0).addBox(-15F, -1F, -1F, 16F, 2F, 2F),
                PartPose.offsetAndRotation(-4F, 18F, 2F, 0F, 0.5759587F, -0.1919862F));
        root.addOrReplaceChild(LEG4PART2, CubeListBuilder.create().texOffs(28, 5).addBox(-15.01F, -1.01F, -1F, 2F, 5F, 2F),
                PartPose.offsetAndRotation(-4F, 18F, 2F, 0F, 0.5759587F, -0.1919862F));
        root.addOrReplaceChild(TAILSEG1, CubeListBuilder.create().texOffs(0, 13).addBox(-2F, -1F, 0F, 4F, 2F, 7F),
                PartPose.offsetAndRotation(0F, 17F, 3F, -0.5576792F, 0F, 0F));
        root.addOrReplaceChild(TAILSEG2, CubeListBuilder.create().texOffs(0, 0).addBox(-1F, 3F, 7F, 2F, 1F, 11F),
                PartPose.offsetAndRotation(0F, 17F, 3F, -0.0349066F, 0F, 0F));
        root.addOrReplaceChild(TAILSEG3, CubeListBuilder.create().texOffs(0, 24).addBox(-1.5F, 1F, 6F, 3F, 2F, 2F),
                PartPose.offsetAndRotation(0F, 17F, 3F, -0.2230717F, 0F, 0F));
        root.addOrReplaceChild(PINCER1, CubeListBuilder.create().texOffs(26, 30).addBox(-0.5F, -0.5F, -5F, 1F, 1F, 5F),
                PartPose.offsetAndRotation(-3F, 19F, -3F, 0F, -0.2230717F, 0F));
        root.addOrReplaceChild(PINCER1PART2, CubeListBuilder.create().texOffs(26, 30).addBox(-0.5F, -0.5F, -5.01F, 2F, 1F, 0F),
                PartPose.offsetAndRotation(-3F, 19F, -3F, 0F, -0.2230717F, 0F));
        root.addOrReplaceChild(PINCER2, CubeListBuilder.create().texOffs(26, 30).addBox(-0.5F, -0.5F, -5F, 1F, 1F, 5F),
                PartPose.offsetAndRotation(3F, 19F, -3F, 0F, 0.2230705F, 0F));
        root.addOrReplaceChild(PINCER2PART2, CubeListBuilder.create().texOffs(26, 28).addBox(-1.5F, -0.5F, -5.01F, 2F, 1F, 0F),
                PartPose.offsetAndRotation(3F, 19F, -3F, 0F, 0.2230705F, 0F));
        root.addOrReplaceChild(SPIKE1, CubeListBuilder.create().texOffs(26, 13).addBox(-0.5F, -0.5F, 0F, 1F, 1F, 6F),
                PartPose.offsetAndRotation(-3F, 16F, -2F, 0.7063936F, -0.2602503F, 0F));
        root.addOrReplaceChild(SPIKE2, CubeListBuilder.create().texOffs(26, 13).addBox(-0.5F, -0.5F, 0F, 1F, 1F, 6F),
                PartPose.offsetAndRotation(-1F, 16F, 1F, 0.7063936F, -0.111544F, 0F));
        root.addOrReplaceChild(SPIKE3, CubeListBuilder.create().texOffs(26, 13).addBox(-0.5F, -0.5F, 0F, 1F, 1F, 6F),
                PartPose.offsetAndRotation(1F, 16F, 1F, 0.7063936F, 0.1115358F, 0F));
        root.addOrReplaceChild(SPIKE4, CubeListBuilder.create().texOffs(26, 13).addBox(-0.5F, -0.5F, 0F, 1F, 1F, 6F),
                PartPose.offsetAndRotation(3F, 16F, -2F, 0.7063936F, 0.260246F, 0F));
        root.addOrReplaceChild(SPIKE5, CubeListBuilder.create().texOffs(26, 13).addBox(-0.5F, -0.5F, 0F, 1F, 1F, 6F),
                PartPose.offsetAndRotation(0F, 16F, -3F, 0.7063936F, 0F, 0F));
        root.addOrReplaceChild(INSIDES1, CubeListBuilder.create().texOffs(0, 30).addBox(-2F, -3F, -3F, 4F, 4F, 0F),
                PartPose.offsetAndRotation(0F, 20F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(INSIDES2, CubeListBuilder.create().texOffs(-1, 29).addBox(-2F, -3F, -4F, 4F, 0F, 1F),
                PartPose.offsetAndRotation(0F, 20F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(INSIDES3, CubeListBuilder.create().texOffs(-1, 29).addBox(-2F, 1F, -4F, 4F, 0F, 1F),
                PartPose.offsetAndRotation(0F, 20F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(INSIDES4, CubeListBuilder.create().texOffs(0, 29).addBox(-2F, -3F, -4F, 0F, 4F, 1F),
                PartPose.offsetAndRotation(0F, 20F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(INSIDES5, CubeListBuilder.create().texOffs(0, 29).addBox(2F, -3F, -4F, 0F, 4F, 1F),
                PartPose.offsetAndRotation(0F, 20F, 0F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, TEXTURE_WIDTH, TEXTURE_HEIGHT);
    }
}
