// GENERATED by tools/gen_models.py from reference/jar/models/ModelDragonfly.json - do not edit.
package com.swbr.orespawn.client.model.geom;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Geometry of OreSpawn's ModelDragonfly (26 parts), copied unchanged from the 1.7.10 jar.
 * Part order is the order the original constructor created them.
 */
public final class DragonflyGeometry {

    public static final int TEXTURE_WIDTH = 64;
    public static final int TEXTURE_HEIGHT = 64;

    public static final String SHAPE1 = "Shape1";
    public static final String LFWING = "lfwing";
    public static final String SHAPE3 = "Shape3";
    public static final String SHAPE4 = "Shape4";
    public static final String SHAPE5 = "Shape5";
    public static final String RJAW = "rjaw";
    public static final String LJAW = "ljaw";
    public static final String TAIL1 = "tail1";
    public static final String TAIL2 = "tail2";
    public static final String SHAPE10 = "Shape10";
    public static final String SHAPE11 = "Shape11";
    public static final String SHAPE12 = "Shape12";
    public static final String SHAPE13 = "Shape13";
    public static final String SHAPE14 = "Shape14";
    public static final String SHAPE15 = "Shape15";
    public static final String SHAPE16 = "Shape16";
    public static final String SHAPE17 = "Shape17";
    public static final String SHAPE18 = "Shape18";
    public static final String SHAPE19 = "Shape19";
    public static final String SHAPE20 = "Shape20";
    public static final String SHAPE21 = "Shape21";
    public static final String SHAPE22 = "Shape22";
    public static final String SHAPE23 = "Shape23";
    public static final String LRWING = "lrwing";
    public static final String RFWING = "rfwing";
    public static final String RRWING = "rrwing";

    /** Every part in creation order. */
    public static final String[] PARTS = {
            SHAPE1,
            LFWING,
            SHAPE3,
            SHAPE4,
            SHAPE5,
            RJAW,
            LJAW,
            TAIL1,
            TAIL2,
            SHAPE10,
            SHAPE11,
            SHAPE12,
            SHAPE13,
            SHAPE14,
            SHAPE15,
            SHAPE16,
            SHAPE17,
            SHAPE18,
            SHAPE19,
            SHAPE20,
            SHAPE21,
            SHAPE22,
            SHAPE23,
            LRWING,
            RFWING,
            RRWING
    };

    /** Parts the original hid at construction time (showModel = false or isHidden = true). */
    public static final String[] HIDDEN = {};

    private DragonflyGeometry() {}

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild(SHAPE1, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 5F, 4F, 7F),
                PartPose.offsetAndRotation(0F, 16F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(LFWING, CubeListBuilder.create().texOffs(0, 33).addBox(0F, 0F, 0F, 10F, 1F, 3F),
                PartPose.offsetAndRotation(5F, 16F, 1F, 0F, 0.4886922F, 0F));
        root.addOrReplaceChild(SHAPE3, CubeListBuilder.create().texOffs(0, 13).addBox(-2F, 0F, -4F, 4F, 3F, 4F),
                PartPose.offsetAndRotation(2.5F, 16F, -1F, 0.4886922F, 0F, 0F));
        root.addOrReplaceChild(SHAPE4, CubeListBuilder.create().texOffs(9, 21).addBox(0F, 0F, 0F, 1F, 2F, 3F),
                PartPose.offsetAndRotation(1F, 18F, -6F, 0.4886922F, 0.1745329F, 0F));
        root.addOrReplaceChild(SHAPE5, CubeListBuilder.create().texOffs(0, 21).addBox(0F, 0F, 0F, 1F, 2F, 3F),
                PartPose.offsetAndRotation(3F, 18F, -6F, 0.4886922F, -0.1745329F, 0F));
        root.addOrReplaceChild(RJAW, CubeListBuilder.create().texOffs(0, 27).addBox(-1F, 0F, 0F, 1F, 3F, 1F),
                PartPose.offsetAndRotation(2F, 19F, -5F, 0.4363323F, 0.1745329F, 0F));
        root.addOrReplaceChild(LJAW, CubeListBuilder.create().texOffs(5, 27).addBox(0F, 0F, 0F, 1F, 3F, 1F),
                PartPose.offsetAndRotation(3F, 19F, -5F, 0.4363323F, -0.1745329F, 0F));
        root.addOrReplaceChild(TAIL1, CubeListBuilder.create().texOffs(25, 0).addBox(-1F, 0F, 0F, 3F, 3F, 7F),
                PartPose.offsetAndRotation(2F, 16F, 7F, 0F, 0F, 0F));
        root.addOrReplaceChild(TAIL2, CubeListBuilder.create().texOffs(25, 11).addBox(0F, 0F, 0F, 1F, 2F, 9F),
                PartPose.offsetAndRotation(2F, 16F, 14F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE10, CubeListBuilder.create().texOffs(23, 0).addBox(-1F, 0F, 0F, 1F, 4F, 1F),
                PartPose.offsetAndRotation(1F, 18F, 0F, -0.2792527F, 0F, 0.3490659F));
        root.addOrReplaceChild(SHAPE11, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, -4F, 1F, 1F, 4F),
                PartPose.offsetAndRotation(-1F, 21F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE12, CubeListBuilder.create().texOffs(18, 12).addBox(-1F, 0F, 0F, 1F, 3F, 1F),
                PartPose.offsetAndRotation(0F, 21F, -4F, 0F, 0F, -0.1919862F));
        root.addOrReplaceChild(SHAPE13, CubeListBuilder.create().texOffs(18, 0).addBox(0F, 0F, 0F, 1F, 4F, 1F),
                PartPose.offsetAndRotation(4F, 18F, 0F, -0.2792527F, 0F, -0.3490659F));
        root.addOrReplaceChild(SHAPE14, CubeListBuilder.create().texOffs(51, 0).addBox(0F, 0F, -4F, 1F, 1F, 4F),
                PartPose.offsetAndRotation(5F, 21F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE15, CubeListBuilder.create().texOffs(13, 12).addBox(0F, 0F, 0F, 1F, 3F, 1F),
                PartPose.offsetAndRotation(5F, 21F, -4F, 0F, 0F, 0.1919862F));
        root.addOrReplaceChild(SHAPE16, CubeListBuilder.create().texOffs(9, 53).addBox(0F, 0F, 0F, 3F, 1F, 1F),
                PartPose.offsetAndRotation(5F, 19.5F, 3F, 0F, 0F, 0.6457718F));
        root.addOrReplaceChild(SHAPE17, CubeListBuilder.create().texOffs(0, 56).addBox(0F, 0F, 0F, 1F, 3F, 1F),
                PartPose.offsetAndRotation(6F, 21F, 3F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE18, CubeListBuilder.create().texOffs(0, 53).addBox(-3F, 0F, 0F, 3F, 1F, 1F),
                PartPose.offsetAndRotation(0F, 19.5F, 3F, 0F, 0F, -0.6457718F));
        root.addOrReplaceChild(SHAPE19, CubeListBuilder.create().texOffs(5, 56).addBox(-1F, 0F, 0F, 1F, 3F, 1F),
                PartPose.offsetAndRotation(-1F, 21F, 3F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE20, CubeListBuilder.create().texOffs(9, 61).addBox(0F, 0F, 0F, 3F, 1F, 1F),
                PartPose.offsetAndRotation(4F, 19.5F, 6F, 0F, -0.6457718F, 0.5061455F));
        root.addOrReplaceChild(SHAPE21, CubeListBuilder.create().texOffs(0, 61).addBox(0F, 0F, 0F, 3F, 1F, 1F),
                PartPose.offsetAndRotation(1.5F, 19.5F, 7F, 0F, -2.391101F, 0.5061455F));
        root.addOrReplaceChild(SHAPE22, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 1F, 3F, 1F),
                PartPose.offsetAndRotation(-1F, 21F, 7.5F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE23, CubeListBuilder.create().texOffs(0, 13).addBox(0F, 0F, 0F, 1F, 3F, 1F),
                PartPose.offsetAndRotation(5F, 21F, 7.5F, 0F, 0F, 0F));
        root.addOrReplaceChild(LRWING, CubeListBuilder.create().texOffs(0, 38).addBox(0F, 0F, -3F, 10F, 1F, 3F),
                PartPose.offsetAndRotation(5F, 16F, 6F, 0F, -0.3839724F, 0F));
        root.addOrReplaceChild(RFWING, CubeListBuilder.create().texOffs(0, 48).addBox(-10F, 0F, 0F, 10F, 1F, 3F),
                PartPose.offsetAndRotation(0F, 16F, 1F, 0F, -0.4886922F, 0F));
        root.addOrReplaceChild(RRWING, CubeListBuilder.create().texOffs(0, 43).addBox(-10F, 0F, -3F, 10F, 1F, 3F),
                PartPose.offsetAndRotation(0F, 16F, 6F, 0F, 0.3839724F, 0F));
        return LayerDefinition.create(mesh, TEXTURE_WIDTH, TEXTURE_HEIGHT);
    }
}
