// GENERATED by tools/gen_models.py from reference/jar/models/ModelDragon.json - do not edit.
package com.swbr.orespawn.client.model.geom;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Geometry of OreSpawn's ModelDragon (55 parts), copied unchanged from the 1.7.10 jar.
 * Part order is the order the original constructor created them.
 */
public final class DragonGeometry {

    public static final int TEXTURE_WIDTH = 256;
    public static final int TEXTURE_HEIGHT = 128;

    public static final String HORN1 = "horn1";
    public static final String HORN2 = "horn2";
    public static final String TAIL6 = "tail6";
    public static final String WING15 = "wing15";
    public static final String SPIKE1 = "spike1";
    public static final String SPIKE2 = "spike2";
    public static final String SPIKE3 = "spike3";
    public static final String SPIKE4 = "spike4";
    public static final String WING14 = "wing14";
    public static final String SPIKE5 = "spike5";
    public static final String SPIKE6 = "spike6";
    public static final String SPIKE7 = "spike7";
    public static final String SPIKE8 = "spike8";
    public static final String SPIKE9 = "spike9";
    public static final String SPIKE10 = "spike10";
    public static final String HEAD = "head";
    public static final String BODY = "body";
    public static final String LEG1 = "leg1";
    public static final String LEG2 = "leg2";
    public static final String LEG3 = "leg3";
    public static final String LEG4 = "leg4";
    public static final String BODY2 = "body2";
    public static final String NECK1 = "neck1";
    public static final String BODY3 = "body3";
    public static final String NECK2 = "neck2";
    public static final String NECK3 = "neck3";
    public static final String LEG5 = "leg5";
    public static final String LEG6 = "leg6";
    public static final String LEG7 = "leg7";
    public static final String LEG9 = "leg9";
    public static final String FOOT1 = "foot1";
    public static final String FOOT2 = "foot2";
    public static final String LEG10 = "leg10";
    public static final String LEG11 = "leg11";
    public static final String FOOT3 = "foot3";
    public static final String FOOT4 = "foot4";
    public static final String TAIL1 = "tail1";
    public static final String TAIL2 = "tail2";
    public static final String TAIL3 = "tail3";
    public static final String MOUTH1 = "mouth1";
    public static final String MOUTH2 = "mouth2";
    public static final String TAIL5 = "tail5";
    public static final String WING1 = "wing1";
    public static final String WING2 = "wing2";
    public static final String WING3 = "wing3";
    public static final String WING4 = "wing4";
    public static final String WING5 = "wing5";
    public static final String WING6 = "wing6";
    public static final String WING7 = "wing7";
    public static final String WING8 = "wing8";
    public static final String WING9 = "wing9";
    public static final String WING10 = "wing10";
    public static final String WING11 = "wing11";
    public static final String WING12 = "wing12";
    public static final String TAIL4 = "tail4";

    /** Every part in creation order. */
    public static final String[] PARTS = {
            HORN1,
            HORN2,
            TAIL6,
            WING15,
            SPIKE1,
            SPIKE2,
            SPIKE3,
            SPIKE4,
            WING14,
            SPIKE5,
            SPIKE6,
            SPIKE7,
            SPIKE8,
            SPIKE9,
            SPIKE10,
            HEAD,
            BODY,
            LEG1,
            LEG2,
            LEG3,
            LEG4,
            BODY2,
            NECK1,
            BODY3,
            NECK2,
            NECK3,
            LEG5,
            LEG6,
            LEG7,
            LEG9,
            FOOT1,
            FOOT2,
            LEG10,
            LEG11,
            FOOT3,
            FOOT4,
            TAIL1,
            TAIL2,
            TAIL3,
            MOUTH1,
            MOUTH2,
            TAIL5,
            WING1,
            WING2,
            WING3,
            WING4,
            WING5,
            WING6,
            WING7,
            WING8,
            WING9,
            WING10,
            WING11,
            WING12,
            TAIL4
    };

    /** Parts the original hid at construction time (showModel = false or isHidden = true). */
    public static final String[] HIDDEN = {};

    private DragonGeometry() {}

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild(HORN1, CubeListBuilder.create().texOffs(0, 39).addBox(2F, -4F, 1F, 2F, 2F, 6F),
                PartPose.offsetAndRotation(0F, 6F, -23F, 0.4089647F, 0.2602503F, 0F));
        root.addOrReplaceChild(HORN2, CubeListBuilder.create().texOffs(0, 39).addBox(-4F, -4F, 1F, 2F, 2F, 6F),
                PartPose.offsetAndRotation(0F, 6F, -23F, 0.4089647F, -0.2602503F, 0F));
        root.addOrReplaceChild(TAIL6, CubeListBuilder.create().texOffs(0, 49).addBox(-1F, 0F, -2F, 2F, 6F, 4F),
                PartPose.offsetAndRotation(0F, 7F, 43F, 1.570796F, 0F, 0F));
        root.addOrReplaceChild(WING15, CubeListBuilder.create().texOffs(0, 62).addBox(1F, -1F, 1F, 12F, 1F, 8F),
                PartPose.offsetAndRotation(4F, 3F, -5F, -0.0743572F, -0.4089594F, 0F));
        root.addOrReplaceChild(SPIKE1, CubeListBuilder.create().texOffs(0, 73).addBox(-1F, -3F, -5F, 2F, 2F, 4F),
                PartPose.offsetAndRotation(0F, 6F, -17F, 0F, 0F, 0F));
        root.addOrReplaceChild(SPIKE2, CubeListBuilder.create().texOffs(0, 73).addBox(-1F, -3F, -5F, 2F, 2F, 4F),
                PartPose.offsetAndRotation(0F, 6F, -11F, 0F, 0F, 0F));
        root.addOrReplaceChild(SPIKE3, CubeListBuilder.create().texOffs(0, 73).addBox(-1F, -4F, 1F, 2F, 2F, 4F),
                PartPose.offsetAndRotation(0F, 7F, 25F, 0F, 0F, 0F));
        root.addOrReplaceChild(SPIKE4, CubeListBuilder.create().texOffs(0, 73).addBox(-1F, -2F, 0F, 2F, 2F, 4F),
                PartPose.offsetAndRotation(0F, 3F, -7F, 0F, 0F, 0F));
        root.addOrReplaceChild(WING14, CubeListBuilder.create().texOffs(0, 62).addBox(-13F, -1F, 0F, 12F, 1F, 8F),
                PartPose.offsetAndRotation(-4F, 3F, -5F, -0.0698132F, 0.4089656F, 0F));
        root.addOrReplaceChild(SPIKE5, CubeListBuilder.create().texOffs(0, 73).addBox(-1F, -2F, 0F, 2F, 2F, 4F),
                PartPose.offsetAndRotation(0F, 3F, -1F, 0F, 0F, 0F));
        root.addOrReplaceChild(SPIKE6, CubeListBuilder.create().texOffs(0, 73).addBox(-1F, -2F, 0F, 2F, 2F, 4F),
                PartPose.offsetAndRotation(0F, 3F, 5F, 0F, 0F, 0F));
        root.addOrReplaceChild(SPIKE7, CubeListBuilder.create().texOffs(0, 73).addBox(-1F, -4F, 1F, 2F, 2F, 4F),
                PartPose.offsetAndRotation(0F, 7F, 13F, 0F, 0F, 0F));
        root.addOrReplaceChild(SPIKE8, CubeListBuilder.create().texOffs(0, 73).addBox(-1F, -2F, 1F, 2F, 2F, 4F),
                PartPose.offsetAndRotation(0F, 5F, 19F, 0F, 0F, 0F));
        root.addOrReplaceChild(SPIKE9, CubeListBuilder.create().texOffs(0, 73).addBox(-1F, -4F, 1F, 2F, 2F, 4F),
                PartPose.offsetAndRotation(0F, 7F, 31F, 0F, 0F, 0F));
        root.addOrReplaceChild(SPIKE10, CubeListBuilder.create().texOffs(0, 73).addBox(-1F, -4F, 2F, 2F, 2F, 4F),
                PartPose.offsetAndRotation(0F, 7F, 36F, 0F, 0F, 0F));
        root.addOrReplaceChild(HEAD, CubeListBuilder.create().texOffs(0, 81).addBox(-4F, -4F, -8F, 8F, 8F, 8F),
                PartPose.offsetAndRotation(0F, 6F, -23F, 0F, 0F, 0F));
        root.addOrReplaceChild(BODY, CubeListBuilder.create().texOffs(1, 99).addBox(-6F, -10F, -7F, 12F, 18F, 10F),
                PartPose.offsetAndRotation(0F, 5F, 2F, 1.570796F, 0F, 0F));
        root.addOrReplaceChild(LEG1, CubeListBuilder.create().texOffs(47, 112).addBox(-4F, -1F, -2F, 4F, 9F, 5F),
                PartPose.offsetAndRotation(-4F, 11F, 8F, -0.6320364F, 0F, 0F));
        root.addOrReplaceChild(LEG2, CubeListBuilder.create().texOffs(47, 112).addBox(1F, -1F, -2F, 4F, 9F, 5F),
                PartPose.offsetAndRotation(3F, 11F, 8F, -0.6320364F, 0F, 0F));
        root.addOrReplaceChild(LEG3, CubeListBuilder.create().texOffs(18, 47).addBox(-3F, -2F, -2F, 4F, 9F, 4F),
                PartPose.offsetAndRotation(-4F, 11F, -5F, 0.5576792F, 0F, 0F));
        root.addOrReplaceChild(LEG4, CubeListBuilder.create().texOffs(18, 47).addBox(0F, -2F, -2F, 4F, 9F, 4F),
                PartPose.offsetAndRotation(3F, 11F, -5F, 0.5576792F, 0F, 0F));
        root.addOrReplaceChild(BODY2, CubeListBuilder.create().texOffs(68, 94).addBox(-5F, 0F, 0F, 10F, 22F, 10F),
                PartPose.offsetAndRotation(0F, 12F, -10F, 1.570796F, 0F, 0F));
        root.addOrReplaceChild(NECK1, CubeListBuilder.create().texOffs(43, 85).addBox(-3F, -3F, 0F, 6F, 6F, 6F),
                PartPose.offsetAndRotation(0F, 7F, 25F, 0F, 0F, 0F));
        root.addOrReplaceChild(BODY3, CubeListBuilder.create().texOffs(70, 59).addBox(-4F, 0F, 0F, 8F, 24F, 8F),
                PartPose.offsetAndRotation(0F, 11F, -11F, 1.570796F, 0F, 0F));
        root.addOrReplaceChild(NECK2, CubeListBuilder.create().texOffs(43, 85).addBox(-3F, -2F, -6F, 6F, 6F, 6F),
                PartPose.offsetAndRotation(0F, 6F, -11F, 0F, 0F, 0F));
        root.addOrReplaceChild(NECK3, CubeListBuilder.create().texOffs(43, 85).addBox(-3F, -2F, -6F, 6F, 6F, 6F),
                PartPose.offsetAndRotation(0F, 6F, -17F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEG5, CubeListBuilder.create().texOffs(47, 99).addBox(0F, 3F, 3F, 4F, 8F, 4F),
                PartPose.offsetAndRotation(3F, 11F, -5F, -0.5576792F, 0F, 0F));
        root.addOrReplaceChild(LEG6, CubeListBuilder.create().texOffs(47, 99).addBox(-3F, 3F, 3F, 4F, 8F, 4F),
                PartPose.offsetAndRotation(-4F, 11F, -5F, -0.5576792F, 0F, 0F));
        root.addOrReplaceChild(LEG7, CubeListBuilder.create().texOffs(38, 73).addBox(1F, 2F, -8F, 4F, 5F, 4F),
                PartPose.offsetAndRotation(3F, 11F, 8F, 0.8922867F, 0F, 0F));
        root.addOrReplaceChild(LEG9, CubeListBuilder.create().texOffs(38, 73).addBox(-4F, 2F, -8F, 4F, 5F, 4F),
                PartPose.offsetAndRotation(-4F, 11F, 8F, 0.8922867F, 0F, 0F));
        root.addOrReplaceChild(FOOT1, CubeListBuilder.create().texOffs(43, 63).addBox(-3F, 11F, -5F, 4F, 2F, 6F),
                PartPose.offsetAndRotation(-4F, 11F, -5F, 0F, 0F, 0F));
        root.addOrReplaceChild(FOOT2, CubeListBuilder.create().texOffs(43, 63).addBox(0F, 11F, -5F, 4F, 2F, 6F),
                PartPose.offsetAndRotation(3F, 11F, -5F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEG10, CubeListBuilder.create().texOffs(39, 52).addBox(1F, 6F, 2F, 4F, 5F, 4F),
                PartPose.offsetAndRotation(3F, 11F, 8F, -0.5576792F, 0F, 0F));
        root.addOrReplaceChild(LEG11, CubeListBuilder.create().texOffs(39, 52).addBox(-4F, 6F, 2F, 4F, 5F, 4F),
                PartPose.offsetAndRotation(-4F, 11F, 8F, -0.5576792F, 0F, 0F));
        root.addOrReplaceChild(FOOT3, CubeListBuilder.create().texOffs(43, 63).addBox(1F, 11F, -7F, 4F, 2F, 6F),
                PartPose.offsetAndRotation(3F, 11F, 8F, 0F, 0F, 0F));
        root.addOrReplaceChild(FOOT4, CubeListBuilder.create().texOffs(43, 63).addBox(-4F, 11F, -7F, 4F, 2F, 6F),
                PartPose.offsetAndRotation(-4F, 11F, 8F, 0F, 0F, 0F));
        root.addOrReplaceChild(TAIL1, CubeListBuilder.create().texOffs(43, 85).addBox(-3F, -3F, 0F, 6F, 6F, 6F),
                PartPose.offsetAndRotation(0F, 7F, 13F, 0F, 0F, 0F));
        root.addOrReplaceChild(TAIL2, CubeListBuilder.create().texOffs(43, 85).addBox(-3F, -3F, 0F, 6F, 6F, 6F),
                PartPose.offsetAndRotation(0F, 7F, 19F, 0F, 0F, 0F));
        root.addOrReplaceChild(TAIL3, CubeListBuilder.create().texOffs(56, 45).addBox(-3F, -3F, 0F, 4F, 6F, 6F),
                PartPose.offsetAndRotation(1F, 7F, 31F, 0F, 0F, 0F));
        root.addOrReplaceChild(MOUTH1, CubeListBuilder.create().texOffs(90, 22).addBox(-3F, -1F, -15F, 6F, 3F, 8F),
                PartPose.offsetAndRotation(0F, 6F, -23F, 0F, 0F, 0F));
        root.addOrReplaceChild(MOUTH2, CubeListBuilder.create().texOffs(90, 6).addBox(-2F, 1F, -5F, 4F, 2F, 8F),
                PartPose.offsetAndRotation(0F, 7F, -32F, 0.0698132F, 0F, 0F));
        root.addOrReplaceChild(TAIL5, CubeListBuilder.create().texOffs(87, 36).addBox(0F, 0F, -5F, 0F, 11F, 10F),
                PartPose.offsetAndRotation(0F, 7F, 49F, 1.570796F, 0F, 0F));
        root.addOrReplaceChild(WING1, CubeListBuilder.create().texOffs(26, 40).addBox(0F, -1F, -1F, 11F, 2F, 2F),
                PartPose.offsetAndRotation(4F, 3F, -5F, 0F, -0.4833219F, 0F));
        root.addOrReplaceChild(WING2, CubeListBuilder.create().texOffs(110, 88).addBox(-1F, -1F, 0F, 2F, 2F, 36F),
                PartPose.offsetAndRotation(19F, 3F, -23F, 0F, 1.041001F, 0F));
        root.addOrReplaceChild(WING3, CubeListBuilder.create().texOffs(109, 60).addBox(-1F, -1F, -24F, 2F, 2F, 24F),
                PartPose.offsetAndRotation(12F, 3F, -1F, -0.0090881F, -0.3497888F, 0F));
        root.addOrReplaceChild(WING4, CubeListBuilder.create().texOffs(26, 40).addBox(-11F, -1F, -1F, 11F, 2F, 2F),
                PartPose.offsetAndRotation(-4F, 3F, -5F, 0F, 0.4833166F, 0F));
        root.addOrReplaceChild(WING5, CubeListBuilder.create().texOffs(109, 60).addBox(-1F, -1F, -24F, 2F, 2F, 24F),
                PartPose.offsetAndRotation(-12F, 3F, -1F, -0.0090932F, 0.3323281F, 0F));
        root.addOrReplaceChild(WING6, CubeListBuilder.create().texOffs(110, 88).addBox(-1F, -1F, 0F, 2F, 2F, 36F),
                PartPose.offsetAndRotation(-20F, 3F, -23F, 0F, -1.041002F, 0F));
        root.addOrReplaceChild(WING7, CubeListBuilder.create().texOffs(124, 21).addBox(-8F, 0F, 1F, 8F, 1F, 36F),
                PartPose.offsetAndRotation(19F, 2F, -23F, 0F, 1.041001F, 0F));
        root.addOrReplaceChild(WING8, CubeListBuilder.create().texOffs(122, 10).addBox(-11F, -1F, 0F, 28F, 1F, 8F),
                PartPose.offsetAndRotation(12F, 3F, -1F, 0.002272F, 1.264073F, -0.0174533F));
        root.addOrReplaceChild(WING9, CubeListBuilder.create().texOffs(0, 10).addBox(-25F, -1F, 7F, 18F, 1F, 26F),
                PartPose.offsetAndRotation(19F, 3F, -23F, 0.002272F, 1.264073F, 0F));
        root.addOrReplaceChild(WING10, CubeListBuilder.create().texOffs(122, 10).addBox(-23F, -1F, 0F, 33F, 1F, 8F),
                PartPose.offsetAndRotation(-12F, 3F, -1F, -0.0022689F, -1.226894F, 0F));
        root.addOrReplaceChild(WING11, CubeListBuilder.create().texOffs(124, 21).addBox(0F, -1F, 1F, 8F, 1F, 36F),
                PartPose.offsetAndRotation(-20F, 3F, -23F, 0F, -1.041002F, 0F));
        root.addOrReplaceChild(WING12, CubeListBuilder.create().texOffs(0, 10).addBox(7F, -1F, 7F, 18F, 1F, 26F),
                PartPose.offsetAndRotation(-20F, 3F, -23F, 0.002272F, -1.264072F, 0F));
        root.addOrReplaceChild(TAIL4, CubeListBuilder.create().texOffs(56, 45).addBox(-3F, -3F, 0F, 4F, 6F, 6F),
                PartPose.offsetAndRotation(1F, 7F, 37F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, TEXTURE_WIDTH, TEXTURE_HEIGHT);
    }
}
