// GENERATED by tools/gen_models.py from reference/jar/models/ModelEmperorScorpion.json - do not edit.
package com.swbr.orespawn.client.model.geom;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Geometry of OreSpawn's ModelEmperorScorpion (78 parts), copied unchanged from the 1.7.10 jar.
 * Part order is the order the original constructor created them.
 */
public final class EmperorScorpionGeometry {

    public static final int TEXTURE_WIDTH = 256;
    public static final int TEXTURE_HEIGHT = 128;

    public static final String HEAD = "Head";
    public static final String SEG1 = "Seg1";
    public static final String SEG2 = "Seg2";
    public static final String SEG3 = "Seg3";
    public static final String SEG4 = "Seg4";
    public static final String SEG5 = "Seg5";
    public static final String SEG6 = "Seg6";
    public static final String SEG7 = "Seg7";
    public static final String SEG8 = "Seg8";
    public static final String TAILSEG1 = "Tailseg1";
    public static final String TAILSEG2 = "Tailseg2";
    public static final String TAILSEG3 = "Tailseg3";
    public static final String TAILSEG4 = "Tailseg4";
    public static final String TAILSEG5 = "Tailseg5";
    public static final String TAILSEG6 = "Tailseg6";
    public static final String TAILSEG7 = "Tailseg7";
    public static final String TAILSEG8 = "Tailseg8";
    public static final String STINGER1 = "Stinger1";
    public static final String STINGER2 = "Stinger2";
    public static final String STINGER3 = "Stinger3";
    public static final String LEFT_SHOULDER = "LeftShoulder";
    public static final String LEFT_ARM_SEG1 = "LeftArmSeg1";
    public static final String LEFT_ARM_SEG2 = "LeftArmSeg2";
    public static final String LEFT_ARM_SEG3 = "LeftArmSeg3";
    public static final String LEFT_ARM_SEG4 = "LeftArmSeg4";
    public static final String RIGHT_SHOULDER = "RightShoulder";
    public static final String RIGHT_ARM_SEG1 = "RightArmSeg1";
    public static final String RIGHT_ARM_SEG2 = "RightArmSeg2";
    public static final String RIGHT_ARM_SEG3 = "RightArmSeg3";
    public static final String RIGHT_ARM_SEG4 = "RightArmSeg4";
    public static final String RIGHT_PINCER = "RightPincer";
    public static final String LEFT_PINCER = "LeftPincer";
    public static final String LEFTEYE = "Lefteye";
    public static final String RIGHTEYE = "Righteye";
    public static final String RIGHT_MANDIBLE = "RightMandible";
    public static final String LEFT_MANDIBLE = "LeftMandible";
    public static final String RIGHT_MAN_PART2 = "RightManPart2";
    public static final String LEFT_MAN_PART2 = "LeftManPart2";
    public static final String LEG1_SEG1 = "Leg1Seg1";
    public static final String LEG1_SEG2 = "Leg1Seg2";
    public static final String LEG1_SEG3 = "Leg1Seg3";
    public static final String LEG1_SEG4 = "Leg1Seg4";
    public static final String LEG1_SEG5 = "Leg1Seg5";
    public static final String LEG2_SEG1 = "Leg2Seg1";
    public static final String LEG2_SEG2 = "Leg2Seg2";
    public static final String LEG2_SEG3 = "Leg2Seg3";
    public static final String LEG2_SEG4 = "Leg2Seg4";
    public static final String LEG2_SEG5 = "Leg2Seg5";
    public static final String LEG3_SEG1 = "Leg3Seg1";
    public static final String LEG3_SEG2 = "Leg3Seg2";
    public static final String LEG3_SEG3 = "Leg3Seg3";
    public static final String LEG3_SEG4 = "Leg3Seg4";
    public static final String LEG3_SEG5 = "Leg3Seg5";
    public static final String LEG4_SEG1 = "Leg4Seg1";
    public static final String LEG4_SEG2 = "Leg4Seg2";
    public static final String LEG4_SEG3 = "Leg4Seg3";
    public static final String LEG4_SEG4 = "Leg4Seg4";
    public static final String LEG4_SEG5 = "Leg4Seg5";
    public static final String LEG5_SEG1 = "Leg5Seg1";
    public static final String LEG5_SEG2 = "Leg5Seg2";
    public static final String LEG5_SEG3 = "Leg5Seg3";
    public static final String LEG5_SEG4 = "Leg5Seg4";
    public static final String LEG5_SEG5 = "Leg5Seg5";
    public static final String LEG6_SEG1 = "Leg6Seg1";
    public static final String LEG6_SEG2 = "Leg6Seg2";
    public static final String LEG6_SEG3 = "Leg6Seg3";
    public static final String LEG6_SEG4 = "Leg6Seg4";
    public static final String LEG6_SEG5 = "Leg6Seg5";
    public static final String LEG7_SEG1 = "Leg7Seg1";
    public static final String LEG7_SEG2 = "Leg7Seg2";
    public static final String LEG7_SEG3 = "Leg7Seg3";
    public static final String LEG7_SEG4 = "Leg7Seg4";
    public static final String LEG7_SEG5 = "Leg7Seg5";
    public static final String LEG8_SEG1 = "Leg8Seg1";
    public static final String LEG8_SEG2 = "Leg8Seg2";
    public static final String LEG8_SEG3 = "Leg8Seg3";
    public static final String LEG8_SEG4 = "Leg8Seg4";
    public static final String LEG8_SEG5 = "Leg8Seg5";

    /** Every part in creation order. */
    public static final String[] PARTS = {
            HEAD,
            SEG1,
            SEG2,
            SEG3,
            SEG4,
            SEG5,
            SEG6,
            SEG7,
            SEG8,
            TAILSEG1,
            TAILSEG2,
            TAILSEG3,
            TAILSEG4,
            TAILSEG5,
            TAILSEG6,
            TAILSEG7,
            TAILSEG8,
            STINGER1,
            STINGER2,
            STINGER3,
            LEFT_SHOULDER,
            LEFT_ARM_SEG1,
            LEFT_ARM_SEG2,
            LEFT_ARM_SEG3,
            LEFT_ARM_SEG4,
            RIGHT_SHOULDER,
            RIGHT_ARM_SEG1,
            RIGHT_ARM_SEG2,
            RIGHT_ARM_SEG3,
            RIGHT_ARM_SEG4,
            RIGHT_PINCER,
            LEFT_PINCER,
            LEFTEYE,
            RIGHTEYE,
            RIGHT_MANDIBLE,
            LEFT_MANDIBLE,
            RIGHT_MAN_PART2,
            LEFT_MAN_PART2,
            LEG1_SEG1,
            LEG1_SEG2,
            LEG1_SEG3,
            LEG1_SEG4,
            LEG1_SEG5,
            LEG2_SEG1,
            LEG2_SEG2,
            LEG2_SEG3,
            LEG2_SEG4,
            LEG2_SEG5,
            LEG3_SEG1,
            LEG3_SEG2,
            LEG3_SEG3,
            LEG3_SEG4,
            LEG3_SEG5,
            LEG4_SEG1,
            LEG4_SEG2,
            LEG4_SEG3,
            LEG4_SEG4,
            LEG4_SEG5,
            LEG5_SEG1,
            LEG5_SEG2,
            LEG5_SEG3,
            LEG5_SEG4,
            LEG5_SEG5,
            LEG6_SEG1,
            LEG6_SEG2,
            LEG6_SEG3,
            LEG6_SEG4,
            LEG6_SEG5,
            LEG7_SEG1,
            LEG7_SEG2,
            LEG7_SEG3,
            LEG7_SEG4,
            LEG7_SEG5,
            LEG8_SEG1,
            LEG8_SEG2,
            LEG8_SEG3,
            LEG8_SEG4,
            LEG8_SEG5
    };

    /** Parts the original hid at construction time (showModel = false or isHidden = true). */
    public static final String[] HIDDEN = {};

    private EmperorScorpionGeometry() {}

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        addParts0(root);
        addParts1(root);
        return LayerDefinition.create(mesh, TEXTURE_WIDTH, TEXTURE_HEIGHT);
    }

    private static void addParts0(PartDefinition root) {
        root.addOrReplaceChild(HEAD, CubeListBuilder.create().texOffs(0, 104).addBox(-9F, -4F, -16F, 18F, 8F, 16F),
                PartPose.offsetAndRotation(0F, 13F, -8F, 0F, 0F, 0F));
        root.addOrReplaceChild(SEG1, CubeListBuilder.create().texOffs(0, 78).addBox(-9F, -4F, 0F, 18F, 8F, 4F),
                PartPose.offsetAndRotation(0F, 13F, -8F, 0F, 0F, 0F));
        root.addOrReplaceChild(SEG2, CubeListBuilder.create().texOffs(0, 65).addBox(-8.5F, -4.1F, 4F, 17F, 8F, 4F),
                PartPose.offsetAndRotation(0F, 13F, -8F, 0F, 0F, 0F));
        root.addOrReplaceChild(SEG3, CubeListBuilder.create().texOffs(0, 50).addBox(-9.5F, -4F, 8F, 19F, 8F, 5F),
                PartPose.offsetAndRotation(0F, 13F, -8F, 0F, 0F, 0F));
        root.addOrReplaceChild(SEG4, CubeListBuilder.create().texOffs(0, 35).addBox(-9F, -4.1F, 13F, 18F, 8F, 6F),
                PartPose.offsetAndRotation(0F, 13F, -8F, 0F, 0F, 0F));
        root.addOrReplaceChild(SEG5, CubeListBuilder.create().texOffs(45, 91).addBox(-8.5F, -4F, 19F, 17F, 8F, 3F),
                PartPose.offsetAndRotation(0F, 13F, -8F, 0F, 0F, 0F));
        root.addOrReplaceChild(SEG6, CubeListBuilder.create().texOffs(45, 79).addBox(-8F, -4.1F, 22F, 16F, 8F, 3F),
                PartPose.offsetAndRotation(0F, 13F, -8F, 0F, 0F, 0F));
        root.addOrReplaceChild(SEG7, CubeListBuilder.create().texOffs(43, 66).addBox(-7F, -4F, 25F, 14F, 8F, 3F),
                PartPose.offsetAndRotation(0F, 13F, -8F, 0F, 0F, 0F));
        root.addOrReplaceChild(SEG8, CubeListBuilder.create().texOffs(49, 53).addBox(-5.5F, -4.1F, 28F, 11F, 8F, 2F),
                PartPose.offsetAndRotation(0F, 13F, -8F, 0F, 0F, 0F));
        root.addOrReplaceChild(TAILSEG1, CubeListBuilder.create().texOffs(92, 0).addBox(-4F, -1F, 0F, 8F, 4F, 10F),
                PartPose.offsetAndRotation(0F, 13F, 20F, 0.5948578F, 0F, 0F));
        root.addOrReplaceChild(TAILSEG2, CubeListBuilder.create().texOffs(90, 15).addBox(-3.5F, -2F, 0F, 7F, 4F, 12F),
                PartPose.offsetAndRotation(0F, 10F, 27F, 1.07818F, 0F, 0F));
        root.addOrReplaceChild(TAILSEG3, CubeListBuilder.create().texOffs(96, 32).addBox(-3F, -2F, 1F, 6F, 4F, 10F),
                PartPose.offsetAndRotation(0F, 2F, 32F, 1.710216F, 0F, 0F));
        root.addOrReplaceChild(TAILSEG4, CubeListBuilder.create().texOffs(96, 47).addBox(-2.5F, -2F, 0F, 5F, 4F, 11F),
                PartPose.offsetAndRotation(0F, -7F, 31F, 2.267895F, 0F, 0F));
        root.addOrReplaceChild(TAILSEG5, CubeListBuilder.create().texOffs(98, 63).addBox(-2F, -2F, 0F, 4F, 4F, 11F),
                PartPose.offsetAndRotation(0F, -14F, 25F, 2.899932F, 0F, 0F));
        root.addOrReplaceChild(TAILSEG6, CubeListBuilder.create().texOffs(98, 79).addBox(-2F, -2F, 0F, 4F, 4F, 11F),
                PartPose.offsetAndRotation(0F, -17F, 16F, -2.602503F, 0F, 0F));
        root.addOrReplaceChild(TAILSEG7, CubeListBuilder.create().texOffs(94, 95).addBox(-3F, -2F, 0F, 6F, 4F, 11F),
                PartPose.offsetAndRotation(0F, -12F, 8F, -0.2230717F, 0F, 0F));
        root.addOrReplaceChild(TAILSEG8, CubeListBuilder.create().texOffs(102, 111).addBox(-4F, -2F, 4F, 8F, 4F, 5F),
                PartPose.offsetAndRotation(0F, -12F, 8F, -0.2230717F, 0F, 0F));
        root.addOrReplaceChild(STINGER1, CubeListBuilder.create().texOffs(83, 0).addBox(-0.5F, -0.5F, 0F, 1F, 1F, 3F),
                PartPose.offsetAndRotation(0F, -10F, 18F, 0.2230717F, 0F, 0F));
        root.addOrReplaceChild(STINGER2, CubeListBuilder.create().texOffs(83, 0).addBox(-0.5F, -0.5F, 0F, 1F, 1F, 3F),
                PartPose.offsetAndRotation(0F, -10.5F, 20.5F, -0.2602503F, 0F, 0F));
        root.addOrReplaceChild(STINGER3, CubeListBuilder.create().texOffs(79, 5).addBox(-0.5F, -0.5F, 0F, 1F, 1F, 5F),
                PartPose.offsetAndRotation(0F, -10F, 23F, -0.8551081F, 0F, 0F));
        root.addOrReplaceChild(LEFT_SHOULDER, CubeListBuilder.create().texOffs(69, 103).addBox(-3F, -3F, -4F, 6F, 6F, 4F),
                PartPose.offsetAndRotation(7F, 13F, -22F, 0F, -0.8551081F, 0F));
        root.addOrReplaceChild(LEFT_ARM_SEG1, CubeListBuilder.create().texOffs(55, 0).addBox(-3F, -3F, -10F, 4F, 6F, 13F),
                PartPose.offsetAndRotation(10F, 13F, -24F, 0F, -2.044824F, 0F));
        root.addOrReplaceChild(LEFT_ARM_SEG2, CubeListBuilder.create().texOffs(130, 0).addBox(-7F, -3F, -17F, 8F, 6F, 17F),
                PartPose.offsetAndRotation(19F, 13F, -22F, 0F, -0.7435722F, 0F));
        root.addOrReplaceChild(LEFT_ARM_SEG3, CubeListBuilder.create().texOffs(130, 50).addBox(-3F, -3F, -24F, 4F, 6F, 24F),
                PartPose.offsetAndRotation(29F, 13F, -33F, 0F, 0.3717861F, 0F));
        root.addOrReplaceChild(LEFT_ARM_SEG4, CubeListBuilder.create().texOffs(181, 0).addBox(-3F, -3F, -14F, 8F, 6F, 12F),
                PartPose.offsetAndRotation(29F, 13F, -33F, 0F, 1.487144F, 0F));
        root.addOrReplaceChild(RIGHT_SHOULDER, CubeListBuilder.create().texOffs(69, 103).addBox(-3F, -3F, -4F, 6F, 6F, 4F),
                PartPose.offsetAndRotation(-7F, 13F, -22F, 0F, 0.8551066F, 0F));
        root.addOrReplaceChild(RIGHT_ARM_SEG1, CubeListBuilder.create().texOffs(55, 0).addBox(-1F, -3F, -10F, 4F, 6F, 13F),
                PartPose.offsetAndRotation(-10F, 13F, -24F, 0F, 2.044828F, 0F));
        root.addOrReplaceChild(RIGHT_ARM_SEG2, CubeListBuilder.create().texOffs(130, 0).addBox(-1F, -3F, -17F, 8F, 6F, 17F),
                PartPose.offsetAndRotation(-19F, 13F, -22F, 0F, 0.7435801F, 0F));
        root.addOrReplaceChild(RIGHT_ARM_SEG3, CubeListBuilder.create().texOffs(130, 50).addBox(-1F, -3F, -24F, 4F, 6F, 24F),
                PartPose.offsetAndRotation(-29F, 13F, -33F, 0F, -0.37179F, 0F));
        root.addOrReplaceChild(RIGHT_ARM_SEG4, CubeListBuilder.create().texOffs(181, 0).addBox(-5F, -3F, -14F, 8F, 6F, 12F),
                PartPose.offsetAndRotation(-29F, 13F, -33F, 0F, -1.487143F, 0F));
        root.addOrReplaceChild(RIGHT_PINCER, CubeListBuilder.create().texOffs(130, 24).addBox(-1F, -3F, -19F, 2F, 6F, 19F),
                PartPose.offsetAndRotation(-17F, 13F, -33F, 0F, -0.0743611F, 0F));
        root.addOrReplaceChild(LEFT_PINCER, CubeListBuilder.create().texOffs(130, 24).addBox(-1F, -3F, -19F, 2F, 6F, 19F),
                PartPose.offsetAndRotation(17F, 13F, -33F, 0F, 0.0743685F, 0F));
        root.addOrReplaceChild(LEFTEYE, CubeListBuilder.create().texOffs(0, 113).addBox(-0.5F, -5F, -7.5F, 3F, 2F, 3F),
                PartPose.offsetAndRotation(0F, 13F, -8F, 0F, 0F, 0.2974289F));
        root.addOrReplaceChild(RIGHTEYE, CubeListBuilder.create().texOffs(0, 113).addBox(-2.5F, -5F, -7.5F, 3F, 2F, 3F),
                PartPose.offsetAndRotation(0F, 13F, -8F, 0F, 0F, -0.2974216F));
        root.addOrReplaceChild(RIGHT_MANDIBLE, CubeListBuilder.create().texOffs(76, 55).addBox(-2F, -3F, -4F, 4F, 4F, 4F),
                PartPose.offsetAndRotation(-2F, 13F, -23F, 0.1115358F, 0.3346075F, 0F));
        root.addOrReplaceChild(LEFT_MANDIBLE, CubeListBuilder.create().texOffs(76, 55).addBox(-2F, -3F, -4F, 4F, 4F, 4F),
                PartPose.offsetAndRotation(2F, 13F, -23F, 0.111544F, -0.3346145F, 0F));
        root.addOrReplaceChild(RIGHT_MAN_PART2, CubeListBuilder.create().texOffs(82, 64).addBox(-0.5F, -0.5F, -6F, 1F, 1F, 6F),
                PartPose.offsetAndRotation(-3F, 11F, -26F, 1.189716F, 0F, 0F));
        root.addOrReplaceChild(LEFT_MAN_PART2, CubeListBuilder.create().texOffs(82, 64).addBox(-0.5F, -0.5F, -6F, 1F, 1F, 6F),
                PartPose.offsetAndRotation(3F, 11F, -26F, 1.188848F, 0F, 0F));
        root.addOrReplaceChild(LEG1_SEG1, CubeListBuilder.create().texOffs(20, 20).addBox(0F, -1.5F, -2F, 4F, 3F, 4F),
                PartPose.offsetAndRotation(9F, 13F, -10F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEG1_SEG2, CubeListBuilder.create().texOffs(21, 0).addBox(0F, -1.5F, -1.5F, 13F, 3F, 3F),
                PartPose.offsetAndRotation(12F, 13F, -10F, 0F, 0F, -0.9294576F));
        root.addOrReplaceChild(LEG1_SEG3, CubeListBuilder.create().texOffs(15, 8).addBox(0F, -1.5F, -1.5F, 13F, 3F, 3F),
                PartPose.offsetAndRotation(18F, 3F, -10F, 0F, 0F, 0.6320361F));
        root.addOrReplaceChild(LEG1_SEG4, CubeListBuilder.create().texOffs(0, 14).addBox(0F, -1.5F, -1.5F, 3F, 10F, 3F),
                PartPose.offsetAndRotation(26F, 12F, -10F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEG1_SEG5, CubeListBuilder.create().texOffs(0, 0).addBox(0F, -1.5F, -1.5F, 7F, 3F, 3F),
                PartPose.offsetAndRotation(27F, 19F, -10F, 0F, 0F, 0.669215F));
        root.addOrReplaceChild(LEG2_SEG1, CubeListBuilder.create().texOffs(20, 20).addBox(0F, -1.5F, -2F, 4F, 3F, 4F),
                PartPose.offsetAndRotation(8.5F, 13F, -4F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEG2_SEG2, CubeListBuilder.create().texOffs(21, 0).addBox(0F, -1.5F, -1.5F, 13F, 3F, 3F),
                PartPose.offsetAndRotation(12F, 13F, -4F, 0F, 0F, -0.9294576F));
        root.addOrReplaceChild(LEG2_SEG3, CubeListBuilder.create().texOffs(15, 8).addBox(0F, -1.5F, -1.5F, 13F, 3F, 3F),
                PartPose.offsetAndRotation(18F, 3F, -4F, 0F, 0F, 0.6320361F));
        root.addOrReplaceChild(LEG2_SEG4, CubeListBuilder.create().texOffs(0, 14).addBox(0F, -1.5F, -1.5F, 3F, 10F, 3F),
                PartPose.offsetAndRotation(26F, 12F, -4F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEG2_SEG5, CubeListBuilder.create().texOffs(0, 0).addBox(0F, -1.5F, -1.5F, 7F, 3F, 3F),
                PartPose.offsetAndRotation(27F, 19F, -4F, 0F, 0F, 0.669215F));
        root.addOrReplaceChild(LEG3_SEG1, CubeListBuilder.create().texOffs(20, 20).addBox(0F, -1.5F, -2F, 4F, 3F, 4F),
                PartPose.offsetAndRotation(9.5F, 13F, 2F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEG3_SEG2, CubeListBuilder.create().texOffs(21, 0).addBox(0F, -1.5F, -1.5F, 13F, 3F, 3F),
                PartPose.offsetAndRotation(12F, 13F, 2F, 0F, 0F, -0.9294576F));
        root.addOrReplaceChild(LEG3_SEG3, CubeListBuilder.create().texOffs(15, 8).addBox(0F, -1.5F, -1.5F, 13F, 3F, 3F),
                PartPose.offsetAndRotation(18F, 3F, 2F, 0F, 0F, 0.6320361F));
        root.addOrReplaceChild(LEG3_SEG4, CubeListBuilder.create().texOffs(0, 14).addBox(0F, -1.5F, -1.5F, 3F, 10F, 3F),
                PartPose.offsetAndRotation(26F, 12F, 2F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEG3_SEG5, CubeListBuilder.create().texOffs(0, 0).addBox(0F, -1.5F, -1.5F, 7F, 3F, 3F),
                PartPose.offsetAndRotation(27F, 19F, 2F, 0F, 0F, 0.669215F));
        root.addOrReplaceChild(LEG4_SEG1, CubeListBuilder.create().texOffs(20, 20).addBox(0F, -1.5F, -2F, 4F, 3F, 4F),
                PartPose.offsetAndRotation(9F, 13F, 8F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEG4_SEG2, CubeListBuilder.create().texOffs(21, 0).addBox(0F, -1.5F, -1.5F, 13F, 3F, 3F),
                PartPose.offsetAndRotation(12F, 13F, 8F, 0F, 0F, -0.9294576F));
        root.addOrReplaceChild(LEG4_SEG3, CubeListBuilder.create().texOffs(15, 8).addBox(0F, -1.5F, -1.5F, 13F, 3F, 3F),
                PartPose.offsetAndRotation(18F, 3F, 8F, 0F, 0F, 0.6320361F));
        root.addOrReplaceChild(LEG4_SEG4, CubeListBuilder.create().texOffs(0, 14).addBox(0F, -1.5F, -1.5F, 3F, 10F, 3F),
                PartPose.offsetAndRotation(26F, 12F, 8F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEG4_SEG5, CubeListBuilder.create().texOffs(0, 0).addBox(0F, -1.5F, -1.5F, 7F, 3F, 3F),
                PartPose.offsetAndRotation(27F, 19F, 8F, 0F, 0F, 0.669215F));
        root.addOrReplaceChild(LEG5_SEG1, CubeListBuilder.create().texOffs(20, 20).addBox(-4F, -1.5F, -2F, 4F, 3F, 4F),
                PartPose.offsetAndRotation(-9F, 13F, -10F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEG5_SEG2, CubeListBuilder.create().texOffs(21, 0).addBox(-13F, -1.5F, -1.5F, 13F, 3F, 3F),
                PartPose.offsetAndRotation(-12F, 14F, -10F, 0F, 0F, 0.9294653F));
    }

    private static void addParts1(PartDefinition root) {
        root.addOrReplaceChild(LEG5_SEG3, CubeListBuilder.create().texOffs(15, 8).addBox(-13F, -1.5F, -1.5F, 13F, 3F, 3F),
                PartPose.offsetAndRotation(-18F, 4F, -10F, 0F, 0F, -0.6320364F));
        root.addOrReplaceChild(LEG5_SEG4, CubeListBuilder.create().texOffs(0, 14).addBox(-3F, -1.5F, -1.5F, 3F, 10F, 3F),
                PartPose.offsetAndRotation(-26F, 12F, -10F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEG5_SEG5, CubeListBuilder.create().texOffs(0, 0).addBox(0F, -1.5F, -1.5F, 7F, 3F, 3F),
                PartPose.offsetAndRotation(-27F, 19F, -10F, 0F, 0F, 2.240008F));
        root.addOrReplaceChild(LEG6_SEG1, CubeListBuilder.create().texOffs(20, 20).addBox(-4F, -1.5F, -2F, 4F, 3F, 4F),
                PartPose.offsetAndRotation(-8.5F, 13F, -4F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEG6_SEG2, CubeListBuilder.create().texOffs(21, 0).addBox(-13F, -1.5F, -1.5F, 13F, 3F, 3F),
                PartPose.offsetAndRotation(-12F, 14F, -4F, 0F, 0F, 0.9294576F));
        root.addOrReplaceChild(LEG6_SEG3, CubeListBuilder.create().texOffs(15, 8).addBox(-13F, -1.5F, -1.5F, 13F, 3F, 3F),
                PartPose.offsetAndRotation(-18F, 4F, -4F, 0F, 0F, -0.6320361F));
        root.addOrReplaceChild(LEG6_SEG4, CubeListBuilder.create().texOffs(0, 14).addBox(-3F, -1.5F, -1.5F, 3F, 10F, 3F),
                PartPose.offsetAndRotation(-26F, 12F, -4F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEG6_SEG5, CubeListBuilder.create().texOffs(0, 0).addBox(0F, -1.5F, -1.5F, 7F, 3F, 3F),
                PartPose.offsetAndRotation(-27F, 19F, -4F, 0F, 0F, 2.240008F));
        root.addOrReplaceChild(LEG7_SEG1, CubeListBuilder.create().texOffs(20, 20).addBox(-4F, -1.5F, -2F, 4F, 3F, 4F),
                PartPose.offsetAndRotation(-9.5F, 13F, 2F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEG7_SEG2, CubeListBuilder.create().texOffs(21, 0).addBox(-13F, -1.5F, -1.5F, 13F, 3F, 3F),
                PartPose.offsetAndRotation(-12F, 14F, 2F, 0F, 0F, 0.9294576F));
        root.addOrReplaceChild(LEG7_SEG3, CubeListBuilder.create().texOffs(15, 8).addBox(-13F, -1.5F, -1.5F, 13F, 3F, 3F),
                PartPose.offsetAndRotation(-18F, 4F, 2F, 0F, 0F, -0.6320361F));
        root.addOrReplaceChild(LEG7_SEG4, CubeListBuilder.create().texOffs(0, 14).addBox(-3F, -1.5F, -1.5F, 3F, 10F, 3F),
                PartPose.offsetAndRotation(-26F, 12F, 2F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEG7_SEG5, CubeListBuilder.create().texOffs(0, 0).addBox(0F, -1.5F, -1.5F, 7F, 3F, 3F),
                PartPose.offsetAndRotation(-27F, 19F, 2F, 0F, 0F, 2.240008F));
        root.addOrReplaceChild(LEG8_SEG1, CubeListBuilder.create().texOffs(20, 20).addBox(-4F, -1.5F, -2F, 4F, 3F, 4F),
                PartPose.offsetAndRotation(-9F, 13F, 8F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEG8_SEG2, CubeListBuilder.create().texOffs(21, 0).addBox(-12F, -1.5F, -1.5F, 13F, 3F, 3F),
                PartPose.offsetAndRotation(-12F, 14F, 8F, 0F, 0F, 0.9294576F));
        root.addOrReplaceChild(LEG8_SEG3, CubeListBuilder.create().texOffs(15, 8).addBox(-13F, -1.5F, -1.5F, 13F, 3F, 3F),
                PartPose.offsetAndRotation(-18F, 4F, 8F, 0F, 0F, -0.6320361F));
        root.addOrReplaceChild(LEG8_SEG4, CubeListBuilder.create().texOffs(0, 14).addBox(-3F, -1.5F, -1.5F, 3F, 10F, 3F),
                PartPose.offsetAndRotation(-26F, 12F, 8F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEG8_SEG5, CubeListBuilder.create().texOffs(0, 0).addBox(0F, -1.5F, -1.5F, 7F, 3F, 3F),
                PartPose.offsetAndRotation(-27F, 19F, 8F, 0F, 0F, 2.240008F));
    }
}
