// GENERATED by tools/gen_models.py from reference/jar/models/ModelFlounder.json - do not edit.
package com.swbr.orespawn.client.model.geom;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Geometry of OreSpawn's ModelFlounder (6 parts), copied unchanged from the 1.7.10 jar.
 * Part order is the order the original constructor created them.
 */
public final class FlounderGeometry {

    public static final int TEXTURE_WIDTH = 64;
    public static final int TEXTURE_HEIGHT = 32;

    public static final String BODY = "body";
    public static final String HEAD = "head";
    public static final String TAIL1 = "tail1";
    public static final String TAIL2 = "tail2";
    public static final String RFIN = "rfin";
    public static final String LFIN = "lfin";

    /** Every part in creation order. */
    public static final String[] PARTS = {
            BODY,
            HEAD,
            TAIL1,
            TAIL2,
            RFIN,
            LFIN
    };

    /** Parts the original hid at construction time (showModel = false or isHidden = true). */
    public static final String[] HIDDEN = {};

    private FlounderGeometry() {}

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild(BODY, CubeListBuilder.create().texOffs(0, 16).addBox(-4F, 0F, -5F, 8F, 1F, 12F),
                PartPose.offsetAndRotation(0F, 22F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(HEAD, CubeListBuilder.create().texOffs(0, 5).addBox(-2F, 0F, 0F, 4F, 1F, 2F),
                PartPose.offsetAndRotation(0F, 22F, -7F, 0F, 0F, 0F));
        root.addOrReplaceChild(TAIL1, CubeListBuilder.create().texOffs(30, 0).addBox(-2F, 0F, 0F, 4F, 1F, 2F),
                PartPose.offsetAndRotation(0F, 22F, 7F, 0F, 0F, 0F));
        root.addOrReplaceChild(TAIL2, CubeListBuilder.create().texOffs(30, 4).addBox(-3F, 0F, 2F, 6F, 1F, 3F),
                PartPose.offsetAndRotation(0F, 22F, 7F, 0F, 0F, 0F));
        root.addOrReplaceChild(RFIN, CubeListBuilder.create().texOffs(12, 0).addBox(-3F, 0F, 0F, 3F, 1F, 2F),
                PartPose.offsetAndRotation(-4F, 22F, -2F, 0F, 0F, 0F));
        root.addOrReplaceChild(LFIN, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 3F, 1F, 2F),
                PartPose.offsetAndRotation(4F, 22F, -2F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, TEXTURE_WIDTH, TEXTURE_HEIGHT);
    }
}
