// GENERATED by tools/gen_models.py from reference/jar/models/ModelFrog.json - do not edit.
package com.swbr.orespawn.client.model.geom;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Geometry of OreSpawn's ModelFrog (10 parts), copied unchanged from the 1.7.10 jar.
 * Part order is the order the original constructor created them.
 */
public final class FrogGeometry {

    public static final int TEXTURE_WIDTH = 64;
    public static final int TEXTURE_HEIGHT = 64;

    public static final String BODY = "body";
    public static final String JAW = "jaw";
    public static final String LFLEG = "lfleg";
    public static final String RFLEG = "rfleg";
    public static final String LLEG1 = "lleg1";
    public static final String RLEG1 = "rleg1";
    public static final String LLEG2 = "lleg2";
    public static final String RLEG2 = "rleg2";
    public static final String LEYE = "leye";
    public static final String REYE = "reye";

    /** Every part in creation order. */
    public static final String[] PARTS = {
            BODY,
            JAW,
            LFLEG,
            RFLEG,
            LLEG1,
            RLEG1,
            LLEG2,
            RLEG2,
            LEYE,
            REYE
    };

    /** Parts the original hid at construction time (showModel = false or isHidden = true). */
    public static final String[] HIDDEN = {};

    private FrogGeometry() {}

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild(BODY, CubeListBuilder.create().texOffs(41, 0).addBox(-4F, -10F, 0F, 8F, 11F, 2F),
                PartPose.offsetAndRotation(0F, 24F, 2F, 0.7330383F, 0F, 0F));
        root.addOrReplaceChild(JAW, CubeListBuilder.create().texOffs(42, 15).addBox(-4F, -8F, 0F, 8F, 8F, 1F),
                PartPose.offsetAndRotation(0F, 24F, 2F, 1.22173F, 0F, 0F));
        root.addOrReplaceChild(LFLEG, CubeListBuilder.create().texOffs(14, 0).addBox(0F, 0F, 0F, 1F, 5F, 1F),
                PartPose.offsetAndRotation(3F, 20F, 0F, -0.5235988F, 0F, -0.4712389F));
        root.addOrReplaceChild(RFLEG, CubeListBuilder.create().texOffs(20, 0).addBox(-1F, 0F, 0F, 1F, 5F, 1F),
                PartPose.offsetAndRotation(-3F, 20F, 0F, -0.5235988F, 0F, 0.4712389F));
        root.addOrReplaceChild(LLEG1, CubeListBuilder.create().texOffs(10, 8).addBox(0F, -9F, -1F, 1F, 9F, 2F),
                PartPose.offsetAndRotation(3F, 24F, 3F, 0F, 0F, 0.2268928F));
        root.addOrReplaceChild(RLEG1, CubeListBuilder.create().texOffs(18, 8).addBox(-1F, -9F, -1F, 1F, 9F, 2F),
                PartPose.offsetAndRotation(-3F, 24F, 3F, 0F, 0F, -0.2268928F));
        root.addOrReplaceChild(LLEG2, CubeListBuilder.create().texOffs(11, 20).addBox(0F, 0F, 0F, 1F, 10F, 1F),
                PartPose.offsetAndRotation(5F, 15F, 3F, 0F, 0F, -0.3839724F));
        root.addOrReplaceChild(RLEG2, CubeListBuilder.create().texOffs(19, 20).addBox(-1F, 0F, 0F, 1F, 10F, 1F),
                PartPose.offsetAndRotation(-5F, 15F, 3F, 0F, 0F, 0.3839724F));
        root.addOrReplaceChild(LEYE, CubeListBuilder.create().texOffs(0, 8).addBox(0F, 0F, 0F, 1F, 2F, 1F),
                PartPose.offsetAndRotation(2F, 17F, -2F, 0.7330383F, 0F, 0F));
        root.addOrReplaceChild(REYE, CubeListBuilder.create().texOffs(0, 4).addBox(0F, 0F, 0F, 1F, 2F, 1F),
                PartPose.offsetAndRotation(-3F, 17F, -2F, 0.7330383F, 0F, 0F));
        return LayerDefinition.create(mesh, TEXTURE_WIDTH, TEXTURE_HEIGHT);
    }
}
