// GENERATED by tools/gen_models.py from reference/jar/models/ModelGhost.json - do not edit.
package com.swbr.orespawn.client.model.geom;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Geometry of OreSpawn's ModelGhost (3 parts), copied unchanged from the 1.7.10 jar.
 * Part order is the order the original constructor created them.
 */
public final class GhostGeometry {

    public static final int TEXTURE_WIDTH = 64;
    public static final int TEXTURE_HEIGHT = 64;

    public static final String HEAD_AND_BODY = "HeadAndBody";
    public static final String LARM = "LArm";
    public static final String RARM = "RArm";

    /** Every part in creation order. */
    public static final String[] PARTS = {
            HEAD_AND_BODY,
            LARM,
            RARM
    };

    /** Parts the original hid at construction time (showModel = false or isHidden = true). */
    public static final String[] HIDDEN = {};

    private GhostGeometry() {}

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild(HEAD_AND_BODY, CubeListBuilder.create().texOffs(0, 0).addBox(-3F, 0F, -3F, 6F, 21F, 6F),
                PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(LARM, CubeListBuilder.create().texOffs(34, 0).addBox(-1F, -1F, -1F, 2F, 11F, 2F),
                PartPose.offsetAndRotation(3F, 6F, 0F, 0F, 0F, -0.3316126F));
        root.addOrReplaceChild(RARM, CubeListBuilder.create().texOffs(25, 0).addBox(-1F, -1F, -1F, 2F, 11F, 2F),
                PartPose.offsetAndRotation(-3F, 6F, 0F, 0F, 0F, 0.3316126F));
        return LayerDefinition.create(mesh, TEXTURE_WIDTH, TEXTURE_HEIGHT);
    }
}
