// GENERATED by tools/gen_models.py from reference/jar/models/ModelGhostSkelly.json - do not edit.
package com.swbr.orespawn.client.model.geom;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Geometry of OreSpawn's ModelGhostSkelly (10 parts), copied unchanged from the 1.7.10 jar.
 * Part order is the order the original constructor created them.
 */
public final class GhostSkellyGeometry {

    public static final int TEXTURE_WIDTH = 128;
    public static final int TEXTURE_HEIGHT = 64;

    public static final String BODY = "body";
    public static final String SHIRT = "shirt";
    public static final String HEAD = "head";
    public static final String STEM = "stem";
    public static final String RARM = "rarm";
    public static final String LARM = "larm";
    public static final String RSLEEVE = "rsleeve";
    public static final String LSLEEVE = "lsleeve";
    public static final String LCHAINS = "lchains";
    public static final String RCHAINS = "rchains";

    /** Every part in creation order. */
    public static final String[] PARTS = {
            BODY,
            SHIRT,
            HEAD,
            STEM,
            RARM,
            LARM,
            RSLEEVE,
            LSLEEVE,
            LCHAINS,
            RCHAINS
    };

    /** Parts the original hid at construction time (showModel = false or isHidden = true). */
    public static final String[] HIDDEN = {};

    private GhostSkellyGeometry() {}

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild(BODY, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 1F, 21F, 1F),
                PartPose.offsetAndRotation(0F, -1F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHIRT, CubeListBuilder.create().texOffs(42, 43).addBox(-2F, 0F, -2F, 5F, 12F, 5F),
                PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(HEAD, CubeListBuilder.create().texOffs(40, 29).addBox(-3F, 0F, -3F, 7F, 5F, 7F),
                PartPose.offsetAndRotation(0F, -6F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(STEM, CubeListBuilder.create().texOffs(49, 23).addBox(0F, 0F, 0F, 1F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -8F, 0F, 0.1745329F, 0F, 0.1745329F));
        root.addOrReplaceChild(RARM, CubeListBuilder.create().texOffs(26, 0).addBox(-14F, 0F, 0F, 15F, 1F, 1F),
                PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(LARM, CubeListBuilder.create().texOffs(63, 0).addBox(0F, 0F, 0F, 15F, 1F, 1F),
                PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(RSLEEVE, CubeListBuilder.create().texOffs(31, 7).addBox(-11F, 0F, -1F, 9F, 8F, 3F),
                PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(LSLEEVE, CubeListBuilder.create().texOffs(71, 7).addBox(3F, 0F, -1F, 9F, 8F, 3F),
                PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(LCHAINS, CubeListBuilder.create().texOffs(98, 0).addBox(11F, -1F, 0F, 3F, 16F, 1F),
                PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(RCHAINS, CubeListBuilder.create().texOffs(12, 0).addBox(-13F, -1F, 0F, 3F, 10F, 1F),
                PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, TEXTURE_WIDTH, TEXTURE_HEIGHT);
    }
}
