// GENERATED by tools/gen_models.py from reference/jar/models/ModelGiantRobot.json - do not edit.
package com.swbr.orespawn.client.model.geom;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Geometry of OreSpawn's ModelGiantRobot (18 parts), copied unchanged from the 1.7.10 jar.
 * Part order is the order the original constructor created them.
 */
public final class GiantRobotGeometry {

    public static final int TEXTURE_WIDTH = 256;
    public static final int TEXTURE_HEIGHT = 512;

    public static final String HIP = "Hip";
    public static final String THIGH = "Thigh";
    public static final String SHIN = "Shin";
    public static final String FOOT1 = "Foot1";
    public static final String FOOT2 = "Foot2";
    public static final String FOOT3 = "Foot3";
    public static final String THIGH2 = "Thigh2";
    public static final String THIGH3 = "Thigh3";
    public static final String BACK1 = "Back1";
    public static final String BACK2 = "Back2";
    public static final String BACK3 = "Back3";
    public static final String SHOULDERS = "Shoulders";
    public static final String NECK = "Neck";
    public static final String HEAD = "Head";
    public static final String ARM1 = "Arm1";
    public static final String ARM2 = "Arm2";
    public static final String ARM3 = "Arm3";
    public static final String KNUCKLES = "Knuckles";

    /** Every part in creation order. */
    public static final String[] PARTS = {
            HIP,
            THIGH,
            SHIN,
            FOOT1,
            FOOT2,
            FOOT3,
            THIGH2,
            THIGH3,
            BACK1,
            BACK2,
            BACK3,
            SHOULDERS,
            NECK,
            HEAD,
            ARM1,
            ARM2,
            ARM3,
            KNUCKLES
    };

    /** Parts the original hid at construction time (showModel = false or isHidden = true). */
    public static final String[] HIDDEN = {};

    private GiantRobotGeometry() {}

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild(HIP, CubeListBuilder.create().texOffs(0, 0).addBox(-4F, -4F, -15F, 8F, 8F, 30F),
                PartPose.offsetAndRotation(0F, -60F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(THIGH, CubeListBuilder.create().texOffs(0, 115).addBox(-3F, -3F, -3F, 6F, 43F, 6F),
                PartPose.offsetAndRotation(0F, -58F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHIN, CubeListBuilder.create().texOffs(0, 167).addBox(-3F, -3F, -3F, 6F, 43F, 6F),
                PartPose.offsetAndRotation(0F, -18F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(FOOT1, CubeListBuilder.create().texOffs(0, 282).addBox(-7F, 38F, -11F, 14F, 4F, 17F),
                PartPose.offsetAndRotation(0F, -18F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(FOOT2, CubeListBuilder.create().texOffs(0, 246).addBox(-6F, 19F, -8F, 12F, 19F, 13F),
                PartPose.offsetAndRotation(0F, -18F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(FOOT3, CubeListBuilder.create().texOffs(0, 219).addBox(-5F, 5F, -5F, 10F, 14F, 9F),
                PartPose.offsetAndRotation(0F, -18F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(THIGH2, CubeListBuilder.create().texOffs(0, 43).addBox(-7F, -8F, -7F, 14F, 24F, 14F),
                PartPose.offsetAndRotation(0F, -58F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(THIGH3, CubeListBuilder.create().texOffs(0, 84).addBox(-5F, 16F, -5F, 10F, 17F, 10F),
                PartPose.offsetAndRotation(0F, -58F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(BACK1, CubeListBuilder.create().texOffs(125, 138).addBox(-4F, -20F, -4F, 8F, 24F, 8F),
                PartPose.offsetAndRotation(0F, -60F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(BACK2, CubeListBuilder.create().texOffs(125, 95).addBox(-13F, -42F, -10F, 26F, 24F, 16F),
                PartPose.offsetAndRotation(0F, -60F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(BACK3, CubeListBuilder.create().texOffs(125, 43).addBox(-17F, -68F, -13F, 34F, 26F, 20F),
                PartPose.offsetAndRotation(0F, -60F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHOULDERS, CubeListBuilder.create().texOffs(60, 200).addBox(-22F, -64F, -4F, 44F, 8F, 8F),
                PartPose.offsetAndRotation(0F, -60F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(NECK, CubeListBuilder.create().texOffs(125, 29).addBox(-4F, -70F, -4F, 8F, 2F, 8F),
                PartPose.offsetAndRotation(0F, -60F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(HEAD, CubeListBuilder.create().texOffs(127, 0).addBox(-7F, -82F, -7F, 14F, 12F, 14F),
                PartPose.offsetAndRotation(0F, -60F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(ARM1, CubeListBuilder.create().texOffs(77, 250).addBox(-6F, -6F, -6F, 12F, 21F, 12F),
                PartPose.offsetAndRotation(28F, -120F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(ARM2, CubeListBuilder.create().texOffs(73, 300).addBox(-4F, 15F, -4F, 8F, 24F, 8F),
                PartPose.offsetAndRotation(28F, -120F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(ARM3, CubeListBuilder.create().texOffs(61, 350).addBox(-3F, -3F, -3F, 6F, 33F, 6F),
                PartPose.offsetAndRotation(28F, -81F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(KNUCKLES, CubeListBuilder.create().texOffs(56, 400).addBox(-7F, 30F, -5F, 14F, 12F, 10F),
                PartPose.offsetAndRotation(28F, -81F, 0F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, TEXTURE_WIDTH, TEXTURE_HEIGHT);
    }
}
