// GENERATED by tools/gen_models.py from reference/jar/models/ModelGodzilla.json - do not edit.
package com.swbr.orespawn.client.model.geom;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Geometry of OreSpawn's ModelGodzilla (71 parts), copied unchanged from the 1.7.10 jar.
 * Part order is the order the original constructor created them.
 */
public final class GodzillaGeometry {

    public static final int TEXTURE_WIDTH = 1024;
    public static final int TEXTURE_HEIGHT = 1024;

    public static final String LTOE1 = "LToe1";
    public static final String LTOE3 = "LToe3";
    public static final String LTOE2 = "LToe2";
    public static final String LTOE9 = "LToe9";
    public static final String LTOE8 = "LToe8";
    public static final String LTOE7 = "LToe7";
    public static final String LTOE6 = "LToe6";
    public static final String LTOE5 = "LToe5";
    public static final String LTOE4 = "LToe4";
    public static final String RTOE9 = "RToe9";
    public static final String RTOE6 = "RToe6";
    public static final String RTOE5 = "RToe5";
    public static final String RTOE2 = "RToe2";
    public static final String RTOE1 = "RToe1";
    public static final String RTOE4 = "RToe4";
    public static final String RTOE7 = "RToe7";
    public static final String RTOE8 = "RToe8";
    public static final String RTOE3 = "RToe3";
    public static final String LTHIGH = "LThigh";
    public static final String LLOWER_LEG = "LLowerLeg";
    public static final String LUPPER_LEG = "LUpperLeg";
    public static final String TAIL_TIP = "TailTip";
    public static final String RLEG_LOWER = "RLegLower";
    public static final String RLEG_UPPER = "RLegUpper";
    public static final String RTHIGH = "RThigh";
    public static final String LOWER_JAW = "LowerJaw";
    public static final String TAIL_BASE = "TailBase";
    public static final String TAIL2 = "Tail2";
    public static final String TAIL3 = "Tail3";
    public static final String TAIL4 = "Tail4";
    public static final String TAIL5 = "Tail5";
    public static final String TAIL6 = "Tail6";
    public static final String TAIL7 = "Tail7";
    public static final String BODY_BOTTOM = "BodyBottom";
    public static final String RLOWER_ARM = "RLowerArm";
    public static final String BODY_CENTER = "BodyCenter";
    public static final String NECK = "Neck";
    public static final String TOP_JAW = "TopJaw";
    public static final String HEAD = "Head";
    public static final String BODY_TOP = "BodyTop";
    public static final String RSHOULDER = "RShoulder";
    public static final String RTHUMB_TIP = "RThumbTip";
    public static final String RUPPER_ARM = "RUpperArm";
    public static final String RHAND = "RHand";
    public static final String RTHUMB_BASE = "RThumbBase";
    public static final String R3RD_FINGER_TIP = "R3rdFingerTip";
    public static final String R3RD_FINGER_BASE = "R3rdFingerBase";
    public static final String RINDEX_TIP = "RIndexTip";
    public static final String RINDEX_BASE = "RIndexBase";
    public static final String LSHOULDER = "LShoulder";
    public static final String LUPPER_ARM = "LUpperArm";
    public static final String LLOWER_ARM = "LLowerArm";
    public static final String LINDEX_BASE = "LIndexBase";
    public static final String LINDEX_TIP = "LIndexTip";
    public static final String LHAND = "LHand";
    public static final String LTHUMB_BASE = "LThumbBase";
    public static final String LTHUMB_TIP = "LThumbTip";
    public static final String L3RD_FINGER_TIP = "L3rdFingerTip";
    public static final String L3RD_FINGER_BASE = "L3rdFingerBase";
    public static final String LSPIKES1 = "Lspikes1";
    public static final String RSPIKES1 = "Rspikes1";
    public static final String LSPIKE2 = "Lspike2";
    public static final String RSPIKE2 = "Rspike2";
    public static final String LSPIKE3 = "Lspike3";
    public static final String RSPIKE3 = "Rspike3";
    public static final String LSPIKE4 = "Lspike4";
    public static final String RSPIKE4 = "Rspike4";
    public static final String LSPIKE5 = "Lspike5";
    public static final String RSPIKE5 = "Rspike5";
    public static final String SPIKE6 = "Spike6";
    public static final String SPIKES7 = "Spikes7";

    /** Every part in creation order. */
    public static final String[] PARTS = {
            LTOE1,
            LTOE3,
            LTOE2,
            LTOE9,
            LTOE8,
            LTOE7,
            LTOE6,
            LTOE5,
            LTOE4,
            RTOE9,
            RTOE6,
            RTOE5,
            RTOE2,
            RTOE1,
            RTOE4,
            RTOE7,
            RTOE8,
            RTOE3,
            LTHIGH,
            LLOWER_LEG,
            LUPPER_LEG,
            TAIL_TIP,
            RLEG_LOWER,
            RLEG_UPPER,
            RTHIGH,
            LOWER_JAW,
            TAIL_BASE,
            TAIL2,
            TAIL3,
            TAIL4,
            TAIL5,
            TAIL6,
            TAIL7,
            BODY_BOTTOM,
            RLOWER_ARM,
            BODY_CENTER,
            NECK,
            TOP_JAW,
            HEAD,
            BODY_TOP,
            RSHOULDER,
            RTHUMB_TIP,
            RUPPER_ARM,
            RHAND,
            RTHUMB_BASE,
            R3RD_FINGER_TIP,
            R3RD_FINGER_BASE,
            RINDEX_TIP,
            RINDEX_BASE,
            LSHOULDER,
            LUPPER_ARM,
            LLOWER_ARM,
            LINDEX_BASE,
            LINDEX_TIP,
            LHAND,
            LTHUMB_BASE,
            LTHUMB_TIP,
            L3RD_FINGER_TIP,
            L3RD_FINGER_BASE,
            LSPIKES1,
            RSPIKES1,
            LSPIKE2,
            RSPIKE2,
            LSPIKE3,
            RSPIKE3,
            LSPIKE4,
            RSPIKE4,
            LSPIKE5,
            RSPIKE5,
            SPIKE6,
            SPIKES7
    };

    /** Parts the original hid at construction time (showModel = false or isHidden = true). */
    public static final String[] HIDDEN = {};

    private GodzillaGeometry() {}

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        addParts0(root);
        addParts1(root);
        return LayerDefinition.create(mesh, TEXTURE_WIDTH, TEXTURE_HEIGHT);
    }

    private static void addParts0(PartDefinition root) {
        root.addOrReplaceChild(LTOE1, CubeListBuilder.create().texOffs(45, 1002).addBox(-5F, -2F, -40F, 10F, 10F, 6F),
                PartPose.offsetAndRotation(54F, 16F, 6F, 0F, 0.7853982F, 0F));
        root.addOrReplaceChild(LTOE3, CubeListBuilder.create().texOffs(0, 955).addBox(-8F, -8F, -26F, 16F, 16F, 30F),
                PartPose.offsetAndRotation(54F, 16F, 6F, 0F, 0.7853982F, 0F));
        root.addOrReplaceChild(LTOE2, CubeListBuilder.create().texOffs(0, 1002).addBox(-7F, -6F, -34F, 14F, 14F, 8F),
                PartPose.offsetAndRotation(54F, 16F, 6F, 0F, 0.7853982F, 0F));
        root.addOrReplaceChild(LTOE9, CubeListBuilder.create().texOffs(0, 955).addBox(-8F, -8F, -26F, 16F, 16F, 30F),
                PartPose.offsetAndRotation(54F, 16F, 6F, 0F, -0.7853982F, 0F));
        root.addOrReplaceChild(LTOE8, CubeListBuilder.create().texOffs(0, 1002).addBox(-7F, -6F, -34F, 14F, 14F, 8F),
                PartPose.offsetAndRotation(54F, 16F, 6F, 0F, -0.7853982F, 0F));
        root.addOrReplaceChild(LTOE7, CubeListBuilder.create().texOffs(45, 1002).addBox(-5F, -2F, -40F, 10F, 10F, 6F),
                PartPose.offsetAndRotation(54F, 16F, 6F, 0F, -0.7853982F, 0F));
        root.addOrReplaceChild(LTOE6, CubeListBuilder.create().texOffs(92, 955).addBox(-8F, -8F, -26F, 16F, 16F, 36F),
                PartPose.offsetAndRotation(54F, 16F, 6F, 0F, 0F, 0F));
        root.addOrReplaceChild(LTOE5, CubeListBuilder.create().texOffs(0, 1002).addBox(-7F, -6F, -34F, 14F, 14F, 8F),
                PartPose.offsetAndRotation(54F, 16F, 6F, 0F, 0F, 0F));
        root.addOrReplaceChild(LTOE4, CubeListBuilder.create().texOffs(45, 1002).addBox(-5F, -2F, -40F, 10F, 10F, 6F),
                PartPose.offsetAndRotation(54F, 16F, 6F, 0F, 0F, 0F));
        root.addOrReplaceChild(RTOE9, CubeListBuilder.create().texOffs(0, 955).addBox(-8F, -8F, -26F, 16F, 16F, 30F),
                PartPose.offsetAndRotation(-54F, 16F, 6F, 0F, 0.7853982F, 0F));
        root.addOrReplaceChild(RTOE6, CubeListBuilder.create().texOffs(92, 955).addBox(-8F, -8F, -26F, 16F, 16F, 36F),
                PartPose.offsetAndRotation(-54F, 16F, 6F, 0F, 0F, 0F));
        root.addOrReplaceChild(RTOE5, CubeListBuilder.create().texOffs(0, 1002).addBox(-7F, -6F, -34F, 14F, 14F, 8F),
                PartPose.offsetAndRotation(-54F, 16F, 6F, 0F, 0F, 0F));
        root.addOrReplaceChild(RTOE2, CubeListBuilder.create().texOffs(0, 1002).addBox(-7F, -6F, -34F, 14F, 14F, 8F),
                PartPose.offsetAndRotation(-54F, 16F, 6F, 0F, -0.7853982F, 0F));
        root.addOrReplaceChild(RTOE1, CubeListBuilder.create().texOffs(45, 1002).addBox(-5F, -2F, -40F, 10F, 10F, 6F),
                PartPose.offsetAndRotation(-54F, 16F, 6F, 0F, -0.7853982F, 0F));
        root.addOrReplaceChild(RTOE4, CubeListBuilder.create().texOffs(45, 1002).addBox(-5F, -2F, -40F, 10F, 10F, 6F),
                PartPose.offsetAndRotation(-54F, 16F, 6F, 0F, 0F, 0F));
        root.addOrReplaceChild(RTOE7, CubeListBuilder.create().texOffs(45, 1002).addBox(-5F, -2F, -40F, 10F, 10F, 6F),
                PartPose.offsetAndRotation(-54F, 16F, 6F, 0F, 0.7853982F, 0F));
        root.addOrReplaceChild(RTOE8, CubeListBuilder.create().texOffs(0, 1002).addBox(-7F, -6F, -34F, 14F, 14F, 8F),
                PartPose.offsetAndRotation(-54F, 16F, 6F, 0F, 0.7853982F, 0F));
        root.addOrReplaceChild(RTOE3, CubeListBuilder.create().texOffs(0, 955).addBox(-8F, -8F, -26F, 16F, 16F, 30F),
                PartPose.offsetAndRotation(-54F, 16F, 6F, 0F, -0.7853982F, 0F));
        root.addOrReplaceChild(LTHIGH, CubeListBuilder.create().texOffs(192, 350).addBox(0F, -14F, -21F, 28F, 28F, 42F),
                PartPose.offsetAndRotation(40F, -91F, 2F, -0.5585054F, 0F, 0F));
        root.addOrReplaceChild(LLOWER_LEG, CubeListBuilder.create().texOffs(202, 556).addBox(-15F, -62F, -15F, 30F, 62F, 30F),
                PartPose.offsetAndRotation(54F, 14F, 6F, 0.1745329F, -0.1308997F, 0F));
        root.addOrReplaceChild(LUPPER_LEG, CubeListBuilder.create().texOffs(152, 420).addBox(-16F, -52F, -16F, 32F, 52F, 32F),
                PartPose.offsetAndRotation(56F, -36F, -5F, -0.1745329F, -0.3926991F, -0.0872665F));
        root.addOrReplaceChild(TAIL_TIP, CubeListBuilder.create().texOffs(0, 694).addBox(-6F, 0F, -5F, 12F, 21F, 10F),
                PartPose.offsetAndRotation(0F, 18F, 203F, 1.53589F, 0F, 0F));
        root.addOrReplaceChild(RLEG_LOWER, CubeListBuilder.create().texOffs(200, 646).addBox(-15F, -62F, -15F, 30F, 62F, 30F),
                PartPose.offsetAndRotation(-54F, 16F, 6F, 0.1745329F, 0.1308997F, 0F));
        root.addOrReplaceChild(RLEG_UPPER, CubeListBuilder.create().texOffs(152, 420).addBox(-16F, -52F, -16F, 32F, 52F, 32F),
                PartPose.offsetAndRotation(-56F, -36F, -5F, -0.1745329F, 0.3926991F, 0.0872665F));
        root.addOrReplaceChild(RTHIGH, CubeListBuilder.create().texOffs(192, 350).addBox(-28F, -14F, -21F, 28F, 28F, 42F),
                PartPose.offsetAndRotation(-40F, -91F, 2F, -0.5585054F, 0F, 0F));
        root.addOrReplaceChild(LOWER_JAW, CubeListBuilder.create().texOffs(272, 0).addBox(-13F, -5F, -50F, 26F, 11F, 50F),
                PartPose.offsetAndRotation(0F, -142F, -109F, 0.5235988F, 0F, 0F));
        root.addOrReplaceChild(TAIL_BASE, CubeListBuilder.create().texOffs(0, 240).addBox(-32F, 0F, -29F, 64F, 40F, 58F),
                PartPose.offsetAndRotation(0F, -73F, 26F, 0.7853982F, 0F, 0F));
        root.addOrReplaceChild(TAIL2, CubeListBuilder.create().texOffs(0, 338).addBox(-25F, 0F, -23F, 50F, 36F, 46F),
                PartPose.offsetAndRotation(0F, -48F, 48F, 0.6981317F, 0F, 0F));
        root.addOrReplaceChild(TAIL3, CubeListBuilder.create().texOffs(0, 420).addBox(-20F, 0F, -18F, 40F, 36F, 36F),
                PartPose.offsetAndRotation(0F, -24F, 66F, 0.8726646F, 0F, 0F));
        root.addOrReplaceChild(TAIL4, CubeListBuilder.create().texOffs(0, 492).addBox(-16F, 0F, -14F, 32F, 42F, 28F),
                PartPose.offsetAndRotation(0F, -3F, 87F, 1.134464F, 0F, 0F));
        root.addOrReplaceChild(TAIL5, CubeListBuilder.create().texOffs(0, 556).addBox(-13F, 0F, -11F, 26F, 42F, 22F),
                PartPose.offsetAndRotation(0F, 12F, 116F, 1.53589F, 0F, 0F));
        root.addOrReplaceChild(TAIL6, CubeListBuilder.create().texOffs(0, 614).addBox(-10F, 0F, -9F, 20F, 32F, 18F),
                PartPose.offsetAndRotation(0F, 14F, 154F, 1.53589F, 0F, 0F));
        root.addOrReplaceChild(TAIL7, CubeListBuilder.create().texOffs(0, 658).addBox(-8F, 0F, -7F, 16F, 22F, 14F),
                PartPose.offsetAndRotation(0F, 16F, 185F, 1.53589F, 0F, 0F));
        root.addOrReplaceChild(BODY_BOTTOM, CubeListBuilder.create().texOffs(0, 104).addBox(-40F, 0F, -36F, 80F, 64F, 72F),
                PartPose.offsetAndRotation(0F, -112F, -20F, 0.8726646F, 0F, 0F));
        root.addOrReplaceChild(RLOWER_ARM, CubeListBuilder.create().texOffs(245, 240).addBox(-48F, -11F, -11F, 48F, 22F, 22F),
                PartPose.offsetAndRotation(-80F, -115F, -61F, 0F, -0.7853982F, -0.2617994F));
        root.addOrReplaceChild(BODY_CENTER, CubeListBuilder.create().texOffs(0, 0).addBox(-36F, -32F, -32F, 72F, 40F, 64F),
                PartPose.offsetAndRotation(0F, -112F, -20F, 1.134464F, 0F, 0F));
        root.addOrReplaceChild(NECK, CubeListBuilder.create().texOffs(0, 720).addBox(-23F, -23F, -32F, 46F, 46F, 32F),
                PartPose.offsetAndRotation(0F, -144F, -71F, -0.0698132F, 0F, 0F));
        root.addOrReplaceChild(TOP_JAW, CubeListBuilder.create().texOffs(0, 892).addBox(-14F, -8F, -73F, 28F, 26F, 33F),
                PartPose.offsetAndRotation(0F, -156F, -98F, 0.0872665F, 0F, 0F));
        root.addOrReplaceChild(HEAD, CubeListBuilder.create().texOffs(0, 808).addBox(-17F, -18F, -40F, 34F, 36F, 40F),
                PartPose.offsetAndRotation(0F, -156F, -98F, 0.0872665F, 0F, 0F));
        root.addOrReplaceChild(BODY_TOP, CubeListBuilder.create().texOffs(0, 0).addBox(-36F, -32F, -32F, 72F, 40F, 64F),
                PartPose.offsetAndRotation(0F, -126F, -50F, 1.308997F, 0F, 0F));
        root.addOrReplaceChild(RSHOULDER, CubeListBuilder.create().texOffs(304, 96).addBox(-16F, -32F, -32F, 16F, 42F, 46F),
                PartPose.offsetAndRotation(-36F, -130F, -42F, 1.308997F, 0F, 0F));
        root.addOrReplaceChild(RTHUMB_TIP, CubeListBuilder.create().texOffs(422, 18).addBox(5F, 1F, -43F, 8F, 8F, 12F),
                PartPose.offsetAndRotation(-115F, -100F, -99F, 0F, 0F, 0F));
        root.addOrReplaceChild(RUPPER_ARM, CubeListBuilder.create().texOffs(304, 184).addBox(-54F, -13F, -13F, 54F, 26F, 26F),
                PartPose.offsetAndRotation(-38F, -130F, -52F, 0F, -0.2617994F, -0.3490659F));
        root.addOrReplaceChild(RHAND, CubeListBuilder.create().texOffs(245, 292).addBox(-13F, -13F, -13F, 26F, 26F, 26F),
                PartPose.offsetAndRotation(-115F, -100F, -99F, -1.071467F, 2.007129F, 0.1745329F));
        root.addOrReplaceChild(RTHUMB_BASE, CubeListBuilder.create().texOffs(424, 57).addBox(2F, 1F, -32F, 8F, 8F, 20F),
                PartPose.offsetAndRotation(-115F, -100F, -99F, 0F, -0.1047198F, 0F));
        root.addOrReplaceChild(R3RD_FINGER_TIP, CubeListBuilder.create().texOffs(422, 18).addBox(-10F, 0F, -41F, 8F, 8F, 12F),
                PartPose.offsetAndRotation(-115F, -100F, -99F, 0F, 0.6806784F, 0F));
        root.addOrReplaceChild(R3RD_FINGER_BASE, CubeListBuilder.create().texOffs(424, 57).addBox(-11F, -3F, -30F, 8F, 8F, 20F),
                PartPose.offsetAndRotation(-115F, -100F, -99F, 0.122173F, 0.6457718F, 0F));
        root.addOrReplaceChild(RINDEX_TIP, CubeListBuilder.create().texOffs(422, 18).addBox(-4F, -12F, -43F, 8F, 8F, 12F),
                PartPose.offsetAndRotation(-115F, -100F, -99F, -0.2094395F, 0.1745329F, 0F));
        root.addOrReplaceChild(RINDEX_BASE, CubeListBuilder.create().texOffs(424, 57).addBox(-4F, -9F, -34F, 8F, 8F, 20F),
                PartPose.offsetAndRotation(-115F, -100F, -99F, -0.2792527F, 0.1570796F, 0F));
        root.addOrReplaceChild(LSHOULDER, CubeListBuilder.create().texOffs(304, 96).addBox(0F, -32F, -32F, 16F, 42F, 46F),
                PartPose.offsetAndRotation(36F, -130F, -42F, 1.308997F, 0F, 0F));
        root.addOrReplaceChild(LUPPER_ARM, CubeListBuilder.create().texOffs(304, 184).addBox(0F, -13F, -13F, 54F, 26F, 26F),
                PartPose.offsetAndRotation(38F, -130F, -52F, 0F, 0.296706F, 0.3490659F));
        root.addOrReplaceChild(LLOWER_ARM, CubeListBuilder.create().texOffs(245, 240).addBox(0F, -11F, -11F, 48F, 22F, 22F),
                PartPose.offsetAndRotation(80F, -115F, -61F, 0F, 0.7853982F, 0.2617994F));
        root.addOrReplaceChild(LINDEX_BASE, CubeListBuilder.create().texOffs(424, 57).addBox(-4F, -13F, -32F, 8F, 8F, 20F),
                PartPose.offsetAndRotation(115F, -100F, -99F, -0.1570796F, -0.1396263F, 0F));
        root.addOrReplaceChild(LINDEX_TIP, CubeListBuilder.create().texOffs(422, 18).addBox(-1F, -18F, -41F, 8F, 8F, 12F),
                PartPose.offsetAndRotation(115F, -100F, -99F, 0F, -0.0349066F, 0F));
        root.addOrReplaceChild(LHAND, CubeListBuilder.create().texOffs(245, 292).addBox(-13F, -13F, -13F, 26F, 26F, 26F),
                PartPose.offsetAndRotation(115F, -100F, -99F, 0.9599311F, 1.308997F, 0.1745329F));
        root.addOrReplaceChild(LTHUMB_BASE, CubeListBuilder.create().texOffs(424, 57).addBox(-8F, -2F, -32F, 8F, 8F, 20F),
                PartPose.offsetAndRotation(115F, -100F, -98F, 0.1396263F, 0.2617994F, 0F));
        root.addOrReplaceChild(LTHUMB_TIP, CubeListBuilder.create().texOffs(422, 18).addBox(-12F, 2F, -40F, 8F, 8F, 12F),
                PartPose.offsetAndRotation(115F, -100F, -99F, 0F, 0.1396263F, 0F));
        root.addOrReplaceChild(L3RD_FINGER_TIP, CubeListBuilder.create().texOffs(422, 18).addBox(9F, 2F, -42F, 8F, 8F, 12F),
                PartPose.offsetAndRotation(115F, -100F, -99F, 0.0349066F, -0.3316126F, 0F));
        root.addOrReplaceChild(L3RD_FINGER_BASE, CubeListBuilder.create().texOffs(424, 57).addBox(4F, -5F, -33F, 8F, 8F, 20F),
                PartPose.offsetAndRotation(115F, -100F, -99F, 0.2617994F, -0.4712389F, 0F));
        root.addOrReplaceChild(LSPIKES1, CubeListBuilder.create().texOffs(500, 0).addBox(0F, -10F, 0F, 0F, 10F, 11F),
                PartPose.offsetAndRotation(5F, -168F, -86F, -0.0872665F, 0F, -0.0174533F));
    }

    private static void addParts1(PartDefinition root) {
        root.addOrReplaceChild(RSPIKES1, CubeListBuilder.create().texOffs(500, 0).addBox(0F, -10F, 0F, 0F, 10F, 11F),
                PartPose.offsetAndRotation(-5F, -168F, -86F, -0.0872665F, 0F, -0.0174533F));
        root.addOrReplaceChild(LSPIKE2, CubeListBuilder.create().texOffs(500, 30).addBox(0F, -25F, 0F, 0F, 25F, 21F),
                PartPose.offsetAndRotation(10F, -162F, -63F, -0.2617994F, 0F, -0.0174533F));
        root.addOrReplaceChild(RSPIKE2, CubeListBuilder.create().texOffs(500, 30).addBox(0F, -25F, 0F, 0F, 25F, 21F),
                PartPose.offsetAndRotation(-10F, -162F, -63F, -0.2617994F, 0F, -0.0174533F));
        root.addOrReplaceChild(LSPIKE3, CubeListBuilder.create().texOffs(500, 80).addBox(0F, -45F, 0F, 0F, 45F, 34F),
                PartPose.offsetAndRotation(14F, -153F, -32F, -0.4363323F, 0F, -0.0174533F));
        root.addOrReplaceChild(RSPIKE3, CubeListBuilder.create().texOffs(500, 80).addBox(0F, -45F, 0F, 0F, 45F, 34F),
                PartPose.offsetAndRotation(-14F, -153F, -32F, -0.4363323F, 0F, -0.0174533F));
        root.addOrReplaceChild(LSPIKE4, CubeListBuilder.create().texOffs(500, 165).addBox(0F, -50F, 0F, 0F, 50F, 36F),
                PartPose.offsetAndRotation(18F, -131F, 13F, -0.715585F, 0F, -0.0174533F));
        root.addOrReplaceChild(RSPIKE4, CubeListBuilder.create().texOffs(500, 165).addBox(0F, -50F, 0F, 0F, 50F, 36F),
                PartPose.offsetAndRotation(-18F, -131F, 13F, -0.715585F, 0F, -0.0174533F));
        root.addOrReplaceChild(LSPIKE5, CubeListBuilder.create().texOffs(500, 255).addBox(12F, -67F, 5F, 0F, 39F, 27F),
                PartPose.offsetAndRotation(0F, -73F, 26F, -0.7853982F, 0F, -0.0174533F));
        root.addOrReplaceChild(RSPIKE5, CubeListBuilder.create().texOffs(500, 255).addBox(-12F, -67F, 5F, 0F, 39F, 27F),
                PartPose.offsetAndRotation(0F, -73F, 26F, -0.7853982F, 0F, -0.0174533F));
        root.addOrReplaceChild(SPIKE6, CubeListBuilder.create().texOffs(500, 325).addBox(0F, -48F, 11F, 0F, 25F, 21F),
                PartPose.offsetAndRotation(0F, -48F, 48F, -0.8901179F, 0F, -0.0174533F));
        root.addOrReplaceChild(SPIKES7, CubeListBuilder.create().texOffs(500, 376).addBox(0F, -29F, 20F, 0F, 10F, 11F),
                PartPose.offsetAndRotation(0F, -24F, 66F, -0.7504916F, 0F, -0.0174533F));
    }
}
