// GENERATED by tools/gen_models.py from reference/jar/models/ModelIsland.json - do not edit.
package com.swbr.orespawn.client.model.geom;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Geometry of OreSpawn's ModelIsland (3 parts), copied unchanged from the 1.7.10 jar.
 * Part order is the order the original constructor created them.
 */
public final class IslandGeometry {

    public static final int TEXTURE_WIDTH = 64;
    public static final int TEXTURE_HEIGHT = 32;

    public static final String SHAPE1 = "Shape1";
    public static final String SHAPE2 = "Shape2";
    public static final String SHAPE3 = "Shape3";

    /** Every part in creation order. */
    public static final String[] PARTS = {
            SHAPE1,
            SHAPE2,
            SHAPE3
    };

    /** Parts the original hid at construction time (showModel = false or isHidden = true). */
    public static final String[] HIDDEN = {};

    private IslandGeometry() {}

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild(SHAPE1, CubeListBuilder.create().texOffs(0, 0).addBox(-4F, -4F, -4F, 8F, 8F, 8F),
                PartPose.offsetAndRotation(0F, 16F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE2, CubeListBuilder.create().texOffs(32, 0).addBox(-4F, -4F, -4F, 8F, 8F, 8F),
                PartPose.offsetAndRotation(0F, 16F, 0F, 0.7853982F, 0.7853982F, 0.7853982F));
        root.addOrReplaceChild(SHAPE3, CubeListBuilder.create().texOffs(32, 16).addBox(-4F, -4F, -4F, 8F, 8F, 8F),
                PartPose.offsetAndRotation(0F, 16F, 0F, 0.7853982F, 0.7853982F, 0.7853982F));
        return LayerDefinition.create(mesh, TEXTURE_WIDTH, TEXTURE_HEIGHT);
    }
}
