// GENERATED by tools/gen_models.py from reference/jar/models/ModelMosquito.json - do not edit.
package com.swbr.orespawn.client.model.geom;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Geometry of OreSpawn's ModelMosquito (5 parts), copied unchanged from the 1.7.10 jar.
 * Part order is the order the original constructor created them.
 */
public final class MosquitoGeometry {

    public static final int TEXTURE_WIDTH = 32;
    public static final int TEXTURE_HEIGHT = 32;

    public static final String BODY = "body";
    public static final String LEFTWING1 = "leftwing1";
    public static final String RIGHTWING1 = "rightwing1";
    public static final String LEFTWING2 = "leftwing2";
    public static final String RIGHTWING2 = "rightwing2";

    /** Every part in creation order. */
    public static final String[] PARTS = {
            BODY,
            LEFTWING1,
            RIGHTWING1,
            LEFTWING2,
            RIGHTWING2
    };

    /** Parts the original hid at construction time (showModel = false or isHidden = true). */
    public static final String[] HIDDEN = {};

    private MosquitoGeometry() {}

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild(BODY, CubeListBuilder.create().texOffs(8, 18).addBox(0F, 0F, -2F, 1F, 1F, 8F),
                PartPose.offsetAndRotation(0F, 17F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEFTWING1, CubeListBuilder.create().texOffs(16, 13).addBox(1F, 0F, -1F, 3F, 1F, 3F),
                PartPose.offsetAndRotation(1F, 17F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(RIGHTWING1, CubeListBuilder.create().texOffs(2, 13).addBox(-4F, 0F, -1F, 3F, 1F, 3F),
                PartPose.offsetAndRotation(0F, 17F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEFTWING2, CubeListBuilder.create().texOffs(15, 8).addBox(0F, 0F, 0F, 5F, 1F, 1F),
                PartPose.offsetAndRotation(1F, 17F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(RIGHTWING2, CubeListBuilder.create().texOffs(2, 8).addBox(-5F, 0F, 0F, 5F, 1F, 1F),
                PartPose.offsetAndRotation(0F, 17F, 0F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, TEXTURE_WIDTH, TEXTURE_HEIGHT);
    }
}
