// GENERATED by tools/gen_models.py from reference/jar/models/ModelPitchBlack.json - do not edit.
package com.swbr.orespawn.client.model.geom;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Geometry of OreSpawn's ModelPitchBlack (101 parts), copied unchanged from the 1.7.10 jar.
 * Part order is the order the original constructor created them.
 */
public final class PitchBlackGeometry {

    public static final int TEXTURE_WIDTH = 512;
    public static final int TEXTURE_HEIGHT = 256;

    public static final String LCLAW1 = "lclaw1";
    public static final String BODY = "body";
    public static final String LEFTLEG1 = "leftleg1";
    public static final String TAIL1 = "tail1";
    public static final String LEFTLEG2 = "leftleg2";
    public static final String BODY2 = "body2";
    public static final String LEFTLEG3 = "leftleg3";
    public static final String TAIL2 = "tail2";
    public static final String TAIL3 = "tail3";
    public static final String LCLAW2 = "lclaw2";
    public static final String LCLAW3 = "lclaw3";
    public static final String LCLAW4 = "lclaw4";
    public static final String LCLAW5 = "lclaw5";
    public static final String LCLAW6 = "lclaw6";
    public static final String LCLAW7 = "lclaw7";
    public static final String TAIL4 = "tail4";
    public static final String TAIL5 = "tail5";
    public static final String TAIL6 = "tail6";
    public static final String TAIL7 = "tail7";
    public static final String TAIL8 = "tail8";
    public static final String TAIL9 = "tail9";
    public static final String TAILPOINT1 = "tailpoint1";
    public static final String TAILPOINT2 = "tailpoint2";
    public static final String LLEGSPIKE = "llegspike";
    public static final String TAILSPIKE1 = "tailspike1";
    public static final String TAILSPIKE2 = "tailspike2";
    public static final String TAILSPIKE3 = "tailspike3";
    public static final String TAILSPIKE4 = "tailspike4";
    public static final String TAILSPIKE5 = "tailspike5";
    public static final String TAILSPIKE6 = "tailspike6";
    public static final String NECK1 = "neck1";
    public static final String NECK2 = "neck2";
    public static final String NECK3 = "neck3";
    public static final String HEAD1 = "head1";
    public static final String LEYE = "leye";
    public static final String REYE = "reye";
    public static final String HEAD2 = "head2";
    public static final String HEAD3 = "head3";
    public static final String HEAD4 = "head4";
    public static final String HEAD5 = "head5";
    public static final String HEAD6 = "head6";
    public static final String JAW1 = "jaw1";
    public static final String JAW2 = "jaw2";
    public static final String JAW3 = "jaw3";
    public static final String JAW4 = "jaw4";
    public static final String TOOTH1 = "tooth1";
    public static final String TOOTH2 = "tooth2";
    public static final String TOOTH3 = "tooth3";
    public static final String TOOTH4 = "tooth4";
    public static final String TOOTH5 = "tooth5";
    public static final String JAW5 = "jaw5";
    public static final String HEAD7 = "head7";
    public static final String TOOTH6 = "tooth6";
    public static final String TOOTH7 = "tooth7";
    public static final String TOOTH8 = "tooth8";
    public static final String TOOTH9 = "tooth9";
    public static final String TOOTH10 = "tooth10";
    public static final String TOOTH11 = "tooth11";
    public static final String TOOTH12 = "tooth12";
    public static final String TOOTH13 = "tooth13";
    public static final String RIGHTLEG1 = "rightleg1";
    public static final String RIGHTLEG2 = "rightleg2";
    public static final String TOOTH14 = "tooth14";
    public static final String TOOTH15 = "tooth15";
    public static final String TOOTH16 = "tooth16";
    public static final String TOOTH17 = "tooth17";
    public static final String TOOTH18 = "tooth18";
    public static final String TOOTH19 = "tooth19";
    public static final String TOOTH20 = "tooth20";
    public static final String TOOTH21 = "tooth21";
    public static final String TOOTH22 = "tooth22";
    public static final String TOOTH23 = "tooth23";
    public static final String RIGHTLEG3 = "rightleg3";
    public static final String LLEGSPIKE2 = "llegspike2";
    public static final String RCLAW2 = "rclaw2";
    public static final String RCLAW4 = "rclaw4";
    public static final String RCLAW1 = "rclaw1";
    public static final String RCLAW5 = "rclaw5";
    public static final String RCLAW7 = "rclaw7";
    public static final String RCLAW3 = "rclaw3";
    public static final String RCLAW6 = "rclaw6";
    public static final String WING1 = "wing1";
    public static final String WING2 = "wing2";
    public static final String WING3 = "wing3";
    public static final String MEM1 = "mem1";
    public static final String MEM2 = "mem2";
    public static final String MEM3 = "mem3";
    public static final String WINGCLAW1 = "wingclaw1";
    public static final String WINGCLAW2 = "wingclaw2";
    public static final String WINGCLAW3 = "wingclaw3";
    public static final String LSHOULDER = "lshoulder";
    public static final String RSHOULDER = "rshoulder";
    public static final String RWING1 = "rwing1";
    public static final String RMEM1 = "rmem1";
    public static final String RWING2 = "rwing2";
    public static final String RMEM2 = "rmem2";
    public static final String RWING3 = "rwing3";
    public static final String RMEM3 = "rmem3";
    public static final String RWINGCLAW1 = "rwingclaw1";
    public static final String RWINGCLAW2 = "rwingclaw2";
    public static final String RWINGCLAW3 = "rwingclaw3";

    /** Every part in creation order. */
    public static final String[] PARTS = {
            LCLAW1,
            BODY,
            LEFTLEG1,
            TAIL1,
            LEFTLEG2,
            BODY2,
            LEFTLEG3,
            TAIL2,
            TAIL3,
            LCLAW2,
            LCLAW3,
            LCLAW4,
            LCLAW5,
            LCLAW6,
            LCLAW7,
            TAIL4,
            TAIL5,
            TAIL6,
            TAIL7,
            TAIL8,
            TAIL9,
            TAILPOINT1,
            TAILPOINT2,
            LLEGSPIKE,
            TAILSPIKE1,
            TAILSPIKE2,
            TAILSPIKE3,
            TAILSPIKE4,
            TAILSPIKE5,
            TAILSPIKE6,
            NECK1,
            NECK2,
            NECK3,
            HEAD1,
            LEYE,
            REYE,
            HEAD2,
            HEAD3,
            HEAD4,
            HEAD5,
            HEAD6,
            JAW1,
            JAW2,
            JAW3,
            JAW4,
            TOOTH1,
            TOOTH2,
            TOOTH3,
            TOOTH4,
            TOOTH5,
            JAW5,
            HEAD7,
            TOOTH6,
            TOOTH7,
            TOOTH8,
            TOOTH9,
            TOOTH10,
            TOOTH11,
            TOOTH12,
            TOOTH13,
            RIGHTLEG1,
            RIGHTLEG2,
            TOOTH14,
            TOOTH15,
            TOOTH16,
            TOOTH17,
            TOOTH18,
            TOOTH19,
            TOOTH20,
            TOOTH21,
            TOOTH22,
            TOOTH23,
            RIGHTLEG3,
            LLEGSPIKE2,
            RCLAW2,
            RCLAW4,
            RCLAW1,
            RCLAW5,
            RCLAW7,
            RCLAW3,
            RCLAW6,
            WING1,
            WING2,
            WING3,
            MEM1,
            MEM2,
            MEM3,
            WINGCLAW1,
            WINGCLAW2,
            WINGCLAW3,
            LSHOULDER,
            RSHOULDER,
            RWING1,
            RMEM1,
            RWING2,
            RMEM2,
            RWING3,
            RMEM3,
            RWINGCLAW1,
            RWINGCLAW2,
            RWINGCLAW3
    };

    /** Parts the original hid at construction time (showModel = false or isHidden = true). */
    public static final String[] HIDDEN = {};

    private PitchBlackGeometry() {}

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        addParts0(root);
        addParts1(root);
        return LayerDefinition.create(mesh, TEXTURE_WIDTH, TEXTURE_HEIGHT);
    }

    private static void addParts0(PartDefinition root) {
        root.addOrReplaceChild(LCLAW1, CubeListBuilder.create().texOffs(300, 111).addBox(-3F, 0F, -3F, 2F, 3F, 6F),
                PartPose.offsetAndRotation(7F, 21F, 11F, 0F, 0.6632251F, 0F));
        root.addOrReplaceChild(BODY, CubeListBuilder.create().texOffs(400, 26).addBox(-6F, -12F, -9F, 12F, 12F, 9F),
                PartPose.offsetAndRotation(0F, 0F, 9F, 0.0698132F, 0F, 0F));
        root.addOrReplaceChild(LEFTLEG1, CubeListBuilder.create().texOffs(300, 10).addBox(-1F, -5F, -20F, 5F, 10F, 10F),
                PartPose.offsetAndRotation(7F, 5F, 23F, -0.5759587F, 0F, 0F));
        root.addOrReplaceChild(TAIL1, CubeListBuilder.create().texOffs(400, 82).addBox(-5F, -6F, 0F, 8F, 10F, 12F),
                PartPose.offsetAndRotation(1F, -3F, 22F, -0.1745329F, 0F, 0F));
        root.addOrReplaceChild(LEFTLEG2, CubeListBuilder.create().texOffs(300, 31).addBox(-1F, -10F, -4F, 4F, 12F, 5F),
                PartPose.offsetAndRotation(7F, 5F, 23F, 0.9773844F, 0F, 0F));
        root.addOrReplaceChild(BODY2, CubeListBuilder.create().texOffs(400, 50).addBox(0F, -3F, -3F, 12F, 14F, 16F),
                PartPose.offsetAndRotation(-6F, -9F, 10F, -0.1047198F, 0F, 0F));
        root.addOrReplaceChild(LEFTLEG3, CubeListBuilder.create().texOffs(300, 51).addBox(-1F, -19F, 1F, 3F, 18F, 4F),
                PartPose.offsetAndRotation(7F, 21F, 11F, -0.5235988F, 0F, 0F));
        root.addOrReplaceChild(TAIL2, CubeListBuilder.create().texOffs(400, 106).addBox(-3F, -4F, 0F, 6F, 8F, 10F),
                PartPose.offsetAndRotation(0F, -2F, 33F, -0.1396263F, 0F, 0F));
        root.addOrReplaceChild(TAIL3, CubeListBuilder.create().texOffs(400, 126).addBox(-2F, -2F, 0F, 4F, 5F, 10F),
                PartPose.offsetAndRotation(0F, -1F, 42F, -0.1396263F, 0F, 0F));
        root.addOrReplaceChild(LCLAW2, CubeListBuilder.create().texOffs(300, 76).addBox(-1F, -1F, -6F, 3F, 4F, 13F),
                PartPose.offsetAndRotation(7F, 21F, 11F, 0F, 0F, 0F));
        root.addOrReplaceChild(LCLAW3, CubeListBuilder.create().texOffs(300, 95).addBox(2F, 0F, -6F, 2F, 3F, 10F),
                PartPose.offsetAndRotation(7F, 21F, 11F, 0F, -0.6632251F, 0F));
        root.addOrReplaceChild(LCLAW4, CubeListBuilder.create().texOffs(310, 123).addBox(0F, 1F, -9F, 1F, 2F, 3F),
                PartPose.offsetAndRotation(7F, 21F, 11F, 0F, 0F, 0F));
        root.addOrReplaceChild(LCLAW5, CubeListBuilder.create().texOffs(300, 123).addBox(-2.5F, 1F, -5F, 1F, 2F, 2F),
                PartPose.offsetAndRotation(7F, 21F, 11F, 0F, 0.6632251F, 0F));
        root.addOrReplaceChild(LCLAW6, CubeListBuilder.create().texOffs(322, 123).addBox(2.5F, 1F, -9F, 1F, 2F, 3F),
                PartPose.offsetAndRotation(7F, 21F, 11F, 0F, -0.6632251F, 0F));
        root.addOrReplaceChild(LCLAW7, CubeListBuilder.create().texOffs(333, 123).addBox(0F, 1F, 7F, 1F, 2F, 3F),
                PartPose.offsetAndRotation(7F, 21F, 11F, 0F, 0F, 0F));
        root.addOrReplaceChild(TAIL4, CubeListBuilder.create().texOffs(400, 143).addBox(-2F, -2F, 0F, 4F, 4F, 10F),
                PartPose.offsetAndRotation(0F, 0F, 51F, -0.1396263F, 0F, 0F));
        root.addOrReplaceChild(TAIL5, CubeListBuilder.create().texOffs(400, 159).addBox(-1.5F, -2F, 0F, 3F, 3F, 10F),
                PartPose.offsetAndRotation(0F, 1F, 59F, -0.1396263F, 0F, 0F));
        root.addOrReplaceChild(TAIL6, CubeListBuilder.create().texOffs(400, 180).addBox(0F, 0F, 0F, 2F, 2F, 10F),
                PartPose.offsetAndRotation(0F, 0F, 68F, -0.1396263F, 0.1745329F, 0F));
        root.addOrReplaceChild(TAIL7, CubeListBuilder.create().texOffs(400, 180).addBox(-2F, 0F, 0F, 2F, 2F, 10F),
                PartPose.offsetAndRotation(0F, 0F, 68F, -0.1396263F, -0.1745329F, 0F));
        root.addOrReplaceChild(TAIL8, CubeListBuilder.create().texOffs(400, 180).addBox(0F, 0F, 0F, 2F, 2F, 10F),
                PartPose.offsetAndRotation(-4F, 1F, 77F, -0.1396263F, -0.1745329F, 0F));
        root.addOrReplaceChild(TAIL9, CubeListBuilder.create().texOffs(400, 180).addBox(0F, 0F, 0F, 2F, 2F, 10F),
                PartPose.offsetAndRotation(2F, 1F, 77F, -0.1396263F, 0.1745329F, 0F));
        root.addOrReplaceChild(TAILPOINT1, CubeListBuilder.create().texOffs(400, 200).addBox(-1F, -1F, 0F, 1F, 1F, 22F),
                PartPose.offsetAndRotation(5F, 3F, 85F, -0.1919862F, 0.1745329F, 0F));
        root.addOrReplaceChild(TAILPOINT2, CubeListBuilder.create().texOffs(400, 200).addBox(-1F, -1F, 0F, 1F, 1F, 22F),
                PartPose.offsetAndRotation(-4F, 3F, 86F, -0.1919862F, -0.1745329F, 0F));
        root.addOrReplaceChild(LLEGSPIKE, CubeListBuilder.create().texOffs(300, 131).addBox(0F, -28F, 1F, 1F, 12F, 1F),
                PartPose.offsetAndRotation(7F, 21F, 11F, -0.6981317F, 0F, 0F));
        root.addOrReplaceChild(TAILSPIKE1, CubeListBuilder.create().texOffs(400, 230).addBox(1F, -1F, 0F, 1F, 1F, 1F),
                PartPose.offsetAndRotation(2F, 1F, 77F, -0.1396263F, 0.1745329F, 0F));
        root.addOrReplaceChild(TAILSPIKE2, CubeListBuilder.create().texOffs(400, 230).addBox(1F, -1F, 6F, 1F, 1F, 1F),
                PartPose.offsetAndRotation(0F, 0F, 68F, -0.1396263F, 0.1745329F, 0F));
        root.addOrReplaceChild(TAILSPIKE3, CubeListBuilder.create().texOffs(400, 230).addBox(1F, -1F, 2F, 1F, 1F, 1F),
                PartPose.offsetAndRotation(0F, 0F, 68F, -0.1396263F, 0.1745329F, 0F));
        root.addOrReplaceChild(TAILSPIKE4, CubeListBuilder.create().texOffs(400, 230).addBox(0F, -1F, 0F, 1F, 1F, 1F),
                PartPose.offsetAndRotation(-4F, 1F, 77F, -0.1396263F, -0.1745329F, 0F));
        root.addOrReplaceChild(TAILSPIKE5, CubeListBuilder.create().texOffs(400, 230).addBox(-2F, -1F, 6F, 1F, 1F, 1F),
                PartPose.offsetAndRotation(0F, 0F, 68F, -0.1396263F, -0.1745329F, 0F));
        root.addOrReplaceChild(TAILSPIKE6, CubeListBuilder.create().texOffs(400, 230).addBox(-2F, -1F, 2F, 1F, 1F, 1F),
                PartPose.offsetAndRotation(0F, 0F, 68F, -0.1396263F, -0.1745329F, 0F));
        root.addOrReplaceChild(NECK1, CubeListBuilder.create().texOffs(400, 7).addBox(-4F, -4F, 0F, 8F, 8F, 8F),
                PartPose.offsetAndRotation(0F, -4F, -5F, 0.0872665F, 0F, 0F));
        root.addOrReplaceChild(NECK2, CubeListBuilder.create().texOffs(375, 10).addBox(-3F, -3F, -3F, 6F, 6F, 4F),
                PartPose.offsetAndRotation(0F, -4F, -5F, -0.0523599F, 0F, 0F));
        root.addOrReplaceChild(NECK3, CubeListBuilder.create().texOffs(375, 23).addBox(-2F, -2F, -6F, 4F, 4F, 8F),
                PartPose.offsetAndRotation(0F, -4F, -9F, -0.2443461F, 0F, 0F));
        root.addOrReplaceChild(HEAD1, CubeListBuilder.create().texOffs(123, 3).addBox(-18F, -1F, -12F, 36F, 1F, 12F),
                PartPose.offsetAndRotation(0F, -6F, -14F, -0.2443461F, 0F, 0F));
        root.addOrReplaceChild(LEYE, CubeListBuilder.create().texOffs(76, 2).addBox(18F, -1F, -13F, 3F, 3F, 15F),
                PartPose.offsetAndRotation(0F, -6F, -14F, -0.2443461F, 0F, 0F));
        root.addOrReplaceChild(REYE, CubeListBuilder.create().texOffs(32, 2).addBox(-21F, -1F, -13F, 3F, 3F, 15F),
                PartPose.offsetAndRotation(0F, -6F, -14F, -0.2443461F, 0F, 0F));
        root.addOrReplaceChild(HEAD2, CubeListBuilder.create().texOffs(140, 18).addBox(-8F, -2F, -11F, 16F, 1F, 11F),
                PartPose.offsetAndRotation(0F, -6F, -14F, -0.2443461F, 0F, 0F));
        root.addOrReplaceChild(HEAD3, CubeListBuilder.create().texOffs(143, 32).addBox(-2F, -4F, -14F, 4F, 4F, 16F),
                PartPose.offsetAndRotation(0F, -6F, -14F, -0.2443461F, 0F, 0F));
        root.addOrReplaceChild(HEAD4, CubeListBuilder.create().texOffs(152, 55).addBox(-1F, -10F, -13F, 2F, 8F, 12F),
                PartPose.offsetAndRotation(0F, -6F, -14F, -0.3665191F, 0F, 0F));
        root.addOrReplaceChild(HEAD5, CubeListBuilder.create().texOffs(154, 77).addBox(-0.5F, -18F, -11F, 1F, 9F, 9F),
                PartPose.offsetAndRotation(0F, -6F, -14F, -0.4363323F, 0F, 0F));
        root.addOrReplaceChild(HEAD6, CubeListBuilder.create().texOffs(160, 97).addBox(-0.5F, -24F, -10F, 1F, 8F, 4F),
                PartPose.offsetAndRotation(0F, -6F, -14F, -0.6632251F, 0F, 0F));
        root.addOrReplaceChild(JAW1, CubeListBuilder.create().texOffs(143, 114).addBox(-2F, 1F, -14F, 4F, 4F, 15F),
                PartPose.offsetAndRotation(0F, -6F, -14F, 0.1919862F, 0F, 0F));
        root.addOrReplaceChild(JAW2, CubeListBuilder.create().texOffs(150, 149).addBox(-1F, 4F, -12F, 2F, 5F, 11F),
                PartPose.offsetAndRotation(0F, -6F, -14F, 0.2617994F, 0F, 0F));
        root.addOrReplaceChild(JAW3, CubeListBuilder.create().texOffs(154, 168).addBox(-0.5F, 8F, -10F, 1F, 4F, 8F),
                PartPose.offsetAndRotation(0F, -6F, -14F, 0.3316126F, 0F, 0F));
        root.addOrReplaceChild(JAW4, CubeListBuilder.create().texOffs(158, 182).addBox(-0.5F, 11F, -7F, 1F, 4F, 4F),
                PartPose.offsetAndRotation(0F, -6F, -14F, 0.4014257F, 0F, 0F));
        root.addOrReplaceChild(TOOTH1, CubeListBuilder.create().texOffs(0, 0).addBox(-2F, 0F, -14F, 1F, 3F, 1F),
                PartPose.offsetAndRotation(0F, -6F, -14F, -0.2443461F, 0F, 0F));
        root.addOrReplaceChild(TOOTH2, CubeListBuilder.create().texOffs(0, 0).addBox(-0.5F, 0F, -14F, 1F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -6F, -14F, -0.2443461F, 0F, 0F));
        root.addOrReplaceChild(TOOTH3, CubeListBuilder.create().texOffs(0, 0).addBox(1F, 0F, -14F, 1F, 3F, 1F),
                PartPose.offsetAndRotation(0F, -6F, -14F, -0.2443461F, 0F, 0F));
        root.addOrReplaceChild(TOOTH4, CubeListBuilder.create().texOffs(0, 0).addBox(-2F, 0F, -12F, 1F, 3F, 1F),
                PartPose.offsetAndRotation(0F, -6F, -14F, -0.2443461F, 0F, 0F));
        root.addOrReplaceChild(TOOTH5, CubeListBuilder.create().texOffs(0, 0).addBox(1F, 0F, -12F, 1F, 3F, 1F),
                PartPose.offsetAndRotation(0F, -6F, -14F, -0.2443461F, 0F, 0F));
        root.addOrReplaceChild(JAW5, CubeListBuilder.create().texOffs(151, 135).addBox(-3F, 1F, -4F, 6F, 5F, 7F),
                PartPose.offsetAndRotation(0F, -6F, -14F, 0.1919862F, 0F, 0F));
        root.addOrReplaceChild(HEAD7, CubeListBuilder.create().texOffs(185, 34).addBox(-3F, -5F, -3F, 6F, 5F, 7F),
                PartPose.offsetAndRotation(0F, -6F, -14F, -0.2443461F, 0F, 0F));
        root.addOrReplaceChild(TOOTH6, CubeListBuilder.create().texOffs(0, 0).addBox(-2F, 0F, -10F, 1F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -6F, -14F, -0.2443461F, 0F, 0F));
        root.addOrReplaceChild(TOOTH7, CubeListBuilder.create().texOffs(0, 0).addBox(1F, 0F, -10F, 1F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -6F, -14F, -0.2443461F, 0F, 0F));
        root.addOrReplaceChild(TOOTH8, CubeListBuilder.create().texOffs(0, 0).addBox(-2F, 0F, -8F, 1F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -6F, -14F, -0.2443461F, 0F, 0F));
        root.addOrReplaceChild(TOOTH9, CubeListBuilder.create().texOffs(0, 0).addBox(1F, 0F, -8F, 1F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -6F, -14F, -0.2443461F, 0F, 0F));
        root.addOrReplaceChild(TOOTH10, CubeListBuilder.create().texOffs(0, 0).addBox(-2F, 0F, -6F, 1F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -6F, -14F, -0.2443461F, 0F, 0F));
        root.addOrReplaceChild(TOOTH11, CubeListBuilder.create().texOffs(0, 0).addBox(1F, 0F, -6F, 1F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -6F, -14F, -0.2443461F, 0F, 0F));
        root.addOrReplaceChild(TOOTH12, CubeListBuilder.create().texOffs(0, 0).addBox(-2F, 0F, -4F, 1F, 1F, 1F),
                PartPose.offsetAndRotation(0F, -6F, -14F, -0.2443461F, 0F, 0F));
        root.addOrReplaceChild(TOOTH13, CubeListBuilder.create().texOffs(-1, 0).addBox(1F, 0F, -4F, 1F, 1F, 1F),
                PartPose.offsetAndRotation(0F, -6F, -14F, -0.2443461F, 0F, 0F));
    }

    private static void addParts1(PartDefinition root) {
        root.addOrReplaceChild(RIGHTLEG1, CubeListBuilder.create().texOffs(250, 10).addBox(-1F, -5F, -20F, 5F, 10F, 10F),
                PartPose.offsetAndRotation(-10F, 5F, 23F, -0.5934119F, 0F, 0F));
        root.addOrReplaceChild(RIGHTLEG2, CubeListBuilder.create().texOffs(250, 32).addBox(0F, -10F, -4F, 4F, 12F, 5F),
                PartPose.offsetAndRotation(-10F, 5F, 23F, 0.9773844F, 0F, 0F));
        root.addOrReplaceChild(TOOTH14, CubeListBuilder.create().texOffs(0, 0).addBox(0.5F, -2F, -14F, 1F, 3F, 1F),
                PartPose.offsetAndRotation(0F, -6F, -14F, 0.1919862F, 0F, 0F));
        root.addOrReplaceChild(TOOTH15, CubeListBuilder.create().texOffs(0, 0).addBox(-1.5F, -2F, -14F, 1F, 3F, 1F),
                PartPose.offsetAndRotation(0F, -6F, -14F, 0.1919862F, 0F, 0F));
        root.addOrReplaceChild(TOOTH16, CubeListBuilder.create().texOffs(0, 0).addBox(1F, -1F, -12F, 1F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -6F, -14F, 0.1919862F, 0F, 0F));
        root.addOrReplaceChild(TOOTH17, CubeListBuilder.create().texOffs(0, 0).addBox(-2F, -1F, -12F, 1F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -6F, -14F, 0.1919862F, 0F, 0F));
        root.addOrReplaceChild(TOOTH18, CubeListBuilder.create().texOffs(0, 0).addBox(1F, -1F, -10F, 1F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -6F, -14F, 0.1919862F, 0F, 0F));
        root.addOrReplaceChild(TOOTH19, CubeListBuilder.create().texOffs(0, 0).addBox(-2F, -1F, -10F, 1F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -6F, -14F, 0.1919862F, 0F, 0F));
        root.addOrReplaceChild(TOOTH20, CubeListBuilder.create().texOffs(0, 0).addBox(-2F, -1F, -8F, 1F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -6F, -14F, 0.1919862F, 0F, 0F));
        root.addOrReplaceChild(TOOTH21, CubeListBuilder.create().texOffs(0, 0).addBox(1F, -1F, -8F, 1F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -6F, -14F, 0.1919862F, 0F, 0F));
        root.addOrReplaceChild(TOOTH22, CubeListBuilder.create().texOffs(0, 0).addBox(1F, 0F, -6F, 1F, 1F, 1F),
                PartPose.offsetAndRotation(0F, -6F, -14F, 0.1919862F, 0F, 0F));
        root.addOrReplaceChild(TOOTH23, CubeListBuilder.create().texOffs(0, 0).addBox(-2F, 0F, -6F, 1F, 1F, 1F),
                PartPose.offsetAndRotation(0F, -6F, -14F, 0.1919862F, 0F, 0F));
        root.addOrReplaceChild(RIGHTLEG3, CubeListBuilder.create().texOffs(250, 52).addBox(-1F, -19F, 1F, 3F, 18F, 4F),
                PartPose.offsetAndRotation(-8F, 21F, 11F, -0.5235988F, 0F, 0F));
        root.addOrReplaceChild(LLEGSPIKE2, CubeListBuilder.create().texOffs(250, 130).addBox(0F, -28F, 1F, 1F, 12F, 1F),
                PartPose.offsetAndRotation(-8F, 21F, 11F, -0.6981317F, 0F, 0F));
        root.addOrReplaceChild(RCLAW2, CubeListBuilder.create().texOffs(250, 76).addBox(-1F, -1F, -6F, 3F, 4F, 13F),
                PartPose.offsetAndRotation(-8F, 21F, 11F, 0F, 0F, 0F));
        root.addOrReplaceChild(RCLAW4, CubeListBuilder.create().texOffs(250, 123).addBox(0F, 1F, -9F, 1F, 2F, 3F),
                PartPose.offsetAndRotation(-8F, 21F, 11F, 0F, 0F, 0F));
        root.addOrReplaceChild(RCLAW1, CubeListBuilder.create().texOffs(250, 111).addBox(2F, 0F, -4F, 2F, 3F, 6F),
                PartPose.offsetAndRotation(-8F, 21F, 11F, 0F, -0.6632251F, 0F));
        root.addOrReplaceChild(RCLAW5, CubeListBuilder.create().texOffs(261, 123).addBox(2.5F, 1F, -6F, 1F, 2F, 2F),
                PartPose.offsetAndRotation(-8F, 21F, 11F, 0F, -0.6632251F, 0F));
        root.addOrReplaceChild(RCLAW7, CubeListBuilder.create().texOffs(283, 123).addBox(0F, 1F, 7F, 1F, 2F, 3F),
                PartPose.offsetAndRotation(-8F, 21F, 11F, 0F, 0F, 0F));
        root.addOrReplaceChild(RCLAW3, CubeListBuilder.create().texOffs(250, 95).addBox(-3F, 0F, -6F, 2F, 3F, 10F),
                PartPose.offsetAndRotation(-8F, 21F, 11F, 0F, 0.6632251F, 0F));
        root.addOrReplaceChild(RCLAW6, CubeListBuilder.create().texOffs(270, 123).addBox(-2.5F, 1F, -9F, 1F, 2F, 3F),
                PartPose.offsetAndRotation(-8F, 21F, 11F, 0F, 0.6632251F, 0F));
        root.addOrReplaceChild(WING1, CubeListBuilder.create().texOffs(10, 30).addBox(-1F, -1F, -1F, 23F, 3F, 3F),
                PartPose.offsetAndRotation(6F, -12F, 3F, 0F, 0.0872665F, -0.1396263F));
        root.addOrReplaceChild(WING2, CubeListBuilder.create().texOffs(10, 40).addBox(-1F, -1F, -1F, 44F, 2F, 2F),
                PartPose.offsetAndRotation(27F, -15F, 1F, 0F, 0F, 0F));
        root.addOrReplaceChild(WING3, CubeListBuilder.create().texOffs(10, 50).addBox(-1F, -1F, -1F, 23F, 2F, 2F),
                PartPose.offsetAndRotation(70F, -15F, 1F, 0F, -0.0872665F, 0.1745329F));
        root.addOrReplaceChild(MEM1, CubeListBuilder.create().texOffs(10, 60).addBox(-2F, 0F, 0F, 24F, 1F, 21F),
                PartPose.offsetAndRotation(6F, -12F, 3F, 0F, 0.0872665F, -0.1396263F));
        root.addOrReplaceChild(MEM2, CubeListBuilder.create().texOffs(10, 85).addBox(0F, 0F, 0F, 43F, 1F, 21F),
                PartPose.offsetAndRotation(27F, -15F, 1F, 0F, 0F, 0F));
        root.addOrReplaceChild(MEM3, CubeListBuilder.create().texOffs(10, 110).addBox(0F, 0F, 0F, 23F, 1F, 21F),
                PartPose.offsetAndRotation(70F, -15F, 1F, 0F, -0.0872665F, 0.1745329F));
        root.addOrReplaceChild(WINGCLAW1, CubeListBuilder.create().texOffs(85, 49).addBox(0F, 0F, -9F, 1F, 1F, 8F),
                PartPose.offsetAndRotation(70F, -15F, 1F, 0F, 0F, 0F));
        root.addOrReplaceChild(WINGCLAW2, CubeListBuilder.create().texOffs(67, 50).addBox(0F, 0F, -7F, 1F, 1F, 6F),
                PartPose.offsetAndRotation(70F, -15F, 1F, 0F, 0.6108652F, 0F));
        root.addOrReplaceChild(WINGCLAW3, CubeListBuilder.create().texOffs(106, 50).addBox(1F, 0F, -7F, 1F, 1F, 5F),
                PartPose.offsetAndRotation(69F, -15F, 1F, 0F, -0.6108652F, 0F));
        root.addOrReplaceChild(LSHOULDER, CubeListBuilder.create().texOffs(370, 40).addBox(0F, 0F, 0F, 3F, 2F, 6F),
                PartPose.offsetAndRotation(3F, -13F, 1F, 0.0698132F, 0F, 0F));
        root.addOrReplaceChild(RSHOULDER, CubeListBuilder.create().texOffs(370, 50).addBox(0F, 0F, 0F, 3F, 2F, 6F),
                PartPose.offsetAndRotation(-6F, -13F, 1F, 0.0698132F, 0F, 0F));
        root.addOrReplaceChild(RWING1, CubeListBuilder.create().texOffs(10, 140).addBox(-22F, -1F, -1F, 23F, 3F, 3F),
                PartPose.offsetAndRotation(-6F, -12F, 3F, 0F, -0.0872665F, 0.1396263F));
        root.addOrReplaceChild(RMEM1, CubeListBuilder.create().texOffs(10, 170).addBox(-22F, 0F, 0F, 24F, 1F, 21F),
                PartPose.offsetAndRotation(-6F, -12F, 3F, 0F, -0.0872665F, 0.1396263F));
        root.addOrReplaceChild(RWING2, CubeListBuilder.create().texOffs(10, 150).addBox(-43F, -1F, -1F, 44F, 2F, 2F),
                PartPose.offsetAndRotation(-27F, -15F, 1F, 0F, 0F, 0F));
        root.addOrReplaceChild(RMEM2, CubeListBuilder.create().texOffs(10, 195).addBox(-43F, 0F, 0F, 43F, 1F, 21F),
                PartPose.offsetAndRotation(-27F, -15F, 1F, 0F, 0F, 0F));
        root.addOrReplaceChild(RWING3, CubeListBuilder.create().texOffs(10, 160).addBox(-22F, -1F, -1F, 23F, 2F, 2F),
                PartPose.offsetAndRotation(-70F, -15F, 1F, 0F, 0.0872665F, -0.1745329F));
        root.addOrReplaceChild(RMEM3, CubeListBuilder.create().texOffs(10, 220).addBox(-23F, 0F, 0F, 23F, 1F, 21F),
                PartPose.offsetAndRotation(-70F, -15F, 1F, 0F, 0.0872665F, -0.1745329F));
        root.addOrReplaceChild(RWINGCLAW1, CubeListBuilder.create().texOffs(81, 157).addBox(0F, 0F, -9F, 1F, 1F, 8F),
                PartPose.offsetAndRotation(-70F, -15F, 1F, 0F, 0F, 0F));
        root.addOrReplaceChild(RWINGCLAW2, CubeListBuilder.create().texOffs(64, 160).addBox(0F, 0F, -7F, 1F, 1F, 6F),
                PartPose.offsetAndRotation(-70F, -15F, 1F, 0F, -0.6108652F, 0F));
        root.addOrReplaceChild(RWINGCLAW3, CubeListBuilder.create().texOffs(103, 159).addBox(0F, 0F, -6F, 1F, 1F, 5F),
                PartPose.offsetAndRotation(-70F, -15F, 1F, 0F, 0.6108652F, 0F));
    }
}
