// GENERATED by tools/gen_models.py from reference/jar/models/ModelRat.json - do not edit.
package com.swbr.orespawn.client.model.geom;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Geometry of OreSpawn's ModelRat (12 parts), copied unchanged from the 1.7.10 jar.
 * Part order is the order the original constructor created them.
 */
public final class RatGeometry {

    public static final int TEXTURE_WIDTH = 64;
    public static final int TEXTURE_HEIGHT = 64;

    public static final String BODY = "body";
    public static final String TAIL1 = "tail1";
    public static final String TAIL2 = "tail2";
    public static final String LFLEG = "lfleg";
    public static final String RFLEG = "rfleg";
    public static final String LRLEG = "lrleg";
    public static final String RRLEG = "rrleg";
    public static final String BODY2 = "body2";
    public static final String HEAD = "head";
    public static final String NOSE = "nose";
    public static final String LEAR = "lear";
    public static final String REAR = "rear";

    /** Every part in creation order. */
    public static final String[] PARTS = {
            BODY,
            TAIL1,
            TAIL2,
            LFLEG,
            RFLEG,
            LRLEG,
            RRLEG,
            BODY2,
            HEAD,
            NOSE,
            LEAR,
            REAR
    };

    /** Parts the original hid at construction time (showModel = false or isHidden = true). */
    public static final String[] HIDDEN = {};

    private RatGeometry() {}

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild(BODY, CubeListBuilder.create().texOffs(27, 0).addBox(-2F, -1F, 0F, 5F, 3F, 10F),
                PartPose.offsetAndRotation(0F, 20F, -3F, 0F, 0F, 0F));
        root.addOrReplaceChild(TAIL1, CubeListBuilder.create().texOffs(0, 30).addBox(-0.5F, -1F, 0F, 2F, 2F, 9F),
                PartPose.offsetAndRotation(0F, 21F, 7F, 0F, 0F, 0F));
        root.addOrReplaceChild(TAIL2, CubeListBuilder.create().texOffs(0, 43).addBox(0F, 0F, 0F, 1F, 1F, 12F),
                PartPose.offsetAndRotation(0F, 21F, 16F, 0F, 0F, 0F));
        root.addOrReplaceChild(LFLEG, CubeListBuilder.create().texOffs(0, 14).addBox(0F, 0F, 0F, 1F, 2F, 1F),
                PartPose.offsetAndRotation(2F, 22F, -2F, 0F, 0F, 0F));
        root.addOrReplaceChild(RFLEG, CubeListBuilder.create().texOffs(10, 14).addBox(0F, 0F, 0F, 1F, 2F, 1F),
                PartPose.offsetAndRotation(-2F, 22F, -2F, 0F, 0F, 0F));
        root.addOrReplaceChild(LRLEG, CubeListBuilder.create().texOffs(0, 18).addBox(0F, 0F, 0F, 2F, 4F, 2F),
                PartPose.offsetAndRotation(2F, 20F, 4F, 0F, 0F, 0F));
        root.addOrReplaceChild(RRLEG, CubeListBuilder.create().texOffs(9, 18).addBox(0F, 0F, 0F, 2F, 4F, 2F),
                PartPose.offsetAndRotation(-3F, 20F, 4F, 0F, 0F, 0F));
        root.addOrReplaceChild(BODY2, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 1F, 1F, 6F),
                PartPose.offsetAndRotation(0F, 18F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(HEAD, CubeListBuilder.create().texOffs(27, 17).addBox(-1F, -2F, -3F, 3F, 2F, 4F),
                PartPose.offsetAndRotation(0F, 22F, -4F, 0F, 0F, 0F));
        root.addOrReplaceChild(NOSE, CubeListBuilder.create().texOffs(27, 25).addBox(0F, -1F, -5F, 1F, 1F, 2F),
                PartPose.offsetAndRotation(0F, 22F, -4F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEAR, CubeListBuilder.create().texOffs(0, 9).addBox(0F, 0F, 0F, 1F, 1F, 1F),
                PartPose.offsetAndRotation(1.5F, 19.5F, -4F, 0F, 0F, 0F));
        root.addOrReplaceChild(REAR, CubeListBuilder.create().texOffs(5, 9).addBox(0F, 0F, 0F, 1F, 1F, 1F),
                PartPose.offsetAndRotation(-1.5F, 19.5F, -4F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, TEXTURE_WIDTH, TEXTURE_HEIGHT);
    }
}
