// GENERATED by tools/gen_models.py from reference/jar/models/ModelRobot2.json - do not edit.
package com.swbr.orespawn.client.model.geom;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Geometry of OreSpawn's ModelRobot2 (15 parts), copied unchanged from the 1.7.10 jar.
 * Part order is the order the original constructor created them.
 */
public final class Robot2Geometry {

    public static final int TEXTURE_WIDTH = 256;
    public static final int TEXTURE_HEIGHT = 512;

    public static final String RLEG1 = "rleg1";
    public static final String RLEG2 = "rleg2";
    public static final String SHAPE3 = "Shape3";
    public static final String LLEG2 = "lleg2";
    public static final String LLEG1 = "lleg1";
    public static final String SHAPE6 = "Shape6";
    public static final String SHAPE7 = "Shape7";
    public static final String SHAPE8 = "Shape8";
    public static final String RARM3 = "rarm3";
    public static final String RARM2 = "rarm2";
    public static final String RARM1 = "rarm1";
    public static final String LARM3 = "larm3";
    public static final String LARM2 = "larm2";
    public static final String LARM1 = "larm1";
    public static final String HEAD = "head";

    /** Every part in creation order. */
    public static final String[] PARTS = {
            RLEG1,
            RLEG2,
            SHAPE3,
            LLEG2,
            LLEG1,
            SHAPE6,
            SHAPE7,
            SHAPE8,
            RARM3,
            RARM2,
            RARM1,
            LARM3,
            LARM2,
            LARM1,
            HEAD
    };

    /** Parts the original hid at construction time (showModel = false or isHidden = true). */
    public static final String[] HIDDEN = {};

    private Robot2Geometry() {}

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild(RLEG1, CubeListBuilder.create().texOffs(10, 250).addBox(-14F, 24F, -7F, 16F, 24F, 16F),
                PartPose.offsetAndRotation(-10F, -24F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(RLEG2, CubeListBuilder.create().texOffs(10, 150).addBox(-12F, 0F, -6F, 12F, 24F, 12F),
                PartPose.offsetAndRotation(-10F, -24F, 1F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE3, CubeListBuilder.create().texOffs(10, 50).addBox(-4F, 0F, -2F, 26F, 8F, 12F),
                PartPose.offsetAndRotation(-9F, -32F, -3F, 0F, 0F, 0F));
        root.addOrReplaceChild(LLEG2, CubeListBuilder.create().texOffs(10, 200).addBox(0F, 0F, -6F, 12F, 24F, 12F),
                PartPose.offsetAndRotation(10F, -24F, 1F, 0F, 0F, 0F));
        root.addOrReplaceChild(LLEG1, CubeListBuilder.create().texOffs(10, 300).addBox(-2F, 24F, -7F, 16F, 24F, 16F),
                PartPose.offsetAndRotation(10F, -24F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE6, CubeListBuilder.create().texOffs(10, 100).addBox(-4F, -8F, -3F, 8F, 8F, 8F),
                PartPose.offsetAndRotation(0F, -32F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE7, CubeListBuilder.create().texOffs(10, 350).addBox(0F, 0F, 0F, 26F, 8F, 12F),
                PartPose.offsetAndRotation(-13F, -48F, -5F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE8, CubeListBuilder.create().texOffs(16, 400).addBox(0F, 0F, 0F, 44F, 18F, 14F),
                PartPose.offsetAndRotation(-22F, -66F, -6F, 0F, 0F, 0F));
        root.addOrReplaceChild(RARM3, CubeListBuilder.create().texOffs(100, 100).addBox(-16F, -16F, -7F, 16F, 24F, 17F),
                PartPose.offsetAndRotation(-22F, -58F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(RARM2, CubeListBuilder.create().texOffs(100, 200).addBox(-14F, 8F, -5F, 12F, 24F, 12F),
                PartPose.offsetAndRotation(-22F, -58F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(RARM1, CubeListBuilder.create().texOffs(100, 300).addBox(-14F, 32F, -5F, 12F, 24F, 12F),
                PartPose.offsetAndRotation(-22F, -58F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(LARM3, CubeListBuilder.create().texOffs(100, 50).addBox(0F, -16F, -7F, 16F, 24F, 17F),
                PartPose.offsetAndRotation(22F, -58F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(LARM2, CubeListBuilder.create().texOffs(100, 150).addBox(2F, 8F, -5F, 12F, 24F, 12F),
                PartPose.offsetAndRotation(21F, -58F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(LARM1, CubeListBuilder.create().texOffs(100, 250).addBox(2F, 32F, -5F, 12F, 24F, 12F),
                PartPose.offsetAndRotation(21F, -58F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(HEAD, CubeListBuilder.create().texOffs(50, 10).addBox(-7F, -12F, -5F, 15F, 12F, 10F),
                PartPose.offsetAndRotation(0F, -66F, 1F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, TEXTURE_WIDTH, TEXTURE_HEIGHT);
    }
}
