// GENERATED by tools/gen_models.py from reference/jar/models/ModelRobot4.json - do not edit.
package com.swbr.orespawn.client.model.geom;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Geometry of OreSpawn's ModelRobot4 (56 parts), copied unchanged from the 1.7.10 jar.
 * Part order is the order the original constructor created them.
 */
public final class Robot4Geometry {

    public static final int TEXTURE_WIDTH = 512;
    public static final int TEXTURE_HEIGHT = 512;

    public static final String LEFTFOOTFRONT = "leftfootfront";
    public static final String LEFTFOOTBASE = "leftfootbase";
    public static final String LEFTFOOTBACK = "leftfootback";
    public static final String LEFTFOOTTIP = "leftfoottip";
    public static final String LEFTSHIN = "leftshin";
    public static final String LEFTCALF = "leftcalf";
    public static final String LEFTKNEEGAURD = "leftkneegaurd";
    public static final String LEFTTHIGH = "leftthigh";
    public static final String RIGHTFOOTFRONT = "rightfootfront";
    public static final String RIGHTFOOTTIP = "rightfoottip";
    public static final String RIGHTFOOTBASE = "rightfootbase";
    public static final String RIGHTFOOTBACK = "rightfootback";
    public static final String RIGHTSHIN = "rightshin";
    public static final String RIGHTCALF = "rightcalf";
    public static final String RIGHTKNEEGAURD = "rightkneegaurd";
    public static final String RIGHTTHIGH = "rightthigh";
    public static final String HIPS = "hips";
    public static final String STOMACH = "stomach";
    public static final String CHEST = "chest";
    public static final String NECK = "neck";
    public static final String HEAD = "head";
    public static final String RIGHTTOPSPINEBASE = "righttopspinebase";
    public static final String LEFTTOPSPINEBASE = "lefttopspinebase";
    public static final String RIGHTTOPSPINETIP = "righttopspinetip";
    public static final String LEFTTOPSPINETIP = "lefttopspinetip";
    public static final String MIDDLERIGHTSPINEBASE = "middlerightspinebase";
    public static final String MIDDLELEFTSPINEBASE = "middleleftspinebase";
    public static final String MIDDLELEFTSPINETIP = "middleleftspinetip";
    public static final String MIDDLERIGHTSPINETIP = "middlerightspinetip";
    public static final String TORSO = "torso";
    public static final String RIGHTSHOLDER = "rightsholder";
    public static final String LEFTSHOLDER = "leftsholder";
    public static final String RIGHTSHOLDERGAURD = "rightsholdergaurd";
    public static final String SHEILDBASE = "sheildbase";
    public static final String SHEILDTIP = "sheildtip";
    public static final String RIGHTUPPERARM = "rightupperarm";
    public static final String RIGHTLOWERARM = "rightlowerarm";
    public static final String SHEILDEND = "sheildend";
    public static final String LEFTUPPERARM = "leftupperarm";
    public static final String SHOLDERGAURDTIP = "sholdergaurdtip";
    public static final String CANNONBASE = "cannonbase";
    public static final String CANNONEND = "cannonend";
    public static final String LEFTCANNONPIECE = "leftcannonpiece";
    public static final String TOPCANNONPIECE = "topcannonpiece";
    public static final String RIGHTCANNONPIECE = "rightcannonpiece";
    public static final String BOTTOMCANNONPIECE = "bottomcannonpiece";
    public static final String GLOWYCANNONBIT1 = "glowycannonbit1";
    public static final String GLOWYCANNONBIT2 = "glowycannonbit2";
    public static final String GLOWYCANNONBIT3 = "glowycannonbit3";
    public static final String GLOWYCANNONBIT4 = "glowycannonbit4";
    public static final String GLOWYCANNONBIT5 = "glowycannonbit5";
    public static final String CANNONAMMO = "cannonammo";
    public static final String LOWERRIGHTSPINEBASE = "lowerrightspinebase";
    public static final String LOWERLEFTSPINEBASE = "lowerleftspinebase";
    public static final String LOWERRIGHTSPINETIP = "lowerrightspinetip";
    public static final String LOWERLEFTSPINETIP = "lowerleftspinetip";

    /** Every part in creation order. */
    public static final String[] PARTS = {
            LEFTFOOTFRONT,
            LEFTFOOTBASE,
            LEFTFOOTBACK,
            LEFTFOOTTIP,
            LEFTSHIN,
            LEFTCALF,
            LEFTKNEEGAURD,
            LEFTTHIGH,
            RIGHTFOOTFRONT,
            RIGHTFOOTTIP,
            RIGHTFOOTBASE,
            RIGHTFOOTBACK,
            RIGHTSHIN,
            RIGHTCALF,
            RIGHTKNEEGAURD,
            RIGHTTHIGH,
            HIPS,
            STOMACH,
            CHEST,
            NECK,
            HEAD,
            RIGHTTOPSPINEBASE,
            LEFTTOPSPINEBASE,
            RIGHTTOPSPINETIP,
            LEFTTOPSPINETIP,
            MIDDLERIGHTSPINEBASE,
            MIDDLELEFTSPINEBASE,
            MIDDLELEFTSPINETIP,
            MIDDLERIGHTSPINETIP,
            TORSO,
            RIGHTSHOLDER,
            LEFTSHOLDER,
            RIGHTSHOLDERGAURD,
            SHEILDBASE,
            SHEILDTIP,
            RIGHTUPPERARM,
            RIGHTLOWERARM,
            SHEILDEND,
            LEFTUPPERARM,
            SHOLDERGAURDTIP,
            CANNONBASE,
            CANNONEND,
            LEFTCANNONPIECE,
            TOPCANNONPIECE,
            RIGHTCANNONPIECE,
            BOTTOMCANNONPIECE,
            GLOWYCANNONBIT1,
            GLOWYCANNONBIT2,
            GLOWYCANNONBIT3,
            GLOWYCANNONBIT4,
            GLOWYCANNONBIT5,
            CANNONAMMO,
            LOWERRIGHTSPINEBASE,
            LOWERLEFTSPINEBASE,
            LOWERRIGHTSPINETIP,
            LOWERLEFTSPINETIP
    };

    /** Parts the original hid at construction time (showModel = false or isHidden = true). */
    public static final String[] HIDDEN = {};

    private Robot4Geometry() {}

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild(LEFTFOOTFRONT, CubeListBuilder.create().texOffs(20, 50).addBox(-6F, 22F, -9F, 8F, 5F, 7F),
                PartPose.offsetAndRotation(-8F, -3F, 6F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEFTFOOTBASE, CubeListBuilder.create().texOffs(20, 100).addBox(-4F, 22F, -4F, 4F, 5F, 5F),
                PartPose.offsetAndRotation(-8F, -3F, 6F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEFTFOOTBACK, CubeListBuilder.create().texOffs(20, 150).addBox(-4.5F, 22F, 1F, 5F, 5F, 4F),
                PartPose.offsetAndRotation(-8F, -3F, 6F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEFTFOOTTIP, CubeListBuilder.create().texOffs(20, 200).addBox(-4.5F, 23F, -12F, 5F, 4F, 3F),
                PartPose.offsetAndRotation(-8F, -3F, 6F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEFTSHIN, CubeListBuilder.create().texOffs(20, 250).addBox(-5F, 10F, -9F, 6F, 13F, 6F),
                PartPose.offsetAndRotation(-8F, -3F, 6F, 0.1745329F, 0F, 0F));
        root.addOrReplaceChild(LEFTCALF, CubeListBuilder.create().texOffs(20, 300).addBox(-6F, 10F, -9F, 8F, 8F, 9F),
                PartPose.offsetAndRotation(-8F, -3F, 6F, 0.1745329F, 0F, 0F));
        root.addOrReplaceChild(LEFTKNEEGAURD, CubeListBuilder.create().texOffs(20, 350).addBox(-5.5F, 4F, -14F, 7F, 7F, 1F),
                PartPose.offsetAndRotation(-8F, -3F, 6F, 0.6283185F, 0F, 0F));
        root.addOrReplaceChild(LEFTTHIGH, CubeListBuilder.create().texOffs(20, 400).addBox(-5F, 0F, -4F, 6F, 13F, 8F),
                PartPose.offsetAndRotation(-8F, -3F, 6F, -0.1745329F, 0.1745329F, 0F));
        root.addOrReplaceChild(RIGHTFOOTFRONT, CubeListBuilder.create().texOffs(20, 450).addBox(0F, 22F, -9F, 8F, 5F, 7F),
                PartPose.offsetAndRotation(5F, -3F, 6F, 0F, 0F, 0F));
        root.addOrReplaceChild(RIGHTFOOTTIP, CubeListBuilder.create().texOffs(100, 50).addBox(1.5F, 23F, -12F, 5F, 4F, 3F),
                PartPose.offsetAndRotation(5F, -3F, 6F, 0F, 0F, 0F));
        root.addOrReplaceChild(RIGHTFOOTBASE, CubeListBuilder.create().texOffs(100, 150).addBox(2F, 22F, -4F, 4F, 5F, 5F),
                PartPose.offsetAndRotation(5F, -3F, 6F, 0F, 0F, 0F));
        root.addOrReplaceChild(RIGHTFOOTBACK, CubeListBuilder.create().texOffs(100, 100).addBox(1.5F, 22F, 1F, 5F, 5F, 4F),
                PartPose.offsetAndRotation(5F, -3F, 6F, 0F, 0F, 0F));
        root.addOrReplaceChild(RIGHTSHIN, CubeListBuilder.create().texOffs(100, 200).addBox(1F, 10F, -9F, 6F, 13F, 6F),
                PartPose.offsetAndRotation(5F, -3F, 6F, 0.1745329F, 0F, 0F));
        root.addOrReplaceChild(RIGHTCALF, CubeListBuilder.create().texOffs(100, 250).addBox(0F, 10F, -10F, 8F, 8F, 9F),
                PartPose.offsetAndRotation(5F, -3F, 6F, 0.1745329F, 0F, 0F));
        root.addOrReplaceChild(RIGHTKNEEGAURD, CubeListBuilder.create().texOffs(100, 300).addBox(0.5F, 4F, -15F, 7F, 7F, 1F),
                PartPose.offsetAndRotation(5F, -3F, 6F, 0.6283185F, 0F, 0F));
        root.addOrReplaceChild(RIGHTTHIGH, CubeListBuilder.create().texOffs(100, 400).addBox(0F, 0F, -5F, 6F, 13F, 8F),
                PartPose.offsetAndRotation(5F, -3F, 6F, -0.1745329F, -0.1745329F, 0F));
        root.addOrReplaceChild(HIPS, CubeListBuilder.create().texOffs(100, 350).addBox(0F, 0F, 0F, 14F, 7F, 8F),
                PartPose.offsetAndRotation(-8F, -3F, 2F, 0.1396263F, 0F, 0F));
        root.addOrReplaceChild(STOMACH, CubeListBuilder.create().texOffs(100, 450).addBox(0F, 0F, 0F, 12F, 6F, 7F),
                PartPose.offsetAndRotation(-7F, -9F, 2F, 0.1396263F, 0F, 0F));
        root.addOrReplaceChild(CHEST, CubeListBuilder.create().texOffs(200, 50).addBox(0F, 0F, 0F, 18F, 12F, 13F),
                PartPose.offsetAndRotation(-10F, -23F, -4F, 0.2443461F, 0F, 0F));
        root.addOrReplaceChild(NECK, CubeListBuilder.create().texOffs(200, 100).addBox(0F, 0F, 0F, 6F, 7F, 6F),
                PartPose.offsetAndRotation(-4F, -22F, -7F, 0.8726646F, 0F, 0F));
        root.addOrReplaceChild(HEAD, CubeListBuilder.create().texOffs(200, 150).addBox(-3F, -3F, -5F, 6F, 6F, 8F),
                PartPose.offsetAndRotation(-1F, -26F, -5F, 0.5235988F, 0F, 0F));
        root.addOrReplaceChild(RIGHTTOPSPINEBASE, CubeListBuilder.create().texOffs(200, 200).addBox(0F, 0F, 0F, 2F, 8F, 2F),
                PartPose.offsetAndRotation(3F, -29F, 5F, -0.1396263F, 0F, 0F));
        root.addOrReplaceChild(LEFTTOPSPINEBASE, CubeListBuilder.create().texOffs(200, 250).addBox(0F, 0F, 0F, 2F, 8F, 2F),
                PartPose.offsetAndRotation(-7F, -29F, 5F, -0.1396263F, 0F, 0F));
        root.addOrReplaceChild(RIGHTTOPSPINETIP, CubeListBuilder.create().texOffs(200, 300).addBox(0F, 0F, 0F, 1F, 8F, 1F),
                PartPose.offsetAndRotation(3.5F, -35F, 8F, -0.3316126F, 0F, 0F));
        root.addOrReplaceChild(LEFTTOPSPINETIP, CubeListBuilder.create().texOffs(200, 350).addBox(0F, 0F, 0F, 1F, 8F, 1F),
                PartPose.offsetAndRotation(-6.5F, -35F, 8F, -0.3316126F, 0F, 0F));
        root.addOrReplaceChild(MIDDLERIGHTSPINEBASE, CubeListBuilder.create().texOffs(200, 400).addBox(0F, 0F, 0F, 2F, 8F, 2F),
                PartPose.offsetAndRotation(-6F, -25F, 14F, -0.6981317F, 0F, 0F));
        root.addOrReplaceChild(MIDDLELEFTSPINEBASE, CubeListBuilder.create().texOffs(200, 450).addBox(0F, 0F, 0F, 2F, 8F, 2F),
                PartPose.offsetAndRotation(2F, -25F, 14F, -0.6981317F, 0F, 0F));
        root.addOrReplaceChild(MIDDLELEFTSPINETIP, CubeListBuilder.create().texOffs(300, 50).addBox(0F, 0F, 0F, 1F, 7F, 1F),
                PartPose.offsetAndRotation(2.5F, -28F, 18F, -0.7853982F, 0F, 0F));
        root.addOrReplaceChild(MIDDLERIGHTSPINETIP, CubeListBuilder.create().texOffs(300, 100).addBox(0F, 0F, 0F, 1F, 7F, 1F),
                PartPose.offsetAndRotation(-5.5F, -28F, 18F, -0.7853982F, 0F, 0F));
        root.addOrReplaceChild(TORSO, CubeListBuilder.create().texOffs(300, 150).addBox(0F, 0F, 0F, 14F, 6F, 10F),
                PartPose.offsetAndRotation(-8F, -13F, 0F, 0.1396263F, 0F, 0F));
        root.addOrReplaceChild(RIGHTSHOLDER, CubeListBuilder.create().texOffs(300, 200).addBox(0F, -3F, -3F, 6F, 6F, 6F),
                PartPose.offsetAndRotation(7F, -18F, 4F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEFTSHOLDER, CubeListBuilder.create().texOffs(300, 250).addBox(-6F, -3F, -3F, 6F, 6F, 6F),
                PartPose.offsetAndRotation(-9F, -18F, 4F, 0F, 0F, 0F));
        root.addOrReplaceChild(RIGHTSHOLDERGAURD, CubeListBuilder.create().texOffs(300, 300).addBox(8F, -4F, -4F, 4F, 12F, 9F),
                PartPose.offsetAndRotation(7F, -18F, 4F, -0.2094395F, 0F, 0F));
        root.addOrReplaceChild(SHEILDBASE, CubeListBuilder.create().texOffs(300, 350).addBox(8F, -4F, -30F, 3F, 12F, 19F),
                PartPose.offsetAndRotation(7F, -18F, 4F, 1.047198F, 0F, 0F));
        root.addOrReplaceChild(SHEILDTIP, CubeListBuilder.create().texOffs(300, 400).addBox(9F, -2F, -34F, 3F, 8F, 4F),
                PartPose.offsetAndRotation(6F, -18F, 4F, 1.047198F, 0F, 0F));
        root.addOrReplaceChild(RIGHTUPPERARM, CubeListBuilder.create().texOffs(300, 450).addBox(3F, -1F, -4F, 6F, 13F, 6F),
                PartPose.offsetAndRotation(7F, -18F, 4F, -0.2094395F, 0F, 0F));
        root.addOrReplaceChild(RIGHTLOWERARM, CubeListBuilder.create().texOffs(350, 50).addBox(3F, 0F, -25F, 6F, 6F, 14F),
                PartPose.offsetAndRotation(7F, -18F, 4F, 1.047198F, 0F, 0F));
        root.addOrReplaceChild(SHEILDEND, CubeListBuilder.create().texOffs(350, 100).addBox(8F, -1F, -11F, 3F, 8F, 4F),
                PartPose.offsetAndRotation(7F, -18F, 4F, 1.047198F, 0F, 0F));
        root.addOrReplaceChild(LEFTUPPERARM, CubeListBuilder.create().texOffs(350, 200).addBox(-9F, -1F, -4F, 6F, 15F, 6F),
                PartPose.offsetAndRotation(-9F, -18F, 4F, -0.2094395F, 0F, 0F));
        root.addOrReplaceChild(SHOLDERGAURDTIP, CubeListBuilder.create().texOffs(350, 250).addBox(10F, -3F, -7F, 2F, 5F, 3F),
                PartPose.offsetAndRotation(7F, -18F, 4F, -0.2094395F, 0F, 0F));
        root.addOrReplaceChild(CANNONBASE, CubeListBuilder.create().texOffs(350, 300).addBox(-4F, 0F, -4F, 8F, 12F, 8F),
                PartPose.offsetAndRotation(-15F, -5F, 1F, -0.6981317F, 0F, 0F));
        root.addOrReplaceChild(CANNONEND, CubeListBuilder.create().texOffs(350, 400).addBox(-3F, 11F, -3F, 6F, 4F, 6F),
                PartPose.offsetAndRotation(-15F, -5F, 1F, -0.6981317F, 0F, 0F));
        root.addOrReplaceChild(LEFTCANNONPIECE, CubeListBuilder.create().texOffs(20, 20).addBox(-5F, 11F, -1.5F, 3F, 6F, 3F),
                PartPose.offsetAndRotation(-15F, -5F, 1F, -0.6981317F, 0F, 0F));
        root.addOrReplaceChild(TOPCANNONPIECE, CubeListBuilder.create().texOffs(40, 20).addBox(-1.5F, 11F, -5F, 3F, 6F, 3F),
                PartPose.offsetAndRotation(-15F, -5F, 1F, -0.6981317F, 0F, 0F));
        root.addOrReplaceChild(RIGHTCANNONPIECE, CubeListBuilder.create().texOffs(80, 20).addBox(2F, 11F, -1.5F, 3F, 6F, 3F),
                PartPose.offsetAndRotation(-15F, -5F, 1F, -0.6981317F, 0F, 0F));
        root.addOrReplaceChild(BOTTOMCANNONPIECE, CubeListBuilder.create().texOffs(100, 20).addBox(-1.5F, 11F, 2F, 3F, 6F, 3F),
                PartPose.offsetAndRotation(-15F, -5F, 1F, -0.6981317F, 0F, 0F));
        root.addOrReplaceChild(GLOWYCANNONBIT1, CubeListBuilder.create().texOffs(150, 20).addBox(-3.5F, 0F, -11F, 2F, 5F, 2F),
                PartPose.offsetAndRotation(-15F, -5F, 1F, 0.1745329F, 0F, 0F));
        root.addOrReplaceChild(GLOWYCANNONBIT2, CubeListBuilder.create().texOffs(200, 20).addBox(1.5F, 0F, -11F, 2F, 5F, 2F),
                PartPose.offsetAndRotation(-15F, -5F, 1F, 0.1745329F, 0F, 0F));
        root.addOrReplaceChild(GLOWYCANNONBIT3, CubeListBuilder.create().texOffs(250, 20).addBox(-3F, -2F, -8F, 2F, 5F, 2F),
                PartPose.offsetAndRotation(-15F, -5F, 1F, 0.0872665F, 0F, 0F));
        root.addOrReplaceChild(GLOWYCANNONBIT4, CubeListBuilder.create().texOffs(300, 20).addBox(1F, -2F, -8F, 2F, 5F, 2F),
                PartPose.offsetAndRotation(-15F, -5F, 1F, 0.0872665F, 0F, 0F));
        root.addOrReplaceChild(GLOWYCANNONBIT5, CubeListBuilder.create().texOffs(350, 20).addBox(-1F, -5F, -5F, 2F, 5F, 2F),
                PartPose.offsetAndRotation(-15F, -5F, 1F, 0F, 0F, 0F));
        root.addOrReplaceChild(CANNONAMMO, CubeListBuilder.create().texOffs(400, 400).addBox(-6F, 3F, 0F, 5F, 5F, 5F),
                PartPose.offsetAndRotation(-15F, -5F, 1F, -0.6981317F, 0F, 0F));
        root.addOrReplaceChild(LOWERRIGHTSPINEBASE, CubeListBuilder.create().texOffs(400, 450).addBox(0F, 0F, 0F, 2F, 8F, 2F),
                PartPose.offsetAndRotation(4F, -19F, 15F, -1.047198F, 0F, 0F));
        root.addOrReplaceChild(LOWERLEFTSPINEBASE, CubeListBuilder.create().texOffs(360, 450).addBox(0F, 0F, 0F, 2F, 8F, 2F),
                PartPose.offsetAndRotation(-8F, -19F, 15F, -1.047198F, 0F, 0F));
        root.addOrReplaceChild(LOWERRIGHTSPINETIP, CubeListBuilder.create().texOffs(250, 100).addBox(0F, 0F, 0F, 1F, 7F, 1F),
                PartPose.offsetAndRotation(4.5F, -21F, 20F, -1.134464F, 0F, 0F));
        root.addOrReplaceChild(LOWERLEFTSPINETIP, CubeListBuilder.create().texOffs(150, 100).addBox(0F, 0F, 0F, 1F, 7F, 1F),
                PartPose.offsetAndRotation(-7.5F, -21F, 20F, -1.134464F, 0F, 0F));
        return LayerDefinition.create(mesh, TEXTURE_WIDTH, TEXTURE_HEIGHT);
    }
}
