// GENERATED by tools/gen_models.py from reference/jar/models/ModelRobot1.json - do not edit.
package com.swbr.orespawn.client.model.geom;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Geometry of OreSpawn's ModelRobot1 (27 parts), copied unchanged from the 1.7.10 jar.
 * Part order is the order the original constructor created them.
 */
public final class Robot1Geometry {

    public static final int TEXTURE_WIDTH = 64;
    public static final int TEXTURE_HEIGHT = 32;

    public static final String SHAPE1 = "Shape1";
    public static final String SHAPE2 = "Shape2";
    public static final String SHAPE2A = "Shape2a";
    public static final String SHAPE3 = "Shape3";
    public static final String SHAPE4 = "Shape4";
    public static final String SHAPE5 = "Shape5";
    public static final String SHAPE6 = "Shape6";
    public static final String SHAPE7 = "Shape7";
    public static final String SHAPE8 = "Shape8";
    public static final String SHAPE9 = "Shape9";
    public static final String SHAPE10 = "Shape10";
    public static final String SHAPE11 = "Shape11";
    public static final String SHAPE12 = "Shape12";
    public static final String SHAPE13 = "Shape13";
    public static final String SHAPE14 = "Shape14";
    public static final String SHAPE15 = "Shape15";
    public static final String SHAPE15A = "Shape15a";
    public static final String SHAPE16 = "Shape16";
    public static final String SHAPE17 = "Shape17";
    public static final String SHAPE18 = "Shape18";
    public static final String RFOOT = "rfoot";
    public static final String LFOOT = "lfoot";
    public static final String KEY2 = "key2";
    public static final String KEY1 = "key1";
    public static final String KEY3 = "key3";
    public static final String KEY4 = "key4";
    public static final String KEY5 = "key5";

    /** Every part in creation order. */
    public static final String[] PARTS = {
            SHAPE1,
            SHAPE2,
            SHAPE2A,
            SHAPE3,
            SHAPE4,
            SHAPE5,
            SHAPE6,
            SHAPE7,
            SHAPE8,
            SHAPE9,
            SHAPE10,
            SHAPE11,
            SHAPE12,
            SHAPE13,
            SHAPE14,
            SHAPE15,
            SHAPE15A,
            SHAPE16,
            SHAPE17,
            SHAPE18,
            RFOOT,
            LFOOT,
            KEY2,
            KEY1,
            KEY3,
            KEY4,
            KEY5
    };

    /** Parts the original hid at construction time (showModel = false or isHidden = true). */
    public static final String[] HIDDEN = {};

    private Robot1Geometry() {}

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild(SHAPE1, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 3F, 9F, 3F),
                PartPose.offsetAndRotation(-1F, 13F, -1F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE2, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 1F, 9F, 5F),
                PartPose.offsetAndRotation(0F, 13F, -2F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE2A, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 5F, 9F, 1F),
                PartPose.offsetAndRotation(-2F, 13F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE3, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 7F, 7F, 3F),
                PartPose.offsetAndRotation(-3F, 14F, -1F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE4, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 3F, 7F, 7F),
                PartPose.offsetAndRotation(-1F, 14F, -3F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE5, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 5F, 7F, 5F),
                PartPose.offsetAndRotation(-2F, 14F, -2F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE6, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 5F, 5F, 7F),
                PartPose.offsetAndRotation(-2F, 15F, -3F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE7, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 1F, 5F, 1F),
                PartPose.offsetAndRotation(0F, 15F, 4F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE8, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 7F, 5F, 5F),
                PartPose.offsetAndRotation(-3F, 15F, -2F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE9, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 9F, 5F, 1F),
                PartPose.offsetAndRotation(-4F, 15F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE10, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 1F, 3F, 3F, 8F),
                PartPose.offsetAndRotation(-1F, 16F, -4F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE11, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 9F, 3F, 3F),
                PartPose.offsetAndRotation(-4F, 16F, -1F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE12, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 7F, 3F, 7F),
                PartPose.offsetAndRotation(-3F, 16F, -3F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE13, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 9F, 1F, 5F),
                PartPose.offsetAndRotation(-4F, 17F, -2F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE14, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 5F, 1F, 1F),
                PartPose.offsetAndRotation(-2F, 17F, 4F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE15, CubeListBuilder.create().texOffs(32, 0).addBox(0F, 0F, 0F, 2F, 3F, 1F),
                PartPose.offsetAndRotation(-2F, 15F, -4F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE15A, CubeListBuilder.create().texOffs(32, 0).addBox(0F, 0F, 0F, 2F, 3F, 1F),
                PartPose.offsetAndRotation(1F, 15F, -4F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE16, CubeListBuilder.create().texOffs(45, 0).addBox(0F, 0F, 0F, 3F, 1F, 3F),
                PartPose.offsetAndRotation(-1F, 12F, -1F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE17, CubeListBuilder.create().texOffs(33, 7).addBox(0F, 0F, 0F, 1F, 2F, 1F),
                PartPose.offsetAndRotation(0F, 10F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(SHAPE18, CubeListBuilder.create().texOffs(33, 7).addBox(0F, 0F, 0F, 1F, 2F, 1F),
                PartPose.offsetAndRotation(1.7F, 8.733334F, 0F, 0F, 0F, 0.9667472F));
        root.addOrReplaceChild(RFOOT, CubeListBuilder.create().texOffs(46, 8).addBox(0F, 3F, -2F, 2F, 2F, 4F),
                PartPose.offsetAndRotation(-3F, 19F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(LFOOT, CubeListBuilder.create().texOffs(46, 8).addBox(0F, 3F, -2F, 2F, 2F, 4F),
                PartPose.offsetAndRotation(2F, 19F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(KEY2, CubeListBuilder.create().texOffs(46, 8).addBox(-0.5F, -1.5F, 1F, 1F, 3F, 1F),
                PartPose.offsetAndRotation(0.5F, 17.5F, 5F, 0F, 0F, 0F));
        root.addOrReplaceChild(KEY1, CubeListBuilder.create().texOffs(46, 8).addBox(-0.5F, -0.5F, 0F, 1F, 1F, 3F),
                PartPose.offsetAndRotation(0.5F, 17.5F, 5F, 0F, 0F, 0F));
        root.addOrReplaceChild(KEY3, CubeListBuilder.create().texOffs(46, 8).addBox(-0.5F, -2.5F, 1F, 1F, 1F, 2F),
                PartPose.offsetAndRotation(0.5F, 17.5F, 5F, 0F, 0F, 0F));
        root.addOrReplaceChild(KEY4, CubeListBuilder.create().texOffs(46, 8).addBox(-0.5F, 1.5F, 1F, 1F, 1F, 2F),
                PartPose.offsetAndRotation(0.5F, 17.5F, 5F, 0F, 0F, 0F));
        root.addOrReplaceChild(KEY5, CubeListBuilder.create().texOffs(46, 8).addBox(-0.5F, -1.5F, 3F, 1F, 3F, 1F),
                PartPose.offsetAndRotation(0.5F, 17.5F, 5F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, TEXTURE_WIDTH, TEXTURE_HEIGHT);
    }
}
