// GENERATED by tools/gen_models.py from reference/jar/models/ModelSeaMonster.json - do not edit.
package com.swbr.orespawn.client.model.geom;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Geometry of OreSpawn's ModelSeaMonster (23 parts), copied unchanged from the 1.7.10 jar.
 * Part order is the order the original constructor created them.
 */
public final class SeaMonsterGeometry {

    public static final int TEXTURE_WIDTH = 256;
    public static final int TEXTURE_HEIGHT = 128;

    public static final String TAIL_TIP = "TailTip";
    public static final String TAIL_BASE = "TailBase";
    public static final String TAIL2 = "Tail2";
    public static final String TAIL3 = "Tail3";
    public static final String BODY_BACK = "BodyBack";
    public static final String NECK6 = "Neck6";
    public static final String BODY_FRONT = "BodyFront";
    public static final String NECK_BASE = "NeckBase";
    public static final String NECK2 = "Neck2";
    public static final String NECK3 = "Neck3";
    public static final String NECK4 = "Neck4";
    public static final String NECK5 = "Neck5";
    public static final String BOTTOM_JAW = "BottomJaw";
    public static final String FIN_BACK_RIGHT = "FinBackRight";
    public static final String FIN_BACK_LEFT = "FinBackLeft";
    public static final String FIN_FRONT_LEFT = "FinFrontLeft";
    public static final String FIN_FRONT_RIGHT = "FinFrontRight";
    public static final String TAIL4 = "Tail4";
    public static final String TAIL5 = "Tail5";
    public static final String TAIL6 = "Tail6";
    public static final String TOP_JAW = "TopJaw";
    public static final String RIGHT_EYE = "RightEye";
    public static final String LEFT_EYE = "LeftEye";

    /** Every part in creation order. */
    public static final String[] PARTS = {
            TAIL_TIP,
            TAIL_BASE,
            TAIL2,
            TAIL3,
            BODY_BACK,
            NECK6,
            BODY_FRONT,
            NECK_BASE,
            NECK2,
            NECK3,
            NECK4,
            NECK5,
            BOTTOM_JAW,
            FIN_BACK_RIGHT,
            FIN_BACK_LEFT,
            FIN_FRONT_LEFT,
            FIN_FRONT_RIGHT,
            TAIL4,
            TAIL5,
            TAIL6,
            TOP_JAW,
            RIGHT_EYE,
            LEFT_EYE
    };

    /** Parts the original hid at construction time (showModel = false or isHidden = true). */
    public static final String[] HIDDEN = {};

    private SeaMonsterGeometry() {}

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild(TAIL_TIP, CubeListBuilder.create().texOffs(158, 36).addBox(-1F, -1F, 0F, 2F, 2F, 6F),
                PartPose.offsetAndRotation(0F, 16F, 70F, 0F, 0F, 0F));
        root.addOrReplaceChild(TAIL_BASE, CubeListBuilder.create().texOffs(68, 64).addBox(-7F, -7F, 0F, 14F, 14F, 12F),
                PartPose.offsetAndRotation(0F, 16F, 26F, 0F, 0F, 0F));
        root.addOrReplaceChild(TAIL2, CubeListBuilder.create().texOffs(74, 90).addBox(-6F, -6F, 0F, 12F, 12F, 8F),
                PartPose.offsetAndRotation(0F, 16F, 38F, 0F, 0F, 0F));
        root.addOrReplaceChild(TAIL3, CubeListBuilder.create().texOffs(78, 110).addBox(-5F, -5F, 0F, 10F, 10F, 6F),
                PartPose.offsetAndRotation(0F, 16F, 46F, 0F, 0F, 0F));
        root.addOrReplaceChild(BODY_BACK, CubeListBuilder.create().texOffs(62, 32).addBox(-8F, -8F, 0F, 16F, 16F, 16F),
                PartPose.offsetAndRotation(0F, 16F, 10F, 0F, 0F, 0F));
        root.addOrReplaceChild(NECK6, CubeListBuilder.create().texOffs(20, 28).addBox(-2F, -6F, -2F, 4F, 6F, 4F),
                PartPose.offsetAndRotation(0F, -21F, -25F, 1.22173F, 0F, 0F));
        root.addOrReplaceChild(BODY_FRONT, CubeListBuilder.create().texOffs(62, 0).addBox(-8F, -8F, -16F, 16F, 16F, 16F),
                PartPose.offsetAndRotation(0F, 16F, 10F, 0F, 0F, 0F));
        root.addOrReplaceChild(NECK_BASE, CubeListBuilder.create().texOffs(8, 96).addBox(-5F, -10F, -5F, 10F, 10F, 10F),
                PartPose.offsetAndRotation(0F, 12F, -2F, 0.7853982F, 0F, 0F));
        root.addOrReplaceChild(NECK2, CubeListBuilder.create().texOffs(14, 78).addBox(-3F, -10F, -4F, 6F, 10F, 8F),
                PartPose.offsetAndRotation(0F, 6F, -9F, 0.6981317F, 0F, 0F));
        root.addOrReplaceChild(NECK3, CubeListBuilder.create().texOffs(16, 62).addBox(-3F, -10F, -3F, 6F, 10F, 6F),
                PartPose.offsetAndRotation(0F, -1F, -15F, 0.5235988F, 0F, 0F));
        root.addOrReplaceChild(NECK4, CubeListBuilder.create().texOffs(20, 48).addBox(-2F, -10F, -2F, 4F, 10F, 4F),
                PartPose.offsetAndRotation(0F, -9F, -20F, 0.2617994F, 0F, 0F));
        root.addOrReplaceChild(NECK5, CubeListBuilder.create().texOffs(20, 38).addBox(-2F, -6F, -2F, 4F, 6F, 4F),
                PartPose.offsetAndRotation(0F, -17.6F, -22F, 0.7853982F, 0F, 0F));
        root.addOrReplaceChild(BOTTOM_JAW, CubeListBuilder.create().texOffs(10, 0).addBox(-4F, 0F, -10F, 8F, 3F, 10F),
                PartPose.offsetAndRotation(0F, -23F, -29F, 0.1745329F, 0F, 0F));
        root.addOrReplaceChild(FIN_BACK_RIGHT, CubeListBuilder.create().texOffs(132, 95).addBox(-8F, 0F, 0F, 8F, 1F, 16F),
                PartPose.offsetAndRotation(-7F, 16F, 16F, -0.5235988F, -0.6981317F, 0F));
        root.addOrReplaceChild(FIN_BACK_LEFT, CubeListBuilder.create().texOffs(132, 61).addBox(0F, 0F, 0F, 8F, 1F, 16F),
                PartPose.offsetAndRotation(7F, 16F, 16F, -0.5235988F, 0.6981317F, 0F));
        root.addOrReplaceChild(FIN_FRONT_LEFT, CubeListBuilder.create().texOffs(132, 44).addBox(0F, 0F, 0F, 8F, 1F, 16F),
                PartPose.offsetAndRotation(7F, 16F, -1F, -0.5235988F, 0.6981317F, 0F));
        root.addOrReplaceChild(FIN_FRONT_RIGHT, CubeListBuilder.create().texOffs(132, 78).addBox(-8F, 0F, 0F, 8F, 1F, 16F),
                PartPose.offsetAndRotation(-7F, 16F, -1F, -0.5235988F, -0.6981317F, 0F));
        root.addOrReplaceChild(TAIL4, CubeListBuilder.create().texOffs(152, 0).addBox(-4F, -4F, 0F, 8F, 8F, 6F),
                PartPose.offsetAndRotation(0F, 16F, 52F, 0F, 0F, 0F));
        root.addOrReplaceChild(TAIL5, CubeListBuilder.create().texOffs(154, 14).addBox(-3F, -3F, 0F, 6F, 6F, 6F),
                PartPose.offsetAndRotation(0F, 16F, 58F, 0F, 0F, 0F));
        root.addOrReplaceChild(TAIL6, CubeListBuilder.create().texOffs(156, 26).addBox(-2F, -2F, 0F, 4F, 4F, 6F),
                PartPose.offsetAndRotation(0F, 16F, 64F, 0F, 0F, 0F));
        root.addOrReplaceChild(TOP_JAW, CubeListBuilder.create().texOffs(10, 13).addBox(-4F, -4F, -10F, 8F, 4F, 10F),
                PartPose.offsetAndRotation(0F, -23F, -29F, 0F, 0F, 0F));
        root.addOrReplaceChild(RIGHT_EYE, CubeListBuilder.create().texOffs(46, 16).addBox(-3F, -6F, -5F, 2F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -23F, -29F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEFT_EYE, CubeListBuilder.create().texOffs(4, 16).addBox(1F, -6F, -5F, 2F, 2F, 1F),
                PartPose.offsetAndRotation(0F, -23F, -29F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, TEXTURE_WIDTH, TEXTURE_HEIGHT);
    }
}
