// GENERATED by tools/gen_models.py from reference/jar/models/ModelSeaViper.json - do not edit.
package com.swbr.orespawn.client.model.geom;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Geometry of OreSpawn's ModelSeaViper (34 parts), copied unchanged from the 1.7.10 jar.
 * Part order is the order the original constructor created them.
 */
public final class SeaViperGeometry {

    public static final int TEXTURE_WIDTH = 128;
    public static final int TEXTURE_HEIGHT = 128;

    public static final String TAIL_TIP = "TailTip";
    public static final String NECK = "Neck";
    public static final String T_BASE = "tBase";
    public static final String T2 = "t2";
    public static final String T3 = "t3";
    public static final String T4 = "t4";
    public static final String T5 = "t5";
    public static final String T6 = "t6";
    public static final String T7 = "t7";
    public static final String T8 = "t8";
    public static final String T9 = "t9";
    public static final String T10 = "t10";
    public static final String T12 = "t12";
    public static final String T11 = "t11";
    public static final String T13 = "t13";
    public static final String T14 = "t14";
    public static final String T15 = "t15";
    public static final String T16 = "t16";
    public static final String T17 = "t17";
    public static final String T18 = "t18";
    public static final String T19 = "t19";
    public static final String T20 = "t20";
    public static final String T21 = "t21";
    public static final String MOUTH_BOTTOM = "MouthBottom";
    public static final String TOUNG_BASE = "ToungBase";
    public static final String MIDDLE_TOUNGE = "MiddleTounge";
    public static final String EYE_RIGHT = "EyeRight";
    public static final String EYE_LEFT = "EyeLeft";
    public static final String MOUTH_TOP = "MouthTop";
    public static final String HEAD = "Head";
    public static final String FANG_RIGHT = "FangRight";
    public static final String FANG_LEFT = "FangLeft";
    public static final String FORK_RIGHT = "ForkRight";
    public static final String FORK_LEFT = "ForkLeft";

    /** Every part in creation order. */
    public static final String[] PARTS = {
            TAIL_TIP,
            NECK,
            T_BASE,
            T2,
            T3,
            T4,
            T5,
            T6,
            T7,
            T8,
            T9,
            T10,
            T12,
            T11,
            T13,
            T14,
            T15,
            T16,
            T17,
            T18,
            T19,
            T20,
            T21,
            MOUTH_BOTTOM,
            TOUNG_BASE,
            MIDDLE_TOUNGE,
            EYE_RIGHT,
            EYE_LEFT,
            MOUTH_TOP,
            HEAD,
            FANG_RIGHT,
            FANG_LEFT,
            FORK_RIGHT,
            FORK_LEFT
    };

    /** Parts the original hid at construction time (showModel = false or isHidden = true). */
    public static final String[] HIDDEN = {};

    private SeaViperGeometry() {}

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild(TAIL_TIP, CubeListBuilder.create().texOffs(0, 90).addBox(-1F, -1F, 0F, 2F, 5F, 10F),
                PartPose.offsetAndRotation(1F, 20F, 152F, 0F, -0.6981317F, 0F));
        root.addOrReplaceChild(NECK, CubeListBuilder.create().texOffs(60, 60).addBox(-4F, -4F, -10F, 8F, 8F, 10F),
                PartPose.offsetAndRotation(0F, 4.5F, -1F, -0.2617994F, 0F, 0F));
        root.addOrReplaceChild(T_BASE, CubeListBuilder.create().texOffs(0, 31).addBox(-4F, -4F, 0F, 8F, 8F, 10F),
                PartPose.offsetAndRotation(0F, 4F, -2F, -0.5235988F, 0F, 0F));
        root.addOrReplaceChild(T2, CubeListBuilder.create().texOffs(0, 31).addBox(-4F, -4F, 0F, 8F, 8F, 10F),
                PartPose.offsetAndRotation(0F, 7F, 5F, -1.047198F, 0F, 0F));
        root.addOrReplaceChild(T3, CubeListBuilder.create().texOffs(0, 31).addBox(-4F, -4F, 0F, 8F, 8F, 10F),
                PartPose.offsetAndRotation(0F, 14F, 8F, -0.5235988F, 0F, 0F));
        root.addOrReplaceChild(T4, CubeListBuilder.create().texOffs(0, 31).addBox(-4F, -4F, 0F, 8F, 8F, 10F),
                PartPose.offsetAndRotation(0F, 19F, 15F, -0.0872665F, 0F, 0F));
        root.addOrReplaceChild(T5, CubeListBuilder.create().texOffs(0, 31).addBox(-4F, -4F, 0F, 8F, 8F, 10F),
                PartPose.offsetAndRotation(0F, 20F, 23F, 0F, 0F, 0F));
        root.addOrReplaceChild(T6, CubeListBuilder.create().texOffs(0, 31).addBox(-4F, -4F, 0F, 8F, 8F, 10F),
                PartPose.offsetAndRotation(0F, 20F, 31F, 0F, 0.3490659F, 0F));
        root.addOrReplaceChild(T7, CubeListBuilder.create().texOffs(0, 31).addBox(-4F, -4F, 0F, 8F, 8F, 10F),
                PartPose.offsetAndRotation(2F, 20F, 38F, 0F, 0.6981317F, 0F));
        root.addOrReplaceChild(T8, CubeListBuilder.create().texOffs(0, 31).addBox(-4F, -4F, 0F, 8F, 8F, 10F),
                PartPose.offsetAndRotation(7F, 20F, 44F, 0F, 0.3490659F, 0F));
        root.addOrReplaceChild(T9, CubeListBuilder.create().texOffs(0, 31).addBox(-4F, -4F, 0F, 8F, 8F, 10F),
                PartPose.offsetAndRotation(10F, 20F, 52F, 0F, 0F, 0F));
        root.addOrReplaceChild(T10, CubeListBuilder.create().texOffs(0, 31).addBox(-4F, -4F, 0F, 8F, 8F, 10F),
                PartPose.offsetAndRotation(10F, 20F, 60F, 0F, -0.3490659F, 0F));
        root.addOrReplaceChild(T12, CubeListBuilder.create().texOffs(0, 31).addBox(-4F, -4F, 0F, 8F, 8F, 10F),
                PartPose.offsetAndRotation(2F, 20F, 74F, 0F, -0.6981317F, 0F));
        root.addOrReplaceChild(T11, CubeListBuilder.create().texOffs(0, 31).addBox(-4F, -4F, 0F, 8F, 8F, 10F),
                PartPose.offsetAndRotation(8F, 20F, 67F, 0F, -0.6981317F, 0F));
        root.addOrReplaceChild(T13, CubeListBuilder.create().texOffs(0, 31).addBox(-4F, -4F, 0F, 8F, 8F, 10F),
                PartPose.offsetAndRotation(-4F, 20F, 80F, 0F, -0.3490659F, 0F));
        root.addOrReplaceChild(T14, CubeListBuilder.create().texOffs(0, 51).addBox(-3F, -3F, 0F, 6F, 7F, 10F),
                PartPose.offsetAndRotation(-8F, 20F, 88F, 0F, 0F, 0F));
        root.addOrReplaceChild(T15, CubeListBuilder.create().texOffs(0, 51).addBox(-3F, -3F, 0F, 6F, 7F, 10F),
                PartPose.offsetAndRotation(-8F, 20F, 97F, 0F, 0.3490659F, 0F));
        root.addOrReplaceChild(T16, CubeListBuilder.create().texOffs(0, 51).addBox(-3F, -3F, 0F, 6F, 7F, 10F),
                PartPose.offsetAndRotation(-5F, 20F, 105F, 0F, 0.6981317F, 0F));
        root.addOrReplaceChild(T17, CubeListBuilder.create().texOffs(0, 70).addBox(-2F, -2F, 0F, 4F, 6F, 10F),
                PartPose.offsetAndRotation(1F, 20F, 112F, 0F, 0.6981317F, 0F));
        root.addOrReplaceChild(T18, CubeListBuilder.create().texOffs(0, 70).addBox(-2F, -2F, 0F, 4F, 6F, 10F),
                PartPose.offsetAndRotation(7F, 20F, 119F, 0F, 0.3490659F, 0F));
        root.addOrReplaceChild(T19, CubeListBuilder.create().texOffs(0, 70).addBox(-2F, -2F, 0F, 4F, 6F, 10F),
                PartPose.offsetAndRotation(10F, 20F, 127F, 0F, 0F, 0F));
        root.addOrReplaceChild(T20, CubeListBuilder.create().texOffs(0, 90).addBox(-1F, -1F, 0F, 2F, 5F, 10F),
                PartPose.offsetAndRotation(10F, 20F, 136F, 0F, -0.3490659F, 0F));
        root.addOrReplaceChild(T21, CubeListBuilder.create().texOffs(0, 90).addBox(-1F, -1F, 0F, 2F, 5F, 10F),
                PartPose.offsetAndRotation(7F, 20F, 145F, 0F, -0.6981317F, 0F));
        root.addOrReplaceChild(MOUTH_BOTTOM, CubeListBuilder.create().texOffs(58, 78).addBox(-4F, 0F, -12F, 8F, 2F, 12F),
                PartPose.offsetAndRotation(0F, 4F, -10F, 0.5235988F, 0F, 0F));
        root.addOrReplaceChild(TOUNG_BASE, CubeListBuilder.create().texOffs(70, 17).addBox(-1F, -2F, -11F, 2F, 1F, 6F),
                PartPose.offsetAndRotation(0F, 6F, -8F, 0.2617994F, 0F, 0F));
        root.addOrReplaceChild(MIDDLE_TOUNGE, CubeListBuilder.create().texOffs(70, 10).addBox(-1F, -1F, -17F, 2F, 1F, 6F),
                PartPose.offsetAndRotation(0F, 6F, -8F, 0.1745329F, 0F, 0F));
        root.addOrReplaceChild(EYE_RIGHT, CubeListBuilder.create().texOffs(96, 60).addBox(-7F, -7F, -3F, 1F, 3F, 4F),
                PartPose.offsetAndRotation(0F, 6F, -8F, 0.3490659F, 0F, 0F));
        root.addOrReplaceChild(EYE_LEFT, CubeListBuilder.create().texOffs(50, 60).addBox(6F, -7F, -3F, 1F, 3F, 4F),
                PartPose.offsetAndRotation(0F, 6F, -8F, 0.3490659F, 0F, 0F));
        root.addOrReplaceChild(MOUTH_TOP, CubeListBuilder.create().texOffs(52, 24).addBox(-5F, -6F, -16F, 10F, 6F, 16F),
                PartPose.offsetAndRotation(0F, 6F, -8F, 0F, 0F, 0F));
        root.addOrReplaceChild(HEAD, CubeListBuilder.create().texOffs(60, 46).addBox(-6F, -8F, -6F, 12F, 8F, 6F),
                PartPose.offsetAndRotation(0F, 6F, -8F, 0F, 0F, 0F));
        root.addOrReplaceChild(FANG_RIGHT, CubeListBuilder.create().texOffs(92, 18).addBox(-4F, -3F, -15F, 1F, 5F, 1F),
                PartPose.offsetAndRotation(0F, 6F, -8F, 0.1745329F, 0F, 0F));
        root.addOrReplaceChild(FANG_LEFT, CubeListBuilder.create().texOffs(60, 18).addBox(3F, -3F, -15F, 1F, 5F, 1F),
                PartPose.offsetAndRotation(0F, 6F, -8F, 0.1745329F, 0F, 0F));
        root.addOrReplaceChild(FORK_RIGHT, CubeListBuilder.create().texOffs(60, 3).addBox(6F, 0.6F, -21F, 2F, 1F, 6F),
                PartPose.offsetAndRotation(0F, 6F, -8F, 0.0872665F, 0.4363323F, 0F));
        root.addOrReplaceChild(FORK_LEFT, CubeListBuilder.create().texOffs(80, 3).addBox(-8F, 0.6F, -21F, 2F, 1F, 6F),
                PartPose.offsetAndRotation(0F, 6F, -8F, 0.0872665F, -0.4363323F, 0F));
        return LayerDefinition.create(mesh, TEXTURE_WIDTH, TEXTURE_HEIGHT);
    }
}
