// GENERATED by tools/gen_models.py from reference/jar/models/ModelSpiderRobot.json - do not edit.
package com.swbr.orespawn.client.model.geom;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Geometry of OreSpawn's ModelSpiderRobot (39 parts), copied unchanged from the 1.7.10 jar.
 * Part order is the order the original constructor created them.
 */
public final class SpiderRobotGeometry {

    public static final int TEXTURE_WIDTH = 256;
    public static final int TEXTURE_HEIGHT = 512;

    public static final String LEG1P1 = "Leg1p1";
    public static final String LEG1P2 = "Leg1p2";
    public static final String LEG1P3 = "Leg1p3";
    public static final String FOOT = "Foot";
    public static final String FOOT_SPIKE1 = "FootSpike1";
    public static final String FOOT_SPIKE2 = "FootSpike2";
    public static final String FOOT_SPIKE3 = "FootSpike3";
    public static final String FOOT_SPIKE4 = "FootSpike4";
    public static final String ANKLE_SPIKE1 = "AnkleSpike1";
    public static final String ANKLE_SPIKE2 = "AnkleSpike2";
    public static final String ANKLE_SPIKE3 = "AnkleSpike3";
    public static final String ANKLE_SPIKE4 = "AnkleSpike4";
    public static final String LOWER_KNEE = "LowerKnee";
    public static final String UPPER_KNEE = "UpperKnee";
    public static final String LEG_BUMP1 = "LegBump1";
    public static final String LEG_BUMP2 = "LegBump2";
    public static final String LOWER_KNEE2 = "LowerKnee2";
    public static final String UPPER_KNEE2 = "UpperKnee2";
    public static final String HIP_JOINT = "HipJoint";
    public static final String BODY_CENTER = "BodyCenter";
    public static final String ABDOMEN = "Abdomen";
    public static final String HEAD = "Head";
    public static final String LJAW1 = "Ljaw1";
    public static final String RJAW1 = "Rjaw1";
    public static final String LJAW2 = "Ljaw2";
    public static final String RJAW2 = "Rjaw2";
    public static final String LJAW3 = "Ljaw3";
    public static final String RJAW3 = "Rjaw3";
    public static final String TAIL = "Tail";
    public static final String HEAD_SPIKE1 = "HeadSpike1";
    public static final String HEAD_SPIKE2 = "HeadSpike2";
    public static final String HIP1 = "Hip1";
    public static final String HIP2 = "Hip2";
    public static final String HIP3 = "Hip3";
    public static final String HIP4 = "Hip4";
    public static final String HIP5 = "Hip5";
    public static final String HIP6 = "Hip6";
    public static final String HIP7 = "Hip7";
    public static final String HIP8 = "Hip8";

    /** Every part in creation order. */
    public static final String[] PARTS = {
            LEG1P1,
            LEG1P2,
            LEG1P3,
            FOOT,
            FOOT_SPIKE1,
            FOOT_SPIKE2,
            FOOT_SPIKE3,
            FOOT_SPIKE4,
            ANKLE_SPIKE1,
            ANKLE_SPIKE2,
            ANKLE_SPIKE3,
            ANKLE_SPIKE4,
            LOWER_KNEE,
            UPPER_KNEE,
            LEG_BUMP1,
            LEG_BUMP2,
            LOWER_KNEE2,
            UPPER_KNEE2,
            HIP_JOINT,
            BODY_CENTER,
            ABDOMEN,
            HEAD,
            LJAW1,
            RJAW1,
            LJAW2,
            RJAW2,
            LJAW3,
            RJAW3,
            TAIL,
            HEAD_SPIKE1,
            HEAD_SPIKE2,
            HIP1,
            HIP2,
            HIP3,
            HIP4,
            HIP5,
            HIP6,
            HIP7,
            HIP8
    };

    /** Parts the original hid at construction time (showModel = false or isHidden = true). */
    public static final String[] HIDDEN = {};

    private SpiderRobotGeometry() {}

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild(LEG1P1, CubeListBuilder.create().texOffs(0, 149).addBox(-2F, -2F, 0F, 4F, 4F, 100F),
                PartPose.offsetAndRotation(0F, 0F, 0F, 0.7853982F, 0F, 0F));
        root.addOrReplaceChild(LEG1P2, CubeListBuilder.create().texOffs(0, 149).addBox(-1.5F, -1.5F, 0F, 3F, 3F, 100F),
                PartPose.offsetAndRotation(0F, -70F, 70F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEG1P3, CubeListBuilder.create().texOffs(0, 149).addBox(-1F, -1F, 0F, 2F, 2F, 100F),
                PartPose.offsetAndRotation(0F, -70F, 169F, -0.7853982F, 0F, 0F));
        root.addOrReplaceChild(FOOT, CubeListBuilder.create().texOffs(0, 28).addBox(-3F, -3F, 93F, 6F, 6F, 6F),
                PartPose.offsetAndRotation(0F, -70F, 169F, -0.7853982F, 0F, 0F));
        root.addOrReplaceChild(FOOT_SPIKE1, CubeListBuilder.create().texOffs(29, 27).addBox(2F, 2F, 99F, 1F, 1F, 5F),
                PartPose.offsetAndRotation(0F, -70F, 169F, -0.7853982F, 0F, 0F));
        root.addOrReplaceChild(FOOT_SPIKE2, CubeListBuilder.create().texOffs(29, 34).addBox(-3F, 2F, 99F, 1F, 1F, 5F),
                PartPose.offsetAndRotation(0F, -70F, 169F, -0.7853982F, 0F, 0F));
        root.addOrReplaceChild(FOOT_SPIKE3, CubeListBuilder.create().texOffs(43, 27).addBox(2F, -3F, 99F, 1F, 1F, 5F),
                PartPose.offsetAndRotation(0F, -70F, 169F, -0.7853982F, 0F, 0F));
        root.addOrReplaceChild(FOOT_SPIKE4, CubeListBuilder.create().texOffs(43, 34).addBox(-3F, -3F, 99F, 1F, 1F, 5F),
                PartPose.offsetAndRotation(0F, -70F, 169F, -0.7853982F, 0F, 0F));
        root.addOrReplaceChild(ANKLE_SPIKE1, CubeListBuilder.create().texOffs(1, 42).addBox(3F, -10F, 92F, 1F, 20F, 1F),
                PartPose.offsetAndRotation(0F, -70F, 169F, -0.7853982F, 0F, 0F));
        root.addOrReplaceChild(ANKLE_SPIKE2, CubeListBuilder.create().texOffs(7, 42).addBox(-4F, -10F, 92F, 1F, 20F, 1F),
                PartPose.offsetAndRotation(0F, -70F, 169F, -0.7853982F, 0F, 0F));
        root.addOrReplaceChild(ANKLE_SPIKE3, CubeListBuilder.create().texOffs(14, 42).addBox(-10F, 3F, 92F, 20F, 1F, 1F),
                PartPose.offsetAndRotation(0F, -70F, 169F, -0.7853982F, 0F, 0F));
        root.addOrReplaceChild(ANKLE_SPIKE4, CubeListBuilder.create().texOffs(14, 46).addBox(-10F, -4F, 92F, 20F, 1F, 1F),
                PartPose.offsetAndRotation(0F, -70F, 169F, -0.7853982F, 0F, 0F));
        root.addOrReplaceChild(LOWER_KNEE, CubeListBuilder.create().texOffs(14, 49).addBox(-1.5F, -1.5F, -1F, 3F, 3F, 15F),
                PartPose.offsetAndRotation(0F, -70F, 169F, -0.7853982F, 0F, 0F));
        root.addOrReplaceChild(UPPER_KNEE, CubeListBuilder.create().texOffs(0, 69).addBox(-2.5F, -2.5F, 81F, 5F, 5F, 20F),
                PartPose.offsetAndRotation(0F, -70F, 70F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEG_BUMP1, CubeListBuilder.create().texOffs(52, 50).addBox(-0.5F, -2F, 80F, 1F, 1F, 1F),
                PartPose.offsetAndRotation(0F, -70F, 169F, -0.7853982F, 0F, 0F));
        root.addOrReplaceChild(LEG_BUMP2, CubeListBuilder.create().texOffs(52, 54).addBox(-0.5F, -2F, 70F, 1F, 1F, 1F),
                PartPose.offsetAndRotation(0F, -70F, 169F, -0.7853982F, 0F, 0F));
        root.addOrReplaceChild(LOWER_KNEE2, CubeListBuilder.create().texOffs(0, 96).addBox(-2.5F, -2.5F, -1F, 5F, 5F, 15F),
                PartPose.offsetAndRotation(0F, -70F, 70F, 0F, 0F, 0F));
        root.addOrReplaceChild(UPPER_KNEE2, CubeListBuilder.create().texOffs(0, 119).addBox(-3F, -3F, 81F, 6F, 6F, 20F),
                PartPose.offsetAndRotation(0F, 0F, 0F, 0.7853982F, 0F, 0F));
        root.addOrReplaceChild(HIP_JOINT, CubeListBuilder.create().texOffs(0, 149).addBox(-4F, -4F, 0F, 8F, 8F, 16F),
                PartPose.offsetAndRotation(0F, 0F, 0F, 0.7853982F, 0F, 0F));
        root.addOrReplaceChild(BODY_CENTER, CubeListBuilder.create().texOffs(0, 321).addBox(-18F, -12F, -21F, 36F, 24F, 51F),
                PartPose.offsetAndRotation(0F, -4F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(ABDOMEN, CubeListBuilder.create().texOffs(0, 398).addBox(-24F, -30F, 29F, 48F, 40F, 73F),
                PartPose.offsetAndRotation(0F, -4F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(HEAD, CubeListBuilder.create().texOffs(0, 256).addBox(-15F, -16F, -57F, 30F, 26F, 36F),
                PartPose.offsetAndRotation(0F, -4F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(LJAW1, CubeListBuilder.create().texOffs(75, 26).addBox(-4F, 0F, -4F, 8F, 3F, 8F),
                PartPose.offsetAndRotation(14F, -3F, -56F, 0F, 0F, 0F));
        root.addOrReplaceChild(RJAW1, CubeListBuilder.create().texOffs(75, 26).addBox(-4F, 0F, -4F, 8F, 3F, 8F),
                PartPose.offsetAndRotation(-14F, -3F, -56F, 0F, 0F, 0F));
        root.addOrReplaceChild(LJAW2, CubeListBuilder.create().texOffs(63, 40).addBox(0F, 1F, -3F, 21F, 2F, 6F),
                PartPose.offsetAndRotation(14F, -3F, -56F, 0F, 0.7504916F, 0F));
        root.addOrReplaceChild(RJAW2, CubeListBuilder.create().texOffs(63, 40).addBox(0F, 1F, -3F, 21F, 2F, 6F),
                PartPose.offsetAndRotation(-14F, -3F, -56F, 0F, 2.303835F, 0F));
        root.addOrReplaceChild(LJAW3, CubeListBuilder.create().texOffs(0, 18).addBox(11F, 2F, 14F, 23F, 1F, 4F),
                PartPose.offsetAndRotation(14F, -3F, -56F, 0F, 1.710423F, 0F));
        root.addOrReplaceChild(RJAW3, CubeListBuilder.create().texOffs(0, 18).addBox(11F, 2F, -17F, 23F, 1F, 4F),
                PartPose.offsetAndRotation(-14F, -3F, -56F, 0F, 1.413717F, 0F));
        root.addOrReplaceChild(TAIL, CubeListBuilder.create().texOffs(130, 0).addBox(-5F, -5F, -5F, 10F, 10F, 49F),
                PartPose.offsetAndRotation(0F, -32F, 69F, 0F, 0F, 0F));
        root.addOrReplaceChild(HEAD_SPIKE1, CubeListBuilder.create().texOffs(74, 0).addBox(-1F, -1F, -10F, 2F, 2F, 21F),
                PartPose.offsetAndRotation(6F, -20F, -60F, 0F, 0F, 0F));
        root.addOrReplaceChild(HEAD_SPIKE2, CubeListBuilder.create().texOffs(74, 0).addBox(-1F, -1F, -10F, 2F, 2F, 21F),
                PartPose.offsetAndRotation(-6F, -20F, -60F, 0F, 0F, 0F));
        root.addOrReplaceChild(HIP1, CubeListBuilder.create().texOffs(70, 60).addBox(0F, 0F, 0F, 10F, 10F, 10F),
                PartPose.offsetAndRotation(22F, -3F, 44F, 0F, 0F, 0F));
        root.addOrReplaceChild(HIP2, CubeListBuilder.create().texOffs(70, 60).addBox(0F, 0F, 0F, 10F, 10F, 10F),
                PartPose.offsetAndRotation(-32F, -3F, 44F, 0F, 0F, 0F));
        root.addOrReplaceChild(HIP3, CubeListBuilder.create().texOffs(70, 60).addBox(0F, 0F, 0F, 10F, 10F, 10F),
                PartPose.offsetAndRotation(16F, -1F, 12F, 0F, 0F, 0F));
        root.addOrReplaceChild(HIP4, CubeListBuilder.create().texOffs(70, 60).addBox(0F, 0F, 0F, 10F, 10F, 10F),
                PartPose.offsetAndRotation(-26F, -1F, 12F, 0F, 0F, 0F));
        root.addOrReplaceChild(HIP5, CubeListBuilder.create().texOffs(70, 60).addBox(0F, 0F, 0F, 10F, 10F, 10F),
                PartPose.offsetAndRotation(16F, -1F, -11F, 0F, 0F, 0F));
        root.addOrReplaceChild(HIP6, CubeListBuilder.create().texOffs(70, 60).addBox(0F, 0F, 0F, 10F, 10F, 10F),
                PartPose.offsetAndRotation(-26F, -1F, -11F, 0F, 0F, 0F));
        root.addOrReplaceChild(HIP7, CubeListBuilder.create().texOffs(70, 60).addBox(0F, 0F, 0F, 10F, 10F, 10F),
                PartPose.offsetAndRotation(13F, -3F, -33F, 0F, 0F, 0F));
        root.addOrReplaceChild(HIP8, CubeListBuilder.create().texOffs(70, 60).addBox(0F, 0F, 0F, 10F, 10F, 10F),
                PartPose.offsetAndRotation(-23F, -3F, -33F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, TEXTURE_WIDTH, TEXTURE_HEIGHT);
    }
}
