// GENERATED by tools/gen_models.py from reference/jar/models/ModelTerribleTerror.json - do not edit.
package com.swbr.orespawn.client.model.geom;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Geometry of OreSpawn's ModelTerribleTerror (21 parts), copied unchanged from the 1.7.10 jar.
 * Part order is the order the original constructor created them.
 */
public final class TerribleTerrorGeometry {

    public static final int TEXTURE_WIDTH = 119;
    public static final int TEXTURE_HEIGHT = 72;

    public static final String HORN1 = "Horn1";
    public static final String HORN2 = "Horn2";
    public static final String SNOUT = "Snout";
    public static final String HEAD = "Head";
    public static final String JAW = "Jaw";
    public static final String NECK = "Neck";
    public static final String BODY = "Body";
    public static final String WING1 = "Wing1";
    public static final String WING2 = "Wing2";
    public static final String TAIL1 = "Tail1";
    public static final String TAIL2 = "Tail2";
    public static final String TAIL3 = "Tail3";
    public static final String TAIL4 = "Tail4";
    public static final String FL11 = "FL11";
    public static final String FL12 = "FL12";
    public static final String FL21 = "FL21";
    public static final String FL22 = "FL22";
    public static final String BL21 = "BL21";
    public static final String BL22 = "BL22";
    public static final String BL11 = "BL11";
    public static final String BL12 = "BL12";

    /** Every part in creation order. */
    public static final String[] PARTS = {
            HORN1,
            HORN2,
            SNOUT,
            HEAD,
            JAW,
            NECK,
            BODY,
            WING1,
            WING2,
            TAIL1,
            TAIL2,
            TAIL3,
            TAIL4,
            FL11,
            FL12,
            FL21,
            FL22,
            BL21,
            BL22,
            BL11,
            BL12
    };

    /** Parts the original hid at construction time (showModel = false or isHidden = true). */
    public static final String[] HIDDEN = {};

    private TerribleTerrorGeometry() {}

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild(HORN1, CubeListBuilder.create().texOffs(90, 0).addBox(1F, -4F, 0F, 0F, 2F, 2F),
                PartPose.offsetAndRotation(0F, 17F, -6F, 0F, 0F, 0F));
        root.addOrReplaceChild(HORN2, CubeListBuilder.create().texOffs(102, 0).addBox(-1F, -4F, 0F, 0F, 2F, 2F),
                PartPose.offsetAndRotation(0F, 17F, -6F, 0F, 0F, 0F));
        root.addOrReplaceChild(SNOUT, CubeListBuilder.create().texOffs(64, 0).addBox(-2F, -1F, -4F, 4F, 1F, 4F),
                PartPose.offsetAndRotation(0F, 17F, -6F, 0F, 0F, 0F));
        root.addOrReplaceChild(HEAD, CubeListBuilder.create().texOffs(41, 0).addBox(-2F, -2F, -2F, 4F, 1F, 2F),
                PartPose.offsetAndRotation(0F, 17F, -6F, 0F, 0F, 0F));
        root.addOrReplaceChild(JAW, CubeListBuilder.create().texOffs(42, 5).addBox(-2F, 0F, -4F, 4F, 1F, 4F),
                PartPose.offsetAndRotation(0F, 17F, -6F, 0F, 0F, 0F));
        root.addOrReplaceChild(NECK, CubeListBuilder.create().texOffs(30, 0).addBox(0F, 0F, 0F, 2F, 5F, 2F),
                PartPose.offsetAndRotation(-1F, 18F, -2F, -2.082002F, 0F, 0F));
        root.addOrReplaceChild(BODY, CubeListBuilder.create().texOffs(38, 16).addBox(0F, 0F, 0F, 2F, 3F, 10F),
                PartPose.offsetAndRotation(-1F, 17F, -4F, 0F, 0F, 0F));
        root.addOrReplaceChild(WING1, CubeListBuilder.create().texOffs(36, 37).addBox(0F, 0F, 0F, 0F, 11F, 15F),
                PartPose.offsetAndRotation(0F, 18F, -1F, -0.3490659F, 0F, -2.356194F));
        root.addOrReplaceChild(WING2, CubeListBuilder.create().texOffs(0, 37).addBox(0F, 0F, 0F, 0F, 11F, 15F),
                PartPose.offsetAndRotation(0F, 18F, -1F, -0.3490659F, 0F, 2.356194F));
        root.addOrReplaceChild(TAIL1, CubeListBuilder.create().texOffs(14, 0).addBox(0F, 0F, 0F, 1F, 1F, 6F),
                PartPose.offsetAndRotation(-0.5F, 17F, 6F, -0.5235988F, 0F, 0F));
        root.addOrReplaceChild(TAIL2, CubeListBuilder.create().texOffs(14, 8).addBox(0F, 0F, 0F, 1F, 1F, 6F),
                PartPose.offsetAndRotation(-0.5F, 20F, 11F, 0F, 0F, 0F));
        root.addOrReplaceChild(TAIL3, CubeListBuilder.create().texOffs(17, 16).addBox(0F, 0F, 0F, 1F, 1F, 4F),
                PartPose.offsetAndRotation(-0.5F, 20F, 17F, 0F, -0.6320364F, 0F));
        root.addOrReplaceChild(TAIL4, CubeListBuilder.create().texOffs(16, 23).addBox(-1F, 0.5F, 4F, 3F, 0F, 2F),
                PartPose.offsetAndRotation(-0.5F, 20F, 17F, 0F, -0.6320364F, 0F));
        root.addOrReplaceChild(FL11, CubeListBuilder.create().texOffs(0, 9).addBox(0F, 0F, 0F, 1F, 2F, 1F),
                PartPose.offsetAndRotation(-2F, 19F, -4F, 0.3490659F, 0F, 0.1745329F));
        root.addOrReplaceChild(FL12, CubeListBuilder.create().texOffs(0, 13).addBox(-0.5F, 1F, 1F, 1F, 2F, 1F),
                PartPose.offsetAndRotation(-2F, 19F, -4F, -0.2617994F, 0F, 0F));
        root.addOrReplaceChild(FL21, CubeListBuilder.create().texOffs(5, 9).addBox(0F, 0F, 0F, 1F, 2F, 1F),
                PartPose.offsetAndRotation(1F, 19F, -4F, 0.3490659F, 0F, -0.1745329F));
        root.addOrReplaceChild(FL22, CubeListBuilder.create().texOffs(5, 13).addBox(0.5F, 1F, 1F, 1F, 2F, 1F),
                PartPose.offsetAndRotation(1F, 19F, -4F, -0.2617994F, 0F, 0F));
        root.addOrReplaceChild(BL21, CubeListBuilder.create().texOffs(0, 18).addBox(0F, 0F, 0F, 1F, 2F, 1F),
                PartPose.offsetAndRotation(1F, 18F, 4F, -0.3490659F, 0F, -0.1745329F));
        root.addOrReplaceChild(BL22, CubeListBuilder.create().texOffs(0, 22).addBox(0.5F, 2F, -1F, 1F, 2F, 1F),
                PartPose.offsetAndRotation(1F, 18F, 4F, 0.1745329F, 0F, 0F));
        root.addOrReplaceChild(BL11, CubeListBuilder.create().texOffs(5, 18).addBox(0F, 0F, 0F, 1F, 2F, 1F),
                PartPose.offsetAndRotation(-2F, 18F, 4F, -0.3490659F, 0F, 0.1745329F));
        root.addOrReplaceChild(BL12, CubeListBuilder.create().texOffs(5, 22).addBox(-0.5F, 2F, -1F, 1F, 2F, 1F),
                PartPose.offsetAndRotation(-2F, 18F, 4F, 0.1745329F, 0F, 0F));
        return LayerDefinition.create(mesh, TEXTURE_WIDTH, TEXTURE_HEIGHT);
    }
}
