// GENERATED by tools/gen_models.py from reference/jar/models/ModelTriffid.json - do not edit.
package com.swbr.orespawn.client.model.geom;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Geometry of OreSpawn's ModelTriffid (178 parts), copied unchanged from the 1.7.10 jar.
 * Part order is the order the original constructor created them.
 */
public final class TriffidGeometry {

    public static final int TEXTURE_WIDTH = 532;
    public static final int TEXTURE_HEIGHT = 715;

    public static final String R9 = "r9";
    public static final String B14 = "b14";
    public static final String BASE = "base";
    public static final String B3 = "b3";
    public static final String L57 = "l57";
    public static final String L30 = "l30";
    public static final String B6 = "b6";
    public static final String B7 = "b7";
    public static final String B8 = "b8";
    public static final String B9 = "b9";
    public static final String B11 = "b11";
    public static final String B16 = "b16";
    public static final String H18 = "h18";
    public static final String B13 = "b13";
    public static final String B15 = "b15";
    public static final String H8 = "h8";
    public static final String H1 = "h1";
    public static final String H13 = "h13";
    public static final String H7 = "h7";
    public static final String H3 = "h3";
    public static final String H17 = "h17";
    public static final String H16 = "h16";
    public static final String H23 = "h23";
    public static final String H4 = "h4";
    public static final String H2 = "h2";
    public static final String H21 = "h21";
    public static final String H19 = "h19";
    public static final String H20 = "h20";
    public static final String B10 = "b10";
    public static final String B17 = "b17";
    public static final String H6 = "h6";
    public static final String H11 = "h11";
    public static final String H14 = "h14";
    public static final String H15 = "h15";
    public static final String H10 = "h10";
    public static final String H9 = "h9";
    public static final String H5 = "h5";
    public static final String H12 = "h12";
    public static final String C2 = "c2";
    public static final String C11 = "c11";
    public static final String C1 = "c1";
    public static final String C5 = "c5";
    public static final String C3 = "c3";
    public static final String C4 = "c4";
    public static final String C10 = "c10";
    public static final String C6 = "c6";
    public static final String C7 = "c7";
    public static final String C8 = "c8";
    public static final String C9 = "c9";
    public static final String B1 = "b1";
    public static final String L15 = "l15";
    public static final String B2 = "b2";
    public static final String L43 = "l43";
    public static final String L1 = "l1";
    public static final String L2 = "l2";
    public static final String L3 = "l3";
    public static final String LEAF3 = "leaf3";
    public static final String L4 = "l4";
    public static final String L5 = "l5";
    public static final String L6 = "l6";
    public static final String L7 = "l7";
    public static final String L8 = "l8";
    public static final String L9 = "l9";
    public static final String L10 = "l10";
    public static final String L11 = "l11";
    public static final String L12 = "l12";
    public static final String L13 = "l13";
    public static final String L14 = "l14";
    public static final String B4 = "b4";
    public static final String L31 = "l31";
    public static final String L32 = "l32";
    public static final String LEAF32 = "leaf32";
    public static final String L33 = "l33";
    public static final String L34 = "l34";
    public static final String L35 = "l35";
    public static final String L36 = "l36";
    public static final String L37 = "l37";
    public static final String L38 = "l38";
    public static final String L39 = "l39";
    public static final String L40 = "l40";
    public static final String L41 = "l41";
    public static final String L42 = "l42";
    public static final String L17 = "l17";
    public static final String L18 = "l18";
    public static final String L19 = "l19";
    public static final String L20 = "l20";
    public static final String L21 = "l21";
    public static final String L22 = "l22";
    public static final String L23 = "l23";
    public static final String L24 = "l24";
    public static final String L25 = "l25";
    public static final String L26 = "l26";
    public static final String L27 = "l27";
    public static final String L28 = "l28";
    public static final String L29 = "l29";
    public static final String B5 = "b5";
    public static final String L45 = "l45";
    public static final String L46 = "l46";
    public static final String L47 = "l47";
    public static final String L48 = "l48";
    public static final String L49 = "l49";
    public static final String LEAF49 = "leaf49";
    public static final String L50 = "l50";
    public static final String L51 = "l51";
    public static final String L52 = "l52";
    public static final String L53 = "l53";
    public static final String L54 = "l54";
    public static final String L55 = "l55";
    public static final String L56 = "l56";
    public static final String H22 = "h22";
    public static final String T15 = "t15";
    public static final String T14 = "t14";
    public static final String T13 = "t13";
    public static final String T12 = "t12";
    public static final String T11 = "t11";
    public static final String T10 = "t10";
    public static final String T9 = "t9";
    public static final String T6 = "t6";
    public static final String T2 = "t2";
    public static final String T8 = "t8";
    public static final String T7 = "t7";
    public static final String T5 = "t5";
    public static final String T4 = "t4";
    public static final String T3 = "t3";
    public static final String T1 = "t1";
    public static final String R47 = "r47";
    public static final String R2 = "r2";
    public static final String R6 = "r6";
    public static final String R5 = "r5";
    public static final String R10 = "r10";
    public static final String R7 = "r7";
    public static final String R12 = "r12";
    public static final String R8 = "r8";
    public static final String R11 = "r11";
    public static final String R4 = "r4";
    public static final String R40 = "r40";
    public static final String R45 = "r45";
    public static final String R49 = "r49";
    public static final String R44 = "r44";
    public static final String ROOT43 = "root43";
    public static final String R43 = "r43";
    public static final String R46 = "r46";
    public static final String R48 = "r48";
    public static final String R35 = "r35";
    public static final String R38 = "r38";
    public static final String R42 = "r42";
    public static final String R39 = "r39";
    public static final String R41 = "r41";
    public static final String R18 = "r18";
    public static final String R3 = "r3";
    public static final String R50 = "r50";
    public static final String R31 = "r31";
    public static final String R36 = "r36";
    public static final String R37 = "r37";
    public static final String R22 = "r22";
    public static final String R30 = "r30";
    public static final String R33 = "r33";
    public static final String R34 = "r34";
    public static final String R29 = "r29";
    public static final String R20 = "r20";
    public static final String R24 = "r24";
    public static final String R28 = "r28";
    public static final String R26 = "r26";
    public static final String R25 = "r25";
    public static final String R27 = "r27";
    public static final String R23 = "r23";
    public static final String R21 = "r21";
    public static final String R1 = "r1";
    public static final String R13 = "r13";
    public static final String R16 = "r16";
    public static final String R19 = "r19";
    public static final String R15 = "r15";
    public static final String R14 = "r14";
    public static final String R17 = "r17";
    public static final String R32 = "r32";
    public static final String L16 = "l16";
    public static final String L44 = "l44";
    public static final String ROOT = "root";

    /** Every part in creation order. */
    public static final String[] PARTS = {
            R9,
            B14,
            BASE,
            B3,
            L57,
            L30,
            B6,
            B7,
            B8,
            B9,
            B11,
            B16,
            H18,
            B13,
            B15,
            H8,
            H1,
            H13,
            H7,
            H3,
            H17,
            H16,
            H23,
            H4,
            H2,
            H21,
            H19,
            H20,
            B10,
            B17,
            H6,
            H11,
            H14,
            H15,
            H10,
            H9,
            H5,
            H12,
            C2,
            C11,
            C1,
            C5,
            C3,
            C4,
            C10,
            C6,
            C7,
            C8,
            C9,
            B1,
            L15,
            B2,
            L43,
            L1,
            L2,
            L3,
            LEAF3,
            L4,
            L5,
            L6,
            L7,
            L8,
            L9,
            L10,
            L11,
            L12,
            L13,
            L14,
            B4,
            L31,
            L32,
            LEAF32,
            L33,
            L34,
            L35,
            L36,
            L37,
            L38,
            L39,
            L40,
            L41,
            L42,
            L17,
            L18,
            L19,
            L20,
            L21,
            L22,
            L23,
            L24,
            L25,
            L26,
            L27,
            L28,
            L29,
            B5,
            L45,
            L46,
            L47,
            L48,
            L49,
            LEAF49,
            L50,
            L51,
            L52,
            L53,
            L54,
            L55,
            L56,
            H22,
            T15,
            T14,
            T13,
            T12,
            T11,
            T10,
            T9,
            T6,
            T2,
            T8,
            T7,
            T5,
            T4,
            T3,
            T1,
            R47,
            R2,
            R6,
            R5,
            R10,
            R7,
            R12,
            R8,
            R11,
            R4,
            R40,
            R45,
            R49,
            R44,
            ROOT43,
            R43,
            R46,
            R48,
            R35,
            R38,
            R42,
            R39,
            R41,
            R18,
            R3,
            R50,
            R31,
            R36,
            R37,
            R22,
            R30,
            R33,
            R34,
            R29,
            R20,
            R24,
            R28,
            R26,
            R25,
            R27,
            R23,
            R21,
            R1,
            R13,
            R16,
            R19,
            R15,
            R14,
            R17,
            R32,
            L16,
            L44,
            ROOT
    };

    /** Parts the original hid at construction time (showModel = false or isHidden = true). */
    public static final String[] HIDDEN = {};

    private TriffidGeometry() {}

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        addParts0(root);
        addParts1(root);
        addParts2(root);
        return LayerDefinition.create(mesh, TEXTURE_WIDTH, TEXTURE_HEIGHT);
    }

    private static void addParts0(PartDefinition root) {
        root.addOrReplaceChild(R9, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, 0F, 2F, 2F, 9F),
                PartPose.offsetAndRotation(-15F, 22F, -17F, -0.296706F, 1.151917F, 1.708151F));
        root.addOrReplaceChild(B14, CubeListBuilder.create().texOffs(0, 0).addBox(-4F, -4F, -4F, 7F, 7F, 7F),
                PartPose.offsetAndRotation(0F, -22F, -2.5F, -0.4165037F, 1.689355F, 0.1948779F));
        root.addOrReplaceChild(BASE, CubeListBuilder.create().texOffs(150, 0).addBox(0F, 0F, 0F, 9F, 8F, 9F),
                PartPose.offsetAndRotation(-5F, 16F, -5F, 0F, 0F, 0F));
        root.addOrReplaceChild(B3, CubeListBuilder.create().texOffs(0, 0).addBox(-4F, -4F, -4F, 7F, 8F, 8F),
                PartPose.offsetAndRotation(-2F, 16F, -2F, 0.0523599F, 0.1745329F, -0.2094395F));
        root.addOrReplaceChild(L57, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 1F, 1F, 2F),
                PartPose.offsetAndRotation(0F, -24F, 6F, 2.286381F, 0F, 0F));
        root.addOrReplaceChild(L30, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 1F, 1F, 2F),
                PartPose.offsetAndRotation(-0.5F, -24.5F, -6F, -2.268928F, 0F, 0F));
        root.addOrReplaceChild(B6, CubeListBuilder.create().texOffs(0, 0).addBox(-4F, -4F, -4F, 8F, 8F, 8F),
                PartPose.offsetAndRotation(-4.5F, 2F, -4.5F, -0.1047198F, -0.1396263F, -0.2617994F));
        root.addOrReplaceChild(B7, CubeListBuilder.create().texOffs(0, 0).addBox(-4F, -4F, -4F, 8F, 8F, 8F),
                PartPose.offsetAndRotation(-3F, 4F, -4.5F, 0.4014257F, 0.3490659F, -0.6283185F));
        root.addOrReplaceChild(B8, CubeListBuilder.create().texOffs(0, 0).addBox(-4F, -4F, -4F, 7F, 8F, 8F),
                PartPose.offsetAndRotation(-3F, -5F, -4.5F, -0.0818962F, -0.1342561F, -0.8513902F));
        root.addOrReplaceChild(B9, CubeListBuilder.create().texOffs(0, 0).addBox(-4F, -4F, -4F, 8F, 8F, 8F),
                PartPose.offsetAndRotation(-3F, -5F, -5.5F, -0.0447176F, 1.208305F, -0.1449966F));
        root.addOrReplaceChild(B11, CubeListBuilder.create().texOffs(0, 0).addBox(-3F, -3F, -3F, 6F, 6F, 6F),
                PartPose.offsetAndRotation(-3F, -12F, -5.5F, -0.0447176F, 1.208305F, -0.1449966F));
        root.addOrReplaceChild(B16, CubeListBuilder.create().texOffs(0, 0).addBox(-4F, -4F, -4F, 7F, 8F, 7F),
                PartPose.offsetAndRotation(0F, -17F, -5.5F, -0.2306107F, 0.8365188F, -0.5911399F));
        root.addOrReplaceChild(H18, CubeListBuilder.create().texOffs(80, 0).addBox(0F, 0F, 0F, 3F, 3F, 1F),
                PartPose.offsetAndRotation(2F, -40.5F, -3F, 0.0523599F, -0.4537856F, 0F));
        root.addOrReplaceChild(B13, CubeListBuilder.create().texOffs(0, 0).addBox(-3F, -3F, -3F, 6F, 6F, 6F),
                PartPose.offsetAndRotation(0F, -28F, -1.5F, 0.3531968F, 1.505734F, -0.3308896F));
        root.addOrReplaceChild(B15, CubeListBuilder.create().texOffs(0, 0).addBox(-3F, -3F, -3F, 5F, 5F, 5F),
                PartPose.offsetAndRotation(0F, -27F, -0.5F, 0.5205006F, 1.412787F, 0.8179294F));
        root.addOrReplaceChild(H8, CubeListBuilder.create().texOffs(80, 0).addBox(0F, 0F, 0F, 3F, 5F, 1F),
                PartPose.offsetAndRotation(-1F, -35F, 0.5F, -0.296706F, 0.1745329F, 0F));
        root.addOrReplaceChild(H1, CubeListBuilder.create().texOffs(80, 0).addBox(0F, 0F, 0F, 3F, 5F, 1F),
                PartPose.offsetAndRotation(-1F, -34.5F, -3F, 0.296706F, -0.1745329F, 0F));
        root.addOrReplaceChild(H13, CubeListBuilder.create().texOffs(80, 0).addBox(0F, 0F, 0F, 1F, 1F, 2F),
                PartPose.offsetAndRotation(-2F, -41F, -2.5F, 0.5934119F, -0.0174533F, 0F));
        root.addOrReplaceChild(H7, CubeListBuilder.create().texOffs(80, 0).addBox(0F, 0F, 0F, 3F, 3F, 1F),
                PartPose.offsetAndRotation(-1F, -37.5F, 1F, -0.1745329F, 0.2094395F, 0F));
        root.addOrReplaceChild(H3, CubeListBuilder.create().texOffs(80, 0).addBox(0F, 0F, 0F, 3F, 3F, 1F),
                PartPose.offsetAndRotation(-1F, -40.5F, -3.5F, -0.0523599F, -0.2094395F, 0F));
        root.addOrReplaceChild(H17, CubeListBuilder.create().texOffs(80, 0).addBox(0F, 0F, 0F, 3F, 1F, 3F),
                PartPose.offsetAndRotation(2F, -41.7F, -2.5F, 0F, 0F, 0.6806784F));
        root.addOrReplaceChild(H16, CubeListBuilder.create().texOffs(80, 0).addBox(0F, 0F, 0F, 1F, 3F, 1F),
                PartPose.offsetAndRotation(-1.5F, -34.5F, -2.5F, 0.2617994F, 0F, 0F));
        root.addOrReplaceChild(H23, CubeListBuilder.create().texOffs(80, 0).addBox(0F, 0F, 0F, 3F, 3F, 1F),
                PartPose.offsetAndRotation(2F, -40.5F, 0F, 0.0872665F, 0.7504916F, 0F));
        root.addOrReplaceChild(H4, CubeListBuilder.create().texOffs(80, 0).addBox(0F, 0F, 0F, 3F, 1F, 3F),
                PartPose.offsetAndRotation(-1F, -40.5F, -3.5F, 0.6108652F, -0.0174533F, 0F));
        root.addOrReplaceChild(H2, CubeListBuilder.create().texOffs(80, 0).addBox(0F, 0F, 0F, 3F, 3F, 1F),
                PartPose.offsetAndRotation(-1F, -37.5F, -3.5F, 0.1745329F, -0.2094395F, 0F));
        root.addOrReplaceChild(H21, CubeListBuilder.create().texOffs(80, 0).addBox(-1F, 0F, 0F, 1F, 3F, 1F),
                PartPose.offsetAndRotation(3F, -34.5F, -0.5F, 0.1745329F, -0.7853982F, 0.3839724F));
        root.addOrReplaceChild(H19, CubeListBuilder.create().texOffs(80, 0).addBox(-1F, 0F, 0F, 3F, 3F, 1F),
                PartPose.offsetAndRotation(3F, -37.5F, -2F, 0.1745329F, -0.7853982F, 0F));
        root.addOrReplaceChild(H20, CubeListBuilder.create().texOffs(80, 0).addBox(-1F, 0F, 0F, 1F, 3F, 1F),
                PartPose.offsetAndRotation(3F, -34.5F, -1.5F, 0.5759587F, -0.7853982F, -0.2094395F));
        root.addOrReplaceChild(B10, CubeListBuilder.create().texOffs(0, 0).addBox(-3F, -3F, -3F, 6F, 6F, 6F),
                PartPose.offsetAndRotation(0F, -12F, -6.5F, -0.2677893F, 0.7249829F, -0.4052469F));
        root.addOrReplaceChild(B17, CubeListBuilder.create().texOffs(0, 0).addBox(-3F, -3F, -3F, 5F, 5F, 5F),
                PartPose.offsetAndRotation(0F, -20.5F, -2.5F, 0.7063936F, 1.896109F, 0.7435722F));
        root.addOrReplaceChild(H6, CubeListBuilder.create().texOffs(80, 0).addBox(0F, 0F, 0F, 3F, 3F, 1F),
                PartPose.offsetAndRotation(-1F, -40.5F, 1F, 0.0523599F, 0.2094395F, 0F));
        root.addOrReplaceChild(H11, CubeListBuilder.create().texOffs(80, 0).addBox(0F, 0F, 0F, 1F, 3F, 1F),
                PartPose.offsetAndRotation(-1.5F, -40.5F, 0.5F, 0.0523599F, 0.2094395F, 0F));
        root.addOrReplaceChild(H14, CubeListBuilder.create().texOffs(80, 0).addBox(0F, 0F, 0F, 1F, 3F, 1F),
                PartPose.offsetAndRotation(-1.5F, -40.5F, -3F, -0.0349066F, 0.1396263F, 0F));
        root.addOrReplaceChild(H15, CubeListBuilder.create().texOffs(80, 0).addBox(0F, 0F, 0F, 1F, 3F, 1F),
                PartPose.offsetAndRotation(-1.5F, -37.5F, -3F, 0.1919862F, 0.1396263F, 0F));
        root.addOrReplaceChild(H10, CubeListBuilder.create().texOffs(80, 0).addBox(0F, 0F, 0F, 1F, 3F, 1F),
                PartPose.offsetAndRotation(-1.5F, -37.5F, 0.5F, -0.1919862F, 0F, 0F));
        root.addOrReplaceChild(H9, CubeListBuilder.create().texOffs(80, 0).addBox(0F, 0F, 0F, 1F, 3F, 1F),
                PartPose.offsetAndRotation(-1.5F, -34.5F, -0.5F, -0.2617994F, 0F, 0F));
        root.addOrReplaceChild(H5, CubeListBuilder.create().texOffs(80, 0).addBox(0F, 0F, 0F, 3F, 1F, 3F),
                PartPose.offsetAndRotation(-1F, -42.5F, -0.5F, -0.6108652F, 0.296706F, 0F));
        root.addOrReplaceChild(H12, CubeListBuilder.create().texOffs(80, 0).addBox(0F, 0F, 0F, 1F, 1F, 2F),
                PartPose.offsetAndRotation(-2F, -42F, -0.5F, -0.6108652F, 0.296706F, 0F));
        root.addOrReplaceChild(C2, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 0F, 5F, 2F),
                PartPose.offsetAndRotation(-2F, -29F, -3F, 0F, -0.6632251F, 0.2792527F));
        root.addOrReplaceChild(C11, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 0F, 5F, 2F),
                PartPose.offsetAndRotation(-3F, -29F, 0F, 0.0713623F, 0.5948578F, 0.6335855F));
        root.addOrReplaceChild(C1, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 0F, 5F, 2F),
                PartPose.offsetAndRotation(-3F, -29F, -2F, 0.1745329F, 0F, 0.2792527F));
        root.addOrReplaceChild(C5, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 0F, 5F, 2F),
                PartPose.offsetAndRotation(2.5F, -29F, -2.5F, 0F, -2.617994F, 0.3700098F));
        root.addOrReplaceChild(C3, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 0F, 5F, 2F),
                PartPose.offsetAndRotation(0F, -29F, -3.533333F, 0F, -1.32645F, 0.2792527F));
        root.addOrReplaceChild(C4, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 0F, 5F, 2F),
                PartPose.offsetAndRotation(2.5F, -29F, -4F, 0F, -1.553343F, 0.2792527F));
        root.addOrReplaceChild(C10, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 0F, 5F, 2F),
                PartPose.offsetAndRotation(0F, -30F, 2.5F, 0F, -2.019315F, -0.5222769F));
        root.addOrReplaceChild(C6, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 0F, 5F, 2F),
                PartPose.offsetAndRotation(4.5F, -29F, -0.5F, 0F, -2.373648F, 0.3700098F));
        root.addOrReplaceChild(C7, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 0F, 5F, 2F),
                PartPose.offsetAndRotation(4.5F, -30F, -0.5F, 0F, -0.1801097F, -0.2992052F));
        root.addOrReplaceChild(C8, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 0F, 5F, 2F),
                PartPose.offsetAndRotation(4F, -30F, 0.5F, 0.1487144F, -0.866778F, -0.6709913F));
        root.addOrReplaceChild(C9, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 0F, 5F, 2F),
                PartPose.offsetAndRotation(2F, -30F, 2F, -0.2230717F, -1.573172F, -0.8197058F));
        root.addOrReplaceChild(B1, CubeListBuilder.create().texOffs(0, 0).addBox(-4F, -4F, -4F, 9F, 8F, 9F),
                PartPose.offsetAndRotation(-1F, 13F, -5F, -0.2268928F, -0.3748843F, 0.3520608F));
        root.addOrReplaceChild(L15, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 1F, 2F, 1F),
                PartPose.offsetAndRotation(-5.5F, -31F, -5F, 0.0204482F, -0.065992F, 0.7831261F));
        root.addOrReplaceChild(B2, CubeListBuilder.create().texOffs(0, 0).addBox(-4F, -4F, -4F, 9F, 8F, 9F),
                PartPose.offsetAndRotation(-2F, 8F, -4F, -0.2268928F, -0.3748843F, 0.3520608F));
        root.addOrReplaceChild(L43, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 1F, 1F, 1F),
                PartPose.offsetAndRotation(5.5F, -25.5F, -1.5F, 0F, 0F, -0.5722408F));
        root.addOrReplaceChild(L1, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 1F, 5F, 5F),
                PartPose.offsetAndRotation(-7F, 10F, -4F, 0F, -0.2230717F, -0.7435722F));
        root.addOrReplaceChild(L2, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 1F, 3F, 6F),
                PartPose.offsetAndRotation(-9F, 8.5F, -5F, 0.0698132F, -0.1707118F, -0.9006519F));
        root.addOrReplaceChild(L3, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 1F, 4F, 7F),
                PartPose.offsetAndRotation(-10F, 5.5F, -6F, 0.0698132F, -0.1532585F, -0.3801513F));
        root.addOrReplaceChild(LEAF3, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 1F, 4F, 7F),
                PartPose.offsetAndRotation(-10F, 5.5F, -6F, 0.0698132F, -0.1532585F, -0.3801513F));
        root.addOrReplaceChild(L4, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 1F, 4F, 8F),
                PartPose.offsetAndRotation(-11F, 1.5F, -7F, 0.0698132F, -0.1532585F, -0.1942582F));
        root.addOrReplaceChild(L5, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 1F, 4F, 9F),
                PartPose.offsetAndRotation(-11.5F, -2.5F, -8F, 0.0698132F, -0.1008986F, -0.1418984F));
        root.addOrReplaceChild(L6, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 1F, 6F, 10F),
                PartPose.offsetAndRotation(-12F, -7.5F, -9F, 0.1047198F, -0.1532585F, -0.176805F));
    }

    private static void addParts1(PartDefinition root) {
        root.addOrReplaceChild(L7, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 1F, 4F, 9F),
                PartPose.offsetAndRotation(-13F, -11.5F, -9F, 0.0698132F, -0.1532585F, -0.2291648F));
        root.addOrReplaceChild(L8, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 1F, 4F, 8F),
                PartPose.offsetAndRotation(-13F, -15.5F, -8.5F, 0.0204482F, -0.1532585F, -0.0197253F));
        root.addOrReplaceChild(L9, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 1F, 4F, 7F),
                PartPose.offsetAndRotation(-12.5F, -19.5F, -8F, 0.0204482F, -0.1008986F, 0.1722609F));
        root.addOrReplaceChild(L10, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 1F, 4F, 6F),
                PartPose.offsetAndRotation(-11F, -23.3F, -7.5F, 0.0204482F, -0.065992F, 0.416607F));
        root.addOrReplaceChild(L11, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 1F, 3F, 5F),
                PartPose.offsetAndRotation(-9.5F, -26F, -7F, 0.0204482F, -0.065992F, 0.5038735F));
        root.addOrReplaceChild(L12, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 1F, 3F, 4F),
                PartPose.offsetAndRotation(-8.5F, -28F, -6.5F, 0.0204482F, -0.065992F, 0.5038735F));
        root.addOrReplaceChild(L13, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 1F, 2F, 3F),
                PartPose.offsetAndRotation(-7.5F, -29F, -6F, 0.0204482F, -0.065992F, 0.7482196F));
        root.addOrReplaceChild(L14, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 1F, 2F, 2F),
                PartPose.offsetAndRotation(-6.5F, -30F, -5.5F, 0.0204482F, -0.065992F, 0.7831261F));
        root.addOrReplaceChild(B4, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 8F, 8F, 8F),
                PartPose.offsetAndRotation(-4.5F, 9F, -4.5F, -0.2617994F, -0.1396263F, -0.2617994F));
        root.addOrReplaceChild(L31, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 1F, 5F, 5F),
                PartPose.offsetAndRotation(7.5F, 9F, -3.5F, 0F, 0F, 0.7086656F));
        root.addOrReplaceChild(L32, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 1F, 3F, 6F),
                PartPose.offsetAndRotation(9F, 6.5F, -4F, 0F, 0F, 0.5341327F));
        root.addOrReplaceChild(LEAF32, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 1F, 3F, 7F),
                PartPose.offsetAndRotation(10.5F, 4.5F, -4.5F, 0F, 0F, 0.5864926F));
        root.addOrReplaceChild(L33, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 1F, 3F, 7F),
                PartPose.offsetAndRotation(10.5F, 4.5F, -4.5F, 0F, 0F, 0.5864926F));
        root.addOrReplaceChild(L34, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 1F, 4F, 8F),
                PartPose.offsetAndRotation(11.5F, 1F, -5F, 0F, 0F, 0.3004238F));
        root.addOrReplaceChild(L35, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 1F, 4F, 9F),
                PartPose.offsetAndRotation(12.5F, -2.5F, -5.5F, 0F, 0F, 0.248064F));
        root.addOrReplaceChild(L36, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 1F, 5F, 10F),
                PartPose.offsetAndRotation(12.5F, -7.5F, -6F, 0F, 0F, 0.0037179F));
        root.addOrReplaceChild(L37, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 1F, 4F, 9F),
                PartPose.offsetAndRotation(12F, -11.5F, -5.5F, 0F, 0F, -0.1184552F));
        root.addOrReplaceChild(L38, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 1F, 4F, 8F),
                PartPose.offsetAndRotation(11F, -15F, -5F, 0F, 0F, -0.2755348F));
        root.addOrReplaceChild(L39, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 1F, 4F, 7F),
                PartPose.offsetAndRotation(9.5F, -18.5F, -4.5F, 0F, 0F, -0.4151612F));
        root.addOrReplaceChild(L40, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 1F, 3F, 6F),
                PartPose.offsetAndRotation(8.5F, -21F, -4F, 0F, 0F, -0.4151612F));
        root.addOrReplaceChild(L41, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 1F, 3F, 4F),
                PartPose.offsetAndRotation(7F, -23.5F, -3F, 0F, 0F, -0.5373342F));
        root.addOrReplaceChild(L42, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 1F, 2F, 2F),
                PartPose.offsetAndRotation(6F, -25F, -2F, 0F, 0F, -0.5722408F));
        root.addOrReplaceChild(L17, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 6F, 1F, 3F),
                PartPose.offsetAndRotation(-2.5F, 8.5F, -11F, -0.6283185F, 0F, 0F));
        root.addOrReplaceChild(L18, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 7F, 1F, 3F),
                PartPose.offsetAndRotation(-3F, 7F, -13F, -0.6457718F, 0F, 0F));
        root.addOrReplaceChild(L19, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 8F, 1F, 4F),
                PartPose.offsetAndRotation(-3.5F, 4.5F, -16F, -0.6981317F, 0F, 0F));
        root.addOrReplaceChild(L20, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 9F, 1F, 4F),
                PartPose.offsetAndRotation(-4F, 2F, -18F, -0.9075712F, 0F, 0F));
        root.addOrReplaceChild(L21, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 10F, 1F, 5F),
                PartPose.offsetAndRotation(-4.5F, -2F, -19F, -1.291544F, 0F, 0F));
        root.addOrReplaceChild(L22, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 9F, 1F, 4F),
                PartPose.offsetAndRotation(-4F, -5.5F, -18.5F, -1.64061F, 0F, 0F));
        root.addOrReplaceChild(L23, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 8F, 1F, 4F),
                PartPose.offsetAndRotation(-4F, -8.5F, -17.5F, -1.850049F, 0F, 0F));
        root.addOrReplaceChild(L24, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 7F, 1F, 4F),
                PartPose.offsetAndRotation(-3.5F, -12F, -15.5F, -2.111848F, 0F, 0F));
        root.addOrReplaceChild(L25, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 6F, 1F, 4F),
                PartPose.offsetAndRotation(-3F, -15F, -13F, -2.234021F, 0F, 0F));
        root.addOrReplaceChild(L26, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 5F, 1F, 4F),
                PartPose.offsetAndRotation(-2.5F, -18F, -10.5F, -2.268928F, 0F, 0F));
        root.addOrReplaceChild(L27, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 4F, 1F, 3F),
                PartPose.offsetAndRotation(-2F, -20F, -9F, -2.268928F, 0F, 0F));
        root.addOrReplaceChild(L28, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 3F, 1F, 2F),
                PartPose.offsetAndRotation(-1.5F, -21.5F, -8F, -2.268928F, 0F, 0F));
        root.addOrReplaceChild(L29, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 2F, 1F, 2F),
                PartPose.offsetAndRotation(-1F, -23F, -7F, -2.268928F, 0F, 0F));
        root.addOrReplaceChild(B5, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 8F, 8F, 8F),
                PartPose.offsetAndRotation(-2.5F, 9F, -5.5F, 0.1919862F, -0.1396263F, 0.1745329F));
        root.addOrReplaceChild(L45, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 6F, 1F, 4F),
                PartPose.offsetAndRotation(-3F, 6F, 8.5F, 0.8901179F, 0F, 0F));
        root.addOrReplaceChild(L46, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 7F, 1F, 3F),
                PartPose.offsetAndRotation(-3.5F, 3F, 11F, 1.134464F, 0F, 0F));
        root.addOrReplaceChild(L47, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 8F, 1F, 4F),
                PartPose.offsetAndRotation(-4F, 1F, 12F, 1.343904F, 0F, 0F));
        root.addOrReplaceChild(L48, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 9F, 1F, 3F),
                PartPose.offsetAndRotation(-4F, -3F, 13F, 1.43117F, 0F, 0F));
        root.addOrReplaceChild(L49, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 10F, 1F, 5F),
                PartPose.offsetAndRotation(-4.5F, -6F, 13.5F, 1.53589F, 0F, 0F));
        root.addOrReplaceChild(LEAF49, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 9F, 1F, 3F),
                PartPose.offsetAndRotation(-4F, -11F, 13.5F, 1.658063F, 0F, 0F));
        root.addOrReplaceChild(L50, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 9F, 1F, 3F),
                PartPose.offsetAndRotation(-4F, -11F, 13.5F, 1.658063F, 0F, 0F));
        root.addOrReplaceChild(L51, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 8F, 1F, 3F),
                PartPose.offsetAndRotation(-3.5F, -14F, 13F, 1.797689F, 0F, 0F));
        root.addOrReplaceChild(L52, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 7F, 1F, 3F),
                PartPose.offsetAndRotation(-3F, -16.5F, 12.5F, 2.146755F, 0F, 0F));
        root.addOrReplaceChild(L53, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 6F, 1F, 3F),
                PartPose.offsetAndRotation(-2.5F, -19F, 11F, 2.286381F, 0F, 0F));
        root.addOrReplaceChild(L54, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 5F, 1F, 2F),
                PartPose.offsetAndRotation(-2F, -21F, 9F, 2.286381F, 0F, 0F));
        root.addOrReplaceChild(L55, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 4F, 1F, 2F),
                PartPose.offsetAndRotation(-1.5F, -22F, 8F, 2.286381F, 0F, 0F));
        root.addOrReplaceChild(L56, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 2F, 1F, 2F),
                PartPose.offsetAndRotation(-0.5F, -23F, 7F, 2.286381F, 0F, 0F));
        root.addOrReplaceChild(H22, CubeListBuilder.create().texOffs(80, 0).addBox(-1F, 0F, 0F, 3F, 3F, 1F),
                PartPose.offsetAndRotation(2F, -37.5F, 0F, -0.1745329F, 0.6108652F, 0F));
        root.addOrReplaceChild(T15, CubeListBuilder.create().texOffs(0, 40).addBox(-6F, 0F, 0F, 6F, 1F, 1F),
                PartPose.offsetAndRotation(-1F, -40.5F, -1F, 0.0174533F, 0F, 0F));
        root.addOrReplaceChild(T14, CubeListBuilder.create().texOffs(0, 40).addBox(-3F, 0F, 0F, 3F, 1F, 1F),
                PartPose.offsetAndRotation(-3F, -38F, -1F, 0F, 0.0349066F, -0.2443461F));
        root.addOrReplaceChild(T13, CubeListBuilder.create().texOffs(0, 40).addBox(-3F, 0F, 0F, 3F, 1F, 1F),
                PartPose.offsetAndRotation(-5.5F, -36.8F, -1F, 0F, -0.1047198F, -0.3141593F));
        root.addOrReplaceChild(T12, CubeListBuilder.create().texOffs(0, 40).addBox(-3F, 0F, 0F, 3F, 1F, 1F),
                PartPose.offsetAndRotation(-7.5F, -36F, -1F, 0F, -0.1396263F, -0.3665191F));
        root.addOrReplaceChild(T11, CubeListBuilder.create().texOffs(0, 40).addBox(-3F, 0F, 0F, 3F, 1F, 1F),
                PartPose.offsetAndRotation(-10F, -35.5F, -1.5F, 0F, 0.0698132F, -0.2443461F));
        root.addOrReplaceChild(T10, CubeListBuilder.create().texOffs(0, 40).addBox(-3F, 0F, 0F, 3F, 1F, 1F),
                PartPose.offsetAndRotation(-12.5F, -35.5F, -1F, -0.0174533F, -0.0174533F, -0.0174533F));
        root.addOrReplaceChild(T9, CubeListBuilder.create().texOffs(0, 40).addBox(-6F, 0F, 0F, 6F, 1F, 1F),
                PartPose.offsetAndRotation(-14.5F, -35.5F, -1F, -0.0174533F, -0.0174533F, -0.0174533F));
        root.addOrReplaceChild(T6, CubeListBuilder.create().texOffs(0, 40).addBox(-6F, 0F, 0F, 6F, 1F, 1F),
                PartPose.offsetAndRotation(-29.5F, -35.5F, -1F, -0.0174533F, -0.1396263F, 0.0872665F));
        root.addOrReplaceChild(T2, CubeListBuilder.create().texOffs(0, 50).addBox(-3F, 0F, 0F, 3F, 1F, 1F),
                PartPose.offsetAndRotation(-46.5F, -32F, -1.5F, 0.0523599F, 0.2792527F, -0.4363323F));
        root.addOrReplaceChild(T8, CubeListBuilder.create().texOffs(0, 40).addBox(-6F, 0F, 0F, 6F, 1F, 1F),
                PartPose.offsetAndRotation(-19.5F, -35.5F, -1F, -0.0174533F, -0.0349066F, 0.1745329F));
    }

    private static void addParts2(PartDefinition root) {
        root.addOrReplaceChild(T7, CubeListBuilder.create().texOffs(0, 40).addBox(-6F, 0F, 0F, 6F, 1F, 1F),
                PartPose.offsetAndRotation(-24.5F, -36F, -1F, -0.0174533F, 0.2268928F, -0.0523599F));
        root.addOrReplaceChild(T5, CubeListBuilder.create().texOffs(0, 40).addBox(-6F, 0F, 0F, 6F, 1F, 1F),
                PartPose.offsetAndRotation(-34.5F, -36F, -1F, -0.0174533F, 0.1396263F, -0.296706F));
        root.addOrReplaceChild(T4, CubeListBuilder.create().texOffs(0, 40).addBox(-6F, 0F, 0F, 6F, 1F, 1F),
                PartPose.offsetAndRotation(-39.5F, -34F, -1F, -0.0174533F, 0.3839724F, -0.2094395F));
        root.addOrReplaceChild(T3, CubeListBuilder.create().texOffs(0, 40).addBox(-3F, 0F, 0F, 3F, 1F, 1F),
                PartPose.offsetAndRotation(-44.5F, -33F, -1F, 0.1396263F, 0.122173F, -0.3839724F));
        root.addOrReplaceChild(T1, CubeListBuilder.create().texOffs(0, 50).addBox(-3F, 0F, 0F, 3F, 1F, 1F),
                PartPose.offsetAndRotation(-46.5F, -32F, -0.5F, 0.1396263F, -0.2792527F, -0.4537856F));
        root.addOrReplaceChild(R47, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, 0F, 2F, 2F, 5F),
                PartPose.offsetAndRotation(-12F, 22F, -0.4F, 0F, -0.0872665F, -0.2094395F));
        root.addOrReplaceChild(R2, CubeListBuilder.create().texOffs(0, 0).addBox(0F, 0F, 0F, 2F, 2F, 5F),
                PartPose.offsetAndRotation(-11F, 22F, -11F, 0.418879F, 0.7330383F, 0.3817004F));
        root.addOrReplaceChild(R6, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, 0F, 1F, 1F, 5F),
                PartPose.offsetAndRotation(-17F, 24.5F, -6.5F, 0.7330383F, 1.797689F, 0.7831261F));
        root.addOrReplaceChild(R5, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, 0F, 2F, 2F, 6F),
                PartPose.offsetAndRotation(-16F, 22F, -11F, 0.5061455F, 1.151917F, 1.463804F));
        root.addOrReplaceChild(R10, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, 0F, 1F, 1F, 5F),
                PartPose.offsetAndRotation(-18F, 24F, -13.5F, 0.5992297F, 1.27409F, 0.5759587F));
        root.addOrReplaceChild(R7, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, 0F, 1F, 1F, 5F),
                PartPose.offsetAndRotation(-20F, 24.5F, -10.5F, 0.5061455F, 1.186824F, 0.416607F));
        root.addOrReplaceChild(R12, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, 0F, 1F, 1F, 5F),
                PartPose.offsetAndRotation(-14F, 24F, -18.5F, 0.3665191F, 0.2268928F, -0.0349066F));
        root.addOrReplaceChild(R8, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, 0F, 1F, 1F, 5F),
                PartPose.offsetAndRotation(-22F, 25F, -14.5F, 0.1396263F, 0.418879F, 0F));
        root.addOrReplaceChild(R11, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, 0F, 1F, 1F, 5F),
                PartPose.offsetAndRotation(-18F, 24F, -19.5F, 0.3665191F, 0.4712389F, -0.0349066F));
        root.addOrReplaceChild(R4, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, -3F, 1F, 1F, 5F),
                PartPose.offsetAndRotation(-7.5F, 21.5F, -15F, 0F, -0.0174533F, -0.3665191F));
        root.addOrReplaceChild(R40, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, 1F, 1F, 1F, 5F),
                PartPose.offsetAndRotation(-13F, 21F, 14.6F, -0.0349066F, 2.530727F, 0.2268928F));
        root.addOrReplaceChild(R45, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, 0F, 1F, 1F, 6F),
                PartPose.offsetAndRotation(-14F, 21.5F, -2.9F, -0.2443461F, -2.061864F, 0.122173F));
        root.addOrReplaceChild(R49, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, 0F, 2F, 2F, 5F),
                PartPose.offsetAndRotation(-12F, 22F, 4.6F, 0.1919862F, 1.518436F, 0.1919862F));
        root.addOrReplaceChild(R44, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, 0F, 2F, 2F, 5F),
                PartPose.offsetAndRotation(-16F, 22F, 6.6F, -0.0174533F, 2.007129F, 0.1396263F));
        root.addOrReplaceChild(ROOT43, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, 0F, 2F, 2F, 5F),
                PartPose.offsetAndRotation(-16F, 22F, 6.6F, -0.0174533F, 2.007129F, 0.1396263F));
        root.addOrReplaceChild(R43, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, 0F, 1F, 1F, 6F),
                PartPose.offsetAndRotation(-22F, 22.5F, 8.1F, -0.0174533F, 1.902409F, 0.1396263F));
        root.addOrReplaceChild(R46, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, 0F, 1F, 1F, 6F),
                PartPose.offsetAndRotation(-11F, 22.5F, 0.1F, 0.0872665F, -2.323663F, -0.0698132F));
        root.addOrReplaceChild(R48, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, 0F, 1F, 1F, 6F),
                PartPose.offsetAndRotation(-11F, 22.5F, 3.1F, -0.296706F, -2.131677F, 0.1919862F));
        root.addOrReplaceChild(R35, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, -0.5F, 1F, 1F, 4F),
                PartPose.offsetAndRotation(2F, 21.5F, 12.6F, -0.2435199F, 1.963237F, -0.1776311F));
        root.addOrReplaceChild(R38, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, -1F, 1F, 1F, 5F),
                PartPose.offsetAndRotation(-3F, 21.5F, 10.6F, -0.3665191F, 1.064651F, 0.2443461F));
        root.addOrReplaceChild(R42, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, 1F, 2F, 2F, 5F),
                PartPose.offsetAndRotation(-8F, 21F, 8.6F, 0F, 2.199115F, 0.1745329F));
        root.addOrReplaceChild(R39, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, 0F, 2F, 2F, 5F),
                PartPose.offsetAndRotation(-8F, 21F, 8.6F, 0F, 1.117011F, 0.1570796F));
        root.addOrReplaceChild(R41, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, 1F, 2F, 2F, 5F),
                PartPose.offsetAndRotation(-11F, 21F, 11.6F, 0F, 2.338741F, 0.1745329F));
        root.addOrReplaceChild(R18, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, -5F, 1F, 1F, 6F),
                PartPose.offsetAndRotation(1F, 22F, -16F, 0.5304149F, -0.3531968F, -0.4848711F));
        root.addOrReplaceChild(R3, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, 0F, 2F, 2F, 5F),
                PartPose.offsetAndRotation(-8F, 21F, -14F, 0F, -0.1396263F, 0F));
        root.addOrReplaceChild(R50, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, 0F, 2F, 2F, 5F),
                PartPose.offsetAndRotation(-8F, 21F, 4.6F, 0F, 1.500983F, 0.1745329F));
        root.addOrReplaceChild(R31, CubeListBuilder.create().texOffs(111, 0).addBox(2F, -2F, 0F, 1F, 1F, 4F),
                PartPose.offsetAndRotation(5.5F, 21.5F, 8F, 0.2230717F, 1.580091F, 0.6404016F));
        root.addOrReplaceChild(R36, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, -4F, 1F, 1F, 5F),
                PartPose.offsetAndRotation(2F, 21.5F, 8.6F, 0.3141593F, -2.064859F, -0.418879F));
        root.addOrReplaceChild(R37, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, -4F, 2F, 2F, 5F),
                PartPose.offsetAndRotation(0F, 21F, 4.6F, 0F, -2.658271F, 0.1570796F));
        root.addOrReplaceChild(R22, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, 0F, 6F, 2F, 2F),
                PartPose.offsetAndRotation(9F, 21F, -5F, 0.1115358F, 2.189201F, 0F));
        root.addOrReplaceChild(R30, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, -4F, 1F, 1F, 5F),
                PartPose.offsetAndRotation(9.5F, 20.5F, 5F, 0.669215F, -2.212127F, 0.5288657F));
        root.addOrReplaceChild(R33, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, -4F, 1F, 1F, 5F),
                PartPose.offsetAndRotation(6.5F, 21.5F, 8F, 0.2230717F, 3.141593F, 0.6404016F));
        root.addOrReplaceChild(R34, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, -4F, 2F, 2F, 6F),
                PartPose.offsetAndRotation(5F, 21F, 4.6F, 0F, -2.658271F, 0.1570796F));
        root.addOrReplaceChild(R29, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, -4F, 5F, 2F, 2F),
                PartPose.offsetAndRotation(5F, 21F, 2.6F, 0F, 0.3665191F, 0F));
        root.addOrReplaceChild(R20, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, 0F, 4F, 1F, 1F),
                PartPose.offsetAndRotation(6F, 21.5F, -10.5F, 2.509556F, -0.2788396F, 2.658271F));
        root.addOrReplaceChild(R24, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, 0F, 6F, 2F, 2F),
                PartPose.offsetAndRotation(6F, 21F, -2F, 0.1115358F, 1.07219F, 0F));
        root.addOrReplaceChild(R28, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, -4F, 5F, 2F, 2F),
                PartPose.offsetAndRotation(9F, 21F, 1F, 0F, 0.1055459F, 0F));
        root.addOrReplaceChild(R26, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, -4F, 4F, 1F, 1F),
                PartPose.offsetAndRotation(12F, 21.5F, 0.5F, 0.0174533F, -0.4521332F, 0.4363323F));
        root.addOrReplaceChild(R25, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, 0F, 4F, 1F, 1F),
                PartPose.offsetAndRotation(15F, 23F, -1.5F, -0.0371786F, 0.3194262F, -0.1532585F));
        root.addOrReplaceChild(R27, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, 0F, 4F, 1F, 1F),
                PartPose.offsetAndRotation(11F, 22.5F, -2.5F, 0.3346075F, -1.019004F, 0.2557062F));
        root.addOrReplaceChild(R23, CubeListBuilder.create().texOffs(111, 0).addBox(-1F, 0F, -1F, 5F, 1F, 1F),
                PartPose.offsetAndRotation(11F, 21.5F, -6.5F, 0.3346075F, 0.2078904F, 0.5903137F));
        root.addOrReplaceChild(R21, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, 0F, 4F, 1F, 1F),
                PartPose.offsetAndRotation(6F, 21.5F, -10.5F, -3.141593F, -1.691627F, 2.658271F));
        root.addOrReplaceChild(R1, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, 0F, 2F, 2F, 5F),
                PartPose.offsetAndRotation(-8F, 21F, -8F, 0.418879F, 0.6108652F, -0.2617994F));
        root.addOrReplaceChild(R13, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, -5F, 2F, 2F, 5F),
                PartPose.offsetAndRotation(-1F, 20F, -6F, 0.418879F, 0.6108652F, -0.2617994F));
        root.addOrReplaceChild(R16, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, -5F, 2F, 2F, 5F),
                PartPose.offsetAndRotation(-2F, 20F, -12F, 0.418879F, -0.4673145F, -0.2617994F));
        root.addOrReplaceChild(R19, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, -7F, 1F, 1F, 7F),
                PartPose.offsetAndRotation(-2F, 20F, -12F, 0.5304149F, -1.508316F, -0.2617994F));
        root.addOrReplaceChild(R15, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, -5F, 1F, 1F, 5F),
                PartPose.offsetAndRotation(-2F, 20F, -12F, 0.5304149F, 0.6108652F, -0.2617994F));
        root.addOrReplaceChild(R14, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, -5F, 1F, 1F, 5F),
                PartPose.offsetAndRotation(-2F, 20F, -12F, 0.5304149F, 3.141593F, -0.2617994F));
        root.addOrReplaceChild(R17, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, -5F, 1F, 1F, 5F),
                PartPose.offsetAndRotation(1F, 22F, -16F, 0.5304149F, 0.8365188F, -0.4848711F));
        root.addOrReplaceChild(R32, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, -4F, 1F, 1F, 5F),
                PartPose.offsetAndRotation(6.5F, 21.5F, 8F, 0.669215F, -2.212127F, 0.5288657F));
        root.addOrReplaceChild(L16, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 5F, 1F, 5F),
                PartPose.offsetAndRotation(-2F, 10F, -9F, -0.5585054F, 0F, 0F));
        root.addOrReplaceChild(L44, CubeListBuilder.create().texOffs(40, 0).addBox(0F, 0F, 0F, 5F, 1F, 5F),
                PartPose.offsetAndRotation(-2.5F, 9F, 4.5F, 0.6457718F, 0F, 0F));
        root.addOrReplaceChild(ROOT, CubeListBuilder.create().texOffs(111, 0).addBox(0F, 0F, 0F, 2F, 2F, 5F),
                PartPose.offsetAndRotation(-11F, 22F, -11F, 0.418879F, 0.7330383F, 0.3817004F));
    }
}
