// GENERATED by tools/gen_models.py from reference/jar/models/ModelWaterDragon.json - do not edit.
package com.swbr.orespawn.client.model.geom;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Geometry of OreSpawn's ModelWaterDragon (24 parts), copied unchanged from the 1.7.10 jar.
 * Part order is the order the original constructor created them.
 */
public final class WaterDragonGeometry {

    public static final int TEXTURE_WIDTH = 128;
    public static final int TEXTURE_HEIGHT = 128;

    public static final String HEAD = "Head";
    public static final String NECK1 = "neck1";
    public static final String BODY1 = "body1";
    public static final String LEG8 = "Leg8";
    public static final String LEG2 = "Leg2";
    public static final String LEG7 = "Leg7";
    public static final String LEG1 = "Leg1";
    public static final String NECK2 = "neck2";
    public static final String NECK3 = "neck3";
    public static final String NECK4 = "neck4";
    public static final String BODY2 = "body2";
    public static final String BODY3 = "body3";
    public static final String BODY4 = "body4";
    public static final String TAIL1 = "tail1";
    public static final String TAILMIDDLE = "tailmiddle";
    public static final String TAILTOP = "tailtop";
    public static final String TAILBOTTOM = "tailbottom";
    public static final String NOSE = "nose";
    public static final String HEADFIN = "headfin";
    public static final String RIGHTEAR = "rightear";
    public static final String LEFTEAR = "leftear";
    public static final String NEACKFIN = "neackfin";
    public static final String BODYFIN = "Bodyfin";
    public static final String JAW = "jaw";

    /** Every part in creation order. */
    public static final String[] PARTS = {
            HEAD,
            NECK1,
            BODY1,
            LEG8,
            LEG2,
            LEG7,
            LEG1,
            NECK2,
            NECK3,
            NECK4,
            BODY2,
            BODY3,
            BODY4,
            TAIL1,
            TAILMIDDLE,
            TAILTOP,
            TAILBOTTOM,
            NOSE,
            HEADFIN,
            RIGHTEAR,
            LEFTEAR,
            NEACKFIN,
            BODYFIN,
            JAW
    };

    /** Parts the original hid at construction time (showModel = false or isHidden = true). */
    public static final String[] HIDDEN = {};

    private WaterDragonGeometry() {}

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild(HEAD, CubeListBuilder.create().texOffs(79, 64).addBox(-4F, -4F, -8F, 7F, 8F, 8F),
                PartPose.offsetAndRotation(0F, 0F, -3F, 0F, 0F, 0F));
        root.addOrReplaceChild(NECK1, CubeListBuilder.create().texOffs(29, 70).addBox(-2F, 0F, -3F, 5F, 5F, 5F),
                PartPose.offsetAndRotation(-1F, 4F, -5F, -0.1858931F, 0F, 0F));
        root.addOrReplaceChild(BODY1, CubeListBuilder.create().texOffs(0, 33).addBox(-5F, -4F, -6F, 9F, 9F, 9F),
                PartPose.offsetAndRotation(0F, 19F, 2F, 0F, 0F, 0F));
        root.addOrReplaceChild(LEG8, CubeListBuilder.create().texOffs(23, 25).addBox(0F, -1F, -1F, 9F, 2F, 3F),
                PartPose.offsetAndRotation(3F, 22F, -2F, 0F, 0.5759587F, 0.1919862F));
        root.addOrReplaceChild(LEG2, CubeListBuilder.create().texOffs(80, 18).addBox(0F, -1F, -1F, 9F, 2F, 3F),
                PartPose.offsetAndRotation(2F, 22F, 13F, 0F, -0.5759587F, 0.1919862F));
        root.addOrReplaceChild(LEG7, CubeListBuilder.create().texOffs(23, 18).addBox(-9F, -1F, -1F, 9F, 2F, 3F),
                PartPose.offsetAndRotation(-4F, 22F, -1F, 0F, -0.5759587F, -0.1919862F));
        root.addOrReplaceChild(LEG1, CubeListBuilder.create().texOffs(80, 25).addBox(-9F, -1F, -2F, 9F, 2F, 3F),
                PartPose.offsetAndRotation(-3F, 22F, 14F, 0F, 0.5759587F, -0.1919862F));
        root.addOrReplaceChild(NECK2, CubeListBuilder.create().texOffs(0, 11).addBox(-2F, 0F, -2F, 5F, 5F, 5F),
                PartPose.offsetAndRotation(-1F, 9F, -7F, 0.1115358F, 0F, 0F));
        root.addOrReplaceChild(NECK3, CubeListBuilder.create().texOffs(0, 22).addBox(-2F, 0F, -2F, 5F, 5F, 5F),
                PartPose.offsetAndRotation(-1F, 14F, -6F, 0.4461433F, 0F, 0F));
        root.addOrReplaceChild(NECK4, CubeListBuilder.create().texOffs(26, 12).addBox(-3F, 0F, -2F, 5F, 3F, 3F),
                PartPose.offsetAndRotation(0F, 18F, -4F, 1.226894F, 0F, 0F));
        root.addOrReplaceChild(BODY2, CubeListBuilder.create().texOffs(0, 52).addBox(-5F, -5F, 0F, 7F, 7F, 9F),
                PartPose.offsetAndRotation(1F, 21F, 5F, 0F, 0F, 0F));
        root.addOrReplaceChild(BODY3, CubeListBuilder.create().texOffs(0, 69).addBox(-3F, -3F, 0F, 5F, 5F, 7F),
                PartPose.offsetAndRotation(0F, 20F, 14F, 0F, 0F, 0F));
        root.addOrReplaceChild(BODY4, CubeListBuilder.create().texOffs(0, 89).addBox(-1F, -1F, 0F, 3F, 3F, 5F),
                PartPose.offsetAndRotation(-1F, 19F, 21F, 0F, 0F, 0F));
        root.addOrReplaceChild(TAIL1, CubeListBuilder.create().texOffs(0, 82).addBox(0F, 0F, 0F, 1F, 2F, 3F),
                PartPose.offsetAndRotation(-1F, 19F, 25F, 0F, 0F, 0F));
        root.addOrReplaceChild(TAILMIDDLE, CubeListBuilder.create().texOffs(55, 37).addBox(-1F, -6F, 0F, 2F, 11F, 9F),
                PartPose.offsetAndRotation(0F, 19F, 28F, 0F, 0F, 0F));
        root.addOrReplaceChild(TAILTOP, CubeListBuilder.create().texOffs(82, 36).addBox(-1F, -11F, 0F, 2F, 11F, 9F),
                PartPose.offsetAndRotation(0F, 14F, 28F, -0.6320364F, 0F, 0F));
        root.addOrReplaceChild(TAILBOTTOM, CubeListBuilder.create().texOffs(56, 60).addBox(0F, 0F, 0F, 2F, 11F, 9F),
                PartPose.offsetAndRotation(-1F, 23F, 28F, 0.6320361F, 0F, -0.0174533F));
        root.addOrReplaceChild(NOSE, CubeListBuilder.create().texOffs(54, 19).addBox(-3F, -2F, -5F, 5F, 5F, 5F),
                PartPose.offsetAndRotation(0F, -2F, -11F, 0F, 0F, 0F));
        root.addOrReplaceChild(HEADFIN, CubeListBuilder.create().texOffs(0, 99).addBox(0F, -5F, 0F, 0F, 10F, 9F),
                PartPose.offsetAndRotation(0F, -4F, -6F, 0.1396263F, 0F, 0F));
        root.addOrReplaceChild(RIGHTEAR, CubeListBuilder.create().texOffs(38, 32).addBox(0F, 0F, 0F, 0F, 5F, 5F),
                PartPose.offsetAndRotation(-4F, -2F, -5F, 0.0698132F, -0.418879F, 0F));
        root.addOrReplaceChild(LEFTEAR, CubeListBuilder.create().texOffs(38, 32).addBox(0F, 0F, 0F, 0F, 5F, 5F),
                PartPose.offsetAndRotation(3F, -2F, -5F, 0.0698132F, 0.418879F, 0F));
        root.addOrReplaceChild(NEACKFIN, CubeListBuilder.create().texOffs(42, 47).addBox(0F, -1F, 0F, 0F, 5F, 5F),
                PartPose.offsetAndRotation(0F, 3F, -3F, -0.185895F, 0F, 0F));
        root.addOrReplaceChild(BODYFIN, CubeListBuilder.create().texOffs(21, 91).addBox(0F, -6F, -3F, 0F, 10F, 9F),
                PartPose.offsetAndRotation(0F, 15F, 2F, -0.0698132F, 0F, 0F));
        root.addOrReplaceChild(JAW, CubeListBuilder.create().texOffs(76, 8).addBox(-2F, 0F, -5F, 5F, 1F, 5F),
                PartPose.offsetAndRotation(-1F, 3F, -10F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, TEXTURE_WIDTH, TEXTURE_HEIGHT);
    }
}
