// GENERATED by tools/gen_models.py from reference/jar/models/ModelWormSmall.json - do not edit.
package com.swbr.orespawn.client.model.geom;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Geometry of OreSpawn's ModelWormSmall (3 parts), copied unchanged from the 1.7.10 jar.
 * Part order is the order the original constructor created them.
 */
public final class WormSmallGeometry {

    public static final int TEXTURE_WIDTH = 64;
    public static final int TEXTURE_HEIGHT = 32;

    public static final String HEAD = "head";
    public static final String BODY = "body";
    public static final String TAIL = "tail";

    /** Every part in creation order. */
    public static final String[] PARTS = {
            HEAD,
            BODY,
            TAIL
    };

    /** Parts the original hid at construction time (showModel = false or isHidden = true). */
    public static final String[] HIDDEN = {};

    private WormSmallGeometry() {}

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild(HEAD, CubeListBuilder.create().texOffs(0, 0).addBox(-0.5F, -5F, -0.5F, 1F, 5F, 1F),
                PartPose.offsetAndRotation(0F, 14F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(BODY, CubeListBuilder.create().texOffs(6, 0).addBox(-0.5F, -5F, -0.5F, 1F, 5F, 1F),
                PartPose.offsetAndRotation(0F, 19F, 0F, 0F, 0F, 0F));
        root.addOrReplaceChild(TAIL, CubeListBuilder.create().texOffs(12, 0).addBox(-0.5F, -5F, -0.5F, 1F, 5F, 1F),
                PartPose.offsetAndRotation(0F, 24F, 0F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, TEXTURE_WIDTH, TEXTURE_HEIGHT);
    }
}
