// GENERATED by tools/gen_sounds.py from docs/catalog/manifest.json - do not edit.
package com.swbr.orespawn.registry;

import com.swbr.orespawn.OreSpawn;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvent;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

/** Every sound event of the original mod, ids lowercased. */
public final class ModSounds {

    public static final DeferredRegister<SoundEvent> SOUNDS = DeferredRegister.create(Registries.SOUND_EVENT, OreSpawn.MOD_ID);

    /** alien_death - Alien */
    public static final DeferredHolder<SoundEvent, SoundEvent> ALIEN_DEATH = register("alien_death");
    /** alien_hurt - Alien */
    public static final DeferredHolder<SoundEvent, SoundEvent> ALIEN_HURT = register("alien_hurt");
    /** alien_living - Alien */
    public static final DeferredHolder<SoundEvent, SoundEvent> ALIEN_LIVING = register("alien_living");
    /** alo_death - Alosaurus, Bee, Cephadrome, Dragon, GammaMetroid, Kraken, Kyuubi, Lizard, Mantis, Nastysaurus, Pointysaurus, ThePrinceTeen, WormLarge */
    public static final DeferredHolder<SoundEvent, SoundEvent> ALO_DEATH = register("alo_death");
    /** alo_hurt - Alosaurus, Basilisk, Cephadrome, Dragon, EmperorScorpion, Godzilla, Hammerhead, HerculesBeetle, Kyuubi, Lizard, Nastysaurus, Pointysaurus, TRex, ThePrinceTeen */
    public static final DeferredHolder<SoundEvent, SoundEvent> ALO_HURT = register("alo_hurt");
    /** alo_living - Alosaurus, Nastysaurus, Pointysaurus */
    public static final DeferredHolder<SoundEvent, SoundEvent> ALO_LIVING = register("alo_living");
    /** b_dark - Boyfriend */
    public static final DeferredHolder<SoundEvent, SoundEvent> B_DARK = register("b_dark");
    /** b_death_boyfriend - Boyfriend */
    public static final DeferredHolder<SoundEvent, SoundEvent> B_DEATH_BOYFRIEND = register("b_death_boyfriend");
    /** b_death_single - Boyfriend */
    public static final DeferredHolder<SoundEvent, SoundEvent> B_DEATH_SINGLE = register("b_death_single");
    /** b_fight - Boyfriend */
    public static final DeferredHolder<SoundEvent, SoundEvent> B_FIGHT = register("b_fight");
    /** b_happy - Boyfriend */
    public static final DeferredHolder<SoundEvent, SoundEvent> B_HAPPY = register("b_happy");
    /** b_hurt - Boyfriend */
    public static final DeferredHolder<SoundEvent, SoundEvent> B_HURT = register("b_hurt");
    /** b_ow - Boyfriend */
    public static final DeferredHolder<SoundEvent, SoundEvent> B_OW = register("b_ow");
    /** b_rain - Boyfriend */
    public static final DeferredHolder<SoundEvent, SoundEvent> B_RAIN = register("b_rain");
    /** b_taunt - Boyfriend */
    public static final DeferredHolder<SoundEvent, SoundEvent> B_TAUNT = register("b_taunt");
    /** b_thunder - Boyfriend */
    public static final DeferredHolder<SoundEvent, SoundEvent> B_THUNDER = register("b_thunder");
    /** b_water - Boyfriend */
    public static final DeferredHolder<SoundEvent, SoundEvent> B_WATER = register("b_water");
    /** b_woohoo - Boyfriend */
    public static final DeferredHolder<SoundEvent, SoundEvent> B_WOOHOO = register("b_woohoo");
    /** basilisk_living - Basilisk */
    public static final DeferredHolder<SoundEvent, SoundEvent> BASILISK_LIVING = register("basilisk_living");
    /** bb_happy - Boyfriend */
    public static final DeferredHolder<SoundEvent, SoundEvent> BB_HAPPY = register("bb_happy");
    /** Beebuzz - Bee, Mantis */
    public static final DeferredHolder<SoundEvent, SoundEvent> BEEBUZZ = register("beebuzz");
    /** big_splat - CloudShark, Fairy, Frog, Whale, WormLarge, WormMedium */
    public static final DeferredHolder<SoundEvent, SoundEvent> BIG_SPLAT = register("big_splat");
    /** birds - Cockateil */
    public static final DeferredHolder<SoundEvent, SoundEvent> BIRDS = register("birds");
    /** caterkiller_death - CaterKiller */
    public static final DeferredHolder<SoundEvent, SoundEvent> CATERKILLER_DEATH = register("caterkiller_death");
    /** caterkiller_hit - CaterKiller */
    public static final DeferredHolder<SoundEvent, SoundEvent> CATERKILLER_HIT = register("caterkiller_hit");
    /** caterkiller_living - CaterKiller */
    public static final DeferredHolder<SoundEvent, SoundEvent> CATERKILLER_LIVING = register("caterkiller_living");
    /** chain_rattles - GhostSkelly */
    public static final DeferredHolder<SoundEvent, SoundEvent> CHAIN_RATTLES = register("chain_rattles");
    /** chainsaw - Beaver */
    public static final DeferredHolder<SoundEvent, SoundEvent> CHAINSAW = register("chainsaw");
    /** chainsawshort - UltimateSword */
    public static final DeferredHolder<SoundEvent, SoundEvent> CHAINSAWSHORT = register("chainsawshort");
    /** clatter - SpitBug, TrooperBug */
    public static final DeferredHolder<SoundEvent, SoundEvent> CLATTER = register("clatter");
    /** cliffracer - CliffRacer */
    public static final DeferredHolder<SoundEvent, SoundEvent> CLIFFRACER = register("cliffracer");
    /** creepinghorror_dead - CreepingHorror */
    public static final DeferredHolder<SoundEvent, SoundEvent> CREEPINGHORROR_DEAD = register("creepinghorror_dead");
    /** creepinghorror_hit - CreepingHorror */
    public static final DeferredHolder<SoundEvent, SoundEvent> CREEPINGHORROR_HIT = register("creepinghorror_hit");
    /** creepinghorror_living - CreepingHorror */
    public static final DeferredHolder<SoundEvent, SoundEvent> CREEPINGHORROR_LIVING = register("creepinghorror_living");
    /** cricket - Cricket */
    public static final DeferredHolder<SoundEvent, SoundEvent> CRICKET = register("cricket");
    /** crunch - SpitBug, TrooperBug */
    public static final DeferredHolder<SoundEvent, SoundEvent> CRUNCH = register("crunch");
    /** cryo_death - Beaver, Camarasaurus, CaveFisher, Chipmunk, Cryolophosaurus, Gazelle, Hydrolisc, Ostrich, Scorpion, Spyro, Stinky, ThePrince, ThePrincess, VelocityRaptor */
    public static final DeferredHolder<SoundEvent, SoundEvent> CRYO_DEATH = register("cryo_death");
    /** cryo_hurt - Camarasaurus, CaveFisher, Cryolophosaurus, Hydrolisc, Ostrich, VelocityRaptor */
    public static final DeferredHolder<SoundEvent, SoundEvent> CRYO_HURT = register("cryo_hurt");
    /** cryo_living - Cryolophosaurus */
    public static final DeferredHolder<SoundEvent, SoundEvent> CRYO_LIVING = register("cryo_living");
    /** dbdead - DungeonBeast */
    public static final DeferredHolder<SoundEvent, SoundEvent> DBDEAD = register("dbdead");
    /** dbhit - DungeonBeast */
    public static final DeferredHolder<SoundEvent, SoundEvent> DBHIT = register("dbhit");
    /** dragonfly_death - Dragonfly */
    public static final DeferredHolder<SoundEvent, SoundEvent> DRAGONFLY_DEATH = register("dragonfly_death");
    /** dragonfly_hurt - Bee, Dragonfly, Mantis */
    public static final DeferredHolder<SoundEvent, SoundEvent> DRAGONFLY_HURT = register("dragonfly_hurt");
    /** dragonfly_living - Dragonfly */
    public static final DeferredHolder<SoundEvent, SoundEvent> DRAGONFLY_LIVING = register("dragonfly_living");
    /** duck_hurt - Baryonyx, Cassowary, Cockateil, EasterBunny, GammaMetroid, RubberDucky, Spyro, Stinky, ThePrince, ThePrincess */
    public static final DeferredHolder<SoundEvent, SoundEvent> DUCK_HURT = register("duck_hurt");
    /** emperorscorpion_death - Basilisk, EmperorScorpion, SpitBug, TrooperBug */
    public static final DeferredHolder<SoundEvent, SoundEvent> EMPERORSCORPION_DEATH = register("emperorscorpion_death");
    /** fart - StinkBug, Stinky */
    public static final DeferredHolder<SoundEvent, SoundEvent> FART = register("fart");
    /** ghost_sound - Ghost */
    public static final DeferredHolder<SoundEvent, SoundEvent> GHOST_SOUND = register("ghost_sound");
    /** glassdead - EntityThrownRock, Rotator, Urchin */
    public static final DeferredHolder<SoundEvent, SoundEvent> GLASSDEAD = register("glassdead");
    /** glasshit - Rotator, Urchin */
    public static final DeferredHolder<SoundEvent, SoundEvent> GLASSHIT = register("glasshit");
    /** godzilla_death - Godzilla */
    public static final DeferredHolder<SoundEvent, SoundEvent> GODZILLA_DEATH = register("godzilla_death");
    /** godzilla_living - Godzilla */
    public static final DeferredHolder<SoundEvent, SoundEvent> GODZILLA_LIVING = register("godzilla_living");
    /** hammerhead_death - Hammerhead */
    public static final DeferredHolder<SoundEvent, SoundEvent> HAMMERHEAD_DEATH = register("hammerhead_death");
    /** hammerhead_living - Hammerhead */
    public static final DeferredHolder<SoundEvent, SoundEvent> HAMMERHEAD_LIVING = register("hammerhead_living");
    /** hercules_death - HerculesBeetle */
    public static final DeferredHolder<SoundEvent, SoundEvent> HERCULES_DEATH = register("hercules_death");
    /** hover - Elevator */
    public static final DeferredHolder<SoundEvent, SoundEvent> HOVER = register("hover");
    /** king_hit - TheKing, ThePrinceAdult, TheQueen */
    public static final DeferredHolder<SoundEvent, SoundEvent> KING_HIT = register("king_hit");
    /** king_living - TheKing, ThePrinceAdult, TheQueen */
    public static final DeferredHolder<SoundEvent, SoundEvent> KING_LIVING = register("king_living");
    /** kraken_living - Kraken */
    public static final DeferredHolder<SoundEvent, SoundEvent> KRAKEN_LIVING = register("kraken_living");
    /** kyuubi_living - Kyuubi, Robot1, Urchin */
    public static final DeferredHolder<SoundEvent, SoundEvent> KYUUBI_LIVING = register("kyuubi_living");
    /** leaves_death - LeafMonster */
    public static final DeferredHolder<SoundEvent, SoundEvent> LEAVES_DEATH = register("leaves_death");
    /** leaves_hit - Crab, LeafMonster */
    public static final DeferredHolder<SoundEvent, SoundEvent> LEAVES_HIT = register("leaves_hit");
    /** leon_death - Leon */
    public static final DeferredHolder<SoundEvent, SoundEvent> LEON_DEATH = register("leon_death");
    /** leon_hit - Leon */
    public static final DeferredHolder<SoundEvent, SoundEvent> LEON_HIT = register("leon_hit");
    /** leon_living - Leon */
    public static final DeferredHolder<SoundEvent, SoundEvent> LEON_LIVING = register("leon_living");
    /** little_splat - CloudShark, GoldFish, Whale, WormMedium, WormSmall */
    public static final DeferredHolder<SoundEvent, SoundEvent> LITTLE_SPLAT = register("little_splat");
    /** lurkinghorror_dead - LurkingTerror */
    public static final DeferredHolder<SoundEvent, SoundEvent> LURKINGHORROR_DEAD = register("lurkinghorror_dead");
    /** lurkinghorror_hit - LurkingTerror */
    public static final DeferredHolder<SoundEvent, SoundEvent> LURKINGHORROR_HIT = register("lurkinghorror_hit");
    /** lurkinghorror_living - LurkingTerror */
    public static final DeferredHolder<SoundEvent, SoundEvent> LURKINGHORROR_LIVING = register("lurkinghorror_living");
    /** molenoid_death - Molenoid */
    public static final DeferredHolder<SoundEvent, SoundEvent> MOLENOID_DEATH = register("molenoid_death");
    /** molenoid_hit - Molenoid */
    public static final DeferredHolder<SoundEvent, SoundEvent> MOLENOID_HIT = register("molenoid_hit");
    /** molenoid_living - Molenoid */
    public static final DeferredHolder<SoundEvent, SoundEvent> MOLENOID_LIVING = register("molenoid_living");
    /** mosquito - EntityMosquito */
    public static final DeferredHolder<SoundEvent, SoundEvent> MOSQUITO = register("mosquito");
    /** MothraWings - Brutalfly, Cephadrome, Dragon, Leon, Mothra, PitchBlack, TheKing, ThePrinceAdult, ThePrinceTeen, TheQueen */
    public static final DeferredHolder<SoundEvent, SoundEvent> MOTHRA_WINGS = register("mothrawings");
    /** o_dark - Girlfriend */
    public static final DeferredHolder<SoundEvent, SoundEvent> O_DARK = register("o_dark");
    /** o_death_girlfriend - Girlfriend */
    public static final DeferredHolder<SoundEvent, SoundEvent> O_DEATH_GIRLFRIEND = register("o_death_girlfriend");
    /** o_death_single - Girlfriend */
    public static final DeferredHolder<SoundEvent, SoundEvent> O_DEATH_SINGLE = register("o_death_single");
    /** o_fight - Girlfriend */
    public static final DeferredHolder<SoundEvent, SoundEvent> O_FIGHT = register("o_fight");
    /** o_happy - Girlfriend */
    public static final DeferredHolder<SoundEvent, SoundEvent> O_HAPPY = register("o_happy");
    /** o_hurt - Girlfriend */
    public static final DeferredHolder<SoundEvent, SoundEvent> O_HURT = register("o_hurt");
    /** o_ow - Girlfriend */
    public static final DeferredHolder<SoundEvent, SoundEvent> O_OW = register("o_ow");
    /** o_taunt - Girlfriend */
    public static final DeferredHolder<SoundEvent, SoundEvent> O_TAUNT = register("o_taunt");
    /** o_thunder - Girlfriend */
    public static final DeferredHolder<SoundEvent, SoundEvent> O_THUNDER = register("o_thunder");
    /** o_water - Girlfriend */
    public static final DeferredHolder<SoundEvent, SoundEvent> O_WATER = register("o_water");
    /** o_woohoo - Girlfriend */
    public static final DeferredHolder<SoundEvent, SoundEvent> O_WOOHOO = register("o_woohoo");
    /** peacockdead - Peacock */
    public static final DeferredHolder<SoundEvent, SoundEvent> PEACOCKDEAD = register("peacockdead");
    /** peacockhit - Peacock */
    public static final DeferredHolder<SoundEvent, SoundEvent> PEACOCKHIT = register("peacockhit");
    /** peacocklive - Peacock */
    public static final DeferredHolder<SoundEvent, SoundEvent> PEACOCKLIVE = register("peacocklive");
    /** pitchblack_dead - PitchBlack */
    public static final DeferredHolder<SoundEvent, SoundEvent> PITCHBLACK_DEAD = register("pitchblack_dead");
    /** pitchblack_hit - PitchBlack */
    public static final DeferredHolder<SoundEvent, SoundEvent> PITCHBLACK_HIT = register("pitchblack_hit");
    /** pitchblack_living - PitchBlack */
    public static final DeferredHolder<SoundEvent, SoundEvent> PITCHBLACK_LIVING = register("pitchblack_living");
    /** ratdead - Flounder, Irukandji, Rat, Skate */
    public static final DeferredHolder<SoundEvent, SoundEvent> RATDEAD = register("ratdead");
    /** rathit - Rat */
    public static final DeferredHolder<SoundEvent, SoundEvent> RATHIT = register("rathit");
    /** ratlive - Rat */
    public static final DeferredHolder<SoundEvent, SoundEvent> RATLIVE = register("ratlive");
    /** roar - Dragon, Spyro, ThePrince, ThePrinceTeen, ThePrincess */
    public static final DeferredHolder<SoundEvent, SoundEvent> ROAR = register("roar");
    /** robot1_death - Robot1 */
    public static final DeferredHolder<SoundEvent, SoundEvent> ROBOT1_DEATH = register("robot1_death");
    /** robot_death - GiantRobot, Robot2, Robot3, Robot4, Robot5 */
    public static final DeferredHolder<SoundEvent, SoundEvent> ROBOT_DEATH = register("robot_death");
    /** robot_hurt - GiantRobot, Robot2, Robot3, Robot4, Robot5 */
    public static final DeferredHolder<SoundEvent, SoundEvent> ROBOT_HURT = register("robot_hurt");
    /** robot_living - GiantRobot, Robot2, Robot3, Robot4, Robot5 */
    public static final DeferredHolder<SoundEvent, SoundEvent> ROBOT_LIVING = register("robot_living");
    /** robotspider - AntRobot, SpiderRobot */
    public static final DeferredHolder<SoundEvent, SoundEvent> ROBOTSPIDER = register("robotspider");
    /** robotspidermount - AntRobot, SpiderRobot */
    public static final DeferredHolder<SoundEvent, SoundEvent> ROBOTSPIDERMOUNT = register("robotspidermount");
    /** rubybird - RubyBird */
    public static final DeferredHolder<SoundEvent, SoundEvent> RUBYBIRD = register("rubybird");
    /** scorpion_attack - Crab, EmperorScorpion, HerculesBeetle, Scorpion, TrooperBug */
    public static final DeferredHolder<SoundEvent, SoundEvent> SCORPION_ATTACK = register("scorpion_attack");
    /** scorpion_hit - Beaver, Chipmunk, Frog, Gazelle, Robot1, Scorpion */
    public static final DeferredHolder<SoundEvent, SoundEvent> SCORPION_HIT = register("scorpion_hit");
    /** scorpion_living - Crab, EmperorScorpion, HerculesBeetle */
    public static final DeferredHolder<SoundEvent, SoundEvent> SCORPION_LIVING = register("scorpion_living");
    /** seamonster_death - SeaMonster */
    public static final DeferredHolder<SoundEvent, SoundEvent> SEAMONSTER_DEATH = register("seamonster_death");
    /** seamonster_hit - SeaMonster */
    public static final DeferredHolder<SoundEvent, SoundEvent> SEAMONSTER_HIT = register("seamonster_hit");
    /** seamonster_living - SeaMonster */
    public static final DeferredHolder<SoundEvent, SoundEvent> SEAMONSTER_LIVING = register("seamonster_living");
    /** seaviper_death - SeaViper */
    public static final DeferredHolder<SoundEvent, SoundEvent> SEAVIPER_DEATH = register("seaviper_death");
    /** seaviper_hit - SeaViper */
    public static final DeferredHolder<SoundEvent, SoundEvent> SEAVIPER_HIT = register("seaviper_hit");
    /** seaviper_living - SeaViper */
    public static final DeferredHolder<SoundEvent, SoundEvent> SEAVIPER_LIVING = register("seaviper_living");
    /** squid_death - AttackSquid */
    public static final DeferredHolder<SoundEvent, SoundEvent> SQUID_DEATH = register("squid_death");
    /** squid_hurt - AttackSquid */
    public static final DeferredHolder<SoundEvent, SoundEvent> SQUID_HURT = register("squid_hurt");
    /** terribleterror_dead - TerribleTerror */
    public static final DeferredHolder<SoundEvent, SoundEvent> TERRIBLETERROR_DEAD = register("terribleterror_dead");
    /** terribleterror_hit - TerribleTerror */
    public static final DeferredHolder<SoundEvent, SoundEvent> TERRIBLETERROR_HIT = register("terribleterror_hit");
    /** terribleterror_living - TerribleTerror */
    public static final DeferredHolder<SoundEvent, SoundEvent> TERRIBLETERROR_LIVING = register("terribleterror_living");
    /** trex_death - TRex, TheKing, ThePrinceAdult, TheQueen */
    public static final DeferredHolder<SoundEvent, SoundEvent> TREX_DEATH = register("trex_death");
    /** trex_living - TRex */
    public static final DeferredHolder<SoundEvent, SoundEvent> TREX_LIVING = register("trex_living");
    /** triffid_dead - Triffid */
    public static final DeferredHolder<SoundEvent, SoundEvent> TRIFFID_DEAD = register("triffid_dead");
    /** triffid_hit - Triffid */
    public static final DeferredHolder<SoundEvent, SoundEvent> TRIFFID_HIT = register("triffid_hit");
    /** triffid_living - Triffid */
    public static final DeferredHolder<SoundEvent, SoundEvent> TRIFFID_LIVING = register("triffid_living");
    /** vortexlive - Vortex */
    public static final DeferredHolder<SoundEvent, SoundEvent> VORTEXLIVE = register("vortexlive");
    /** waterdragon_death - WaterDragon */
    public static final DeferredHolder<SoundEvent, SoundEvent> WATERDRAGON_DEATH = register("waterdragon_death");
    /** waterdragon_hurt - WaterDragon */
    public static final DeferredHolder<SoundEvent, SoundEvent> WATERDRAGON_HURT = register("waterdragon_hurt");
    /** wtf_hurt - no class reference found */
    public static final DeferredHolder<SoundEvent, SoundEvent> WTF_HURT = register("wtf_hurt");
    /** wtf_living - GammaMetroid */
    public static final DeferredHolder<SoundEvent, SoundEvent> WTF_LIVING = register("wtf_living");

    private ModSounds() {}

    private static DeferredHolder<SoundEvent, SoundEvent> register(String id) {
        return SOUNDS.register(id, () -> SoundEvent.createVariableRangeEvent(
                ResourceLocation.fromNamespaceAndPath(OreSpawn.MOD_ID, id)));
    }

    /** Loads this class so every holder above is registered. */
    public static void init() {}
}
