package com.swbr.orespawn.world.structure;

import com.swbr.orespawn.OreSpawn;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.TagKey;
import net.minecraft.world.level.biome.Biome;

/**
 * The 1.7.10 {@code BiomeGenBase.biomeName} strings that {@code OreSpawnWorld} compared with {@code equals}, as
 * biome tags under {@code data/orespawn/tags/worldgen/biome/legacy_name/}. Each tag lists the direct 1.21.1
 * successors of the named biomes (verhalten/world-02.md "Portierung 1.21.1", docs/catalog/biome_map.json). The
 * "... M" mutations and the flower forest never had those names and are not in the tags, as in the original.
 *
 * <p>The tag files are generated by {@code tools/gen_spawns.py} from the {@code legacy_names} section of
 * {@code biome_map.json}, the same map as the spawn table (DECISIONS R26): biomes 1.21.1 split off a 1.7.10 biome
 * belong to it - lukewarm, warm and cold ocean to "Ocean", mangrove swamp to "Swampland", bamboo jungle to "Jungle".
 * Frozen oceans stay out; 1.7.10 had them as biomes of their own.
 *
 * <p>Where the original tested two names at once ({@code "Forest" || "ForestHills"}), the hills variant merged
 * into the same 1.21.1 biome; the tag carries the pair.
 */
public final class LegacyBiomeNames {

    /** {@code "Forest"}, {@code "ForestHills"} → {@code minecraft:forest}. */
    public static final TagKey<Biome> FOREST = tag("forest");
    /** {@code "Birch Forest"}, {@code "Birch Forest Hills"} → {@code minecraft:birch_forest}. */
    public static final TagKey<Biome> BIRCH_FOREST = tag("birch_forest");
    /** {@code "Jungle"}, {@code "JungleHills"} → {@code minecraft:jungle}, {@code minecraft:bamboo_jungle} (R26). */
    public static final TagKey<Biome> JUNGLE = tag("jungle");
    /** {@code "Plains"} → {@code minecraft:plains}. */
    public static final TagKey<Biome> PLAINS = tag("plains");
    /** {@code "Taiga"} → {@code minecraft:taiga}. */
    public static final TagKey<Biome> TAIGA = tag("taiga");
    /** {@code "Swampland"} → {@code minecraft:swamp}, {@code minecraft:mangrove_swamp} (R26). */
    public static final TagKey<Biome> SWAMPLAND = tag("swampland");
    /**
     * {@code "Ocean"} → {@code minecraft:ocean}, {@code lukewarm_ocean}, {@code warm_ocean}, {@code cold_ocean} (R26). The
     * deep variants had the name "Deep Ocean" and stay out, as in the original.
     */
    public static final TagKey<Biome> OCEAN = tag("ocean");
    /** {@code "River"} → {@code minecraft:river}. */
    public static final TagKey<Biome> RIVER = tag("river");
    /** {@code "Extreme Hills"} → {@code minecraft:windswept_hills}. */
    public static final TagKey<Biome> EXTREME_HILLS = tag("extreme_hills");
    /** {@code "Desert"} → {@code minecraft:desert}. */
    public static final TagKey<Biome> DESERT = tag("desert");
    /** {@code "Ice Plains"} → {@code minecraft:snowy_plains}. */
    public static final TagKey<Biome> ICE_PLAINS = tag("ice_plains");
    /** {@code "Roofed Forest"} → {@code minecraft:dark_forest}. */
    public static final TagKey<Biome> ROOFED_FOREST = tag("roofed_forest");

    private LegacyBiomeNames() {
    }

    private static TagKey<Biome> tag(final String name) {
        return TagKey.create(Registries.BIOME, ResourceLocation.fromNamespaceAndPath(OreSpawn.MOD_ID, "legacy_name/" + name));
    }
}
