package com.swbr.orespawn.world.spawn;

import com.google.gson.JsonElement;
import com.google.gson.JsonParser;
import com.mojang.serialization.Codec;
import com.mojang.serialization.JsonOps;
import com.mojang.serialization.codecs.RecordCodecBuilder;
import com.swbr.orespawn.OreSpawn;
import com.swbr.orespawn.config.OreSpawnConfig;
import com.swbr.orespawn.config.stats.MobSwitches;
import com.swbr.orespawn.platform.Holidays;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.lang.ref.WeakReference;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;
import javax.annotation.Nullable;
import net.minecraft.core.Holder;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.packs.resources.Resource;
import net.minecraft.tags.TagKey;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.MobCategory;
import net.minecraft.world.level.biome.Biome;
import net.neoforged.neoforge.common.ModConfigSpec;

/**
 * The natural spawn table of {@code data/<ns>/spawn_table/<path>.json}, generated by
 * {@code tools/gen_spawns.py} from the 348 {@code EntityRegistry.addSpawn} calls of
 * {@code OreSpawnMain.make_some_more_things} (OreSpawnMain.java:4176-4641), the lists of
 * {@code BiomeGenUtopianPlains} and the dino list of {@code ChunkProviderOreSpawn2.getPossibleCreatures}.
 *
 * <p>The table is already mapped to 1.21.1 biomes and merged (DECISIONS R18: two 1.7.10 biomes on one
 * 1.21.1 biome keep the larger entry, entries of one 1.7.10 list stay as they were). What is left for
 * run time is exactly what the original decided at run time: the {@code *Enable} switches, which
 * {@code AllMobsDisable} may have zeroed ({@link MobSwitches}), and the date of Halloween and Easter.
 *
 * <p>A key is a biome id or, with a leading {@code #}, a biome tag (DECISIONS R26: {@code hell} is
 * {@code #minecraft:is_nether}, the whole 1.21.1 Nether). Tag membership is only known once the server's registries
 * are bound, so the R18 merge rule for a biome reached through several keys runs here, in
 * {@link #entries(Holder)}, instead of in the generator.
 */
public final class SpawnTable {

    /** {@code date} of an entry: no date condition, October 31st, April 20th (OreSpawnMain.java:4181, :4341). */
    public enum DateGuard {
        NONE, HALLOWEEN, EASTER;

        static final Codec<DateGuard> CODEC = Codec.STRING.xmap(
                s -> DateGuard.valueOf(s.toUpperCase(Locale.ROOT)),
                d -> d.name().toLowerCase(Locale.ROOT));
    }

    /**
     * One {@code SpawnListEntry(class, weight, min, max)} of a 1.7.10 list, with its guard.
     *
     * @param entity   registry id; may name an entity that a later wave registers (see {@link #resolve})
     * @param category the list it stood in, mapped by {@code docs/catalog/biome_map.json} (R18: 1:1, also
     *                 for hostile mobs in {@code ambient})
     * @param flags    OreSpawnMOBS config keys; all must be != 0
     * @param date     date guard, evaluated at server start (R18)
     * @param source   original file and line, for the log and for readers
     * @param todo     the wave that brings the entity type, empty when it exists already
     */
    public record Entry(ResourceLocation entity, MobCategory category, int weight, int min, int max,
                        List<String> flags, DateGuard date, String source, Optional<String> todo) {

        static final Codec<Entry> CODEC = RecordCodecBuilder.create(i -> i.group(
                ResourceLocation.CODEC.fieldOf("entity").forGetter(Entry::entity),
                MobCategory.CODEC.fieldOf("category").forGetter(Entry::category),
                Codec.INT.fieldOf("weight").forGetter(Entry::weight),
                Codec.INT.fieldOf("min").forGetter(Entry::min),
                Codec.INT.fieldOf("max").forGetter(Entry::max),
                Codec.STRING.listOf().fieldOf("flags").forGetter(Entry::flags),
                DateGuard.CODEC.optionalFieldOf("date", DateGuard.NONE).forGetter(Entry::date),
                Codec.STRING.fieldOf("source").forGetter(Entry::source),
                Codec.STRING.optionalFieldOf("todo").forGetter(Entry::todo)
        ).apply(i, Entry::new));

        /**
         * The guard of the original, in its order: the date block encloses the Halloween lines
         * (:4181), Easter is {@code EasterBunnyEnable != 0 && easter_day != 0} (:4341), every other
         * entry is {@code if (<Flag> != 0)}.
         */
        public boolean active() {
            if (this.date == DateGuard.HALLOWEEN && OreSpawn.halloween == 0) {
                return false;
            }
            for (final String flag : this.flags) {
                if (!MobSwitches.enabled(switchFor(flag))) {
                    return false;
                }
            }
            return this.date != DateGuard.EASTER || OreSpawn.easter_day != 0;
        }

        /**
         * The registered type, or {@code null} while the entity's wave has not been ported.
         *
         * <p>W12 ran before W09-W11 (user request 2026-09-13); since W11 (2026-09-14) every entry resolves.
         * An entry whose id is not registered is still skipped rather than failing the server start.
         */
        @Nullable
        public EntityType<?> resolve() {
            return BuiltInRegistries.ENTITY_TYPE.getOptional(this.entity).orElse(null);
        }
    }

    /**
     * Top level {@code {"biomes": {<biome id> | #<biome tag>: [entries]}}}; the generator's {@code _about},
     * {@code _counts}, {@code _merged} are ignored. Keys stay strings here and are split in {@link #load}.
     */
    static final Codec<Map<String, List<Entry>>> CODEC =
            Codec.unboundedMap(Codec.STRING, Entry.CODEC.listOf()).fieldOf("biomes").codec();

    /** OreSpawnMOBS key -> value, filled once from the public fields of {@link OreSpawnConfig.Mobs}. */
    private static final Map<String, ModConfigSpec.IntValue> SWITCHES = new HashMap<>();

    private static WeakReference<MinecraftServer> loadedFor = new WeakReference<>(null);
    @Nullable
    private static ResourceLocation loadedId;
    @Nullable
    private static SpawnTable loaded;

    private final Map<ResourceLocation, List<Entry>> biomes;
    /** Tag keys, sorted by tag id. */
    private final Map<TagKey<Biome>, List<Entry>> tags;

    private SpawnTable(final Map<ResourceLocation, List<Entry>> biomes, final Map<TagKey<Biome>, List<Entry>> tags) {
        this.biomes = biomes;
        this.tags = tags;
    }

    /**
     * Entries stored under this biome id, unguarded; {@link Entry#active()} and {@link Entry#resolve()} decide.
     * Entries that reach the biome through a tag key are not included - see {@link #entries(Holder)}.
     */
    public List<Entry> entries(final ResourceLocation biome) {
        return this.biomes.getOrDefault(biome, List.of());
    }

    /** Entries stored under this tag key, unguarded. */
    public List<Entry> entries(final TagKey<Biome> tag) {
        return this.tags.getOrDefault(tag, List.of());
    }

    /** Every biome id the table names as a key (tag keys are in {@link #tags()}). */
    public Set<ResourceLocation> biomes() {
        return this.biomes.keySet();
    }

    /** Every biome tag the table names as a key. */
    public Set<TagKey<Biome>> tags() {
        return this.tags.keySet();
    }

    /**
     * Every entry that applies to this biome, unguarded: its id key first, then each tag key the biome is in, sorted
     * by tag id.
     *
     * <p>When more than one key applies, the lists are merged as {@code tools/gen_spawns.py} merges two 1.7.10 lists
     * on one 1.21.1 biome (DECISIONS R18): per entity, category, flags and date the key whose largest entry is
     * largest by (weight, max, min) wins - the earlier key on a tie - and all of that key's entries of the group
     * stay; within one key nothing is merged. The shipped table never needs this (the Nether is reached only through
     * its tag); a datapack or another mod's tag can.
     */
    public List<Entry> entries(final Holder<Biome> biome) {
        final List<List<Entry>> sources = new ArrayList<>();
        biome.unwrapKey().ifPresent(key -> {
            final List<Entry> direct = this.biomes.get(key.location());
            if (direct != null) {
                sources.add(direct);
            }
        });
        for (final Map.Entry<TagKey<Biome>, List<Entry>> tag : this.tags.entrySet()) {
            if (biome.is(tag.getKey())) {
                sources.add(tag.getValue());
            }
        }
        if (sources.isEmpty()) {
            return List.of();
        }
        if (sources.size() == 1) {
            return sources.get(0);
        }
        final Comparator<Entry> size = Comparator.comparingInt(Entry::weight).thenComparingInt(Entry::max)
                .thenComparingInt(Entry::min);
        final Map<MergeKey, Entry> best = new HashMap<>();
        final Map<MergeKey, Integer> winner = new HashMap<>();
        for (int i = 0; i < sources.size(); ++i) {
            for (final Entry entry : sources.get(i)) {
                final MergeKey key = MergeKey.of(entry);
                final Entry current = best.get(key);
                if (current == null || size.compare(entry, current) > 0) {
                    best.put(key, entry);
                    winner.put(key, i);
                }
            }
        }
        final List<Entry> merged = new ArrayList<>();
        for (int i = 0; i < sources.size(); ++i) {
            for (final Entry entry : sources.get(i)) {
                if (winner.get(MergeKey.of(entry)) == i) {
                    merged.add(entry);
                }
            }
        }
        return merged;
    }

    /** The group of the R18 merge rule. */
    private record MergeKey(ResourceLocation entity, MobCategory category, List<String> flags, DateGuard date) {
        static MergeKey of(final Entry entry) {
            return new MergeKey(entry.entity(), entry.category(), List.copyOf(entry.flags()), entry.date());
        }
    }

    /**
     * The table for the server whose biome modifiers are being applied, loaded once per server start.
     *
     * <p>NeoForge applies biome modifiers in {@code ServerLifecycleHooks.handleServerAboutToStart} <em>before</em>
     * it posts {@code ServerAboutToStartEvent} (ServerLifecycleHooks.java:97-98). The date check of
     * {@code platform.GameEvents} therefore comes too late for the spawn lists; the first load per server
     * runs {@link Holidays#evaluate()} itself, which is the "at server start" of R18.
     */
    public static synchronized SpawnTable forServer(@Nullable final MinecraftServer server, final ResourceLocation id) {
        if (loaded != null && id.equals(loadedId) && loadedFor.get() == server && server != null) {
            return loaded;
        }
        Holidays.evaluate();
        final SpawnTable table = load(server, id);
        logUnresolved(table, id);
        loaded = table;
        loadedId = id;
        loadedFor = new WeakReference<>(server);
        return table;
    }

    private static SpawnTable load(@Nullable final MinecraftServer server, final ResourceLocation id) {
        final ResourceLocation file = id.withPath(p -> "spawn_table/" + p + ".json");
        final JsonElement json;
        try {
            if (server != null) {
                // Datapack path, so a datapack may replace the table like any other data file.
                final Optional<Resource> resource = server.getResourceManager().getResource(file);
                if (resource.isEmpty()) {
                    throw new IllegalStateException("OreSpawn spawn table " + file + " not found");
                }
                try (Reader reader = resource.get().openAsReader()) {
                    json = JsonParser.parseReader(reader);
                }
            } else {
                // No server (a unit test calling in directly): the copy shipped in the jar.
                final String path = "/data/" + file.getNamespace() + "/" + file.getPath();
                try (InputStream in = SpawnTable.class.getResourceAsStream(path)) {
                    if (in == null) {
                        throw new IllegalStateException("OreSpawn spawn table " + path + " not on the classpath");
                    }
                    json = JsonParser.parseReader(new InputStreamReader(in, StandardCharsets.UTF_8));
                }
            }
        } catch (IOException e) {
            throw new IllegalStateException("OreSpawn spawn table " + file + " unreadable", e);
        }
        final Map<String, List<Entry>> keys = CODEC.parse(JsonOps.INSTANCE, json)
                .getOrThrow(msg -> new IllegalStateException("OreSpawn spawn table " + file + ": " + msg));
        final Map<ResourceLocation, List<Entry>> biomes = new HashMap<>();
        final Map<ResourceLocation, List<Entry>> tagsById = new TreeMap<>();
        for (final Map.Entry<String, List<Entry>> key : keys.entrySet()) {
            for (final Entry entry : key.getValue()) {
                for (final String flag : entry.flags()) {
                    switchFor(flag); // fails here, at load, not in the middle of a biome
                }
            }
            if (key.getKey().startsWith("#")) {
                tagsById.put(parseKey(file, key.getKey().substring(1)), List.copyOf(key.getValue()));
            } else {
                biomes.put(parseKey(file, key.getKey()), List.copyOf(key.getValue()));
            }
        }
        final Map<TagKey<Biome>, List<Entry>> tags = new LinkedHashMap<>();
        tagsById.forEach((tagId, entries) -> tags.put(TagKey.create(Registries.BIOME, tagId), entries));
        return new SpawnTable(Map.copyOf(biomes), Collections.unmodifiableMap(tags));
    }

    private static ResourceLocation parseKey(final ResourceLocation file, final String key) {
        return ResourceLocation.read(key)
                .getOrThrow(msg -> new IllegalStateException("OreSpawn spawn table " + file + ": key " + key + ": " + msg));
    }

    private static void logUnresolved(final SpawnTable table, final ResourceLocation id) {
        final Set<String> missing = new TreeSet<>();
        final Set<String> misc = new TreeSet<>();
        int count = 0;
        final List<List<Entry>> all = new ArrayList<>(table.biomes.values());
        all.addAll(table.tags.values());
        for (final List<Entry> entries : all) {
            for (final Entry entry : entries) {
                count++;
                final EntityType<?> type = entry.resolve();
                if (type == null) {
                    missing.add(entry.entity() + entry.todo().map(w -> " (" + w + ")").orElse(""));
                } else if (type.getCategory() == MobCategory.MISC) {
                    misc.add(entry.entity().toString());
                }
            }
        }
        OreSpawn.LOG.info("OreSpawn spawn table {}: {} entries in {} biomes and {} biome tags, halloween={}, easter_day={}",
                id, count, table.biomes.size(), table.tags.size(), OreSpawn.halloween, OreSpawn.easter_day);
        if (!missing.isEmpty()) {
            OreSpawn.LOG.info("OreSpawn spawn table {}: skipping entity types not registered yet: {}", id, missing);
        }
        if (!misc.isEmpty()) {
            OreSpawn.LOG.warn("OreSpawn spawn table {}: skipping MobCategory.MISC types (SpawnerData would turn them into pigs): {}",
                    id, misc);
        }
    }

    /** The IntValue of an OreSpawnMOBS key; the generator checked the names against OreSpawnConfig.java. */
    static ModConfigSpec.IntValue switchFor(final String key) {
        synchronized (SWITCHES) {
            if (SWITCHES.isEmpty()) {
                for (final Field field : OreSpawnConfig.Mobs.class.getFields()) {
                    if (!Modifier.isStatic(field.getModifiers()) && field.getType() == ModConfigSpec.IntValue.class) {
                        try {
                            SWITCHES.put(field.getName(), (ModConfigSpec.IntValue) field.get(OreSpawnConfig.MOBS));
                        } catch (IllegalAccessException e) {
                            throw new IllegalStateException(e);
                        }
                    }
                }
            }
            final ModConfigSpec.IntValue value = SWITCHES.get(key);
            if (value == null) {
                throw new IllegalStateException("OreSpawn spawn table names unknown OreSpawnMOBS key " + key);
            }
            return value;
        }
    }
}
