"""Generate config/OreSpawnConfig.java from the 628 original config keys in docs/catalog/manifest.json.

One COMMON spec, one nested class per original category, field names = original keys, defaults =
the jar's defaults (DECISIONS R3). OreSpawnIDS is skipped: numeric ids do not exist in 1.21.1 (R2).
No ranges are imposed here - the original clamped some values after reading them, and that clamping
is ported next to the code that reads the value, exactly where the original did it.

Generated - never edit by hand.
"""
from __future__ import annotations

import collections
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src" / "main" / "java" / "com" / "swbr" / "orespawn" / "config" / "OreSpawnConfig.java"
SKIP = {"OreSpawnIDS"}
CLASS_NAMES = {
    "OreSpawnTWEAKS": ("Tweaks", "TWEAKS"),
    "OreSpawnWEAPONS": ("Weapons", "WEAPONS"),
    "OreSpawnMOBS": ("Mobs", "MOBS"),
    "OreSpawnARMOR": ("Armor", "ARMOR"),
    "OreSpawnORES": ("Ores", "ORES"),
}


def main() -> int:
    manifest = json.loads((ROOT / "docs" / "catalog" / "manifest.json").read_text(encoding="utf-8"))
    cats = collections.OrderedDict()
    for c in manifest["config"]:
        if c["category"] in SKIP:
            continue
        if c["type"] != "I":
            print(f"unsupported config type {c['type']} for {c['category']}.{c['key']}")
            return 1
        cats.setdefault(c["category"], []).append(c)
    unknown = set(cats) - set(CLASS_NAMES)
    if unknown:
        print(f"unknown categories: {unknown}")
        return 1

    body = []
    for cat, keys in cats.items():
        cls, _ = CLASS_NAMES[cat]
        body += ["", f"    /** Original category {cat} ({len(keys)} keys). */",
                 f"    public static final class {cls} {{"]
        for k in keys:
            via = " -> ".join(k.get("via") or [])
            body.append(f"        /** Target {k['target']}, read in {via}. */")
            body.append(f"        public final ModConfigSpec.IntValue {k['key']};")
        body += ["", f"        {cls}(ModConfigSpec.Builder b) {{", f"            b.push(\"{cat}\");"]
        for k in keys:
            body.append(f"            {k['key']} = b.defineInRange(\"{k['key']}\", {int(k['default'])}, Integer.MIN_VALUE, Integer.MAX_VALUE);")
        body += ["            b.pop();", "        }", "    }"]

    fields = [f"    public static final {CLASS_NAMES[c][0]} {CLASS_NAMES[c][1]};" for c in cats]
    inits = [f"        {CLASS_NAMES[c][1]} = new {CLASS_NAMES[c][0]}(b);" for c in cats]
    total = sum(len(v) for v in cats.values())
    java = "\n".join([
        "// GENERATED by tools/gen_config.py from docs/catalog/manifest.json - do not edit.",
        "package com.swbr.orespawn.config;",
        "",
        "import net.neoforged.neoforge.common.ModConfigSpec;",
        "",
        "/**",
        f" * OreSpawn's original configuration, {total} keys with the jar's defaults, as one COMMON spec",
        " * ({@code config/orespawn-common.toml}). Values needed during registration are read through",
        " * {@link EarlyConfig}, because NeoForge loads COMMON configs only after the registry events.",
        " */",
        "public final class OreSpawnConfig {",
        "",
        "    public static final ModConfigSpec SPEC;",
        *fields,
        "",
        "    static {",
        "        ModConfigSpec.Builder b = new ModConfigSpec.Builder();",
        *inits,
        "        SPEC = b.build();",
        "    }",
        "",
        "    private OreSpawnConfig() {}",
        *body,
        "}",
        "",
    ])
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(java, encoding="utf-8", newline="\n")
    print(f"generated {total} config keys in {len(cats)} categories -> {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
